### PR TITLE
AMIGAOS: Fixes to the automatic installation

### PR DESCRIPTION
**Pull request by raziel-**
Updated the readme converter script and amigaos.mk

Someone has to please update rm2ag.rexx.in as i have no idea what to do there and don´t want to break anything

### CODE REVIEW

**Comment by lotharsm** [comment]
Looks like the only difference in the RM2AG.rexx.in compared to RM2AG.rexx is a different way to describe the version numer, since the .in files are usually used for building the final "product" by our Perl maintenance/versioning scripts:

```
# diff dists/amigaos/RM2AG.rexx dists/amigaos/RM2AG.rexx.in
81c81
< CALL WRITELN guide_write,'@$VER: ScummVM Readme 2.3.0git'
---
> CALL WRITELN guide_write,'@$VER: ScummVM Readme @VERSION@'
126a127
```

**Comment by raziel-** [comment]
@lotharsm 

Would that be correct?

**Comment by lotharsm** [comment]
Yes, that's correct. Merging :-)

**Comment by raziel-** [comment]
Thank you

**Comment by criezy** [comment]
The changes in this pull request have broken the AmigaOS daily builds on buildbot:
```
makedir ALL FORCE Games:ScummVM
make: makedir: Command not found
make: *** [../../src-master/src/backends/platform/sdl/amigaos/amigaos.mk:12: amigaosdist] Error 127
```

**Comment by raziel-** [comment]
Yeah.

Makedir is not a program from the SDK toolchain, but a system program.

I dont know how to solve this, mkdir is broken and unusable for automatic installation, at least locally.

Otoh, amigaos.mk is not really needed for daily builds, isn't it?
Could the amigaos.mk simply be flagged as "do not use" for buildbot?

Thank you

**Comment by lephilousophe** [comment]
For newer buildbot (still testing), I introduced shims for Amiga commands which can be found at `https://github.com/lephilousophe/dockerized-bb/tree/master/toolchains/amigaos4/packages/amiga-shims`.
Maybe they can be installed on old buildbot in `/opt/toolchains/amigaos4-gcc-8.3.0/bin`.
They are not perfect but they seem to work properly for the packaging scripts (Makefile and REXX)

**Comment by lotharsm** [comment]
@lephilousophe if it's just a matter of copying all the files from the `amiga-shims` directory to the buildbot, then I can do it. Is there any further adjustment to be made?

**Comment by lephilousophe** [comment]
Normally none. They are just shell scripts which parse AmigaOS arguments and try to map them on POSIX commands

**Pull request merged**
