### PR TITLE
Adding Inherit the Earth - Quest for the Orb (CD Windows-French)

### PR DESCRIPTION
**Pull request by Darknior**
I have take the last MASTER git version and work to add the last French fan trad game to scummVM.
It's **Inherit the Earth - Quest for the Orb** that use **SAGA** engine :

I modify :
- detection_table.h : To add MD5 + Size of french files.
- itedata.cpp : Adding all the french text.
- introproc_ite.cpp / itedata.h / puzzle.cpp / saga.cpp : To update table and ifelse make the trad working.

I respect all your charts to make it fine. Working very well on last ScummVM 1.10 on PI.

https://youtu.be/rsTX-C8dXK8

Please can you add it to the source code for future release. Thanks

[ITE FR Trad - Sourcecode.zip](https://github.com/scummvm/scummvm/files/1416629/ITE.FR.Trad.-.Sourcecode.zip)

### CODE REVIEW

**Comment by csnover** [comment]
Hi, it looks like you created a pull request that is trying to merge our 1.9 branch into our master branch, instead of creating one that contains your code. Could you please edit this PR to use the correct branch so it can be evaluated? Thanks!

**Comment by Darknior** [comment]
I can't :(
I have : into base: **master**  from **branch-1-9**
I can change master to **1.9** but not 1.9 to **master** ...
I'm not strong with GIT, can you teach me ?

**Comment by angstsmurf** [comment]
A good start is to make your own fork of the ScummVM repository with the Fork button at the top right.

**Comment by criezy** [comment]
To propose changes to the source code, the flow to follow is as described below:
1. First fork the ScummVM repository (if you have not already done so).
2. Clone your fork locally to your computer.
3. Create a branch in your local clone.
4. Make and commit your changes.
5. Push those back to your fork on GitHub.
6. Finally open the pull request from the branch in your fork to the scummvm master.

There is more details in the Git Help section, and in particular at https://help.github.com/categories/collaborating-with-issues-and-pull-requests/, but if you have never used GitHub before you might want to start at the top of the Help (and in particular the Bootcamp section) at https://help.github.com/.

**Comment by digitall** [comment]
@Darknior : Since you seem to be having problems with getting this code into git and opening a PR and this PR is on the closed v1.9 branch, rather than the development master branch, I have downloaded your zip file of the changed files and patched these against the latest master code. I have opened the result as a new PR, https://github.com/scummvm/scummvm/pull/1046

I will close this and the team can look at the code changes and comment there.

Thanks for providing this code.

**Pull request closed without merging**
