### PR TITLE
COMMON: Don't attempt to guess host endianness if it has been set previously

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by bonki** [comment]
Under which circumstances would this trigger? Where else would these be defined if not in `config.h` or inside this very `if`?

**Comment by ccawley2011** [comment]
This is to allow the possibility of defining these in portlibs.h

**Comment by bonki** [comment]
Maybe we should migrate the whole construct to `portdefs.h` instead and mandate that all platforms provide one instead of introducing a third place where these can be defined? There are other things in `scummsys.h` which could/should be moved to `portdefs.h` and doing so would make ports more self-contained and `scummsys.h` a less cluttered and a bit more maintainable.

Is there a good reason not to do this?

**Comment by digitall** [comment]
@bonki : If we are going to migrate to all ports having a portsdef.h then wouldn't adding this change provide a first step in migrating each of the platforms over? If so, then adding this change should probably be done in either case.

**Comment by bluegr** [comment]
I concur with @bonki on this, we should either migrate to all ports having a portsdef.h, or keep things as they are.

At the moment, this pull request does not offer any noteworthy change on its own, so it should either be expanded with changes to portsdefs.h, or closed.

**Comment by bluegr** [comment]
Three months later... any update on this?

**Comment by bluegr** [comment]
As mentioned, this pull request does not offer any notable change on its own. If we move the host endianness defines in portdefs.h in the future, we can revisit this change.

Until then, we might decide on a different way of detecting whether to run this code or not. As it stands, this pull request is just a suggestion, for a feature that isn’t done in the suggested way.

Therefore, I’m closing this

**Pull request closed without merging**
