### PR TITLE
SCUMM: Fix an original tapestry glitch in Indy3 VGA (Trac#3208)

### PR DESCRIPTION
**Pull request by dwatteau**
## Context

The 256-color versions of Indy3 have a very strange purple line next to the big tapestry that's in the middle of room 135, in Castle Brunwald.

indy3-vga-tapestry-glitch

Yeah, it's just that little purple line and I'm probably too obsessive, but the good news is that it's been reported by some other users years ago in [Trac#3208](https://bugs.scummvm.org/ticket/3208), so I'm not alone! That's the first room you can enter in Castle Brunwald, and the only thing there is in this room is this tapestry, and this glitch. Also happens in the original interpreters.

It looks like an artist made some wrong click when redrawing this object for the VGA versions, or maybe the compression routine for those images had some bug. QA was probably rushed for this port, too, since Indy3 has various oversights related to the VGA conversion. A similar problem was fixed in commit 6735e3c0f006730831f020e31b3385ee55f58edb.

The tapestry glitch was a bit harder to fix, because the glitched line hides several pixels with different colors, and because this resource is in a compressed format (see `unkDecode11()`). AFAICS, v3 games have no concept of transparent pixels for background objects, so that simpler solution wouldn't work either. Trimming the leftmost 'strip' could also work (the glitch is on the large tapestry object, not on the background), but I couldn't find a safe way of doing that for `unkDecode11()`.

So I have redrawn a fixed `OI_0324` with the old `BMRP.EXE` tool, diffed the two resources and then added a small mechanism which patches (for copyright reasons) the impacted bytes from the original resource, as it is being read. This is a very low-level trick, so various checks have been added to make sure that we're not corrupting something (incl. any fan-made modified Indy3), and also in order to make the workaround a bit easier to follow.

## How to test

1. Start a 256-color version of Indy3 (the DOS release from GOG, the Windows release from Steam, or the FM-TOWNS version)
2. Use `room 135` in the ScummVM debugger
3. Make sure that the tapestry doesn't show this purple line anymore, and that nothing glitches. If you need to exit the room, use the "Look at" verb on the tapestry; it will "unlock" Indy.

**An FM-TOWNS test would be very welcome!** I know this bug exists in this version, but I don't have it. I don't know if the OI is identical between the two releases, or if it'd need some adjustment.

### CODE REVIEW

**Comment by raziel-** [comment]
FM-TOWNS:

The glitch is blue :-)
Original

and it's gone with your patch
Fixed

**Comment by dwatteau** [comment]
@raziel- Very cool, thanks for your test! So indeed the OI itself is probably identical, but the room palette is a bit different.

**Comment by raziel-** [comment]
@dwatteau

Beside Indy 3 i also own Zak McKracken as FM-TOWNS, so if you need to do some testing there, just shout :-)

**Comment by dwatteau** [comment]
> @dwatteau
> 
> Beside Indy 3 i also own Zak McKracken as FM-TOWNS, so if you need to do some testing there, just shout :-)

Thanks! Fortunately, I have that one, since GOG sells it (well, they didn't include the Japanese version, though, so I'm still missing that one).

**Comment by raziel-** [comment]
@dwatteau

Ok, great :-)

btw, is it just me and my failing eyesight or does Indy appear brighter in the fix?
Especially his suit seems to be one shade lighter than in the original (but also his "nose" and the rest of the shadows on him)

**Comment by dwatteau** [comment]
@raziel- Yes, that's strange, maybe your capture or image tool changed something a bit? The Alt-S shortcut in ScummVM should give you the same color rendering with and without this Enhancement.

Or maybe the workaround itself messes up with the room palette, but that would be strange 🤔

**Comment by raziel-** [comment]
Hum, now it gets interesting.
Using ctrl+s produces a very interesting piece of screenshot, not really usable, so probably bugged on my end...will add it tomorrow and report back.

**Comment by raziel-** [comment]
scummvm-indy3-fm-00003
This is what I get in-game, launcher is fine.
Seems the alpha channel is handled wrong???

**Comment by dwatteau** [comment]
> scummvm-indy3-fm-00003
> This is what I get in-game, launcher is fine.
> Seems the alpha channel is handled wrong???

Is that on AmigaOS or something similar? Do you have the fix from PR #4155 in your current build? I wonder if it could be related (it might be better to investigate this in a different PR or Trac issue, though).

**Comment by raziel-** [comment]
This was taken from your tapestry fix tree, so if that fix is in there, than yes

This is on AmigaOS, yes, SDL2, OGLES2, game with shaders

**Comment by raziel-** [comment]
Done, bug item 13857

**Comment by bluegr** [comment]
Nice, thanks!

**Pull request merged**
