### PR TITLE
CRYO: Remove dead code

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by bluegr** [comment]
The Cryo engine is not complete, so I am not sure if this code is really not necessary, or if it is meant to be used in the future.

**Comment by digitall** [comment]
@bluegr : True, though if the code really is totally dead, it can be removed for now and then recovered from git in future if needed. Looking at this, there is a debug console which was added as example, but not hooked up. This should be removed and then implemented fully... at least to allow the debug levels and flags to be adjusted at runtime if needed, which I could look at doing. Otherwise, the main issue here is the removal of the "dead" sound code. As you say, this is not a fully finished engine, but maybe @Strangerke can shed some light.

**Comment by sev-** [comment]
This git bitrot in the meantime. Please, rebase, and is it OK to merge. Thanks!

**Comment by bluegr** [comment]
Since this code is unused, it makes no sense to keep it around. If it's needed in the future, it can be readded once it's in a mature state.

Merging

**Pull request merged**
