### PR TITLE
SCUMM: Make roland patch work with any MI EGA

### PR DESCRIPTION
**Pull request by BLooperZ**
This allows using the official Roland MT-32 patch available from LucasArts (Monkeyup.exe [*]) along with any EGA version by adjusting the sound directory offsets to match the available patch.

[*] More information about the patch available here: https://dwatteau.github.io/scummfixes/corrupted-monkey1-ega-files-limitedrungames.html (See "Bonus: adding the missing Roland Update")

Notes:
- This was tested specifically on the french EGA version, but as the patch is the only one available I think it safe to use the same offsets as long as this specific patch is present. but we might want to test more versions.
- This needs to be categorized it once #5102 is merged, I am not sure which category is appropriate for this

Thank you

### CODE REVIEW

**Comment by dwatteau** [comment]
Thank you very much for this!

Works fine here with my original EGA French release + the Roland Update hosted by Disney. Maybe the French release indeed had its own supplemental disk back then, but it appears to be lost to time now.

Two small things though:

* `patchOffsets[]` actually has 19 elements, not 20, but maybe this is done in order to have an ever number?
* I'm not sure I'd use `_enableEnhancements` at all here, as the game just gets stuck on a black screen if you don't apply this change. One of the (currently) unwritten rules about Enhancements is that we enforce them if the game mostly becomes unplayable without them. (Maybe this is going to change with the PR linked above though.)

**Comment by bluegr** [comment]
Nice work! Agree with @dwatteau about the use of `_enableEnhancements` in this case

**Comment by BLooperZ** [comment]
Thank you both, I have removed `_enableEnhancements` and changed the array to be of size 19

**Comment by bluegr** [comment]
Nice work, thanks!

**Pull request merged**
