### PR TITLE
AGS: Commits from upstream up to version 3.6.0.41

### PR DESCRIPTION
**Pull request by tag2015**
This PR brings ScummVM's AGS implementation up to date with version 3.6.41,
It includes fixes for priority errors reported in Kathy Rain, Blackwell Convergence,
Resonance, Kill Yourself and probably others.

SKIPPED COMMITS

Engine: fixed TOUCH hints breaking compilation against older SDL2
https://github.com/adventuregamestudio/ags/commit/fbb87c3370501d9acad9c7282c5e951032587c9e
We don't use touch-to-mouse emulation

Common: add bmp and pcx load and save from stream 
https://github.com/adventuregamestudio/ags/commit/41eb660d599e94af31bfeb086392fce5cf1e1116
Upstream changed the routine for loading/saving bmp/pcx files from in-game.
Skipped because it required significant changes.
If needed, this could be probably reimplemented better

Allegro4: removed bmp and pcx load/save code
https://github.com/adventuregamestudio/ags/commit/c8d12571aba7f38231d9e96ccd6a34cd1bfa09ba
related to 41eb660d599e94af31bfeb086392fce5cf1e1116

Allegro4: removed normal packfile implementation + unused datafile
https://github.com/adventuregamestudio/ags/commit/bee3ecb7ef308312fd3149b62bb618e06e8d8310
related to 41eb660d599e94af31bfeb086392fce5cf1e1116

fix Makefile-defs.allegro
https://github.com/adventuregamestudio/ags/commit/680dc99d730285c3474bcf71494f1fdff694e8a3
related to 41eb660d599e94af31bfeb086392fce5cf1e1116

Common: in bitmap loader replaced WRITE3BYTES with a Memory function
https://github.com/adventuregamestudio/ags/commit/869bfd248929fc76dca506d73f05bcd5e063fd86
related to 41eb660d599e94af31bfeb086392fce5cf1e1116

Common: fixed Bitmap's SaveToFile not testing an opened stream
https://github.com/adventuregamestudio/ags/commit/6aeb7d77ec15a61d208a012e4c855b4506155951
related to 41eb660d599e94af31bfeb086392fce5cf1e1116

Allegro: remove bitmap bank stuff
https://github.com/adventuregamestudio/ags/commit/98bec91eb0f45c4765bdb80858d12747d435d897
Not present

Direct3D: use glm instead of the local helper methods
https://github.com/adventuregamestudio/ags/commit/6fb5906269bfe425253c40b8d4c8f7784b589fc0
Different implementation

Common: Fixed new[]/delete mistmatch
https://github.com/adventuregamestudio/ags/commit/8bee9aabb273eff482da606970cbe6abb0a6253b
Already fixed

Common: Fix comment doesn't match macro name
https://github.com/adventuregamestudio/ags/commit/7e562596d7afd61836bca19408cac860df916549
Already fixed

Allegro: additional cblit cleanup
https://github.com/adventuregamestudio/ags/commit/3897e7830d4def1b66cc0990dc082afd348b7ddc
Not in scummvm

Direct3D, OpenGL: replace viewport hacks with proper transform matrix
https://github.com/adventuregamestudio/ags/commit/484f416cc35cd76231854edfa4756272b888a91a
This would require changes, and I'm not sure it's needed in ScummVM's implementation

Direct3D: support sprite batches rendering to a texture
https://github.com/adventuregamestudio/ags/commit/490522fdd412dcdb3c687f88143a62eb935de11a
Couldn't get the shared part to compile and it wouldn't do anything anyway

OGL: support sprite batches rendering to a texture
https://github.com/adventuregamestudio/ags/commit/f1bc41994188eb4330c031a611bc72398ff1d405
Related to 490522fdd412dcdb3c687f88143a62eb935de11a

Engine: render GUI & controls batch to a buffer texture 
https://github.com/adventuregamestudio/ags/commit/2a7895cde22b32bbc7ea60bc23e64152c80d6f80
Related to 490522fdd412dcdb3c687f88143a62eb935de11a
(but may need to be reimplemented)

Direct3D: implement proper blend op settings for a custom render target
https://github.com/adventuregamestudio/ags/commit/c91d3e70ceb9fdd0874dde80d806d8b927302bdd
Different implementation, may need to be addressed later

OpenGL: implement proper blend op settings for a custom render target
https://github.com/adventuregamestudio/ags/commit/3f086f1ef91d37b1d90208b798adf9a9b884a06e
Related to c91d3e70ceb9fdd0874dde80d806d8b927302bdd

Engine: release render targets before switching the gfx mode
https://github.com/adventuregamestudio/ags/commit/5d72fe112cf08d82454e1bf55538ba8eb798461d
Related to c91d3e70ceb9fdd0874dde80d806d8b927302bdd

OpenGL: fixed custom render targets in "screen resolution" mode
https://github.com/adventuregamestudio/ags/commit/bb039ddc807fc9df00baa184bde35b62b3f19bf4
Not present

OpenGL: work with render targets of various sizes
https://github.com/adventuregamestudio/ags/commit/4b900d73b5f544017c1935ddf542af7277ca752d
Related to commit 3f086f1ef91d37b1d90208b798adf9a9b884a06e

Direct3D: work with render targets of various sizes
https://github.com/adventuregamestudio/ags/commit/14eb84c28a75e9756519c17aeaacce8b16343c9d
Related to commit 3f086f1ef91d37b1d90208b798adf9a9b884a06e

Direct3D: fixed rendering at screen resolution (when not stretched)
https://github.com/adventuregamestudio/ags/commit/6fec4943006960ae0a862e9e2af250ae4f9af8c5
Different implementation

Engine: update render target if the GUI got resized
https://github.com/adventuregamestudio/ags/commit/d2f61af07f9751174a4859769570467669c2b1d2
Related to commit 3f086f1ef91d37b1d90208b798adf9a9b884a06e

OpenGL: removed redundant error reporting
https://github.com/adventuregamestudio/ags/commit/c6299a233e19db4cc0a455aeff596842af4d437c
Not present in scummvm

Engine: create raw draw screens only on plugin's demand
https://github.com/adventuregamestudio/ags/commit/1b71780d6e94eca33ee3234fd138213874640ab1
Different implementation

Engine: fixed return value type in DoNullSpriteCallback()
https://github.com/adventuregamestudio/ags/commit/d2de93a9151ca3cb3933b9ede542bad18190a721
Fixed in previous commit

Engine: use unique_ptr<Bitmap> in VideoMemoryGraphicsDriver::ScreenFx
https://github.com/adventuregamestudio/ags/commit/6fd7200ec85ace0abc5020faf79608f3385064e1
Couldn't get it to work with scummvm's implementation

OpenGL: removed incorrect redeclaration of _rendSpriteBatch
https://github.com/adventuregamestudio/ags/commit/e9e66f656dc4188ad2fed74ac15a32b137153984
Not present

Direct3D, OpenGL: fixed a silly rounding mistake in _renderSprite
https://github.com/adventuregamestudio/ags/commit/2bf90321d2a5bd7d23f3e368a325d42856cc9d76
Not present

Direct3D, OpenGL: removed few redundant casts from float to float
https://github.com/adventuregamestudio/ags/commit/624d3306b76182352aecfbbbf5e6692d9afdde36
Not present

Engine: csci gui messages uses intptr_t insted of long
https://github.com/adventuregamestudio/ags/commit/6dbff91f02f3ee53f1c21b797bf48f68f312b78c
Better solution already implemented

### CODE REVIEW

**Comment by digitall** [comment]
@tag2015 : Thanks for doing this. I was looking at it, but it is quite a task to review through the upstream commits and integrate, so kudos.

@criezy : Once this is integrated, we will need to review the open AGS bugs to see which are still present and which are fixed by the upstream patches. If you want help with that, let me know.

**Comment by tag2015** [comment]
> @tag2015 : Thanks for doing this. I was looking at it, but it is quite a task to review through the upstream commits and integrate, so kudos.
> 
> @criezy : Once this is integrated, we will need to review the open AGS bugs to see which are still present and which are fixed by the upstream patches. If you want help with that, let me know.

Well, I can comment in advance on some of the bugs, from what I have tested, as I have most of the games (including the commercial ones except lancelot's hangover):
Issues [#13724](https://bugs.scummvm.org/ticket/13724) [#13725](https://bugs.scummvm.org/ticket/13725) [#13758](https://bugs.scummvm.org/ticket/13758) [13780](https://bugs.scummvm.org/ticket/13780) [#14197](https://bugs.scummvm.org/ticket/14197) (except the "image editor" which is a recent upstream fix) should be fixed.
The font-related issues are still present (such as the "squashed" letters that get reported all the time)
The Excavation of Hob's Barrow still crashes.

**Comment by i30817** [comment]
Incredible work. Thank you for keeping it up to date.

**Comment by digitall** [comment]
@tag2015 : Thanks for confirming those. I suspected we can probably close a fair few after confirming the fix... and I suspected that my current "favourite" bug i.e. Hob's Barrow at https://bugs.scummvm.org/ticket/14072 would still be broken. I think that is an issue in the allegro interface code so different to upstream. It may be present upstream, but a latent issue. However, still haven't got to the bottom of why that happens. Any help gratefully received.

**Comment by digitall** [comment]
@criezy : Do you have time to review this soon or are you happy as-is? Just that we have a bunch of AGS bugs which could probably get closed once this is merged :)

**Comment by criezy** [comment]
> @criezy : Do you have time to review this soon or are you happy as-is? Just that we have a bunch of AGS bugs which could probably get closed once this is merged :)

Yes, I have some time, but there are a lot of commits to review, so it will take a few more days 😉

**Comment by digitall** [comment]
@criezy : No problem. I did suspect you were doing it, but just wanting to try to stop users reporting bugs which upstream have fixed  ... and allow me to finish my backlog of AGS games in my game library *cough* :)

One note, this PR is now in the "This branch cannot be rebased due to too many changes" state. It will likely need you to merge it manually locally as I think the Github UI can't cope with the master changes which may overlap :|

**Comment by criezy** [comment]
Great job.
This has now been merged manually.

**Pull request closed without merging**
