### PR TITLE
COMMON: Fix getDataFork in MacResManager

### PR DESCRIPTION
**Pull request by phcoder**
file->open works only with default archive. Instead open the stream for data fork together with resource fork and keep for the same time.

### CODE REVIEW

**Comment by sev-** [comment]
After looking at the code, I wonder about the following: Streams have their internal state, particularly, position on where they read. With this change, if I understand correctly, the stream is now a SharedPtr for both the resource fork and data fork.

If ever there is a code that reads from them in parallel, will that not be a problem?

Also, the ultimate question. What this code improvement is useful for? What kind of problems does it try to solve?

Also, I see a seemingly unrelated change: introducing a new API for Streams and switching Audio looping to it. Why did they come together with the MacBinary changes?

**Comment by phcoder** [comment]
> After looking at the code, I wonder about the following: Streams have their internal state, particularly, position on where they read. With this change, if I understand correctly, the stream is now a SharedPtr for both the resource fork and data fork.
They are wrapped in SeekableSubReadStream which does the needed seeks. The problem is only if there is an access from 2 different threads.
> 
> If ever there is a code that reads from them in parallel, will that not be a problem?
I can add the needed locks for the access from 2 threads
> 
> Also, the ultimate question. What this code improvement is useful for? What kind of problems does it try to solve?
Opening data forks inside archives and search sets.
> 
> Also, I see a seemingly unrelated change: introducing a new API for Streams and switching Audio looping to it. Why did they come together with the MacBinary changes?

This API is already there. I only add a move-DisposablePtr-semantics overload to it. Previous caller code was basically disassembling DisposablePtr into internal components to achieve the same result. Since then I found that SharedPtr-based DisposablePtr is useful for other stuff. Let me pull this part into a separate PR

**Comment by sev-** [comment]
Please resolve conflicts and also split out audio-related commits into a separate commit if possible

**Comment by phcoder** [comment]
Closing for now. AFAICS all current users use default searchset. New users can use openFileOrDataFork if they need thread-safety or non-default archive

**Pull request closed without merging**
