### PR TITLE
PLUGINS: Big refactoring DO NOT MERGE

### PR DESCRIPTION
**Pull request by henke37**
The plugin code needed an overhaul, so I refactored it.

Key points:
* EngineManager moved to separate files
* Engine related code moved from PluginManager to EngineManager
* Clearer names for various member functions
* Removed stateless plugin enumeration member functions from PluginManager
* The Plugin class now knows if the plugin is loaded or not

### CODE REVIEW

**Comment by henke37** [comment]
Gonna need some feedback on this. And testing. Definitely testing, since I don't use dynamic plugins. There are definitely spots that depend on plugins being loaded without checking that they are.

**Comment by henke37** [comment]
Ok, I feel finished. I did a full check for all usage of plugins and I feel confident that I've examined every spot.

**Comment by henke37** [comment]
So... There is one problem left to solve. That I know of. And as it so happens, I don't know how.

Dynamic plugins don't know their type until loaded. Yet I need to know their type to decide when to load them. Catch 22.

**Comment by henke37** [comment]
Resolved the dynamic type issue by just deferring determining the type to the plugin provider. Which, by default, will detect all plugins as engine plugins. Which is fine for now, since all dynamic plugins are engine plugins right now.

**Comment by sev-** [comment]
Okay, time to look into it. Could you please rebase the PR?

**Comment by henke37** [comment]
It's going to require more than a simple rebase. I'm waiting for the dust to settle after the other PR got merged before I deal with this PR.

**Comment by sev-** [comment]
What is status of this (besides being bitrot)? Still "DO NOT MERGE"?

**Comment by henke37** [comment]
I think I need to do some further debugging to ensure that everything is correct with regards to plugin types.

**Comment by bluegr** [comment]
5 months later... any news?

**Comment by bluegr** [comment]
@henke37 any news?

**Comment by henke37** [comment]
This one would likely require more work than it is worth to merge, it'd be faster to redo the work.

**Pull request closed without merging**
