### PR TITLE
WAGE: Don't require the data fork for the external sound file

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by bluegr** [comment]
Nice work! Merging

**Comment by sev-** [comment]
I apologise for the intrusion, but what is the purpose of this patch? And why it was introduced in the first place?

@bluegr, what makes 'nice' a patch without any description?

**Comment by ccawley2011** [comment]
@sev-: When unpacking a StuffIt archive using The UnArchiver, it will only create the resource fork if the data fork is empty. Thus, the WAGE engine won't load the external sound file because the data fork doesn't exist, even though it only uses the resource fork.

**Comment by sev-** [comment]
Ok, thanks for the explanation. Now it is clear. However, I need to check that it does work with my setup. I do not use UnArchiver, and most probably we will have to support both variants.

**Pull request merged**
