### PR TITLE
SCUMM: Allow scrolling to be less-than-smooth in the FM Towns Loom intro

### PR DESCRIPTION
**Pull request by eriktorbjorn**
In the FM Towns Loom intro, smooth scrolling just isn't fast enough to keep up with the messenger nymph as she flies from the village up to the mountain top. The purpose of this pull request is to make it scroll four pixels at a time when the camera is moving quickly. It detects this by checking the value of VAR(VAR_TIMER_NEXT). This makes it look more like the other versions, while still being fairly smooth.

The only FM Towns games I have are Loom (original CD) and Zak McKracken (GOG), and I've never actually played the latter. But since the option is only there for Loom, and is off by default, I hope it should be safe enough.

The pull request is split into two commits. The first one simply adds the option. The second one is to allow engine option checkboxes to be disabled depending on other such checkboxes. This touches a lot of engines, but only to the extent that their engine options structs are filled out with the new parameters.

The way it works is that each checkbox can belong to one group (where 0 means "no group"), and each checkbox can be designated the leader of a group (again, 0 means "I'm not a leader"), with at most one leader per group. When the group leader is unchecked, every checkbox in the group is disabled, and when they're saved their settings are made false. (It's theoretically possible that this will disable a group leader, in which case everyone in _that_ group should also be disabled... but that's not implemented at the moment.)

This won't cover every use case, of course, but at some point you just have to bite the bullet and switch to the more versatile, dynamic options widget instead. But if there are other suggestions for how to handle this, I'd be happy to drop that part of the pull request.

### CODE REVIEW

**Comment by athrxx** [comment]
I have tested it and it looks good to me. If you're used to the DOS version and haven't ever played the FM-TOWNS version in an emulator (or on real hardware) it will look more natural this way...

Also, I think the description for the option is understandable enough (although it might be "fun" for the translators).

**Comment by eriktorbjorn** [comment]
For those who don't have this version but want to see what it's about, here's an eye-straining comparison: https://youtu.be/dSXAsI1y80k

**Comment by bluegr** [comment]
Well done for the Loom feature, looks very nice!

Regarding the changes to the game options: it would be nice if we could change the checkboxes to radio buttons in mutually exclusive options. The logic that you've written looks good enough, but perhaps it would be possible to also change these widgets visually to look like radio buttons?

**Comment by eriktorbjorn** [comment]
> The logic that you've written looks good enough, but perhaps it would be possible to also change these widgets visually to look like radio buttons?

We already have a radio button widget. You can probably use that if you go to the trouble of making a dynamic settings widget (e.g. like the EGA Loom settings). But this isn't really a radio button situation, I think. It's a "this option unlocks other options" situation. The "Allow semi-smooth scrolling" option is only relevant when smooth scrolling is active. Otherwise, it's disabled:

settings-1

Enabling smooth scrolling enables semi-smooth scrolling:

settings-2

So that you can have both at the same time:

settings-3

Unchecking smooth scrolling disables semi-smooth scrolling, but retain their checked/unchecked status until you save. (Then any disabled checkbox is saved as if it was unchecked.)

settings-4

Athrxx suggested that a drop-down could be appropriate, but since this option is only for FM Towns Loom, it seems inconsistent to me to have a drop-down there and a checkbox for smooth scrolling for every other FM Towns game.

**Pull request merged**
