### PR TITLE
STARK: Fix bad subtitle for Cortez in theater

### PR DESCRIPTION
**Pull request by antoniou79**
Fix for bug https://bugs.scummvm.org/ticket/12967

### CODE REVIEW

**Comment by bluegr** [comment]
I'm confused. Isn't that a similar fix with the one done in #3394?

**Comment by antoniou79** [comment]
> I'm confused. Isn't that a similar fix with the one done in #3394?

Sorry, I did not notice there was an existing PR.

Just to defend my approach. 

It addresses and fixes the same issue but I wanted to make the check for the change as specific as possible, so I filter by game language, character who speaks the line, and then the index (int), subType (int) and finally specific resource name ("Cortez_Laying low #1"), in order to avoid checking every loaded string against the faulty one.

**Comment by aquadran** [comment]
I agree with @antoniou79, this has better checks

**Comment by Thunderforge** [comment]
I agree, this is a better fix than the one I was doing. Thanks!

**Pull request merged**
