### PR TITLE
SCUMM: Attempt to improve timing (see bug #13354)

### PR DESCRIPTION
**Pull request by eriktorbjorn**
According to https://bugs.scummvm.org/ticket/13354 ScummVM is running slightly too slow, so ScummVM takes too long to drown. My guess it's because ScummEngine::waitForTimer() isn't exact, and is likely to overshoot its target.

With this change, the "stop watch" will start at the time waitForTimer() theoretically finishes, so that the overshoot is factored into the measured time the main loop takes.

This seems slightly better to me than trying to fix waitForTimer(), since in the end it will probably be implemented in terms of SDL_Delay(), and that function is documented as not being completely accurate. See https://wiki.libsdl.org/SDL_Delay for details.

### CODE REVIEW

**Comment by eriktorbjorn** [comment]
Of course, it's possible that this will affect other games as well. But since the difference is so small that it can really only be observed over minutes, it's hopefully not a problem.

**Comment by eriktorbjorn** [comment]
Since waitForTimer() is called in a few other places, it may make sense to tray and make that more precise as well. I don't have the time to do that just now, though.

Even so, I think the current approach makes sense for the main loop because we can't sensibly _guarantee_ that it won't overshoot, and it's going to be called thousands of times (ten times per second, I believe) during those ten minutes.

**Comment by athrxx** [comment]
Your guess that ScummEngine::waitForTimer() isn't exact is certainly correct. The original interpreters don't have such a function. We have a single-threaded approach. In the original timing happens through interrupt handlers which will increase a tick counter and the scumm main loop will wait (in a small nested loop) until the next timer is reached. 

My impression was that the timing is also different for certain platforms/targets/scumm versions, since the internal timers run at different speeds, e. g. DOS will use the usual pit timers, Amiga and Mac the usual vblank interrupts, etc. Also, the later Scumm versions seem to use different timing due to iMuse requirements.

So, whatever we do, it will be just a more or less educated estimate...

**Comment by athrxx** [comment]
Do your changes actually "fix" the drowning time for Guybrush?
If we don't achieve that and he just dies at a different wrong time then the commit might not be worth the risk.

**Comment by eriktorbjorn** [comment]
> Do your changes actually "fix" the drowning time for Guybrush?

I'm not sure. I haven't compared it to DOSBox. What I can say is that this script fragment from room-42-205:

```
[0000] (2E) delay(28800);
[0004] (91) animateCostume(VAR_EGO,255);
[0008] (D8) printEgo([Text("Gee, I don't know how much longer I can hold my breath.")]);
[0042] (2E) delay(3600);
[0046] (93) ActorOps(VAR_EGO,[Palette(3,11),Palette(4,1)]);
[0050] (2E) delay(1800);
[0054] (93) ActorOps(VAR_EGO,[Palette(3,3)]);
[005B] (2E) delay(900);
[005F] (93) ActorOps(VAR_EGO,[Palette(3,9)]);
[0066] (2E) delay(900);
[006A] (2C) UserputOff();
[006C] (91) animateCostume(VAR_EGO,255);
[0070] (19) doSentence(STOP);
```

Now seems to run in almost exactly 10 minutes. Which I guess is at the very least the _intention_ of the script.

**Comment by eriktorbjorn** [comment]
At least the part up until the final convulsions seems to run at the same speed as in DOSBox now. If there are differences in the final animation, that's a different problem. I'd have to record them and watch side by side to have a chance to spot that, though.

**Comment by eriktorbjorn** [comment]
Here's a DOSBox/ScummVM comparison I made and uploaded to YouTube:

https://www.youtube.com/watch?v=9kOSkhxUCEs

**Pull request merged**
