### PR TITLE
COMMON: Fix undefined-var-template warning with CLang

### PR DESCRIPTION
**Pull request by lephilousophe**
Another take after #4383.
This has the advantage to be a one line fix which seem to silence the warnings.
Let's see what Github CI think about it.

### CODE REVIEW

**Comment by lephilousophe** [comment]
Sadly, the one-line wasn't working with GCC.
Trying to fix it made me realize the problems with other implementations than what current ScummVM code has.

In eefa72afa1978a9dea10f5b1833fcc8f58a3468e, the singleton variable was defined in a generic fashion and there were several instances of it lying around (across plugins).

In #4883, the singleton variable was hidden inside a template function.
This has the disadvantage of needing a call to the function every time we need the instance.
In addition, I am not sure we won't end up with multiple instances either if compiler decides to inline.
ODR should prevent this, but with plugins I would say we would get the same result as in eefa72afa1978a9dea10f5b1833fcc8f58a3468e.

Currently, the static variable is defined once and its access can be inlined.
Main drawback is that we need to ignore a warning in clang.

Using `template <class T> T *Singleton<T>::_singleton;` fails in GCC because it considers it as a generic definition (with standard constructor) and we get multiple definitions.
We then end up in the same situation as eefa72afa1978a9dea10f5b1833fcc8f58a3468e.

I tried another route by explicitely declaring the singleton variable (like in https://stackoverflow.com/questions/56463004/fixing-warning-wundefined-var-template) and now MSVC is failing and GCC still silently creates duplicates variables.

On the other hand, using `extern template T *Singleton<T>::_singleton` fails in clang.

I would say we are kind of stuck here so here is a proposal with compiler specific checks. Really not elegant!

**Comment by sev-** [comment]
I am not impressed by the fact that now we need to declare a singleton and then define it in a separate file, and wrapping around the namespaces along the way.

Is there a way to still keep it in a single #define?

The fact that it could require compiler-specific definition is, unfortunately, an unavoidable evil.

**Comment by lephilousophe** [comment]
After more investigation, I managed to get rid of the compiler specific (at least it works properly on GCC and CLang).
But I can't get rid of the warning without adding a declaration for every singleton.
It seems you can't declare in a generic way a static member data, it you try do this, it is a definition (with default constructor) and then you end up with multiple definitions of the instance.

**Comment by lephilousophe** [comment]
This fails in MSVC.
I don't really understand why it only fails in cloudmanager.cpp but a quick test in godbolt seems to indicate that adding `/permissive-` fixes the build.
I think it's too intrusive so I would vote on closing this PR.

**Comment by sev-** [comment]
Ok, let's close it then.

**Pull request closed without merging**
