### PR TITLE
* Ultima:Nuvie: Fix show_spell_description

### PR DESCRIPTION
**Pull request by malignantmanor**
when spellbook is not full

### CODE REVIEW

**Comment by bluegr** [comment]
Can you provide more info on what is the actual issue here?

**Comment by malignantmanor** [comment]
When you use the look command to look at the spell incantation and reagents required, it gets the wrong index if there are any missing spells on that page before the one you try to look at.

You can test it with the starting spell book. Detect magic shows create food because there is one missing spell before it.  Light shows douse because there are 5 missing spells before it. All the spells in that book will show the wrong spell in look mode.

This happens in all styles. If you use the Alt-w cheat it will show the right spell because there are no longer any missing spells. This bug existed before moving to Scummvm and might not have ever worked right.

**Comment by digitall** [comment]
@malignantmanor : Thank you for your code contribution. One minor point, the prefix for your commit message should be "ULTIMA: NUVIE:". If you could fix by rebase edit of the messages that will make this easier to merge:
https://wiki.scummvm.org/index.php?title=Commit_Guidelines#Commit_message_formatting

**Comment by bluegr** [comment]
Nice catch! Squashing, to remove the merge commit

**Pull request merged**
