### PR TITLE
GUI: Add a tab for backend-specific options

### PR DESCRIPTION
**Pull request by ccawley2011**
As a demonstration, this is implemented in the Android backend, which replaces the use of the ``kFeatureTouchpadMode`` and ``kFeatureOnScreenControl`` features.

### CODE REVIEW

**Comment by antoniou79** [comment]
It's an interesting change. Is this done to provide better isolation for such features ?  (These features already appeared in a "Control" tab separately, but the code behind that was not a clear that those were backend specific?)

My main concern is whether a regression would be introduced by the example case for Android -- since in a previous fix (https://github.com/scummvm/scummvm/commit/e25ac0bc55d88bb8761450e460ba8b4cd0674145#diff-d112ba6d5371b6b878f86ddd82035bd646f53e85e0a2cc5164233b36f009c11d) I thought it would be better to explicitly set values for un-configured settings so that they would have actually their "keys" registered with ConfMan and hasKey() (if used by any external method, before retrieving the key value) would return "true" properly.

**Comment by ccawley2011** [comment]
> It's an interesting change. Is this done to provide better isolation for such features ? (These features already appeared in a "Control" tab separately, but the code behind that was not a clear that those were backend specific?)

Yes, that was part of the reason for doing this. The other part was to allow the custom dialogs in some of the other ports to be replaced with something that's integrated into the main GUI.

> My main concern is whether a regression would be introduced by the example case for Android -- since in a previous fix ([e25ac0b#diff-d112ba6d5371b6b878f86ddd82035bd646f53e85e0a2cc5164233b36f009c11d](https://github.com/scummvm/scummvm/commit/e25ac0bc55d88bb8761450e460ba8b4cd0674145#diff-d112ba6d5371b6b878f86ddd82035bd646f53e85e0a2cc5164233b36f009c11d)) I thought it would be better to explicitly set values for un-configured settings so that they would have actually their "keys" registered with ConfMan and hasKey() (if used by any external method, before retrieving the key value) would return "true" properly.

That shouldn't be an issue in this case, since `registerDefaultSettings` is called much earlier in initialization than `initBackend` is, which seems to fix the problem.

**Comment by antoniou79** [comment]
Then the changes look good to me.

**Comment by criezy** [comment]
This seems like a good idea to me, and one that could potentially be useful of the iOS backend.
And from a quick glance the implementation in this PR looks OK.

**Comment by bluegr** [comment]
I also love these changes :) Nice work!

**Comment by lotharsm** [comment]
Can we merge this soon so I can rebase https://github.com/scummvm/scummvm/pull/2621 onto it?

**Comment by lotharsm** [comment]
If there are no objections, I'll merge it this weekend, so we can progress with the other upcoming GUI changes.

**Comment by criezy** [comment]
I merged it manually to fix conflicts.

**Pull request closed without merging**
