### PR TITLE
GRIM: Support transcoding Traditional Chinese to Simplified in monkey4

### PR DESCRIPTION
**Pull request by phcoder**
This is on top of my other PR that adds support for Chinese in Monkey4

### CODE REVIEW

**Comment by sev-** [comment]
This must be rebased.

**Review by sev- — APPROVED** [review]
Looks good to me

**Comment by sev-** [comment]
@coderabbitai review

**Comment by bluegr** [comment]
I used the github GUI to resolve the conflicts, but that unfortunately creates a merge commit. This will need to be properly rebased

**Comment by sev-** [comment]
Thank you!

**Pull request merged**
