### PR TITLE
AGS: Organizes entries into "Reality-On-The-Norm" and "Maniac Mansion…

### PR DESCRIPTION
**Pull request by MarcoBorrini99**
This PR adds two big sections _Reality-On-The-Norm_ and _Maniac Mansion Mania_ and moves related entries into them (120 for RoN and 250 for MMM) without adding new content.

Just checked with my archive wthout apparent issues.

### CODE REVIEW

**Comment by tag2015** [comment]
Thanks for your work, Personally, I'm a bit conflicted about this change mostly because in the future (hopefully not too far) we plan to move the detection tables to external files, so it's advisable to avoid huge "cosmetic" changes that  may be unneeded/can't be transferred to the new system.
Also, from a practical point of view this PR is quite hard to review. It would have been much better with multiple smaller commits

**Comment by MarcoBorrini99** [comment]
> Thanks for your work, Personally, I'm a bit conflicted about this change mostly because in the future (hopefully not too far) we plan to move the detection tables to external files, so it's advisable to avoid huge "cosmetic" changes that may be unneeded/can't be transferred to the neiting forw system. Also, from a practical point of view this PR is quite hard to review. It would have been much better with multiple smaller commits

Your point of view Is very clear. Probably this PR should be closed. I'll rearrange it later if applicable

**Comment by bluegr** [comment]
Regardless of the future change to detection entries, it would be good to keep this work, since the grouping of these entries would help a lot in the future.

@MarcoBorrini99 could you please split your changes into smaller commits, so that's easier to review the changes? Right now, it's impossible to review this, and your changes affect a lot of other game entries, too

**Comment by tag2015** [comment]
For reference, on the [wiki](https://wiki.scummvm.org/index.php?title=AGS/Games#Maniac_Mansion_Mania_games) the MMM games are already grouped
One potential issue with RotN is that there are many pre-2.5 games. So you either have two groups, or a single group mixing both supported and unsupported games

**Comment by MarcoBorrini99** [comment]
Undoubtedly it is not particularly easy to follow this huge commit. I will think about whether it is worth rolling back or not to focus on more understandable commits.

ps
@tag2015 My commit already implemented 2 groups for supported and unsupported RotN titles.

**Comment by tag2015** [comment]
> ps @tag2015 My commit already implemented 2 groups for supported and unsupported RotN titles.

Yes I noticed, what I meant is that there's no perfect solution and it's a matter of taste
Anyway, I recently updated the wiki to group the RoN games (see https://wiki.scummvm.org/index.php?title=AGS/Games#Reality-On-The-Norm_games , click expand to view)
If you want you can compare it with your changes and see if there are differences, and decide if you still want to apply the grouping to the detection tables or if the wiki is enough

**Comment by MarcoBorrini99** [comment]
Honestly, I had never considered the wiki as a documentation source for these purposes (my fault). In addition, there are very few differences with my work, so I'd prefer to bring suggestions to the wiki.

I'd like to wait for the official 2.9.0 release to generally update freeware games, Maniam Mansion, Maniam RotN, etc. Is this acceptable?

**Comment by tag2015** [comment]
> I'd like to wait for the official 2.9.0 release to generally update freeware games, Maniam Mansion, Maniam RotN, etc. Is this acceptable?

Sure, whenever you want.
In any case, this PR should probably be closed. There are several conflicts and to split the changes in multiple commits it'll be easier to start from scratch

**Comment by bluegr** [comment]
> > I'd like to wait for the official 2.9.0 release to generally update freeware games, Maniam Mansion, Maniam RotN, etc. Is this acceptable?
> 
> Sure, whenever you want. In any case, this PR should probably be closed. There are several conflicts and to split the changes in multiple commits it'll be easier to start from scratch.

Indeed. This PR is very hard to read, and now we got a lot of conflicts. @MarcoBorrini99, please open a new PR when you have a clearer set of changes.

Closing

**Pull request closed without merging**
