### PR TITLE
AMIGAOS: Few additions and changes to AmigaOS target

### PR DESCRIPTION
**Pull request by raziel-**
Pending feedback from @BeWorld2018 and @theIDinside (emscripten author, though i didn`t touch the code itself)
Also still need to check with a full build (looks promising though)

Any other feedback (especially gcc gurus and dynamic stuff) welcome (looking at you @lephilousophe) :-D
Please ask, if you find something odd, so i can revise and maybe even rethink a change

configure, line 2572ff
- Streamlined target
- Added some gcc safeguard switches
- Fixed comments and a typo

configure, line 4036ff to 4113ff
- Sort emscripten dynamic target alphabetically

I'd like to get your confirmation on the next changes, since it also touches MorphOS.
Otherwise i'll have to split targets.

Conforming to many of the other platforms use of plugin naming
and to distinguish between ScummVM's engine plugins and the OS'
shared objects/libraries names.
configure, line 4051ff
- Changed plugin naming

configure, line 4055ff
- Added use of dl library for dynamic
 builds
- Added "x" flag to "strip" to preserve global symbols for dynamic builds
(honestly stolen from @dwatteau and his PR https://github.com/scummvm/scummvm/pull/3877) ;-)

I hope i did it correctly this time.
Probably cherry picking is possible too now?

Thank you

### CODE REVIEW

**Comment by dwatteau** [comment]
> Added "x" flag to "strip" to preserve global symbols for dynamic builds

Does it really fix something on AmigaOS? I thought calling `strip` with `-x` in this use-case was only necessary for Mach-O/Apple toolchains. GNU binutils on (ELF) Linux doesn't need this flag AFAIK, but maybe AmigaOS chose to behave like macOS.

**Comment by raziel-** [comment]
@dwatteau 

It's a test case/setup, hence the [DO NOT MERGE]

After reading through your PR for MacOS I tought the "can't load plugins without using the -x flag" might also be why I'm getting random plugin load fails and maybe this will remedy the situation, maybe not,  we'll see.

Otoh my problems with plugin loading could have a completely different cause...not really possible to debug here due to missing debuggers...so I'm taking everything I can get.

With this setup and two plugins in place I haven't had a single crash yet, so...here's hoping :-)

**Comment by raziel-** [comment]
I'm good to go.

Tested every engine i own games for and no more crashing plugins.
Also no more crashing shared objects on accessing them.

Some, one or all of the changes seem to have fixed the problems.

Still want to wait for @BeWorld2018 if he'd be ok with the changes.

Any other remarks?

Thank you very much

**Comment by raziel-** [comment]
@chkuendig 

Did i address the wrong emscripten author/maintainer?
My bad, sorry for that...

**Comment by raziel-** [comment]
@bluegr

Since i don't seem to get any feedback from the persons I linked, I have split the targets to not touch MorphOS anymore.

Other than that, it's finished from my side

**Comment by lephilousophe** [comment]
It seems to be safe to merge.
AmigaOS got checked by @raziel-, morphOS has been split, and emscripten edit is just a matter of sorting.

**Comment by chkuendig** [comment]
This is fine from my end. Sorry for the delay. It might conflict with https://github.com/scummvm/scummvm/pull/3046, but this shouldn't be a blocker (i'm still stuck with that PR)

**Comment by raziel-** [comment]
@chkuendig 

Oh  sorry, I didn't know you had one PR waiting...

What should I do?

**Comment by chkuendig** [comment]
Dont worry, merge yours. Ill adjust. As mentioned, mine isnt 100% ready and im somewhat short on time right now

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by raziel-** [comment]
@chkuendig 

Thank you...

**Comment by bluegr** [comment]
Thanks for your work on this, and thanks for the additional feedback!
Merging

**Comment by lephilousophe** [comment]
@raziel- This PR fails to build on buildbot because of `-ldl` (we don't have libdl in the cross compilation toolchain).
Could you check if it's really needed?
As AmigaOS port is using SDL we use SDL facilities to load plugins so libdl should not be needed.
Plus, dlopen function is only used in posix-provider.cpp which is not built under AmigaOS.

**Comment by raziel-** [comment]
@lephilousophe 

I'll do a full build without -ldl and some testing.

Maybe the -mlongcall and strip -x were sufficient for the errors to away...

**Comment by lephilousophe** [comment]
Yes I hope so

**Pull request merged**
