### PR TITLE
COMMON: Mark more symbols as const

### PR DESCRIPTION
**Pull request by ccawley2011**
This should help reduce memory usage a bit on platforms where the executable is in read-only memory.

### CODE REVIEW

**Comment by lephilousophe** [comment]
Looks great!
I suppose that fixing one missing `extern PluginType g_##ID##_type; \` in plugins.cpp will make it build on Windows

**Comment by sev-** [comment]
Yay, great work. Could you please rebase it, so it is mergeable?

**Comment by ccawley2011** [comment]
> Yay, great work. Could you please rebase it, so it is mergeable?

OK, done.

**Comment by ccawley2011** [comment]
I've also added a couple of extra commits that should help out a bit with reducing the amount of writable static data.

**Comment by sev-** [comment]
Thank you!

**Pull request merged**
