### PR TITLE
MAKEFILE: Add dependencies for scummvm.rc

### PR DESCRIPTION
**Pull request by orgads**
When an engine is added or removed, it affects the embedded resources in
scummvm.rc, so config.mk is required.

Apart from that, list all the files it uses and set them as dependencies,
so if a file changes, the resource file will be rebuilt.

### CODE REVIEW

**Comment by orgads** [comment]
Don't merge yet. I need to run some more tests.

**Comment by orgads** [comment]
@ccawley2011 @digitall (others are welcome too ;))

This change currently lists all the required dependencies. Do you think it is valuable to have automatic tracking? I have a preliminary proposal in #2921 but I'm a bit reluctant about it. See my comment there.

What do you think?

**Comment by digitall** [comment]
@orgads: This change looks reasonable. I would suggest that it is not an exclusive-or situation. This PR should be merged and tested as an improvement... then the merits and issues with PR #2921 for automatic dependency tracking can be dealt with.

**Comment by orgads** [comment]
I agree. Merging then.

**Pull request merged**
