### PR TITLE
GLK: Fix build for Symbian.

### PR DESCRIPTION
**Pull request by fedor4ever**
This allow use remove() function.

### CODE REVIEW

**Comment by lephilousophe** [comment]
According to @ccawley2011 this function and some others aren't used and could be removed.
This PR would be useless then.

**Comment by fedor4ever** [comment]
What functions should be removed?

**Comment by sev-** [comment]
Obviously, the one, using `remove()`

**Comment by sev-** [comment]
Closing this as incorrect. The `remove()` usage should be removed from the GLK engine

**Pull request closed without merging**
