### PR TITLE
PINK: Supports Hebrew text font and alignment

### PR DESCRIPTION
**Pull request by Quote58**

### CODE REVIEW

**Comment by bluegr** [comment]
Overall, this looks good. One of the commits still has issues with its formatting (it's missing the prefix)

**Comment by Quote58** [comment]
> Overall, this looks good. One of the commits still has issues with its formatting (it's missing the prefix)

Thanks! What prefix is missing?

**Comment by Quote58** [comment]
Oh wait do you mean the title of the if statement format commit? Shoot, I forgot since I was editing that part after the fact. I will make sure to fix that.

**Comment by bluegr** [comment]
Great work, thanks! Merging

**Pull request merged**
