### PR TITLE
COMMON: Allow registering multiple event mappers

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by aquadran** [comment]
can you put some description, why this change? :)

**Comment by ccawley2011** [comment]
I'm hoping to rebase PR #401 at some point, and this is necessary for it to co-exist with the keymapper.

**Comment by OMGPizzaGuy** [comment]
This makes sense to me. I considered recommending KeymapMatch for mapEvent return type, but the bool is likely more appropriate.

**Comment by sev-** [comment]
Thank you, merging

**Comment by criezy** [comment]
The change from this pull request causes every Esc key events to be sent twice. Any idea why that is?
It seems to only happen with the Esc key.

I first noticed it in the AGS, engine, but you can see that in the Launcher as well. By default the Esc key closes the current dialog, and now if you open the Options dialog and then press Esc it closes not only the Options dialog, but also the Launcher (and thus quits ScummVM). And if from the Options dialog you open the Fluidsynth dialog, pressing Esc once will close both the Fluidsynth and the Options dialog, and you end up in the Launcher.

**Comment by criezy** [comment]
> The change from this pull request causes every Esc key events to be sent twice. Any idea why that is?

Fixed in 63cef724f892d718973682183da20f659d39e988 I think.
I hope the fix is fine. I fixed the Escape key down/up events being sent twice, and the formatting of the code suggested that the `;` after `if (!matchedAction)` was indeed not supposed to be there.
I am not quite sure why the Escape key is mapped to itself, but that caused it to be dispatched as a mapped event and then again as a non-mapped one.

**Pull request merged**
