### PR TITLE
GLK: Remove proxy ctors and copy assignment operator

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by bluegr** [comment]
Thanks, merging

**Comment by criezy** [comment]
It seems to have broken compilation for some platforms on buildbot:
```
In file included from ../../src-master/src/engines/glk/quest/quest.h:29,
                 from ../../src-master/src/engines/glk/metaengine.cpp:49:
../../src-master/src/engines/glk/quest/string.h:42: error: 'Common::String::String' names constructor
../../src-master/src/engines/glk/quest/string.h: In member function 'Glk::Quest::String Glk::Quest::String::substr(size_t, size_t) const':
../../src-master/src/engines/glk/quest/string.h:54: error: no matching function for call to 'Glk::Quest::String::String(const char*, const char*)'
../../src-master/src/engines/glk/quest/string.h:40: note: candidates are: Glk::Quest::String::String()
../../src-master/src/engines/glk/quest/string.h:40: note:                 Glk::Quest::String::String(const Glk::Quest::String&)
../../src-master/src/engines/glk/quest/string.h: In member function 'Glk::Quest::String Glk::Quest::String::substr(size_t) const':
../../src-master/src/engines/glk/quest/string.h:57: error: no matching function for call to 'Glk::Quest::String::String(const char*)'
../../src-master/src/engines/glk/quest/string.h:40: note: candidates are: Glk::Quest::String::String()
../../src-master/src/engines/glk/quest/string.h:40: note:                 Glk::Quest::String::String(const Glk::Quest::String&)
In file included from ../../src-master/src/engines/glk/quest/geas_runner.h:27,
                 from ../../src-master/src/engines/glk/quest/quest.h:30,
                 from ../../src-master/src/engines/glk/metaengine.cpp:49:
../../src-master/src/engines/glk/quest/geas_state.h: In constructor 'Glk::Quest::SVarRecord::SVarRecord(Glk::Quest::String)':
../../src-master/src/engines/glk/quest/geas_state.h:75: error: no matching function for call to 'Glk::Quest::SVarRecord::set(int, const char [1])'
../../src-master/src/engines/glk/quest/geas_state.h:83: note: candidates are: void Glk::Quest::SVarRecord::set(uint, Glk::Quest::String)
../../src-master/src/engines/glk/quest/geas_state.h:91: note:                 void Glk::Quest::SVarRecord::set(Glk::Quest::String)
```

See https://buildbot.scummvm.org/builders/master-dingux/builds/6886/steps/compile/logs/stdio for all the errors for one of those.

**Comment by orgads** [comment]
Ah, using ctor is C++11. 😞 

I'll fix it.

**Comment by orgads** [comment]
Do you have a way to test if https://github.com/scummvm/scummvm/pull/2852 fixes it?

**Comment by criezy** [comment]
No easily without merging the PR.
Personally I keep a Debian VM around with an old compiler to test those kind of things, but in this case it seems easier to merge your PR and see how buildbot reacts to it.

**Comment by criezy** [comment]
This fixed it for at least one of the targets. 👍 
Another one failed for a different reason not related to your commits, and the third one is still running.

**Pull request merged**
