### PR TITLE
I18N: Updated German language file

### PR DESCRIPTION
**Pull request by rootfather**
Hello guys,

I worked together with Simon Sawatzki @SimSaw on the German translation back in 2010 or 2011. Shortly after, I retired from the German translation team and stopped working on the files. Busy life, you know.

But know I left my "Retirement Castle" and want to contribute some localization stuff on a regular base. I started with updating the german language file and doing some "maintenance" to it.

A short summary of today's work:
* translation added for a few missing strings
* fixed a few typos
* replaced all "" with '' to match the original template
* re-translated some strings to make the localization more consistent
* optimized translations for some settings to make the translation more accurate
* updated the translation file version from 1.5.0git to 1.8.0git

Note to yesterday's pull request that I had to "emergency-close": Yesterday, I submitted a .po file that had serious problems with the encoding, thanks to some CR/CRLF conversion stuff and quite dumb attempts on my side to fix this. Of course I noticed most of the problems *after* opening the pull request. This time, the file is clean :)

Best regards
Lothar Serra Mari, aka rootfather
formerly known as Lothar93

### CODE REVIEW

**Comment by SimSaw** [comment]
Hi Lothar! Nice to see you again! You've been away for ages and I wasn't able to contact you besides my best efforts.

Please do not merge this as I still need to review this. I noticed some disimprovements like you changed "Paths" to "Verzeichnisse". However, this string would be too long too display as a tab. Will do the review this weekend.

**Comment by rootfather** [comment]
Hello out there,

I'm currently in touch with Simon about some flaws I introduced in the current revisions of the updated language file. As Simon said, I *highly* recommend *NOT* to merge the commits at the current state, because it would make the translation worse than it was before.

I am currently in touch with Simon - thank you for your fast and very good answer! I think he will tell you when it's time to merge this pull request.

Best regards
Lothar

**Comment by rootfather** [comment]
I merged my repository with scummvm/scummvm and solved the conflicts - now the pull request can be automatically merged again.

**Comment by criezy** [comment]
Can you confirm is this is still being reviewed by Simon and we should wait before merging, or if this can be merged now?

**Comment by rootfather** [comment]
Although I don't think we have major problems with the translation at the current state, we should wait for Simon's final review.

**Comment by SimSaw** [comment]
I have done my review now and the issues in question have all been solved now. This is OK to merge. Thanks for your patience!

**Comment by rootfather** [comment]
Also everything clear from my side. Ready for merging :)

**Comment by rootfather** [comment]
@criezy can you merge this request?

**Comment by criezy** [comment]
I will handle this after I am back home on Friday (I am in The Netherlands for my work this week).

**Comment by criezy** [comment]
I have rebased those commits (getting rid of commits 9f23934 and 190bb4a in the process), cleaned some changes (e.g. I suspect the change of the language in the GUI from 'Deutsch' to 'de' was not done on purpose so I reverted it) and dropped commit 0b29057 (and replaced it with the proper way to update the credits after changing credits.pl).

This should all be in our repository now. Thanks for your work.

**Pull request closed without merging**
