### PR TITLE
GLK: ADRIFT Detection Table updates

### PR DESCRIPTION
**Pull request by MarcoBorrini99**
This PR simply adds 8 new entries and some more data reorganizazion in vaious sections.

PS:
it's really difficult to put versioning info for ADRIFT5 titles

### CODE REVIEW

**Comment by digitall** [comment]
@MarcoBorrini99 You can use "git rebase" on the branch in future, then force push to change the PR to remove the spurious commits. I should be able to do this for you as once a branch is pushed as a PR, github gives upstream developers permissions to change the branch by default (one of the other reasons you should never PR from your master branch(es) here :)

**Comment by digitall** [comment]
@MarcoBorrini99 : Done...

**Comment by MarcoBorrini99** [comment]
> @MarcoBorrini99 You can use "git rebase" on the branch in future, then force push to change the PR to remove the spurious commits. I should be able to do this for you as once a branch is pushed as a PR, github gives upstream developers permissions to change the branch by default (one of the other reasons you should never PR from your master branch(es) here :)

Let's say I did something concpetually not very smart... committing to a renamed already merged branch (It was late that moment).

**Comment by tag2015** [comment]
Why did you close the PR? There are problems with the entries?

**Comment by MarcoBorrini99** [comment]
> Why did you close the PR? There are problems with the entries?

I think I've suffered a breach in my github account, so (probably exaggerating) I've deleted my forks. I'll reopen the same PR this evening along with a update to AGS detection_table.h

**Pull request closed without merging**
