### PR TITLE
HYPNO: Reduce memory usage when opening .lib archives

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by neuromancer** [comment]
This looks good, but it will be merged after master is unfrozen just in case. Btw, do you know much memory is saved using `MemoryReadStream`?

**Comment by ccawley2011** [comment]
> This looks good, but it will be merged after master is unfrozen just in case. Btw, do you know much memory is saved using `MemoryReadStream`?

I'm not sure about exact figures, but loading all archive entries into memory up front causes the DS port to run out of memory when the engine starts, while only loading entries on demand allows Wetlands to start correctly.

**Comment by neuromancer** [comment]
Neat!, how is the general experience of playing Wetlands in the DS using your PRs? Is it playable?

**Comment by ccawley2011** [comment]
> Neat!, how is the general experience of playing Wetlands in the DS using your PRs? Is it playable?

It's playable, but can be slow in places. PR #3963 helps, though, and I'm currently investigating some optimizations in the Smacker decoder which may also improve things.

**Comment by neuromancer** [comment]
Please solve the conflict, so I can merge it. Thanks a lot! :slightly_smiling_face:

**Comment by bluegr** [comment]
Thanks for your work!
Fixed the conflict - squashing into master, since @neuromancer approved this

**Comment by neuromancer** [comment]
Awesome work, thanks @ccawley2011 and @bluegr

**Pull request merged**
