### PR TITLE
AMIGAOS: Update md2ag.rexx

### PR DESCRIPTION
**Pull request by raziel-**
Janitorial and optimize

I need a little help, i forgot how to update the corresponding .in file

### CODE REVIEW

**Comment by criezy** [comment]
> I need a little help, i forgot how to update the corresponding .in file

It looks like you actually forgot how to update the `md2ag.rexx` file itself 😄 
The way you would normally do it is to manually update the `md2ag.rexx.in` file with the changes you want to do, and then run the `devtools/update-version.pl` to regenerate the `md2ag.rexx` file.
The script takes the version as argument, so currently it has be run as `devtools/update-version.pl 2 6 0 git`.
This approach however assumes you have perl available on your platform. If not you would need to ask somebody else to run it for you after changing the `md2ag.rexx.in` file.

**Comment by raziel-** [comment]
@criezy 

I´m pretty sure i broke it, but would it work now?

**Comment by lephilousophe** [comment]
The changes seem OK for me. I hope it won't break buildbot REXX interpreter but we will see that in time.

**Comment by criezy** [comment]
I have checked that running `devtools/update-version.pl 2 6 0 git` now produces the same `md2ag.rexx` as you have in your first commit. So your update of the `md2ag.rexx.in` file is at least consistent with that.

So I think we can merge this now.

**Pull request merged**
