### PR TITLE
AUDIO: Support mono audio output in the mixer

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by AndywinXp** [comment]
Good one! 

Related: do you (or anyone else) think it's feasible to have a GUI option to force mono audio in the Sound tab, as an accessibility feature?

**Comment by ccawley2011** [comment]
> Related: do you (or anyone else) think it's feasible to have a GUI option to force mono audio in the Sound tab, as an accessibility feature?

Sounds interesting, but it might require a fair bit of extra work to allow changing the mixer settings at runtime without deleting and recreating the mixer object.

**Comment by AndywinXp** [comment]
> > Related: do you (or anyone else) think it's feasible to have a GUI option to force mono audio in the Sound tab, as an accessibility feature?
> 
> Sounds interesting, but it might require a fair bit of extra work to allow changing the mixer settings at runtime without deleting and recreating the mixer object.

My idea was even more "simple": I didn't mean for this feature to be toggleable on the GMM, but on the global ScummVM options.

**Comment by ccawley2011** [comment]
> My idea was even more "simple": I didn't mean for this feature to be toggleable on the GMM, but on the global ScummVM options.

It may still be somewhat problematic to delete the mixer if, for example, we start using `Audio::Mixer` to implement text to speech support. For now I've implemented selecting mono audio from the command line when using the SDL backend, and proper GUI integration can be revisited later.

**Comment by AndywinXp** [comment]
Thanks! 🙏 great job!

**Comment by sev-** [comment]
Looks good, thank you!

**Pull request merged**
