### PR TITLE
BACKENDS: Fix codestyle in sdl-graphics.cpp and sdl-graphics.h.

### PR DESCRIPTION
**Pull request by fedor4ever**
See #3170.

### CODE REVIEW

**Comment by sev-** [comment]
What is this obsession with the full stops after every comment? Where does it come from?

**Comment by fedor4ever** [comment]
Mindless copy from #3170. I think it's OK...
Less stupid work is good.

**Comment by bluegr** [comment]
I totally agree with @sev- on this. This pull request just adds full stops after every comment. I really don't see any point in this, plus we really can't update all the existing comments with full stops just for the heck of it. I propose to close this, together with all the other PRs with such changes

**Comment by sev-** [comment]
Indeed, and moreover, the comment is misleading. It is not code style but comment style

**Comment by fedor4ever** [comment]
I stop to waste my time with #3220.

**Pull request closed without merging**
