### PR TITLE
README: add Adibou 1 & 2 in the list of supported games (GOB)

### PR DESCRIPTION
**Pull request by BJNFNE**

### CODE REVIEW

**Comment by bluegr** [comment]
You will also need to update at least the English manual

**Comment by BJNFNE** [comment]
where is the English manual located?

**Comment by sev-** [comment]
The English README in that form is gone. However, it does exist in cz/ and se/ directories. So, perhaps you could sync those too?

**Comment by BJNFNE** [comment]
@sev- done, could you squash it for me? Thanks

**Comment by sev-** [comment]
Thank you!

**Pull request merged**
