### PR TITLE
DEVTOOLS: Fix create_xeen compilation without C++11

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by orgads** [comment]
@Ardash Please review.

**Comment by Ardash** [comment]
In constants.cpp need to change Common::Language::XXX to Common::XXX in two places. If I had permissions, I can fix this
@orgads

**Comment by Ardash** [comment]
Working on it

**Comment by orgads** [comment]
I'm fixing it. Actually compiling now without c++11 :)

**Comment by Ardash** [comment]
Sorry, I haven't seen that's another PR, not mine :)

**Comment by orgads** [comment]
Done. It compiles now. Please review.

**Comment by orgads** [comment]
@Ardash?

**Comment by Ardash** [comment]
I've reviewed all files and I think it's ready for merge.

**Review by Ardash — APPROVED** [review]

**Pull request merged**
