### PR TITLE
AGS: Fix lzwexpand on strict-alignment platforms

### PR DESCRIPTION
**Pull request by dwatteau**
This fixes [Trac#15179](https://bugs.scummvm.org/ticket/15179), where starting Maniac Mansion Deluxe would trigger a SIGBUS on my mips64el device which doesn't allow unaligned memory loads.

This was also caught by `--enable-ubsan` on regular x86: 

``` 
engines/ags/shared/util/lzw.cpp:225:32: runtime error: load of misaligned address 0x5e50b242f227 for type 'const int16_t', which requires 2 byte alignment
0x5e50b242f227: note: pointer points here
 00 00 c8 00 00  d0 00 d0 ff 00 d0 00 d0  00 d0 00 d0 00 d0 00 d0  00 d0 00 d0 ff 00 d0 00  d0 00 d0
             ^ ```
```

Making this a PR, just for a double check, and also to know whether I should send this to upstream AGS as well? Thanks.

### CODE REVIEW

**Comment by bluegr** [comment]
> This fixes [Trac#15179](https://bugs.scummvm.org/ticket/15179), where starting Maniac Mansion Deluxe would trigger a SIGBUS on my mips64el device which doesn't allow unaligned memory loads.

Great work!

> Making this a PR, just for a double check, and also to know whether I should send this to upstream AGS as well? Thanks.

Looks good to me. And yes, please send this to upstream AGS, they'll be more than happy for any help provided :)

**Review by bluegr — APPROVED** [review]
LGTM

**Comment by dwatteau** [comment]
So, I took the feedback from upstream AGS, and changed the PR so that it uses `Memory::ReadInt16LE()` (instead of `memcpy()`) as was suggested there.

This requires `Memory::ReadInt16LE()` to have its strict-alignment measures turned on, which wasn't the case until now, because we didn't forward our `SCUMM_NEED_ALIGNMENT` define to the `AGS_STRICT_ALIGNMENT` one internally expected by AGS. I've fixed that as well in a new commit.

**Comment by bluegr** [comment]
Thanks! Awaiting for PR #6174 before proceeding with this one

**Comment by bluegr** [comment]
Now that #6174 has been merged, this can be merged.
Thanks for your work!

**Pull request merged**
