### PR TITLE
SCI32: Fix QFG4 Wraith fan-patch, bug #10711

### PR DESCRIPTION
**Pull request by sluicebox**
This excludes NRS patches 53.HEP/SCR from QFG4CD since they introduce a lockup bug with wraiths. (Occurs when game-time global 88 is >= $8000.) The GOG release includes every NRS patch except this one.

The only consequence to excluding is that it can break existing save games, but since this game is tagged as unstable, and this only affects save games using this patch that also have the wraith script currently loaded, I think that's acceptable.

I think we should support the rest of the NRS patches in this game since the GOG release includes them, making them effectively a real version, and since this game is so buggy that fans are likely to have already applied them.

By "support" I just mean:
	- Don't enable the "fan-made patch" warning
	- Do our best to make our script patches compatible

I've looked at each patch file and the changes are so minor that I don't think there will be more problems, but if there are we can exclude them too. This patch was just missing an Abs() call that the others have. 

Making script patches compatible just means minding differences in offsets and operand sizes, which needs to be done anyway for multi-version patches, and this only applies when patching of the 11 NRS scripts. I already did that for the Ad Avis room and it's hard to imagine anything being harder than that. (I HOPE)

### CODE REVIEW

**Comment by sluicebox** [comment]
Alternative: we could patch the script, it looks like just a one-byte patch to change a signed less-than to an unsigned-less-than would do it.

**Comment by bluegr** [comment]
> Alternative: we could patch the script, it looks like just a one-byte patch to change a signed less-than to an unsigned-less-than would do it.

Fixing the patch is better than excluding it altogether, so please go with that option

**Comment by sluicebox** [comment]
Great, I'm happy to do it the fun way. =)

This immediately fixes the locked up saved game in the bug tracker, upon loading the wraith will animate and the game will proceed.

**Comment by bluegr** [comment]
Great! Thanks :)

**Pull request merged**
