### PR TITLE
manpage: update cmdline options and hotkeys

### PR DESCRIPTION
**Pull request by kparal**
Add missing cmdline options and hotkeys to the manpage. Add long options
where they were missing. Update existing options description and values.
Improve formatting for important words, arguments, etc. Sort the options
in the same way they are sorted in README, so that future synchronization
is easier. Add info into several places saying that README is more
comprehensive than this manpage.

----

Hello, it took me a while to realize that your manpage contained much less information than the readme file. I decided to fix that and update it. This is my first time editing a manpage, I wasn't familiar with the syntax, but I verified in renders fine for me (Fedora 29).

### CODE REVIEW

**Comment by digitall** [comment]
@kparal : Looks good. Will give it a bit of time for review and comments, but should be fine to merge. Thanks.

**Comment by lotharsm** [comment]
Looks good to me too. Thanks for your work!

**Comment by digitall** [comment]
Since there appear to be no objections and this looks fine, merging as-is.

**Comment by kparal** [comment]
Thanks. And also thanks for working on a great and very useful project.

**Pull request merged**
