### PR TITLE
WINTERMUTE: Printable flag fix, more keyboard mapping, array index check at vKeyToKeyCode()

### PR DESCRIPTION
**Pull request by lolbot-iichan**
1. _currentPrintable was set depending on _currentCharCode, which is 112
for both F1 and 'p' keys, fixed after detailed research on which keys
should be considered printable
2. some keypresses was producing warnings because was not listed in
mappings, added
3. vKeyToKeyCode was not safe if vkey > KEYSTATES_ARRAY_SIZE was
provided, fixed

### CODE REVIEW

**Comment by tobiatesan** [comment]
Looks okay on a cursory glance.
Does not seem to break anything when running either.
I'm satisfied with the changes, if others and particularly @somaen do not complain I'd merge without any further ado.

_However_, forgive my extreme nitpicking, but: would it please be possible for you to to split the commit into three commits, one for each "logical" change, every one of them compiling, [preferably using the imperative mood in the commit message](https://chris.beams.io/posts/git-commit/#imperative) (`WINTERMUTE: Do something`, `WINTERMUTE: Fix something`...)

Should be a matter of seconds, but if you're unfamiliar with `git` I can do it myself.

**Comment by tobiatesan** [comment]
For anyone who might have missed that, @lolbot-iichan has been kind enough to write a simple test game for keyboard input, [it's among my own ones here](https://github.com/tobiatesan/wme_testsuite), if we have any other contributions I wonder if we should move everything to a repo under `scummvm/`

**Comment by lolbot-iichan** [comment]
@tobiatesan Is it better now? 
I hope I didn't fail - haven't used rebase magic for like 9 years.

**Comment by sev-** [comment]
Could you please rebase your branch, so it does not contain the merge commits?

**Comment by lolbot-iichan** [comment]
@sev-, done. 

However please note that @tobiatesan mentioned yesterday at IRC that he would like to make some changes, so this is possibly not the final commit breakdown.

**Comment by tobiatesan** [comment]
I did  volunteer to help you clean up the history, but I see you did just fine.
All three commits look nice enough to me and appear to compile just fine.

To be super pedant, [we'd like the commit messages to respect these best practices](https://chris.beams.io/posts/git-commit/#seven-rules), particularly "imperative mood" and "capitalization", but the breakdown itself looks nice enough to me.

For future reference, the commit messages in a branch can be rewritten easily by running `git rebase -i HEAD^^^^` (the four `^` mean "starting from the 4th last commit from the tip of the branch) and marking commits that need a new messages with the `reword` tag instead of `pick`.

I don't have any objections code-wise.

**Comment by lolbot-iichan** [comment]
@tobiatesan ok, thanks! 
Waiting for @somaen then...

**Comment by tobiatesan** [comment]
Minor change, one week and no complaints yet. I'm taking the liberty to merge.

**Pull request merged**
