### PR TITLE
GRAPHICS: Implement horizontal triangles

### PR DESCRIPTION
**Pull request by lephilousophe**
Everything is in the title.

Simplify drawTriangle in the same time and fix a bad copy paste when
drawing outline with w == h

### CODE REVIEW

**Comment by lephilousophe** [comment]
Forgot to add that I copy pasted from vertical code and changed x by y and so on everywhere.
Some variable names seem bogus to me but they are in the vertical case too so I decided to keep the same logic.

**Comment by Thunderforge** [comment]
Is there some reason we need to draw triangles instead of just using ► or ▶ (unicode characters [U+25BA](https://www.fileformat.info/info/unicode/char/25ba/index.htm) and [U+25B6](https://www.fileformat.info/info/unicode/char/25b6/browsertest.htm) respectively)?

**Comment by criezy** [comment]
> Is there some reason we need to draw triangles instead of just using ► or ▶ (unicode characters [U+25BA](https://www.fileformat.info/info/unicode/char/25ba/index.htm) and [U+25B6](https://www.fileformat.info/info/unicode/char/25b6/browsertest.htm) respectively), which are supposed to be rendered as black triangles (GitHub seems to substitute them with emojis instead).

I can see a few possible reasons, but one of them is that ScummVM can be compiled without freetype support and use BDF fonts, which will not have these characters (and also would not scale well even if they had them).

**Comment by lephilousophe** [comment]
The drawTriangle primitive is more flexible than the Unicode glyphs, you can set the width and height independently. That may be used by some themes out there.

**Comment by lephilousophe** [comment]
Just fixed Codacy issue

**Comment by sev-** [comment]
Thank you!

**Pull request merged**
