### PR TITLE
GOB: use infinite Flowers flag for Adibou2 german version

### PR DESCRIPTION
**Pull request by BJNFNE**

### CODE REVIEW

**Comment by sdelamarre** [comment]
Did you actually check that this workaround works on your German version? It is highly dependent on the variable indexes in the .TOT files, that can change between versions.

**Comment by sev-** [comment]
Yes, a playtest is required.

**Comment by sev-** [comment]
Switching it to draft in the meantime. @BJNFNE when will you plan the playtest?

**Comment by BJNFNE** [comment]
> Switching it to draft in the meantime. @BJNFNE when will you plan the playtest?

@sdelamarre  found out that this version, uses other script offsets so the workaround has to be updated first.

**Comment by sdelamarre** [comment]
@BJNFNE since I confirmed from the script you sent me that your version has by the bug, can you do the following:
- ensure you are able to reproduce it by playtesting (it is not trivial to reproduce so it may require some practicing) 
- try to fix the workaround in ScummVM code. Basically it is just a matter of fetching the current script output
(_vm->_game->_script->pos()) there in your version, and adding it to the condition: 
```
(_vm->_game->_script->pos() == 30743 ||
_vm->_game->_script->pos() == 31074 ||
_vm->_game->_script->pos() == 31109) 
```
- check that it fixes the bug by doing a new playtest 
- update the PR

**Comment by BJNFNE** [comment]
Thanks i try that later at the evening 👍

**Comment by bluegr** [comment]
@BJNFNE any news on this?

**Comment by BJNFNE** [comment]
> @BJNFNE any news on this?

It Looks like i am always to slow to trigger the Bug, so i gave @sdelamarre the version. Maybe he has made some progress.

**Comment by sdelamarre** [comment]
Closing this since you gave up on the task @BJNFNE. I will probably not look at this low-priority enhancement before long, so feel free to ping me if you want to retry and need more guidance.

**Pull request closed without merging**
