### PR TITLE
ULTIMA8: Report mising U8SAVE.000 file on startup

### PR DESCRIPTION
**Pull request by mduggan**
@OMGPizzaGuy does this seem like a reasonable approach?

The game can't really start without this data, no need to continue.

This fixes #12790.

### CODE REVIEW

**Comment by OMGPizzaGuy** [comment]
I didn't notice this previously, but the return value for startGame is not checked in Ultima8Engine::newGame. Any of the missing files should have caused the startup to fail. Additionally, the return value for newGame is not checked either.

I would be inclined to change the return type to a Common::Error and bubble the error message up that way, but that's understandably a larger change.

**Comment by bluegr** [comment]
@mduggan @OMGPizzaGuy I've implemented the changes suggested here in PR #6223

Pick the approach you believe is better :)

**Comment by OMGPizzaGuy** [comment]
> @mduggan @OMGPizzaGuy I've implemented the changes suggested here in PR #6223
> 
> Pick the approach you believe is better :)

The neat part is both approaches are compatible. I think PR #6223 should be merged, but we can also discuss this one for more detailed messages.

**Comment by bluegr** [comment]
Thanks! Merging this as well, to allow for more detailed error messages to the users

**Pull request merged**
