### PR TITLE
AGI: Review games and add new ones

### PR DESCRIPTION
**Pull request by catrplr**
Reviewed all the game in the website [SCI Community created Adventure games](https://sciprogramming.com/fangames.php?eng=agi&cat=All&sort=date) and added new ones in **engines/agi/detection_tables.h (fanmade titles)**

### CODE REVIEW

**Comment by sluicebox** [comment]
Great, thanks! We're very close, but our CoCo3 entry has slightly confused things, and also this is an AGIMOUSE (AGIPAL) game.

Please replace the your sqx line with this, and I'll merge it:

`GAME_FO("sqx", "v1.0 March 12, 2001", "ee0f10a44f94ab091455e643cd547e03", 0x2917, GF_FANMADE|GF_AGIMOUSE, GID_FANMADE, GAMEOPTIONS_DEFAULT), // AGIPAL`

**Comment by catrplr** [comment]
I have replaced it

**Review by bluegr — APPROVED** [review]
LGTM

**Comment by sluicebox** [comment]
@catrplr Looks great! Thank you for researching and preparing this. Merging.

**Pull request merged**
