### PR TITLE
SCI: Portrait correction

### PR DESCRIPTION
**Pull request by Doomlazer**
Width is at 6, bytesPerLine is at 2.

### CODE REVIEW

**Comment by sluicebox** [comment]
Hello, could elaborate on this? Does this fix a visual glitch, crash, etc?

**Comment by Doomlazer** [comment]
Sure; It doesn't change functionality, just makes the code less confusing. 

Look at the error statement, the original code was checking (bytesPerLine < curBitmap.width) which is the opposite of the error text "kPortrait: bytesPerLine larger than actual width".

Take a look at the comments at the top of Portrait::init()

`
	// bitmap-data follows, total of [animation count]
	//   14 bytes bitmap header
	//    -> 4 bytes unknown
	//    -> 2 bytes height
	//    -> 2 bytes width
	//    -> 6 bytes unknown
	//   height * width bitmap data
`
It states the width is at 6, not 2.

@deckarep was referencing this code in an outside project, which is how this was noticed.

Does that clear it up?

**Comment by deckarep** [comment]
For the record my janky script was broken which I pulled off by referencing ScummVM’s implementation and @Doomlazer noticed inconsistencies in ScummVM’s comments vs what the code actually does.


But…as far as I know ScummVM’s implementation of Rave portrait images has been handling great for years…so I’m not even sure how this code “fixes” anything.

@Doomlazer possibly it’s the code comments that are wrong?

**Comment by deckarep** [comment]
Referenced script completely unrelated to ScummVM: https://gist.github.com/deckarep/d09e98827945208db3bd4770f1256235

**Comment by Doomlazer** [comment]
Here is the original commit for reference: https://github.com/scummvm/scummvm/commit/6619d95f48e2b3f5a67c58c4e951d2f371f21a62

If it's more correct to call it bytesPerLine instead of width, leave it as is, but the comments and error message should be cleaned up to avoid confusion.

**Comment by sluicebox** [comment]
@Doomlazer @deckarep Thanks! We have a bugfix release coming out very soon so I wanted to know if this fixed a crash and needed to be fast tracked to make it before the deadline.

I love cleanups like this; I think of the ScummVM SCI code as the de-facto reference, at least that's what I use it for when writing my personal tools and hacks. You could probably stalk my private stuff by the wake of commits they generate, for example: 695b7f92296a48cd695614001dc6391577377101

I'll take a closer look at these changes and the portrait script soon.

**Comment by Doomlazer** [comment]
Yes, I only submitted this because ScummVM is so frequently used as a reference. 

I can see how bytesPerLine would be the preferred name, so feel free to close the PR and just fix the comments and error msg at your leisure. 

Thank you.

**Comment by deckarep** [comment]
@sluicebox - no problem...thanks for your continued improvements to the SCI engine. It's a huge reason as to why ScummVM is awesome.

**Comment by sluicebox** [comment]
@deckarep okay no fair, compliments like that make me prone to merging this sight unseen!

[ also, thank you!! ]

**Comment by Doomlazer** [comment]
Eh, I'm just going to close this PR now. I have a feeling you'll end up keeping the naming conventions as they are and just updating the comments. 

ty

**Pull request closed without merging**
