### PR TITLE
Fix some warnings

### PR DESCRIPTION
**Pull request by fingolfin**
This fixes various warnings compiling ScummVM produces on Mac OS X with clang.

### CODE REVIEW

**Comment by dreammaster** [comment]
I don't see any issue with ACCESS and SHERLOCK changes

**Comment by DrMcCoy** [comment]
The GOB change looks good too.

**Comment by bluegr** [comment]
The changes to the AGI and ZVISION engine look good as well

**Comment by wjp** [comment]
Thanks! (And good to hear from you again.)

**Pull request merged**
