### PR TITLE
NEWS: Convert German NEWS file to Markdown

### PR DESCRIPTION
**Pull request by lotharsm**
This is a conversion of the German edition of the NEWS file, now called NEUES.md. Don't worry about the outdated contents of the file itself - it will get updated as soon as the conversion is done.

I know the integration into the win32.mk file is very rough at the moment and only intended to avoid breaking the compilation progress.

@ccawley2011, could you assist with integrating this file in the pandoc system? :)

### CODE REVIEW

**Comment by ccawley2011** [comment]
> @ccawley2011, could you assist with integrating this file in the pandoc system? :)
 
OK, done in f17ed74.

**Comment by lotharsm** [comment]
> > @ccawley2011, could you assist with integrating this file in the pandoc system? :)
> 
> OK, done in [f17ed74](https://github.com/scummvm/scummvm/commit/f17ed74de5f6381133bd32218f4fc55c9c7b9d86).

Thanks a lot!

The easiest way to integrate this commit is to close this PR and create a new one from your branch, right?

**Comment by bluegr** [comment]
@lotharsm you could also cherry-pick @ccawley2011's commit into your branch, and it will be included with this PR

**Comment by lotharsm** [comment]
@bluegr Nice, thanks! I finally understood how cherry-picking from different branches work :)

**Comment by Kawa-oneechan** [comment]
> @bluegr Nice, thanks! I finally understood how cherry-picking from different ("foreign") repositories work :)

I still don't :smile_cat:

**Comment by ccawley2011** [comment]
One minor comment, the formatting change made in commit 93b9ae2 should be applied here as well, as without it, that section will end up all on one line.

**Comment by lotharsm** [comment]
Thanks, fixed :)

**Pull request merged**
