### PR TITLE
RASPBERRYPI: Remove outdated build flags

### PR DESCRIPTION
**Pull request by ccawley2011**
This fixes detection of OpenGL ES v2 on the buildbot.

### CODE REVIEW

**Comment by lephilousophe** [comment]
> Checking for OpenGL... yes (OpenGL ES 2)
> Checking for GL Extension Wrangler (GLEW)... not needed with OpenGL ES v2

Isn't it OK?

**Comment by ccawley2011** [comment]
> > Checking for OpenGL... yes (OpenGL ES 2)
> 
> > Checking for GL Extension Wrangler (GLEW)... not needed with OpenGL ES v2
> 
> 
> 
> Isn't it OK?

Only for 2D games, where OpenGL is loaded dynamically at runtime. For 3D games, where the OpenGL ES library is linked directly, it recognises that GLEW isn't needed, but the next check fails when attempting to link to the GLESv2 library.

**Comment by lephilousophe** [comment]
Ah, yes you are right.
These includes are here to use the official proprietary OpenGL stack and get hardware acceleration old RPi 1 I think.
Maybe we should tackle the problem on toolchain side?

**Comment by lephilousophe** [comment]
So, after looking at the failure and taking some time to think about it, I think it would be simpler to use
```
-for lib in "-lGLESv2" "-logles2"; do
+for lib in "-lGLESv2" "-logles2" "-lbrcmGLESv2"; do
```
I checked that the test passes by using brcmGLESv2 but I don't have any RPi to check if it works.
What do you think?

**Comment by bluegr** [comment]
Any news on this?

**Comment by sev-** [comment]
Please, update the PR and merge it.

**Comment by aquadran** [comment]
> So, after looking at the failure and taking some time to think about it, I think it would be simpler to use
> 
> ```
> -for lib in "-lGLESv2" "-logles2"; do
> +for lib in "-lGLESv2" "-logles2" "-lbrcmGLESv2"; do
> ```
> 
> I checked that the test passes by using brcmGLESv2 but I don't have any RPi to check if it works. What do you think?

I think it's ok. it will check lib one by one. I have old rpi 1 I could check it. But I have to install something on it, Raspbian should be enough?

**Comment by Macleykun** [comment]
> > So, after looking at the failure and taking some time to think about it, I think it would be simpler to use
> > ```
> > -for lib in "-lGLESv2" "-logles2"; do
> > +for lib in "-lGLESv2" "-logles2" "-lbrcmGLESv2"; do
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I checked that the test passes by using brcmGLESv2 but I don't have any RPi to check if it works. What do you think?
> 
> I think it's ok. it will check lib one by one. I have old rpi 1 I could check it. But I have to install something on it, Raspbian should be enough?

Raspain surely should be enough :) as it’s based on Debian which many other distro’s use aswell!

**Comment by aquadran** [comment]
According what I found on web, '/opt/vc' is present on older pi Debian releases. I installed bullseye and that directory is no longer present.

**Comment by aquadran** [comment]
I think along outdated build flags, build bot should not have outdated Broadcom libs. not adding them to configure

**Comment by aquadran** [comment]
separated changes merged. this is obsolete now

**Pull request closed without merging**
