### PR TITLE
GOB: Add another German variant of adibou2

### PR DESCRIPTION
**Pull request by lotharsm**
This patch adds a detection entry for the German version of Adibou 2 (dubbed "Adi Junior 2" here) I got with an Packard Bell PC, so it is a OEM bundled version.

And yes, this version is most likely the very first PC game I ever played - thank you @sdelamarre!

This version is playable, but in ScummVM, it is missing the intro sequence and starts straight with the character selection screen.

There are a bunch of warnings printed when starting the game:
```
WARNING: File "APPLIS.BOU" not found!
WARNING: File "ENVIR.BOU" not found!
WARNING: File "RESEAU.BOU" not found!
WARNING: File "RAM.BOU" not found!
WARNING: File "RAM16.BOU" not found!
WARNING: File "DEBUGA.BOU" not found!
WARNING: File "CHEAT.BOU" not found!
WARNING: Urban/Playtoons Stub: Unknown Video/Music command: -2, DEBUT!
WARNING: Urban/Playtoons Stub: Unknown Video/Music command: -2, DEBUT!
```

However, since the game itself works, I think adding makes sense at this point.

### CODE REVIEW

**Comment by lotharsm** [comment]
Btw, since I don't know if this version is a special release made for Packard Bell, I'm fine with dropping the "Packard Bell OEM" part of the description. We should keep the custom, translated title though.

**Comment by sdelamarre** [comment]
> This version is playable, but in ScummVM, it is missing the intro sequence and starts straight with the character selection screen.

Should be fixed now ! :blush: (e79da632b6a7469aa902e14f05b477a333007710) The music should also be played in some transitions. It's funny, it is the beginning of the "Three little cats" song ! (the French version use another one). 

> There are a bunch of warnings printed when starting the game

The last two were related to the skipped intro problem, and I think the other ones are just some debug backdoors for the developpers.

**Comment by lotharsm** [comment]
Thank you, I can confirm that the intro issue is indeed fixed. :-)

I also changed the custom game title to what's present in the title screen.

> Should be fixed now ! 😊 ([e79da63](https://github.com/scummvm/scummvm/commit/e79da632b6a7469aa902e14f05b477a333007710)) The music should also be played in some transitions. It's funny, it is the beginning of the "Three little cats" song ! (the French version uses another one).

Yep, and what's really interesting: It seems that there's an additional intro music sequence. When I play it with the original interpreter, it triggers a _different_ song than what's being played in ScummVM.

The music I get when playing with the original interpreter is what I remember from back then. However, I don't remember if the music that is being played with ScummVM was also present there - maybe it is something like "play a different title at the first launch"?

I'll have to retest with a VM and the original interpreter again.

However, since the game is now properly detected and playable, I think I can merge this soon unless I find additional issues when comparing with the original interpreter.

**Comment by lotharsm** [comment]
@sev- Do we have some sort of guidelines regarding the "Packard Bell (OEM)" addition in the game description? I'm not sure if this contains changes that are very specific to the game at all or if we should drop this and just keep the custom game title as shown in the title screen.

**Comment by sev-** [comment]
We normally add those to the `extra` filed to distinguish between versions. In rare cases when the field is used for something else (like for autogenerated names in AGI/WAGE fanmade games), put that into the comment. But in any way, try to document it :D

**Comment by sdelamarre** [comment]
> When` I play it with the original interpreter, it triggers a different song than what's being played in ScummVM.

Interesting, I'll also take a look.

> I think I can merge this soon unless I find additional issues when comparing with the original interpreter

You will probably encounter some cursor glitches I am still working on (cursor replaced by a black square or even disappearing, e.g. in vegetable garden or when selecting a game in Read/Count apps).

**Comment by sev-** [comment]
OK, I'm merging this in the meantime.

**Pull request merged**
