### PR TITLE
SCUMM: Use inline member initialization

### PR DESCRIPTION
**Pull request by orgads**
and initialize all members.

### CODE REVIEW

**Comment by athrxx** [comment]
What is the purpose of the PR? There is no description.
Initialization is good, of course, if we have cases where it is still missing...
But what about the change to inline initialization. Is it just style preference?
The problem for me is, it is basically impossible for me to tell whether you got all variables right.
So, if we do face possible regressions, it would be good to know why we're actually doing this ;-)

**Comment by orgads** [comment]
I wrote a script for this, so the values are all copied from the cpp file.

The main purpose is to prevent missing initializations, and it is also more convenient to have the initializations along with declaration.

**Comment by orgads** [comment]
ping

**Comment by bluegr** [comment]
Overall, it's good to have variable declarations together with their initialization. Now that we're using C++ 11, it's straightforward to use such syntax.

Thanks for your work! Looks good. Merging

**Pull request merged**
