### PR TITLE
SCI: [RFC] Fix PCjr music volume

### PR DESCRIPTION
**Pull request by eriktorbjorn**
It was pointed out in bug #15208 that the PCjr music for SCI games is played at very low volume. On investigation, it seems like the other audio drivers expect the volume to be in the 0-15 range, but the PCjr one has 100 as default, so it probably uses 0-127.

I'm basing the volume table on https://www.smspower.org/Development/SN76489 and its statement that the volume is attenuated "by 2dB for each step in the volume register". But is that the right way to do it? This will have to be one of those "I don't know if I'm doing it right, but the current behavior is clearly wrong" kind of pull requests...

### CODE REVIEW

**Comment by bluegr** [comment]
@eriktorbjorn thanks, but this is definitely not right

If you check further down, in `generateSamples()`, volume is calculated as follows:

    int volume = (_global_volume * _volumes[chan])
                          >> VOLUME_SHIFT;

Where `_volumes` is initially set to 100 per channel. So, `_global_volume` can't have such large values as in this PR, and it seems that the final volume is overflowing with these changes. Having said that, the PC-9801 driver does have a volume table in its `setVolume()` overridden function, but the volume is utilized in a different manner internally

**Comment by eriktorbjorn** [comment]
I'm not sure I follow you... `global_volume` would be at most 127, and `VOLUME_SHIFT` is 3. I'm uncertain what the maximum value of `_volumes[chan]` is but let's be pessimistic and say 255. Then `volume` would be 4048, well within a 16 bit sample?

Or am I missing something obvious. It _is_ getting late here.

**Comment by eriktorbjorn** [comment]
I tried adding some code to look for overflows. Then I tried setting the volume to max in the ScummVM volume settings, and played through a couple of game intros.

- Police Quest II generated samples in the range -2024 through 3905. Without the volume patch it's -239 through 461.
- Space Quest III generated samples in the range -2029 through 3190. Without the volume patch it's  -226 through 376.
- The Colonel's Bequest generated samples in the range -3788 - 6048. Without the volume patch it's -424 through 714.

All well within the range of a 16-bit signed sample. Though of course it's possible I messed up, or that my debug code itself suffers from overflows. This was the code that I added:

```
diff --git a/engines/sci/sound/drivers/pcjr.cpp b/engines/sci/sound/drivers/pcjr.cpp
index 53c2d39e8c2..ef7710b867c 100644
--- a/engines/sci/sound/drivers/pcjr.cpp
+++ b/engines/sci/sound/drivers/pcjr.cpp
@@ -59,6 +59,9 @@ static inline int get_freq(int note) {
 
 class MidiDriver_PCJr : public MidiDriver_Emulated {
 public:
+       int32 _minSample = 0;
+       int32 _maxSample = 0;
+
        friend class MidiPlayer_PCJr;
 
        enum {
@@ -168,6 +171,7 @@ void MidiDriver_PCJr::generateSamples(int16 *data, int len) {
                freq[chan] = get_freq(_notes[chan]);
 
        for (i = 0; i < len; i++) {
+               int32 result32 = 0;
                int16 result = 0;
 
                for (chan = 0; chan < _channels_nr; chan++)
@@ -182,20 +186,30 @@ void MidiDriver_PCJr::generateSamples(int16 *data, int len) {
                                if (_freq_count[chan] - freq[chan] < 0) {
                                        /* Unclean rising edge */
                                        int l = volume << 1;
+                                       result32 += -volume + (l * _freq_count[chan]) / freq[chan];
                                        result += -volume + (l * _freq_count[chan]) / freq[chan];
                                } else if (_freq_count[chan] >= frequency
                                           && _freq_count[chan] - freq[chan] < frequency) {
                                        /* Unclean falling edge */
                                        int l = volume << 1;
+                                       result32 += volume - (l * (_freq_count[chan] - frequency)) / freq[chan];
                                        result += volume - (l * (_freq_count[chan] - frequency)) / freq[chan];
                                } else {
-                                       if (_freq_count[chan] < frequency)
+                                       if (_freq_count[chan] < frequency) {
                                                result += volume;
-                                       else
+                                               result32 += volume;
+                                       } else {
                                                result += -volume;
+                                               result32 += volume;
+                                       }
                                }
                        }
                data[i] = result;
+
+               if (result32 < _minSample)
+                       _minSample = result32;
+               if (result32 > _maxSample)
+                       _maxSample = result32;
        }
 }
 
@@ -226,6 +240,7 @@ int MidiDriver_PCJr::open(int channels) {
 
 void MidiDriver_PCJr::close() {
        _mixer->stopHandle(_mixerSoundHandle);
+       debug("Generated sample range: %d - %d", _minSample, _maxSample);
 }
 
 class MidiPlayer_PCJr : public MidiPlayer {
```

**Comment by eriktorbjorn** [comment]
Looking at it again, I _think_ the maximum value each channel can contribute to the final sample is `volume`, and I _think_ there are at most 3 channels. So for the sample to overflow, `volume` has to be greater than 10,922. As you said, `volume` is calculated as `(_global_volume * _volumes[chan]) >> VOLUME_SHIFT` where `VOLUME_SHIFT` is 3, i.e. a division by 8.

So for things to not overflow, `_global_volume * _volumes[chan]` has to be at most 87,376, I guess? 32,767 divided by 3, multiplied by 8. If _volumes[chan] is at most 255 (based on it being set to `(b >> 16) & 0xff` in `MidiDriver_PCJr::send()`, the maximum safe value for `_global_volume` would be 342, wouldn't it?

The default value for `_global_volume` is 100, which would generate samples between -9,561 and 9,561 I think? Though currently, the SCI engine will set `_global_volume` to no higher than 15, making the sample range -1,434 - 1,434.

But all of this is just cold, hard speculation. If I'm missing something obvious (or not so obvious) I'd love to hear where I went wrong!

**Comment by bluegr** [comment]
The volume changes are indeed guesswork, but the PCjr driver is guesswork as well

I've talked to @athrxx and @NMIError  about this. After some digging, it has been uncovered that this code has been imported from FreeSCI. As @athrxx found, it's a weird mix of SCI0 and SCI1, but it isn't accurate for either version

This code was originally imported from FreeSCI with commit 695bc36b9aff. The original code from FreeSCI is the following:
https://github.com/wjp/freesci-archive/blob/master/src/sfx/softseq/SN76496.c

@athrxx and @NMIError will provide more insights and feedback, when they can

**Comment by athrxx** [comment]
I have started to fix the volume (and other things), but it isn't that trivial, so it may take some time.

**Comment by NMIError** [comment]
I'm disassembling the last version of the SCI0 PCjr driver, and it actually applies attack and release envelopes to the note volume. Very interesting. I'll need some more time to figure this out completely.

**Comment by athrxx** [comment]
> I'm disassembling the last version of the SCI0 PCjr driver, and it actually applies attack and release envelopes to the note volume. Very interesting. I'll need some more time to figure this out completely.

Yes, I have implemented most of it already. Also for SCI1 which uses instrument patches. But it's not yet 100% complete...

**Comment by athrxx** [comment]
> Oh good, I didn't think you'd have made that much progress already! Do you generate samples in the driver? I've been thinking about adapting the MAME emulator for this chip ( https://github.com/mamedev/mame/blob/master/src/devices/sound/sn76496.cpp ) for use in ScummVM; this seems like a good opportunity.

It's mostly done. Unfortunately, the PC Speaker driver also gets channeled through that code. So I am now comparing those drivers and limit some changes to the PCJr. The speaker drivers don't have envelope generators, instrument patch support or even channel volume and velocity support, so everything is a bit simpler.

I haven't changed the way of sample generation (at least not much), since that part seemed to be the least problematic. A
rewrite of the whole thing would look much better, but I tried to stick to the actual task of fixing volume accuracy.

**Comment by bluegr** [comment]
Thanks @eriktorbjorn for the heads up on the volume issue

Also, thanks @NMIError for the analysis, and @athrxx for the analysis and the implementation of a fix for the issue, based on disassembly

Closing this in favor of the work done on the driver, based on disassembly, in PR #6121

**Pull request closed without merging**
