### PR TITLE
GUI: Add lowres support for the renderer dropdown and increase OptionsLabel's width

### PR DESCRIPTION
**Pull request by a-yyg**
On lowres the renderer dropdown (particularly the OpenGL with shaders option) does not fit. By way of caution this also adds lowres support for the description.

### CODE REVIEW

**Comment by a-yyg** [comment]
Since I accidentally force pushed onto the wrong branch and don't know the correct procedure I'll detail here the other changes:
Increased OptionsLabel's width to allow for the 3D Game Renderer:
- The width for the 3D Game Renderer description in the graphics options was too small and this produced ellipses.
- This fixes [Trac #12015](https://bugs.scummvm.org/ticket/12015)

**Comment by sev-** [comment]
Thank you!

**Comment by sev-** [comment]
Uh oh, I merged but did not check the commits :/

Your second commit was named incorrectly: it is lacking subsystem prefix

**Comment by a-yyg** [comment]
Thanks for letting me know.

**Pull request merged**
