### PR TITLE
CREATE-PROJECT: Set MSVC subsystem

### PR DESCRIPTION
**Pull request by henke37**
There is no need to show an unusable console window, so only show that if the text console is enabled.

### CODE REVIEW

**Comment by bluegr** [comment]
Nice work! A good and easy way to manage the console

**Comment by SupSuper** [comment]
Upon further examination, the `text-console` parameter is kinda deceptive. The full name is `USE_TEXT_CONSOLE_FOR_DEBUGGER`.
Personally I like having the text console for debug output but **not** as a debugger, so I'd prefer if the two weren't tied together.

**Comment by sev-** [comment]
What is the status of this PR?

**Comment by henke37** [comment]
As far as I know, ready to merge unless someone has an objection.

**Comment by dreammaster** [comment]
I previously overlooked this pull request. Since I'm at work right now and can't test it, and I'm a bit confused about "text window" vs "console window" in the description. Does this mean that builds done in MSVC won't have the console window open by default?

**Comment by henke37** [comment]
That's the idea yes, if the os level console isn't used, don't show it.

**Comment by dreammaster** [comment]
I've no objection then. As long as it's been tested, a merge is fine by me

**Comment by henke37** [comment]
I've been using it for my builds for like half a year now.

**Pull request merged**
