### PR TITLE
WIN32: Let the PE header control showing the console.

### PR DESCRIPTION
**Pull request by henke37**
This applies DRY to the console config and avoids junk code changes seen by git.

### CODE REVIEW

**Comment by henke37** [comment]
This would eliminate the second step under the [Compiling without Console/Status Window](https://wiki.scummvm.org/index.php?title=Compiling_ScummVM/Visual_Studio#Compiling_without_Console.2FStatus_Window) heading when building in MSVC.

**Comment by sev-** [comment]
Your commits are not liner (containing that merge commit), and you changed the whitespace in the whole file. Could you please clean this up?

**Comment by henke37** [comment]
Not sure how I'd deal with the commits. And I thought I checked for whitespace changes. I blame newlines.

**Comment by henke37** [comment]
And by "not sure" I mean that I don't have the git skills to understand the issue, even less fix it.

**Comment by sev-** [comment]
Well, just redo your changes in the clean branch, but watch that your editor doesn't convert the newlines. Should be pretty straightforward. Also, this would let you squash everything into one commit instead of three.

**Comment by SupSuper** [comment]
@henke37 I've squashed your commits,

**Comment by henke37** [comment]
Much appreciated.

**Comment by bluegr** [comment]
Looks good to me. Nice work! :) +1

**Comment by bluegr** [comment]
This is quite straightforward and well made.

Thanks for your work! Merging

**Pull request merged**
