### PR TITLE
MTROPOLIS: Promote three titles to Unstable

### PR DESCRIPTION
**Pull request by meekee7**
I would like to suggest to promote three mTropolis titles from Unsupported to Unstable. The mTropolis engine implementation is far enough that these titles can do something useful when run with ScummVM. 

### How to Build a Telemedicine Program 
HTBATP offers lectures on the titular subject which consist of audio talks combined with slide shows, but not actual video.
There is also a bit of general informational text to read.

image
image
image
image

#### Current State
ScummVM will play the audio lectures. But while the audio plays the app window freezes in the sense that it is not refreshed or repainted. When the lecture ends it unfreezes.

The text can be read.

### Fun With Architecture
FWA was originally a physical toy consisting of rubber stamps in various shapes that could be layed into buildings and printed onto paper with an inkpad. It also came with a booklet explaining some architectural design and offering templates/inspiration for the rubber stamps.

The CD version consists of a digital version of the booklet (I presume, as I haven't read the original) and a painting/construction activity based around shape-laying. Some of the example buildings from the book activity can be opened directly in the painting tool to be modified.

image

image

#### Current State
The ebook can be read, but the rendering quality is very poor.

image

The painting activity will open, but it cannot load pictures or let you place shapes.

### The Magic World of Beatrix Potter
Beatrix Potter was an author of children's books. This multimedia CD contains various content about Beatrix herself, her work and her tales.

#### Current State
We will break it down by each content item:
image

 - Family: Image gallery. Images do no show.
 - Photo Album: Image gallery with voiceover. Images do not show, voiceover plays.
 - Art: Image Gallery of paintings and other artwork by Beatrix, with voiceover explanations. Images and voiceover do work. 
image

 - 23 Tales: Tales by Beatrix in a shortened/summarized form, read aloud over a slideshow of illustrations. Also includes some background info on those tales. Slideshow images and voiceover do work. 
image

 - Miniature Letters: Letters to be found as collectibles within the other content. I think this is broken.
 - Tom Kitten Film: Animated short of one of the tales. Video playback works.
image

 - Activities: Various activities to print out. Printing, or its lesser ScummVM implementation as saving to a file, does not work.
image

 - Games:
 
image

   - Mazes: Works with limitations. Minor graphical glitches, keyboard controls are partially broken, but mouse controls work.
 
image

   - Dot-Dot: Broken 
 
image

image

   - Jigsaw: Works, but behavior is glitchy
image

   - Colouring: Will error out because of unimplemented plugin data loading.
image

### CODE REVIEW

**Comment by bluegr** [comment]
It's not clear what actually works and what doesn't in these titles, from your description

I couldn't find any info on the first two titles. For the third one (Beatrix Potter), here are some Youtube videos, but again, I don't understand if this game is playable or completable, from your description:
- https://www.youtube.com/watch?v=oWXzyb6bUSM
- https://www.youtube.com/watch?v=m1ov3cm59io

**Comment by meekee7** [comment]
None of these three titles are games with a linear path and an ending to be completed. They are multimedia CDs.
They are "playable" to a degree. I will create more detailed presentations and explanations for each title later.

But if the criterion for unstable status is indeed that a title must be playable or better completable, then this was not enforced in the past. In PRs #4239 and #4431 the Albert/Ernest games and Star Trek: The Game Show demo were added to detection in mTropolis as unstable instead of unsupported, despite being unable to boot at the time.

**Comment by bluegr** [comment]
> But if the criterion for unstable status is indeed that a title must be playable or better completable, then this was not enforced in the past. In PRs #4239 and #4431 the Albert/Ernest games and Star Trek: The Game Show demo were added to detection in mTropolis as unstable instead of unsupported, despite being unable to boot at the time.

This was a mistake, plus mTropolis is an engine that is still not stable, but under development.

Awaiting for your feedback on these game entries

**Comment by meekee7** [comment]
I expanded the PR description.

**Comment by bluegr** [comment]
Thanks for the feedback, it makes sense to promote these titles to unstable, indeed

**Pull request merged**
