### PR TITLE
DOCS: Adding FAQ item about fanmade mods

### PR DESCRIPTION
**Pull request by Thunderforge**
This is the result of a Discord discussion in `#teamtalk`, especially in relation to fan upscales.

### CODE REVIEW

**Review by sev- — APPROVED** [review]

**Comment by lotharsm** [comment]
LGTM!

**Comment by criezy** [comment]
This looks good.
My only question is whether the `Troubleshooting` section is the best place for it. Maybe this should be added as 1.3.11 at the end of the `General` > `Playing games` section?

**Comment by Thunderforge** [comment]
@criezy Good catch; I think I got mixed up with Troubleshooting's "Games" header.

I've med it to section 1.3. Please take another look.

**Review by criezy — APPROVED** [review]

**Comment by criezy** [comment]
Thank you. I will squash and merge now.

**Pull request merged**
