### PR TITLE
GRIFFON: Adding TTS to Intro Story

### PR DESCRIPTION
**Pull request by taylorzhancher**
By passing the words to Text To Speech Manager, this code allows TTS support to the beginning of the game.

### CODE REVIEW

**Comment by bluegr** [comment]
Thanks for your work! However, the way this is done, there is duplicate text for the intro. You could concatenate the existing story array items dynamically into a new string, and pass that to the TTS handler instead.

Also, the commit messages do not follow our guidelines - in this case, each commit should be prefixed with GRIFFON

**Comment by taylorzhancher** [comment]
@bluegr Thank you! Your instructions are helpful. I will come back with it fixed.

**Comment by sev-** [comment]
It would be great if other things like menus also have voice overs.

Also, this is incomplete: this lacks the relevant GUI options, so it could not be added as is.

**Comment by bluegr** [comment]
This has been redone in #2912. Closing this one

**Pull request closed without merging**
