### PR TITLE
TWINE: fixes from original source code

### PR DESCRIPTION
**Pull request by mgerhardy**
This tries to sync our code base with the original code base that was released recently.

A few errors were found, but they still need testing.

- [ ] Tank driving (`change_scene 63`) (savegame at https://bugs.scummvm.org/ticket/13168#no1)
- [x] Sokoban in harbor (push crates) (`change_scene 35`)
- [x] General collision detection for actors
- [ ] Bullet collision

### CODE REVIEW

**Comment by bluegr** [comment]
@mgerhardy is there a reason to keep this PR open? A PR can be opened once all the changes are in a good state to be reviewed and merged.

**Comment by mgerhardy** [comment]
I just thought it might increase visibility and the chance that someone jumps in to help testing the changes. If I should close it, just let me know.

**Comment by sev-** [comment]
This is now bitrot big time

**Comment by sev-** [comment]
Why did you close it? I thought it has a set of proper changes, just needs to be rebased.

Or is there a misunderstanding?

**Pull request closed without merging**
