### PR TITLE
GUI: Easter egg

### PR DESCRIPTION
**Pull request by sev-**
For a long while, I wanted to implement an easter egg to our About dialog. Here it goes.

Looking for your comments, on how suitable that is, or I am completely crazy here.

Request for Comments!

PS. Launch 'about', press 'v'. After browsing through the menu, use arrow keys for the character on the right. or enjoy AI (original one) entertaining you. ESC to quit.

### CODE REVIEW

**Comment by lotharsm** [comment]
Nice touch, I really like little gems like this!

Gameplay wise, I'd prefer a slightly faster character movement for the player. ;)

**Comment by digitall** [comment]
Not sure about suitable, but there are a few warning fixes and general code style fixes that should be applied. I have committed them to the ee_fixup branch on my tree as:
https://github.com/digitall/scummvm/commit/67870b7b42d8feb8f60aeed2c1011f8c891a72cb

**Comment by athrxx** [comment]
I think this is a nice extra for the about dialog.
Not sure whether the move speed should be increased. Maybe very slightly? Works fine for me... :)

**Comment by criezy** [comment]
I think it's fun.
I don't really have any opinion on increasing or not the character movement. I suck at those kind of games anyway and it would probably need to be about 10x slower for me to manage to score a point :-P

**Comment by sev-** [comment]
@digitall thanks, I applied your patch

**Comment by sluicebox** [comment]
I love this! It's fun, looks great, and About boxes are my favorite place to put easter eggs. The speed is good but if it's slightly increased or decreased I expect it will still be good. I mean... it's not like I'm going to score any *less* points...

**Comment by sev-** [comment]
Thanks for your feedback, merging

**Pull request merged**
