### PR TITLE
COMMON: Style guide update for rad2Deg and deg2Rad 

### PR DESCRIPTION
**Pull request by dafioram**
This should of been included in PR1175.

I've changed naming and spaces to matched what is stated or implied in the style guide.

Let me know if I missed any other coding conventions.

### CODE REVIEW

**Comment by dafioram** [comment]
Done.

**Comment by sev-** [comment]
I would still leave them as rad2deg and deg2rad.

**Comment by dafioram** [comment]
I've changed the function names back to lower case, but kept the other coding format improvements.

**Comment by criezy** [comment]
Thank you. This seems good to me now. Merging.

**Pull request merged**
