### PR TITLE
SCUMM: [RFC] Make clicking the Maniac Mansion sentence line work like the manual says

### PR DESCRIPTION
**Pull request by eriktorbjorn**
According to the manual, you can execute commands by clicking on the sentence line.

> **To tell a kid to carry out the directions you've put on the Sentence Line,** either double-click on the final word selected, or click once on the Sentence Line itself. If nothing happens, double check the way you constructed the sentence.

But this doesn't work with the v1 or v2 DOS versions, even though it works with the C64 demo. This is because the verb script doesn't for this, so we have to do that ourselves. It does work in later games, and this pull request is loosely based on how Zak McKracken does it. I'm attaching the verb script from Maniac Mansion v1 and v2, and from Zak McKracken v2 for comparison, but the main difference seems to be that Zak does this:

```
[0049] (48) if (VAR_CLICK_AREA == 5) {
[004F] (9A)   Var[34] = Var[235];
[0052] (**) }
```

[maniac-v1-script-4.txt](https://github.com/scummvm/scummvm/files/8552258/maniac-v1-script-4.txt)
[maniac-v2-script-4.txt](https://github.com/scummvm/scummvm/files/8552259/maniac-v2-script-4.txt)
[zak-v2-script-4.txt](https://github.com/scummvm/scummvm/files/8552260/zak-v2-script-4.txt)

Outstanding questions:

- Should this be an enhancement, or always enabled? At the moment, it's an enhancement that's enabled for the v1 and v2 versions.
- I've already checked that it's not a problem in the C64 demo. (At least not when running it in ScummVM.) I assume that means clicking on the sentence line works in the full C64, and probably also Apple II, versions. Can anyone confirm this?
- ~I don't have the NES version. At the moment it's probably covered by the workaround since it's SCUMM v1, though there  isn't yet any checkbox for it.~
- Is this the best way of doing it, or is there a better way? At the moment, I'm injecting the "did you click on the sentence line" check when script 4 initializes variable 34

### CODE REVIEW

**Comment by AndywinXp** [comment]
With all the great fixes and enhancements SCUMM has received in the last year I'd be surprised not to find any mention of that in the website news article for the next version: great job, and please keep producing these!

**Comment by bluegr** [comment]
Looks good to me! Nice work

**Comment by bluegr** [comment]
I also believe that this can be enabled unconditionally, like we do with the mouse functionality in AGI. 

There are conflicts now, can you please fix them?

**Comment by eriktorbjorn** [comment]
I've never had to resolve conflicts before. I hope I did it right.

By the way, mouse support in AGI isn't unconditional:

image

**Comment by eriktorbjorn** [comment]
No, apparently I can't resolve the conflicts because when I try to rebase it says there are conflicts, and when I resolve the conflicts and try again it says there are conflicts, and when I resolve the conflicts and try again it says there are conflicts, and...

Sometimes I really, really hate Git.

**Comment by bluegr** [comment]
No worries, we can just squash all the commits in this case. Let's keep this under the enhancements flag, like we do for the other features.

**Comment by eriktorbjorn** [comment]
Thanks. I was about to make a new branch and reapply the changes there, because it seemed easier to me.

**Comment by digitall** [comment]
@eriktorbjorn : Dang, a bit too slow. I had a fixed up branch ready to push here :)
Seriously, if you need help sorting out git tangles in future, poke me.

For reference, the solution was:
1. git checkout 9189755da30b4ae721710d708a35767c17c8713d
2. git checkout -b scumm-mm-sentence-line-fixup
3. git branch -D scumm-mm-sentence-line
4. git checkout -b scumm-mm-sentence-line
5. git branch -D scumm-mm-sentence-line-fixup
(branch scumm-mm-sentence-line is now at 9189755da30b4ae721710d708a35767c17c8713d)
6. git rebase master
(rebase stops due to conflict in engines/scumm/detection_tables.h)
(Use an external editor to remove the conflict and markers)
7. git add engines/scumm/detection_tables.h
8. git rebase --continue
(This finishes with no issues)
9. git push -f (to overwrite the branch)...

**Comment by digitall** [comment]
And before anyone says, I had to do similar things with SVN branch conflicts ... but copying things off manually so git still wins :)

**Comment by eriktorbjorn** [comment]
Maybe it was the force push that was missing. I did get the conflict which I tried to edit as well as I could. But I'm disappointed the GitHub web interface didn't handle it better, since that was what it suggested I use to fix the problems.

**Pull request merged**
