### PR TITLE
TWP: bump "give" distance and handle empty text lines gracefully

### PR DESCRIPTION
**Pull request by apoikos**
Hi!

This PR fixes two issues with TWP (GOG/1.0.958) that prevent game completion. Quoting the respective commit messages:
 
### TWP: increase maximum "give" distance

(This was reported as https://bugs.scummvm.org/ticket/15285)
 
Commit 7dd6c4ba627 (TWP: Fix give minimum distance, 2024-03-07) increased the maximum distance for allowing objects to be given from 15 to 30. This works fine for most of the game, but there is at least one instance where 30 prevents a crucial transaction: Ransome exchanging wallets with Willie. This is visible in the following debug log:
    
```
Give 'ransomeWallet' to 'willie'
exec(currentActor,9,ransomeWallet,willie)
noun1.inInventory: YES and noun1.touchable: YES nowalk: NO
walk to obj willie: (1533.000000,91.000000)
walk to obj ransome: 1503.000000,91.000000, 1
Give 'ransomeWallet' to 'willie'
actorArrived
actor arrived with facing 1
call actorArrived callback
actorArrived: exec sentence
actorArrived: noun2 min_dist: 30.265491 > 30.000000 ?
translate(@30087): Willie
sayline: ransome, @24882
talking ransome audio stopped
Give 'ransomeWallet' to 'willie'
talking ransome: @24882
Load lip RANSOME_24882.lip
Lip RANSOME_24882.lip loaded
loadActorSpeech RANSOME_24882.ogg
talking ransome audio id: 250087, dur: 1821
sayLine 'He is too far away.'
```
    
Here we can see Ransome moving within 30.27 distance units from Willie without being obstructed by anything, however this is not close enough for "give" to work. Let's bump MIN_GIVE_DIST to 35, which fixes the issue.

### TWP: ignore empty text lines
    
The SayLineAt class assumes that lines are non-empty strings and accesses the first line character liberally. There is however at least one instance of an empty line returned by the game script that causes the engine to crash:
    
```
saylineAt: (160,85) text=@25923 color=rgba(1.000000,0.800000,0.000000,1.000000) duration=5.000000
sayLine 'Long minutes of furious berry picking later...'
add breakwhilecond name=breakwhiletalking(all) pid=300115, Helpers.bnut (1103)
add breakwhilecond name=breakwhilesound(-16408) pid=300110, playBearSounds ForestMaze.bnut (444)
talking @25923: ended
Resume task: 300115, Helpers.bnut (1103)
cutsceneOverride
create cutscene override
saylineAt: (160,85) text= color=rgba(1.000000,0.800000,0.000000,1.000000) duration=0.000000
scummvm: ./common/str-base.h:183: Common::BaseString<T>::value_type Common::BaseString<T>::operator[](int) const [with T = char; value_type = char]: Assertion `idx < (int)_size' failed.
```
    
I'm not sure whether this is an engine or a game bug (GOG/1.0.958), however it seems reasonable to avoid crashing when receiving an empty line. While we could fix SayLineAt() to handle empty lines gracefully, it looks more straightforward to completely avoid using empty lines returned by the game script in the first place.

### CODE REVIEW

**Review by scemino — CHANGES_REQUESTED** [review]
First of all thanks @apoikos to help fixing the issues.
* For the first commit ba5157e, I would have done the same thing, so I'm OK with it.
* For the second commit 14bebeb I'm just curious to know where exactly in the script you have an empty line.
Anyways, it should not crash. And I would prefer to fix the method here: https://github.com/scummvm/scummvm/blob/0fea35fdd540c134ce53d0e5bde6c07f8ee08d5e/engines/twp/motor.cpp#L567

For this, I see 2 solutions:
- test for emptiness and if so do nothing and return
- or add an assertion

**Comment by bluegr** [comment]
> * For the second commit [14bebeb](https://github.com/scummvm/scummvm/commit/14bebeb77d0c3832c28a1b7a5dc2e4fac3b48fc0) I'm just curious to know where exactly in the script you have an empty line.

The commit message is quite detailed. Here's the offending script line:

    saylineAt: (160,85) text= color=rgba(1.000000,0.800000,0.000000,1.000000) duration=0.000000

**Comment by scemino** [comment]
> > * For the second commit [14bebeb](https://github.com/scummvm/scummvm/commit/14bebeb77d0c3832c28a1b7a5dc2e4fac3b48fc0) I'm just curious to know where exactly in the script you have an empty line.
> 
> @scemino The commit message is quite detailed. Here's the offending script line:
> 
> ```
> saylineAt: (160,85) text= color=rgba(1.000000,0.800000,0.000000,1.000000) duration=0.000000
> ```

I found the line in the original script: Helpers.bnut , line 1115
`sayLineAt(160,85, 0xffcc00, 0, "")`

I remember, this statement is used to reset the previous `sayLineAt`statement, when the cutscene is over.
It's important to understand why this statement exists, it's important because in this example, it means that:
- it's not a bug
- the text has to be reset or you'll have a remaining text in the screen

To conclude, we shouldn't ignore it in the `actorlib.cpp` or the previous "talk" won't be reset, we should return early here:
https://github.com/scummvm/scummvm/blob/0fea35fdd540c134ce53d0e5bde6c07f8ee08d5e/engines/twp/motor.cpp#L567

**Comment by apoikos** [comment]
Thanks both for your comments!

> I found the line in the original script: Helpers.bnut , line 1115
> `sayLineAt(160,85, 0xffcc00, 0, "")`

I just came in to write the same.

> To conclude, we shouldn't ignore it in the `actorlib.cpp` or the previous "talk" won't be reset, we should return early here:

I will push a fix shortly, thanks!

**Review by scemino — APPROVED** [review]
Thank you

**Pull request merged**
