### PR TITLE
ZVISION: comparison between signed and unsigned

### PR DESCRIPTION
**Pull request by fedor4ever**
ZVISION: fix for compilaton warning comparison between signed and unsigned integer expressions

### CODE REVIEW

**Comment by bluegr** [comment]
Please, squash these two commits in one, and change the commit messages to "ZVISION: Fix comparison between signed and unsigned integers"

**Comment by wjp** [comment]
They're two times the same commit, in fact, just with different commit messages.

**Comment by wjp** [comment]
You didn't have to open a new pull request; you could have just updated this one.

**Comment by fedor4ever** [comment]
If it was so simple for me =(
I will be pleased if someone help me with it

**Pull request closed without merging**
