### PR TITLE
GLK: ADRIFT: detection_tables.h overhaul

### PR DESCRIPTION
**Pull request by MarcoBorrini99**
GLK: ADRIFT: detection_tables.h overhaul

This PR adds only some new entries from various competitions but most of all re-arranges detetction_tables.h so I'm asking if this proposal can be accepted.

### CODE REVIEW

**Comment by MarcoBorrini99** [comment]
This should be the latest PR for this system :-)

**Comment by dreammaster** [comment]
Looks good to me, though I think in this case it's better I squash them into a single commit. Thanks for taking the effort to all the cleanup.

**Comment by dreammaster** [comment]
On second thought, I decided it better to maintain the original commits with their descriptions. I just had to manually do the merge so I could reword them to meet our commit message format guidelines.

**Comment by cedricl31** [comment]
Hello Marco,
Thanks for the re-arrangement of adrift games !
I have a doubt about the following entry (i can't find the game anywhere on the usual sites)
DT_ENTRY0("dayattheoffice", "4771123f35431714ad489a2abc4448a9", 13802)

Do you confirm the existence of this version ?

**Comment by MarcoBorrini99** [comment]
> Hello Marco, Thanks for the re-arrangement of adrift games ! I have a doubt about the following entry (i can't find the game anywhere on the usual sites) DT_ENTRY0("dayattheoffice", "4771123f35431714ad489a2abc4448a9", 13802)
> 
> Do you confirm the existence of this version ?

Confirmed. Please check attached file :-) 

[A Day at the Office.zip](https://github.com/scummvm/scummvm/files/11227591/A.Day.at.the.Office.zip)

**Comment by cedricl31** [comment]
Thanks for the file !
By curiosity do you remember where did you get this version ? 
I'm a big fan of IF and this is the first time i see this version (pre-competition release)

**Pull request closed without merging**
