### PR TITLE
AUDIO: Share code between OPL and CMS implementations

### PR DESCRIPTION
**Pull request by ccawley2011**
This should make it easier to support additional sound chips in the future.

### CODE REVIEW

**Review by NMIError — APPROVED** [review]
Nice bit of refactoring! Nothing jumps out at me as problematic, so if all functionality still works, it's fine by me. I can test the Retrowave OPL3 this weekend if you want.

**Comment by ccawley2011** [comment]
> I can test the Retrowave OPL3 this weekend if you want.

That would be quite helpful - I haven't been able to test any of the RealOPL/RealChip drivers.

**Comment by NMIError** [comment]
I just tested a bunch of games with the Retrowave OPL3; Nuked and the CMS emulator as well. It all sounds as it should; no problems.

**Comment by bluegr** [comment]
Thanks for the work @ccawley2011, and thanks for verifying that everything still works, @NMIError!

Very good refactoring :)

**Pull request merged**
