### PR TITLE
AGOS: enable dedicated detection of Simon 1 for the 25th Anniversary edition with full English subtitles

### PR DESCRIPTION
**Pull request by neuromancer**
I drafted this PR to get comments and feedback. It allows to play the 25th Anniversary edition with full English subtitles and speech. I want to know if this is the right path, and if I should add support for german subtitles as well (which also seem to be included in that release).

### CODE REVIEW

**Comment by neuromancer** [comment]
I will re-do this one just to enable the subtitles for the CD release

**Comment by Kirben** [comment]
The original game files in the The 25th Anniversary edition are unchanged, and there would still be missing subtitles in some situations under ScummVM. Mojo Touch just hacked around the subtitle problems, and you would need to look at their source code to see how they did it. Not the type of hacks you would really want to copy...

**Comment by criezy** [comment]
> I will re-do this one just to enable the subtitles for the CD release

Also I am not sure that is a good idea. Many of the subtitles are missing in that release I think, so that could be a strange experience (and a source of many bug reports). It might be better to limit it to the 25th Anniversary edition, assuming support for the missing subtitles can be added in a way that is no too hacky.

**Comment by neuromancer** [comment]
> Mojo Touch just hacked around the subtitle problems, and you would need to look at their source code to see how they did it. Not the type of hacks you would really want to copy...

Where exactly are these hacks located in their source code?

**Pull request closed without merging**
