### PR TITLE
GLK/ADRIFT: Add missing entries for letter A, add prefix checked games

### PR DESCRIPTION
**Pull request by treloret**
GLK/ADRIFT: Add missing entries for letter A, add prefix checked games

Add a prefix to identify them from other glk games, adX where X is the major version (3, 4, and the unsupported 5), only partially done for now, while I keep checking letters

Add game detection:
- A Day In The Life 3- Akari's Story
- The Alchemist
- Alexis-Dalskee
- Another Friday Party
- Archie's Birthday - Chapter 1: Reggie's Gift
- Asylum
- The Average Life
- Adventures of Bob Bobsly
- Adventures of Thumper - Wonder Wombat
- ADRIFTMAS Party
- Adventure
- Aegis
- Albert is Lost!- An Adventure in Real Life
- Alias- Undercover Agent
- Alice's Restaurant Anti-Massacree Adventure
- All Hallows Eve
- The Amazing Uncle Griswold
- The Amazing TV Caper
- Amnesia Kid
- Amy And The Raging Hormones
- The Angel, the Devil and the Human
- Apokalupsis
- Asteroid Aftermath
- Attack of Doc Lobster's Mutant Menagerie of Horror
- El Ancesor
- Attack of the Mutaydid Meat Monsters
- The Adventures of Postman Matt (and his black and white cat)
- The Adventures of Space Boy! Volume II

### CODE REVIEW

**Comment by bluegr** [comment]
Why are we changing the game IDs here? We don't need to reflect the ADRIFT version information to the user in this manner, do we?
Can't we just use a different `DT_ENTRY0` macro, or add appropriate comments to each entry?

**Comment by treloret** [comment]
To prevent overlap and quickly identify the subengine, Adventure being the prime example, don't think any self respecting IF engine doesn't have a port for Adventure, be it the original or the 350+ versions. From the games I just added, numerous had their own versions in different engines. And 3 character identifier just seems right having just checked most of the AGI and SCI fanmade games last year and this year. And I'm going to try to tackle glk one sub-engine at a time.

**Comment by treloret** [comment]
I can provide a link with these additions packed up nicely, since all of them are freeware. Easier than doing what I did.

**Comment by treloret** [comment]
As a side note, to further defend my madness, I've already found a few miss-attributed unsupported ADRIFT 5 games, that were actually 3.90

**Comment by sev-** [comment]
Please, revert the engine prefix. We do not do it for any of the engines normally. You may put the version information in the comments or in the `extra` field in the detection entry.

**Comment by sev-** [comment]
Why did you close the PR?

**Comment by treloret** [comment]
Adrift has postfixes with ... adrift, AGT has prefixes with agt, TADS has postfixes with version number, glulx has plenty of postfixes with glulx. And I don't feel like going through A-D again.

**Pull request closed without merging**
