### PR TITLE
SCUMM: Implement original V0-V2 flashlight shape and size for MM/Zak

### PR DESCRIPTION
**Pull request by segrax**
Fix to use the correct shape/size of the flashlight used by the original engine, covers [10951](https://bugs.scummvm.org/ticket/10951) and [10947](https://bugs.scummvm.org/ticket/10947) 

C64 MM
image

V1
image

V2
image

Zak C64
image

Zak V1
image

Zak V2
image

### CODE REVIEW

**Comment by segrax** [comment]
Ah, and i have unfortunately just noticed that the variable '_flashlight' is not saved, and is adjustable via the o*_lights opcode. can lead to an incorrect flashlight save after restoring a game

ill see if i can get that fixed over the next couple of days

**Comment by ATMcashpoint** [comment]
The shapes of the rounded edges on the MM & Zak DOS V1/V2 flashlight-beams are still wrong. MM & Zak DOS V1 have very chunky rounded edges. For some reason the V2 versions smoothed out the left side only (in a different pattern than appears here).

Also of course Zak DOS V1 shouldn't have the rectangular edges of the C64-style flashlight beam.
mmdosv1flashlight1
mmdosv2flashlight1
zakv1dosflashlight1
zakv2dosflashlight1

**Comment by ATMcashpoint** [comment]
And I just noticed the MM/Zak DOS V1 versions also have different left/right edge designs. Oy, this is complicated!

**Comment by ATMcashpoint** [comment]
It looks like the MM/Zak DOS V1 flashlight left-edge design became the DOS V2 right-edge design.
mmdosv1flashlight2a
mmdosv2flashlight2a

**Comment by ATMcashpoint** [comment]
Here are reference photos of the different lighter spotlights in Zak McKracken, C64/DOS V1/DOS V2:
zakc64lighter
zakv1lighter
zakv2lighter

**Comment by ATMcashpoint** [comment]
And some better reference photos of the MM & Zak V1/V2 flashlight borders.
mmdosv1flashlight3
mmdosv2flashlight3
zakv1dosflashlight3
zakv2dosflashlight3

**Comment by segrax** [comment]
Ok, size/shape has been fixed for Zak v1, and flashlight state is now saved.

Unfortunately I don't have the time to plot out the exact shape of the flashlight for every version at this point in time

**Comment by bluegr** [comment]
Nice! Thanks for your work on this @segrax. This is in a good state to be merged, and a lot of the inconsistencies regarding the flashlight beam among the different versions are addressed.

Plotting the exact flashlight shapes for each version can be done in a separate pull request.

Unfortunately, this means that the two bugs will remain open until the flashlight shapes are done correctly for all versions

Merging

**Pull request merged**
