### PR TITLE
MTROPOLIS: Add detection entries for the German versions of the "Albe…

### PR DESCRIPTION
**Pull request by lotharsm**
This PR adds detection entries for the German Windows releases of the "Uncle Albert" series [1]

There are a bunch of issues:

- albert1: The project files have a "wrong" naming scheme. You need to rename them to "albert1.mpl" and "albert2.mpx". Otherwise, the auto-sorting that happens during the bootstrapping process will load the .mpx file first, causing ScummVM to error out due to missing segment files.
- Loading some of the resource files fails:
WARNING: Couldn't load resources from PE file 'BASIC.X95'!
WARNING: Couldn't load resources from PE file 'BITMAP.R95'!
WARNING: Couldn't load resources from PE file 'EXTRAS.R95'!
WARNING: Couldn't load resources from PE file 'ROTATORK.R95'!
Mabye they are stored in a different format?
- Starting the games fails with `ERROR: Unsupported bit depth!`

All in all, the only thing that actually _works_ right now is detection itself - the games are totally unable to boot. But maybe this can be merged as a starting point for future development.

[1] https://wiki.scummvm.org/index.php?title=MTropolis/Games

### CODE REVIEW

**Comment by somaen** [comment]
Looks good to me, we detect lots of games that don't work at all, so that's fine. I guess perhaps a squash is in order, and dropping the commented out entries?

**Comment by lotharsm** [comment]
I fully agree that this could be squashed into one commit.

However, @elasota suggested that we keep the disabled entries in the detection table for documentation purposes until it is fully clear that the entries are not used. Right now, we don't know yet if they contain information that need to be known to the engine at this point.

**Comment by elasota** [comment]
This needs to be adjusted due to the new revised boot process.  Add a boot ID to detection.h and a boot table entry to boot.cpp, and link the boot ID in the detection entry.

See https://wiki.scummvm.org/index.php?title=MTropolis/Adding_Games or any existing entry.

**Comment by lotharsm** [comment]
Thanks a lot for the heads-up!

While rebasing, I (sort of) messed with my branch, so we probably have to squash and merge this once it is ready.

The detection and boot entries for the `albert2` and `albert3` entries seem to work fine since the game is detected, tries to boot and crashes with
```
WARNING: Data object type ffffffff failed to load!
Failed to load project boot data!
Debugger started, type 'exit' to return to the game.
Type 'help' to see a little list of commands and variables.
ERROR: Failed to load project boot data!
```

Unfortunately, `albert1` is broken and the `missing segment file` issue is back again (we tracked this down to the "weird" naming scheme of the MPL and MPX file).

**Comment by elasota** [comment]
On hold for a bit.  Due to some recent revelations and infra improvements, I'm probably going to redo the boot process again, which'll break compatibility with this.  I'll manually integrate this once that's done.

**Comment by sev-** [comment]
Was the mentioned work already done? So, this could be finally merged?

**Comment by elasota** [comment]
> Was the mentioned work already done? So, this could be finally merged?

No, it was waiting for merge of #4464 but now that that's done I can start doing it.

**Comment by sev-** [comment]
Any updates? The PR starts to bitrot.

**Comment by elasota** [comment]
Just going to fix this up and merge it for now since I'm refocusing priorities and the boot rework is probably not happening any time soon after all.

**Pull request merged**
