### PR TITLE
ADL: Draw Apple II checkerboard cursor

### PR DESCRIPTION
**Pull request by eriktorbjorn**
Based on Apple II emulators, the original drew the blinking cursor as a checkerboard pattern, not as a block. If the cursor was placed on top of a character, it would switch between checkerboard and that character, not invert it. (The original seems to allow for some primitive command-line editing, using the arrow keys. We don't, but if we do the cursor code should support that.)

I have verified that inverted text still works, e.g. in the splash screen for Wizard and Princess. I've made the assumption that the 0x40 bit was only used for the old "cursor inverts the character it's on top of" code, and we don't do that any more.

For the original behavior, see for instance https://archive.org/details/mm_Mystery_House

(Since the game is in the public domain, there should be no problem with that link here.)

### CODE REVIEW

**Comment by eriktorbjorn** [comment]
The Internet Archive link is also a good place to study https://bugs.scummvm.org/ticket/15301

**Comment by einstein95** [comment]
This depends on the model of Apple II, with the Apple II and Apple II+ models having the block cursor while the Apple //e and later models using the checkerboard cursor.

**Comment by eriktorbjorn** [comment]
Cool, I did not know that. What was the most common model? Should we allow for both, or should we just pick one (quite possibly the one we already have) and stick with it?

**Comment by einstein95** [comment]
I'm unsure as to the most popular model, but the //e came out in 1983, much later than Mystery House. Probably wouldn't hurt to allow for both.

**Comment by waltervn** [comment]
I think the main reason I went with the Apple II-style cursor, is that the engine only contains an Apple II font (e.g. no lowercase characters). I assume the checkerboard cursor is actually inside the extended Apple IIe font.

That being said, I do think the checkerboard cursor looks better.

**Comment by eriktorbjorn** [comment]
Something like this, then? Suggestions welcome, including for a better description of the option since English isn't my first language and I've never owned an Apple II.

**Comment by bluegr** [comment]
Looks good, thanks for your work! :)

**Pull request merged**
