### PR TITLE
Add support for Visual Studio 2015 to create_project

### PR DESCRIPTION
**Pull request by Templier**
This adds support for the new version of Visual Studio. 

Note that an updated set of libraries is required for proper linking and they are not backward compatible with VS 2013. You can grab pre-built libraries from the [scummvm-libs](https://github.com/Templier/scummvm-libs) repository. I can transfer that repository to the organization if desired or let the maintainers update the scummvm_vs_libs.zip package instead.

Tested:
 - Visual Studio 2015 RC in debug and release (win32 & x64)
 - Visual Studio 2013 (using the current library pack)

Tasks to complete before this can be merged:
 - [ ] Do not ignore new warnings (C4267 and C4458)
 - [ ] Recreate the scummvm-libs repository to compile for both VS2013 and VS2015
 - [ ] Update create_project to read 2015 and pre-2015 libraries from different folders
 - [ ] Write script to automate building all libraries
 - [ ] Document process to add/update a library in the repository (using git subtree)
 - [ ] Update wiki with new process to get pre-built binaries for Visual Studio
 - [ ] Transfer ownership of repository to ScummVM organization
 - [ ] Update script to allow building MinGW libraries too (optional)

### CODE REVIEW

**Comment by dreammaster** [comment]
Speak of the devil. Just the other day I provided Strangerke with an updated scummvm_libs that contained the extra libraries we now use (x86 only, not x64) for VS 2013 and earlier, as well as the necessary DLLs. Although he hadn't had a chance to update it yet.

I'll download a copy of your lib and integrate it into my update package, and then pass it on for updating on Sourceforge.

**Comment by dreammaster** [comment]
See my [updated scummvm_lib](https://drive.google.com/file/d/0B7K7KNNR87NPV1BYM3ZTRkd0ekk/view?usp=sharing) for the merging of the two versions. I've cut out the src/ folder to keep the size down, and made a separate lib_2015 for your VS 2015 versions of the libraries, to keep them separate from the existing ones.

**Comment by dreammaster** [comment]
Well, compilation doesn't break for me on my existing MSVC2013, but I don't have MSVC2015 installed to actually test the create_project changes. Overall, the changes seem reasonable. Although I'm a wary of the new warning suppressions that this adds: 4267 - possible loss of data in type conversion, and 4458 - variable declaration hides class member.

The latter is something we would want to keep showing as a warning, since it's something that should be fixed across the code base. As for the former, I wasn't aware that the current code-base was generating a "ton" of warnings. Certainly I don't get many warnings when I do a clean build in VS 2013. As with the other warning, it may be better not to set it, and see if anyone is interested in fixing the all the code that generates such errors.

**Comment by dreammaster** [comment]
Also, it may be just co-incidence, but since I tried compiling your revised create_project, I started getting link errors about a 'win_utf8_io' library compiling ScummVM. It's kind of hard to find information on it.. am I correct in thinking that that's a secondary lib file produced by libFlac? I tried using the lib file from your folder, and it seems to work fine in my VS2013.

**Comment by Templier** [comment]
Warnings: You are right, these should not be ignored by default.

win_utf8_io.lib: This is indeed a new dependency introduced by libflac. I thought it would skip it when trying to link in VS2013 but that doesn't seem to be the case.

It looks like I need to revise some of the work before it can be merged. I think the proper way is to redo the scummvm-libs repository to also compile the VS2013 libraries rather than modifying the projects to compile for 2015 instead. This will ensure both sets of libs are in sync. I have edited the pull request description with the TODO list.

**Comment by dreammaster** [comment]
Deprecated in favor of new pull request

**Pull request closed without merging**
