### PR TITLE
ENGINES: Move all game options into the MetaEngine implementation

### PR DESCRIPTION
**Pull request by ccawley2011**
The goal here is to cut down on the amount of places where the `MetaEngineDetection` class is interacted with when the engine is running, with the hope of eventually being able to unload the detection plugin when it's not in use.

### CODE REVIEW

**Comment by sev-** [comment]
Game options are used when rendering GUI. How is it achieved with this PR?

**Comment by ccawley2011** [comment]
> Game options are queried when rendering GUI, the GUIO, those checkboxes in the Engine tab. How is it achieved with this PR?

As I understand it, the original code stored the GUIO options in the configuration, and updated them when adding or launching a game. Calling `getExtraGuiOptions()` would just use the cached options, and this is unchanged by this PR.

**Review by bluegr — APPROVED** [review]
Great! +1 from me

**Comment by bluegr** [comment]
With the changes in #4278, there are conflicts now. @ccawley2011, can you please rebase and fix them?

**Comment by bluegr** [comment]
@ccawley2011, any news?

**Comment by sev-** [comment]
Thank you!

**Pull request merged**
