### PR TITLE
PSP: Remove .MIPS.abiflags* sections from plugins

### PR DESCRIPTION
**Pull request by ccawley2011**
The ELF loader can't handle plugins with these sections, and it doesn't appear to be needed for our purposes.

### CODE REVIEW

**Comment by bluegr** [comment]
According to this: https://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20140707/224651.html

> Mips.abiflags is a new implicitly generated section that  will be present on all new modules. The section contains a versioned data structure which represents essentially information to allow a program loader to determine the requirements of the application

There's also this patch of the ELF loader: https://sources.debian.org/patches/patchelf/0.12-1/Adjust-PT_MIPS_ABIFLAGS-segment-if-present.patch/

> When loading the executable on MIPS, the dynamic loader looks for MIPS
ABI flags using PT_MIPS_ABIFLAGS header. The flags themselves are stored
in the .MIPS.abiflags section, so the header must be updated when the
section is moved.

Which version of the ELF loader is used in the PSP?

**Review by rsn8887 — APPROVED** [review]

**Comment by rsn8887** [comment]
This works perfect for me. I can even build with all engines now. There used to be a crash in the Add Game dialog whenever I tried a build with all engined, but now it works.

This means that after this change, we can probably enable all unstable engines again in the buildbot, and get rid of that separate pspfull build.

**Comment by rsn8887** [comment]
> Which version of the ELF loader is used in the PSP?

It is this one:
https://github.com/scummvm/scummvm/blob/master/backends/plugins/elf/mips-loader.cpp

I don't think it has a version.

**Comment by lephilousophe** [comment]
We can either accept these sections in our loader or strip them when linking.

**Review by lephilousophe — APPROVED** [review]
Looks good to me

**Comment by rsn8887** [comment]
Thanks for the PSP fix!

**Pull request merged**
