### PR TITLE
SCUMM: Add support for the classic SE variants of MI1, MI2, DOTT and FT

### PR DESCRIPTION
**Pull request by bluegr**
### Introduction
This PR aims to support the classic SE variants of MI1, MI2, DOTT (including MM) and FT, found in their SE/remastered versions.

### Information
The reasoning for this PR is that the SE editions are the the only versions of these games that can be purchased online. It has always been possible to use ScummVM with these versions, but [external tools and scripts were needed](https://forums.scummvm.org/viewtopic.php?t=7671) to extract the files of the classic game variants. With the changes in this PR, we can support these classic version variants out of the box.

All of the files of these game variants are packed using a common PAK format.
Support for this format has been added based on the [work done in DoubleFine Explorer](https://github.com/bgbennyboy/DoubleFine-Explorer/blob/master/uDFExplorer_LPAKManager.pas).

### Games
The classic game variants that this PR handles are:
- The Secret of Monkey Island: Special Edition - [Steam](https://store.steampowered.com/app/32360/The_Secret_of_Monkey_Island_Special_Edition/), [GoG](https://www.gog.com/en/game/the_secret_of_monkey_island_special_edition)
- Monkey Island 2 Special Edition: LeChuck’s Revenge - [Steam](https://store.steampowered.com/app/32460/Monkey_Island_2_Special_Edition_LeChucks_Revenge/), [GoG](https://www.gog.com/en/game/monkey_island_2_special_edition_lechucks_revenge)
- Day of the Tentacle Remastered - [Steam](https://store.steampowered.com/app/388210/Day_of_the_Tentacle_Remastered/), [GoG](https://www.gog.com/en/game/day_of_the_tentacle_remastered)
- Full Throttle Remastered - [Steam](https://store.steampowered.com/app/228360/Full_Throttle_Remastered/), [GoG](https://www.gog.com/en/game/full_throttle_remastered)

### TODOs left to fully support these game variants:
- <strike>The new digital music format in MI1. This is a separate implementation, and will not be addressed with this PR. Because of this, external tools are still needed to handle the music in the classic MI1 variant.</strike> **UPDATE**: We now have support for the container XWB audio format used in the SE versions of MI1 and MI2. Also, all the audio CD playing code for MI1 SE has been reused from Loom Steam, and it should work out of the box.
- <strike>Support for the Maniac Mansion easter egg found in DOTT. This will need to be handled separately, as we can't support it at the moment when its files are not in a game folder. </strike> **UPDATE**: This has been implemented now :)
- Handle all the different XWB audio formats: PCM (done), XMA (no need - unused in MI1 and MI2), ADPCM (done), WMA (TODO)

### Plan and next actions
I have a phased approach in mind, regarding support for the Doublefine SE versions (MI1, MI2, MM, DOTT, FT). The enhancements in the list can be done in-tree. It would be good to have WMA support so that music in MI1 classic is playable, but it's not a blocker for this PR:

Phase 1:
- [X] PAK file container format
- [X] XWB audio container format (MI1, MI2)
- [X] Hook MI1 CD audio infrastructure
- [X] PCM and MS ADPCM sound format (music, sfx and speech in all games, apart from MI1 CD audio)
- [ ] WMA sound format (MI1 CD audio)

Phase 2 - enhancements:
- FSB audio container format (DOTT, FT)
- Hook MI2 SE digital music on top of iMUSE (using XWB files)
- Hook MI1 and MI2 SE speech and SFX (using XWB files)
- Hook DOTT SE digital music on top of iMUSE (using XWB files)
- Hook FT SE digital music on top of digital iMUSE (using FSB files)
- Hook DOTT and FT SE remastered speech and SFX (using FSB files)

Any comments are more than welcome :)

### CODE REVIEW

**Comment by AndywinXp** [comment]
This is bonkers :) awesome job!

I have just seen the code and I have yet to try it... but really, this is incredible. You singlehandedly added support for the only versions of those games that people can currently buy on digital stores, for which people previously had to resort to technical tools and such. Thank you!

I'll let you know when I can test it properly, for regressions, etc.

**Comment by bluegr** [comment]
We now have support for the container XWB audio format used in the SE versions of MI1 and MI2. Also, all the audio CD playing code for MI1 SE has been reused from Loom Steam, and it should work out of the box. We're still missing the WMA decoder, so this code is disabled, for now.

**Comment by AndywinXp** [comment]
I just tried the code myself! Wonderful job!

I have a remark however. It seems my GOG copy of DOTT might not be the one your detection entry expects, so the game crashes at startup, along with its Maniac companion. 

Maybe there could be some kind of fallback based on the naming of the resource file? These games had their own share of patch updates throughout their time, so it could just be that supporting only one might not be a viable option.

**Comment by bluegr** [comment]
Thanks for the feedback @AndywinXp!

I've tested all the GoG and Steam versions of these four games. Only DOTT is different between GoG and Steam, so I've added the checksum of its GoG version, too.

You're right about the handling of these game variants in the fallback detector, although they don't get updated anymore. So, although this is important, we can handle the fallback detector changes in-tree, IMHO.

From SteamDB:
- MI1SE has only 1 version released: https://steamdb.info/app/32360/depots/
- MI2SE has only 1 version released: https://steamdb.info/app/32460/depots/
- DOTT's last update was 4 years ago: https://steamdb.info/app/388210/depots/
- FT's last update was 4.5 years ago: https://steamdb.info/app/228360/depots/

**Comment by bluegr** [comment]
Thanks for your review @AndywinXp!
So, we've reached a good milestone now! Further work will be done in-tree.
Merging this.

**Pull request merged**
