### PR TITLE
ANDROIDSDL: Remove deprecated port

### PR DESCRIPTION
**Pull request by lephilousophe**
It seems to me that this port is not used anymore. I propose to remove it.
@antoniou79 There is a comment at `engines/bladerunner/bladerunner.cpp:342` mentioning Android SDL. I am not sure about it.

### CODE REVIEW

**Comment by aquadran** [comment]
we need also remove it on wiki

**Comment by antoniou79** [comment]
It's an else case that was added specifically to address an issue that, at the time, was reported for the Android SDL port and it did not occur on the Android plain port. 

However, the code can be kept since it does cover a possibly unforeseen situation and it's harmless to keep it. We could probably update the comment to remove reference to the Android SDL port and make it more generic.

The issue that the code addressed was reported here:
https://bugs.scummvm.org/ticket/11149

**Comment by lephilousophe** [comment]
Thanks for the insight, I reworded the comment.

**Comment by aquadran** [comment]
is possible to get empty list from android port? "_system->getSupportedFormats();"

**Comment by lephilousophe** [comment]
Current Android port uses `OpenGLGraphicsManager` which provides a fixed list of supported formats so we are safe here.

**Pull request merged**
