### PR TITLE
SCUMM: Fix glitch when Bruno flees Bumpusville (bug #3832)

### PR DESCRIPTION
**Pull request by dwatteau**
See [Trac #3832](https://bugs.scummvm.org/ticket/3832) for more context, screenshots and saves.

In Sam & Max, when Bruno and Trixie leave Bumpusville, a new actor is used for their escape animation, but the original script never removes this actor from the scene, so some parts of Bruno can still be seen on the wall when the door closes (although it's not extremely visible, since Bruno's colours match that of the wall… but once you've seen it…). So this PR forces the removal of this actor just before this happens.

This actually just follows @eriktorbjorn's initial suggestion. The original script (no. 202 in room 47) does this:

```
...
[06B4] (7F) putActorInXY(6,160,100,47)  # <== Combined Bruno+Trixie actor
[06C1] (82) animateActor(6,250)
[06C8] (82) animateActor(6,6)
[06CF] (7F) putActorInXY(12,0,0,0)      # <== Trixie
[06DC] (CA) delayFrames(23)
[06E0] (7F) putActorInXY(11,0,0,0)      # <== Bruno
[06ED] (CA) delayFrames(28)
[06F1] (B6) printDebug.begin()
[06F3] (B6) printDebug.msg(sound(0x9FC6ECA, 0xA) + " ")
[0707] (70) setState(451,0)             # <= The door gets closed
[070E] (43) bitvar2 = 0
[0714] (82) animateActor(2,249)
...
```

and so indeed I don't think there's a better place than `o6_setState()` to catch and fix this. I've just restricted the conditions a bit more.

In order to test this:

1. grab the savegames from the Trac issue above
2. insert the key in security mechanism on the right
3. wait for Bruno to leave the room.

Tested with my original French CD and with the English version from GOG.

### CODE REVIEW

**Comment by bluegr** [comment]
This is such a minor glitch that I had trouble finding it, but yeah, once you see it, you can't miss it :)

Perhaps it would be better to add this workaround to the animateActor() call below?
This seems to be a better place for such functionality

**Comment by dwatteau** [comment]
> Perhaps it would be better to add this workaround to the animateActor() call below? This seems to be a better place for such functionality

OK, I've pushed a new commit for this (I will squash it into a single commit later if necessary).

I thought the `animateActor()` call was too late, because `setState(451,0)` is already done at that point, but it looks like changing the state of the door doesn't immediately close it on the screen. So, while stepping with a debugger, it looks like it still works if the workaround is done in o6_animateActor(), yes. But I can't say if it's safe, I don't really know how the visual updates are done.

I had to add a check for the costume, though, because `animateActor(2,249)` is called twice in that script, the first time being before they leave the room.

**Comment by bluegr** [comment]
Looks good now. Thanks for your work! Merging

**Comment by bluegr** [comment]
Looks good now. Thanks for your work! Merging

**Pull request merged**
