### PR TITLE
Fix duplicate include guard

### PR DESCRIPTION
**Pull request by janisozaur**
The guard clashed with https://github.com/scummvm/scummvm/blob/1a097b1d971e6e3cf3c10f6eb7c7a30def2d2f7c/engines/dialogs.h#L23

### CODE REVIEW

**Comment by digitall** [comment]
@janisozaur : Thanks. Fairly obvious cut-and-paste error. Will commit, though since your commit does not match up with https://wiki.scummvm.org/index.php/Commit_Guidelines#Commit_message_formatting ... Will merge with an amended message. Please stand by.

**Comment by digitall** [comment]
Manually merged as commit cf9690f6b6835b3a9c42013f1b941e85f99129da with minor fixup to commit message, so closing this PR.

@janisozaur : Thanks for spotting this.

**Comment by janisozaur** [comment]
Interesting, I usually am strict about such commit messages myself, especially the subject line. Was it the GitHub link? The lack of subsystem?

FYI: GitHub offers a way to squash-merge a PR, where you can also specify the commit message and it will mark the PR as closed (merged) with appropriate commit.

**Comment by janisozaur** [comment]
I would suggest putting the link you provided as the PR template on GitHub. If you embed it in HTML comments, it won't show up in the formatted text even if someone forgets to remove it out.

**Comment by digitall** [comment]
@janisozaur : Sorry, was the lack of SUBSYSTEM: prefix and the github link should just be a bare note on the related file so removed that (We have gone through CVS, SVN, SF.net and various others so now tend to avoid URLs in commits :)

Ah, sorry should have done it that way i.e. fixup commit and squash, but was just easier to cherry-pick and amend. Anyway, all done.

**Pull request closed without merging**
