### PR TITLE
BASE: Enable aspect ratio correction by default (take 2)

### PR DESCRIPTION
**Pull request by AndywinXp**
Here we go, let's do it 🙂 Take 2 of the previous PR by @lotharsm 

This was highly requested by people. And most importantly by me 😝 

Discussion on: https://github.com/scummvm/scummvm/pull/1542

### CODE REVIEW

**Comment by lotharsm** [comment]
Thank you - I still like the idea ;-)

**Comment by sev-** [comment]
The argument still holds. There is no perfect upscaler, and the current approach leads to artefacts.

I think, the best approach is using Shader for aspect ratio correction, so it uses much higher resolution and proper floating point scaling.

**Comment by AndywinXp** [comment]
> The argument still holds. There is no perfect upscaler, and the current approach leads to artefacts.

While that's true, there's apparently a quite sizable part of the userbase who still turns this on each time regardless. 

I should also mention that in recent years artifacts have been more and more negligible thanks to the current resolution of screens: with a resolution as small as 960p ScummVM can currently display aspect ratio corrected 320x200 images with very negligible artifacts. Of course one could argue that there's a degree of subjective visual perception at play... 🙂

I agree that a scaler would better suit our needs, but until someone develops it... this might be the best compromise at the moment IMHO.

**Comment by raziel-** [comment]
@sev- 
would it be better to completely remove this option then...maybe?

**Comment by sev-** [comment]
Okay, let's give it a try. Please follow up with a NEWS item directly to the master.

**Comment by AndywinXp** [comment]
Will do, thank you! 🙏

**Pull request merged**
