### PR TITLE
DEVTOOLS: Add test for previous dumpercompanion workaround, other changes

### PR DESCRIPTION
**Pull request by einstein95**
Use "MacJapanese" instead of "Mac Japanese", remove commented code from previous PR. These were requested by @rvanlaar

### CODE REVIEW

**Comment by bluegr** [comment]
Thanks for the fixes! Merging

**Comment by gingerbeardman** [comment]
I just came across some other characters that are not dealt with, and upon reading the spec it seems Shift+JIS mapping is missing from the Japanese logic.

see: "Unicode mapping issues and notes"
ftp://ftp.unicode.org/Public/MAPPINGS/VENDORS/APPLE/JAPANESE.TXT

I'll try to fix this myself, please expect a PR

**Comment by gingerbeardman** [comment]
Sadly I don't know Python well enough to code a map like that efficiently.

**Comment by gingerbeardman** [comment]
My WIP is at https://github.com/gingerbeardman/scummvm/commit/39f41332712d4daa7893a7659171d703e50db774

**Comment by rvanlaar** [comment]
@gingerbeardman Thank you for bringing this to our attention. The mapping was automatically generated. We're looking into regenerating it with the included Shift-JIS ranges

**Comment by gingerbeardman** [comment]
My final solution to my task of generating directory listings of these old discs is to use hfsutils (for raw directory listings) plus a small Tcl script (to do the re-encoding).

So, all this to say I probably won't find time to clean up my PR. Feel free to use any part of it or abandon it altogether and close it.

**Pull request merged**
