### PR TITLE
Comprehensive KYRA (EOB) news

### PR DESCRIPTION
**Pull request by vrza**
@athrxx We forgot to mention the first round of changes including the new feature flag "Faithful AD&D rules". Updated NEWS with all the changes.

### CODE REVIEW

**Comment by athrxx** [comment]
Thanks! I wasn't aware that we never mentioned the checkbox before...

**Comment by vrza** [comment]
@athrxx Found another issue. In EotB I level 7, there is an item "Ring of Wizardry" that, when worn, should doubles the number of level 4 and level 5 spells a mage can memorize. This item works in the original game, but has no effect in the ScummVM port.

**Comment by athrxx** [comment]
Thanks! I have made a fix, but it is untested, since I didn't find any savegame with that ring. Please check if its works.

**Comment by vrza** [comment]
@athrxx  I tested, and the fix seems to work, thanks!

Here's a convenient saved game for testing:

[eob.077.gz](https://github.com/user-attachments/files/17866797/eob.077.gz)

Looking at the context in which `checkInventoryForRings` is called, 3 constants become apparent:

```
kRingOfWizardry = 1
kRingOfSustenance = 2
kRingOfFeatherFalling = 3
```

**Comment by athrxx** [comment]
Thanks, the ring seems to work as intended.

I have added the constants you suggested, since it seems like a good idea... ;-).

**Comment by vrza** [comment]
@athrxx Found another issue. After triggering EotB 1 level 10 special quest, monsters don't drop reward items.

Save game:

[eob.111.gz](https://github.com/user-attachments/files/17925895/eob.111.gz)

Explanation from an online guide:

> Level 10, mantis hive
> WHERE: In the southeast of the level is a room with four niches, and three alcoves between those niches.
> WHAT: Go back to level 6 to pick up three kenku eggs; put one in each of the alcoves. If that doesn't work, try the center alcove first, then the southmost
one, then the northmost.
> REWARD: Ring of sustenance, feather fall, and 2x protection +2; you'll have to
fight some mantis to get these.

Didn't check but pretty sure this works in original game.

**Comment by athrxx** [comment]
Thanks! I'll get to it asap... :-)

**Comment by vrza** [comment]
@athrxx I was digging as well, the issue is here:

https://github.com/scummvm/scummvm/blob/5109cd081f4efa2ffc6ec6c4e2592c57c15efedc/engines/kyra/engine/items_eob.cpp#L150

_items table (items spawned in game world) is hard-coded to 600 entries, and it's preallocated.

Simplest fix would be to turn this into a constant and increase the table size.

Nicer fix would be some dynamic allocation.

**Comment by athrxx** [comment]
Interesting. So this is something specific to this savegame. I was wondering if people could manage to actually get the table to overflow.

Original EOB1 has even lesse entries. Only 500. So the problem would come to surface much earlier. The table size of 600 is from EOB II.

I guess I should still fix it, even if it is an original limitation. At least if your diagnosis is right, I haven't done any debugging on this yet (I am still wondering how you managed to blow up the item table so much :-). The only situation in EOB that comes to my mind is the level with the spear throwing monsters which really spawn these spears like crazy).

**Comment by vrza** [comment]
In this case it was probably Kenku on level 6, that respawn infinitely, and often drop rations when killed.

The problem with increasing the table size is that the original games will only load 500 or 600 items from the save file, so the challenge is how to do a save game export without breaking the game.

**Comment by athrxx** [comment]
> The problem with increasing the table size is that the original games will only load 500 or 600 items from the save file, so the challenge is how to do a save game export without breaking the game (losing important items on import).

Yes, that is something to consider. Even the currently existing export function will skip items for EOB I beyond the limit of 500. The "good" thing here is that the savegame export isn't really something that I advertise to the end-user, so it probably doesn't get used much. Would make sense to at least give a warning, though...

**Comment by vrza** [comment]
Wondering if it might make sense to add functionality that would omit or remove commonly repeated item types. In the case above, we can lose 100 rations without breaking the game. Such a function could be used to achieve a sane export save game. Either as part of export, or as a separate command that user can call before export to "clean up".

**Comment by vrza** [comment]
To summarize:

- increase the items table size in ScummVM
- prominent warning when table is full
- warn when exporting original save and export table cannot fit
- implement console tools to manipulate items table

If this sounds good to you, we can divvy up the work -- if you can hunt down where the table size limits are hard-coded, I could write the console tools.

**Comment by athrxx** [comment]
Yes, sure we can share the workload, please go ahead and update the console tools. Maybe warn in the console if the item table would be truncated and ask for abort/continue. And add some command to cleanup the items table.

I have now made the item list size dynamic. I really hope that I didn't break anything :sweat_smile: 

Unfortunately, I can't really test your savegame. It crashes as soon as I kill the first Mantis. The reason is that Tod Uphill has somehow reached level 12 which shouldn't be possible. This causes an invalid read in the experience points table which has entries for 11 levels only (the last entry being the 0xFFFFFFFF blocker). Are the stats manipulated somehow? `increaseCharacterExperience()` should never let you skip over the table boundaries...

If this is a normal (untampered) savegame there might be an unpleasant bug somewhere. In that case, it would be helpful if you also have a savegame where  Tod Uphill still is at level 11.

**Comment by vrza** [comment]
> Tod Uphill has somehow reached level 12

Oh, I forgot about that, but that's another idea I was testing, to increase the level cap to 20.

Here's the rebased feature branch, it should load the savegame fine: https://github.com/vrza/scummvm/tree/eob-level-cap

The challenge with this idea is again savegame export. It's fairly easy to change the level, but rolling back HP gains is a tad more involved.

> I have now made the item list size dynamic.

Looking at the patch now. common/array.h seems to have linear time complexity, including a malloc, on every insert. Does it have advantages over std::vector?

Off the top of my head, since the items in the item list are small (around 14 bytes), a structure based on a regular array, but one that can be doubled in size when filled up would be best, with amortized time complexity.

Also in C++11 collections, perhaps there is a built-in one that's a good fit for this (besides std::vector).

Game engine already has some code that are really methods on this items collection (a good example is finding the unused item slot).

On that note, how do we safely delete items from the items collection? I know that the character inventory can have a reference to an item, any other references that would need to be cleaned up, top of mind?

Here's the WIP branch for console commands. I also gave you write access.

https://github.com/vrza/scummvm/tree/eob-items-console

**Comment by vrza** [comment]
> This causes an invalid read in the experience points table which has entries for 11 levels only (the last entry being the 0xFFFFFFFF blocker).

A few more comments on this.

0xFFFFFFFF blocker is a really bad way to implement this, they could've checked against a some levelCap number instead and it would be less brittle. But, it is what it is.

The original EotB 1 game manual shows XP requirements for Fighter, Thief and Ranger up to level 12, but game data files contain tables that only go to 11.

**Comment by athrxx** [comment]
> > Tod Uphill has somehow reached level 12
> 
> Oh, I forgot about that, but that's another idea I was testing, to increase the level cap to 20.
> 
> Here's the rebased feature branch, it should load the savegame fine: https://github.com/vrza/scummvm/tree/eob-level-cap
> 

What is the purpose of that experiment? It might just unbalance the game and probably not contribute much towards the playing experience... But at least, I am glad that I don't have a bug here  :sweat_smile: 

> The challenge with this idea is again savegame export. It's fairly easy to change the level, but rolling back HP gains is a tad more involved.

I wouldn't spend too much time on that debugger function. It is really something I basically wrote for myself and is in no way intended for the end user. And you needn't turn on the faithful AD&D feature for debugging...

> 
> > I have now made the item list size dynamic.
> 
> Looking at the patch now. common/array.h seems to have linear time complexity, including a malloc, on every insert. Does it have advantages over std::vector?
> 

Yes, the advantage is that it is allowed in ScummVM :grin: . std is not allowed. Anything for which you would need `<>` include brackets is not allowed. For portability reason, we have to stick to our common code. Although it is okay, of course, to add things to the common code. For the items list I think it doesn't really matter what you do, since there is little activity on it and it is not relevant for performance.
 

> Off the top of my head, since the items in the item list are small (around 14 bytes), a structure based on a regular array, but one that can be doubled in size when filled up would be best, with amortized time complexity.
> 
> Also in C++11 collections, perhaps there is a built-in one that's a good fit for this (besides std::vector).
> 
> Game engine already has some code that are really methods on this items collection (a good example is finding the unused item slot).
> 
> On that note, how do we safely delete items from the items collection? I know that the character inventory can have a reference to an item, any other references that would need to be cleaned up, top of mind?

That is a very good question. It seems like a bit of  a pita :sweat_smile: 
What comes to my mind:
- Everything that is somehow chained has to be repaired, so all prev/next indices for all items that are in a chain. Currently, I see only two chains, the `drawObjects` for each block of the currently loaded level and `inventory[16]`, but not 100% sure
- The other inventory slots
- The mouse cursor item
But there might be more hidden...
Fortunately, it is (by far) not as bad as it could be. There is no script state we have to consider. And I also first thought we might have to update all monsters in all levels for their drop items. But the items are only generated when the monsters die and the monsters store only the item types.
Still, it might be a bit much, just for the debugger export. 


> 
> It might make sense to move all this code to a separate Items class, encapsulating the collection data structure and exposing methods to manipulate it.

Honestly, the code could be made more appealing in many ways. But it is kind of not worth it considering the potential for regressions. And for me it is more important to have a codebase that somewhat resembles the original, so that I can do disasm based debugging without too much mind-twisting.

**Comment by criezy** [comment]
> Looking at the patch now. common/array.h seems to have linear time complexity, including a malloc, on every insert. Does it have advantages over std::vector?
> 
> Off the top of my head, since the items in the item list are small (around 14 bytes), a structure based on a regular array, but one that can be doubled in size when filled up would be best, with amortized time complexity.

Actually `Common::Array` doesn't allocate new memory on every insert. It grows by doubling its size. See how both `insert_aux` and `emplace` call `allocCapacity(roundUpCapacity(_size + n));` if it needs to grow, with `roundUpCapacity()` rounding up to the next power of 2.

**Comment by vrza** [comment]
@criezy Thanks, I was quickly scanning the code and overlooked the `roundUpCapacity()` call rounding up (doubling) the size.

@athrxx It's a pita indeed, but I'm making some progress. Still need to figure out how to remove objects from blocks on a different level than current (`deleteBlockItem` seems to work in a current level context, but I might be wrong). And I need to write code that will fix the chaining when the table is compacted and indices change. Do you know the purpose of `item.next` and `item.prev` pointers, are they connected to `drawObjects`?

**Comment by athrxx** [comment]
So, I think it would suffice to go over all blocks of the current level, check if drawObjects are assigned, and if yes, fix that and also iterate over the complete assigned items chain and fix the prev/next indices. Same thing for the inverntory. And for the quiver (inventory[16]) it is also necessary to process the complete chain.

**Pull request merged**
