### PR TITLE
COMMON: Avoid punycoding paths in configuration for Win32

### PR DESCRIPTION
**Pull request by lephilousophe**
Under Win32 paths use colons and dots with a special meaning.
These are puny-encoded and the paths in configuration file are not quite readable anymore.

For such paths, don't puny-encode and return them using the traditional backslash path separator.

I only do it for absolute paths to avoid unplanned consequences with path not absolute (not sure if we have any).

I also fix a `fromConfig` leftover coming from before the introduction of `fromCommandLine`

### CODE REVIEW

**Comment by sev-** [comment]
I wonder, why do you want/need backwards compatibility with backslashes?

**Comment by sluicebox** [comment]
This does not fix the issue on Windows; I'm not sure under what conditions it has any effect.

You mentioned on discord that you're only testing this on wine? I don't know the story there, but I would suggest that this code is far too critical to not develop and test on Windows.

1. Add a game from c:\Games\winnie-dos
2. `path=xn--C-da5o/Games/winnie-dos/` is still written to scummvm.ini

Expected behavior is just like before: no punycode encoding and native path separators.

`punycodeNeedsEncode` returns false here, also that comment is concerning:
```
// with some luck we don't need to punycode the path
if (start && !extract(start).punycodeNeedsEncode()) {
	return toString(Path::kNativeSeparator);
}
```

What problem on Windows does punycode path encoding solve? Using Windows, please =)

I would really like to help on this, because this is my top priority bug to get fixed; it's a blocker for the Windows release. I've had to work around it almost every day I've developed since it landed, so I automated patching my config back to normal. There are entire Sierra communities this will break, because they frequently bounce back and forth between old scummvm forks and new releases. And a big part of what I do is hunt regressions in our codebase, where this breaks me every time. But I don't understand why punycode path encoding is relevant to Windows config files at all. I've seen a lot of path encoding issues while implementing our Windows UNICODE builds, and I thought we were done.

It looks like this code tries to see if it's okay to skip punycode on windows on a path-by-path basis. Even if it worked, that would lead to inconsistent scummvm.ini files where we would never be able to precisely answer the question "why does this one path look so weird?"

I propose that puncycode-path-config writing should be completely disabled on Windows for all strings, instead just Path::toString or whatever with native separator. The current code has severe backwards compatibility consequences for our most popular platform, it is complex, I haven't heard why it's necessary, and it doesn't sound like the code has been tested on the real platform. I am under the impression that writing Windows paths to a text file is a solved problem =)

**Comment by sev-** [comment]
@sluicebox I hear your frustration. Originally this came as part of PR#5833 for handling separators and paths with Unicode.

Or is your question about the need for Punycode in general? If so, I can explain.

**Comment by lephilousophe** [comment]
I don't understand why the change would have not worked for you as I did this exact same test on a Windows 7 VM after having talked to you on Discord.

Anyway, after thinking more about it and playing with some paths on Windows, I didn't manage to find a use case where not encoding the path would cause a problem on UNICODE platforms.
I relaxed the tests for such platforms.

For non UNICODE Win9x, as we get paths in the system encoding, I still keep the punycoding in place where it's needed.

**Comment by raziel-** [comment]
@lephilousophe 

would the amigaos(4) backend qualify for this as well?

we use colons as well, as partition/hdd top level separator (like this: "partition_or_root:sublevel/sublevel/etc")

while dots in names does not have a special meaning and also don't get a special treatment, they are allowed.

...and, I also get this xn-- stuff in the .ini

**Comment by raziel-** [comment]
thank you ❤️

**Comment by lephilousophe** [comment]
I reworked (again) this part and simplified the checks.
On Win32 UNICODE, it's the same as earlier: if there is no bad character (slash, backslash, pipe) everything is written as-is.
Now, on all drive based platforms (including non-Unicode Win32), everything is puny-encoded except if colons are the only character which would cause encoding.
On non-Unicode Win32 we also accept the interrogation mark as it can be used in the path specifier.

To make it work on Win32 with special characters, I had to change the puny-encoding algorithm used for the configuration to not consider path contents as UTF-8 codepoints.
**This has the side effect of breaking some configuration files which were using accented paths and I don't see a way to fix this...**

**Comment by lephilousophe** [comment]
@raziel- I had to patch my patch because I did a bad move by changing the punycodeEncode and punycodeDecode functions.

**Comment by sluicebox** [comment]
Thank you all; I will test these latest changes tonight, and if they don't work as expected, I will try debugging a bit deeper so I can provie more specifics. It sounds like @lephilousophe and I are seeing different things at runtime; so I will try to be thorough in case I made a testing mistake earlier.

@sev Thank you for asking, I acknowledge the need for punycode, but yes I'm only talking about Windows here.

For the record: I raised this issue with @lephilousophe earlier this year and they were very responsive, I just drifted away from discord so this is really on me for not following through months ago. I am self-conscious that my style of framing complex issues come across as confrontational, and I fear that has happened here. Unintetional! I struggle with efficiently expressing ideas without ranting. Please send help! =)

**Comment by sluicebox** [comment]
Works great!

Tested on:
- Several Windowsesuses
- msys2 and msvc builds
- UNICODE and ANSI builds
- Paths with interesting unicode characters

I tested local paths and file share paths like `\\server\share\game\` and both were written to config as expected and read back correctly. If I'm reading this right, there's compatibility code to read the paths in configs that are already encoded, and that's working for me too. In short: I can't find anything that isn't working as it did before. Whahoo, thanks!

**Review by sluicebox — APPROVED** [review]

**Pull request merged**
