### PR TITLE
BACKENDS/WAGE: Improved clipboard support

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by criezy** [comment]
If I understand properly the change in commit 7442d7c, you now have a default clipboard implementation in `OSystem` that is an internal clipboard not shared with any other applications or the system. You however kept the `kFeatureClipboardSupport` flag, and while you removed checks in most places, you kept them in both the unknown game dialog and the cloud wizard, where using the clipboard only makes sense if it can access the system clipboard.

I think this makes sense, but the documentation of the `kFeatureClipboardSupport` should be updated to indicate that `hasTextInClipboard()`, `getTextFromClipboard()`, and `setTextInClipboard()` can still be used when the feature is not supported, but it will be using a clipboard internal to ScummVM and not shared with other applications.

I am not familiar with the wage engine, so I will let others comment on that.

**Comment by criezy** [comment]
@dreammaster Unrelated to this PR, other than the fact it shows up in the diff for commit 7442d7c, I see that you convert unicode characters to ASCII by replacing non-ASCII character with '?' in engines/glk/selection.cpp. Maybe you could use `Common::Encoding` for this, since it might do a bette job (it can do some transliteration, which could for example convert 'café' into 'cafe' rather than 'caf?'). Also you could convert to the current GUI encoding instead of ASCII, since my understanding is that this is what the `OSystem` clipboard functions expect (this is not documented, but at least the SDL and macOS implementations make that assumption).

**Comment by ccawley2011** [comment]
> I think this makes sense, but the documentation of the kFeatureClipboardSupport should be updated to indicate that hasTextInClipboard(), getTextFromClipboard(), and setTextInClipboard() can still be used when the feature is not supported, but it will be using a clipboard internal to ScummVM and not shared with other applications.

OK, done.

**Comment by bluegr** [comment]
Nice work! :)

This is in a good state now. Since this actually adds a clipboard functionality for SDL 1.2, and since it mainly affects WAGE, which is not stable yet, we can merge this regardless of the 2.1.0 release

**Comment by bluegr** [comment]
I talked with @sev about this, and we agreed that it’s fine to merge. Thus, merging this. Thanks for your work!

**Pull request merged**
