### PR TITLE
SCUMM: Improve timing in Sam & Max intro (bug #13378)

### PR DESCRIPTION
**Pull request by eriktorbjorn**
This pull request attempts to improve the timing of the Sam & Max intro. See https://bugs.scummvm.org/ticket/13378 for further details.

It does so in a number of ways:

- The German version inexplicably speeds up the scene where the scientist says "Wirst Du brutzeln, wie eine grobe Bratwurst!" ("You'll fry like a pork sausage."). I've slowed that down to match the speech.
- Sam's German actor speaks quite slowly while Max beats up the scientist. I've slowed down Sam's animation to match that, and the other two animations (Sam fiddling with the rope and Max beating up the scientist) are played twice. This isn't quite seamless, but I think it looks better than just leaving them frozen.
- Several broken-up lines (i.e. lines with embedded "wait" instructions) have been re-timed so that the subtitles and speech are in sync. This may be a bit futile because for the rest of the game the timings are calculated guesses. But I needed it for the aforementioned Max-beats-up-the-scientist scene.

In the Italian version, Sam's actor speaks very quickly in the max-beats-up-the-scientist scene, so there that whole scene was sped up which made it look rather ridiculous. I've toned that down a bit, while slowing down the two background animations to make them look normal. I've also added re-timings of a couple of broken-up lines.

The other versions did not have any of the animation issues, but it seemed a shame not to re-time the broken-up lines, so I've added that for the French, English and Spanish versions as well. (Note that the Spanish version uses the English voices.)

However...

It was pointed out to me that the French floppy version uses a completely different recording than the CD version. I've restricted the French re-timings to the CD version, since that's all I have. (And so do you if, like me, you bought the game on GOG. I don't know about Steam.)

Do any of the other localized floppy versions use different recordings than their CD counterparts? I have absolutely no idea. Heck, I don't even know about the English floppy version but I _assume_ they used the same actors there.

Of course, all these changes are enhancements, so they can be turned off.

### CODE REVIEW

**Comment by AndywinXp** [comment]
Great job as always, this has been bothering me for a couple of decades :)

**Comment by dwatteau** [comment]
Thanks @eriktorbjorn!

I have the French floppy version here, so here's my attempt at improving its timing. I don't know how `talkDelay` is meant to be calculated, so this comes from a lot of trials-and-errors.

I've also tweaked the French CD version a tiny bit.

```diff
diff --git a/engines/scumm/string.cpp b/engines/scumm/string.cpp
index a97797721a3..3d812bf2f01 100644
--- a/engines/scumm/string.cpp
+++ b/engines/scumm/string.cpp
@@ -446,13 +446,26 @@ bool ScummEngine::handleNextCharsetCode(Actor *a, int *code) {
 				TimingAdjustment timingAdjustmentsFRCD[] = {
 					{ "Oh.",              85,  0 },
 					{ "H\x82, pas mal.",  80,  0 },
-					{ "Yiik!",            110, 0 },
+					{ "Yiik!",            130, 0 },
+					{ "Huh?",             70,  0 },
 					{ "Je peux garder",   130, 0 },
 					{ "Pourquoi est-ce",  120, 0 },
 					{ "Nous pourrons",    80,  0 },
 					{ "Je peux conduire", 220, 0 }
 				};
 
+				TimingAdjustment timingAdjustmentsFRFloppy[] = {
+					{ "Et pour me",       120, 0 },
+					{ "C'est que^euh^",   100, 0 },
+					{ "vous \x88tes",     65,  0 },
+					{ "^impr\x82visible", 170, 0 },
+					{ "Pourquoi est-ce",  100, 0 },
+					{ "Filons de cet",    190, 0 },
+					{ "Nous pourrons",    65,  0 },
+					{ "Je peux conduire", 170, 0 },
+					{ "Je n'oublierai",   90,  0 }
+				};
+
 				TimingAdjustment timingAdjustmentsES[] = {
 					{ "Y por eso^",       130, 0 },
 					{ "es simplemente",   100, 0 },
@@ -477,7 +490,10 @@ bool ScummEngine::handleNextCharsetCode(Actor *a, int *code) {
 					numAdjustments = ARRAYSIZE(timingAdjustmentsIT);
 					break;
 				case Common::FR_FRA:
-					if (strcmp(_game.variant, "Floppy") != 0) {
+					if (strcmp(_game.variant, "Floppy") == 0) {
+						adjustments = timingAdjustmentsFRFloppy;
+						numAdjustments = ARRAYSIZE(timingAdjustmentsFRFloppy);
+					} else {
 						adjustments = timingAdjustmentsFRCD;
 						numAdjustments = ARRAYSIZE(timingAdjustmentsFRCD);
 					}
```

(Note to French readers: the sub differs from the text here and there, and the original text has several typos…)

**Comment by eriktorbjorn** [comment]
Thanks! I've incorporated your French floppy timings. Please test to make sure I didn't mess up.

Trial and error is the exact method I'm using myself. I've lost count of the number of times I've watched the intro in different languages, and I really hope I won't have to do it again any time soon. Please?

I guess there's still the matter of the Italian floppy version. Does anyone know if that one had different voices too?

I guess it's possible that the Spanish floppy version does too, but that CD version uses the English voices. Would they really have made a Spanish floppy intro, and then just given up on the CD version?

**Comment by AndywinXp** [comment]
I know you asked about it before, so I'm sorry for the late reply, but the Italian floppy version has the Eng floppy dub for the intro, so no need to worry about it

**Comment by dwatteau** [comment]
> Thanks! I've incorporated your French floppy timings. Please test to make sure I didn't mess up.

@eriktorbjorn: I've updated and built this branch again, and it's alright. Thanks!

**Comment by eriktorbjorn** [comment]
> I know you asked about it before, so I'm sorry for the late reply, but the Italian floppy version has the Eng floppy dub for the intro, so no need to worry about it (it probably should keep the original timings though)

Since the original timings would be based on the length of the Italian subtitles, we may want to re-time some of the lines just like with the Spanish CD version (which also uses the English voices).

I assume the English floppy version uses the same voices as the CD version, so those adjustments apply to both?

Once that's done, only the Spanish floppy version remains unknown I guess.

**Comment by AndywinXp** [comment]
> > I know you asked about it before, so I'm sorry for the late reply, but the Italian floppy version has the Eng floppy dub for the intro, so no need to worry about it (it probably should keep the original timings though)
> 
> Since the original timings would be based on the length of the Italian subtitles, we may want to re-time some of the lines just like with the Spanish CD version (which also uses the English voices).

Hmm, you're probably right. I have a person who can test the ita floppy version (I don't have it), may I ask you to hold on this until a day or two at most?

**Comment by eriktorbjorn** [comment]
> may I ask you to hold on this until a day or two at most?

Sure, I have no immediate plans for merging this. It would be good if some developer had the Italian floppy version to test with, since re-timing requires trial and error.

I've been able to confirm that the English floppy version uses the same voices as the CD one, so those timings should apply to both. Hopefully the same also applies to the Spanish one.

**Comment by eriktorbjorn** [comment]
https://www.youtube.com/watch?v=2m38adNzhbo suggests that the Spanish floppy version uses the English voices, and the same subtitles as the CD version. So that one probably works fine.

**Comment by eriktorbjorn** [comment]
I was able to test with an Italian floppy version, so it should be ok now. (I had to disable one workaround made for the CD version, because it wasn't needed here.)

**Comment by AndywinXp** [comment]
Nice job! :)

**Comment by eriktorbjorn** [comment]
This bug is also mentioned in https://wiki.scummvm.org/index.php?title=SCUMM/Bugs so that page will have to be updated if/when this pull request is merged.

**Pull request merged**
