### PR TITLE
DIRECTOR/FREESCAPE: Fix -Wformat warnings on 32-bit platforms

### PR DESCRIPTION
**Pull request by dwatteau**
The following PR fixes GCC `-Wformat` warnings on 32-bits platforms in the DIRECTOR and FREESCAPE engines.

It's just a switch from `%ld` to `%lld` for int64 types.

Any objection?

### CODE REVIEW

**Comment by rvanlaar** [comment]
Removing warnings is +1. 
No objections from me on the director side of things.

**Comment by bluegr** [comment]
Thanks! Yes, we have made such changes in the past, e.g. in d66fe413a11d6f870492b539f8ce0d4f35278a5d
Merging

**Comment by meekee7** [comment]
Now I am getting these warnings on 64bit Linux builds instead (Debian 11, GCC 10.2), with a mismatch between ``long long int`` and ``long int``.
Newbie question: the C standard library offers format macro constants in ``<inttypes.h>`` for exactly this scenario. Why can't we use these, or roll out our own macros for this task?
See [here](https://en.cppreference.com/w/c/types/integer) and [here](https://en.cppreference.com/w/cpp/header/cinttypes) for details and listings.

Example usage:
```
int64 num = 10;
printf("Foo %" PRId64 " Bar", num);

```

The alternative would be to always cast the format string argument to the format specifier type, of course.

**Comment by dwatteau** [comment]
Ah sorry if I missed testing this configuration as well…

It looks like we deal with this with different ways in the codebase. Sometimes we just just force a long int cast (if supporting a 64-bit value is not very important) or then long long int casts.

I don't think we use the standard macros you suggest much, at the moment. Maybe because using a simple cast may seem a bit more convenient/quicker. Dunno.

Maybe @lephilousophe or someone else has a suggestion for the best way of dealing with this?

**Comment by dwatteau** [comment]
Everyone on Discord was OK with using `<inttypes.h>` and PRId64/PRIx64 as you suggested @meekee7, so I've just pushed a fix doing that.

Sorry for the new warnings I've had introduced when trying to fix the previous ones, and thanks for reporting the problem!

**Pull request merged**
