### PR TITLE
GRIFFON: Replace use of abs() with ABS()

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by dafioram** [comment]
What is the advantage of using our common utils ABS vs abs?

**Comment by digitall** [comment]
@dafioram : The abs() function is part of the C standard library as int abs(int):
https://www.gnu.org/software/libc/manual/html_node/Absolute-Value.html

The common/util.h ABS is a templated inline function and thus should be more efficient due to inlining and usage of the same type i.e. the return and parameter type will adapt to uint8, int16 etc. rather than being fixed at int:
https://github.com/scummvm/scummvm/blob/master/common/util.h#L48

Apart from this, it removes a dependency on a standard library function which could do odd things if accidently called on a float / double (should be using fabs() for that instead of abs()) ...

**Comment by sluicebox** [comment]
Yes, this is good. Most (all?) of these are floats and abs(float) doesn't compile on visual studio 2015.

UH... not that... um... anyone uses that... 

Gotta go!

**Comment by sev-** [comment]
Thanks, merging!

**Pull request merged**
