### PR TITLE
BACKENDS: Refactor mixer manager classes

### PR DESCRIPTION
**Pull request by ccawley2011**
Mixer managers can now be used with non-SDL backends.

### CODE REVIEW

**Comment by bluegr** [comment]
It would be nice if the two associated TODOs are implemented in the Android and Tizen backends. Since you started refactoring this, could you please finish these two parts, so that they won't be forgotten?

**Comment by ccawley2011** [comment]
The Android backend has been refactored, although I would appreciate it if one of the other Android developers could review the changes. I can't make any major changes to the Tizen backend since I don't have any way of compiling or testing it.

**Comment by ccawley2011** [comment]
This PR is now based on top of PR #2398. I've also removed the Android-specific changes from this PR, as it can be added in a separate PR.

**Comment by lephilousophe** [comment]
Tizen port got dropped yesterday. That's one less point to worry about.

**Comment by sev-** [comment]
Thank you, that is much cleaner now. Merging.

**Pull request merged**
