### PR TITLE
GOB: Allow loose patches

### PR DESCRIPTION
**Pull request by BLooperZ**
This changes the priority when loading files to prefer loose files over archived ones.
thus allow easier patching of game files.

This seems to be supported on the original executable in later games
and adding this support for all versions can be considered QoL update.

Thanks

### CODE REVIEW

**Comment by sev-** [comment]
Could you please provide real-world usage for this feature? Since this change will be quite noisy on attempts to open non-existent files.

**Comment by BLooperZ** [comment]
From my view as fan translation maker/modder, I can use it for testing changes (fonts/modified scripts for RTL support etc) more easily.
It also allows the patches themselves to be simpler.

In broader sense, this behaviour seems to be common in other engines (e.g. kyra, toonstruck, sci).
and in this specific engine, it is supported in the original executable of Adibou 2 (and newer)

**Comment by sev-** [comment]
So, there is no real-world usage at this moment. We are not adding loose and untested features like this.

And as I mentioned, this particular solution will be checking loose files every time there is a file access which is a big overhead for an unused functionality.

Taking this information into account, what would you say, is it OK for me to close this PR without merging?

**Comment by BLooperZ** [comment]
Ok, closing then
thank you

**Comment by BLooperZ** [comment]
Actually, what if this could be a disabled by default gui option? (like in grim userdata.lab)

Please note that there are many engines currently using similiar mechanism as mentioned, so overhead is probably not very big issue

and that there was some interest in making it easier to make script patches when discussed (on discord, brought together with scumm script, the original question suggested scumm and gob)

**Pull request closed without merging**
