### PR TITLE
GUI: Embiggen the Options dialogs

### PR DESCRIPTION
**Pull request by SupSuper**
ScummVM has grown a lot of options over the years. Maybe the dialog should grow as well?

Before:
image

After:
image

### CODE REVIEW

**Review by bluegr — APPROVED** [review]

**Comment by lotharsm** [comment]
I wonder if the THEMERC version needs to be bumped here as well? Or is a version bump only necessary if new widgets/elements are introduced?

**Comment by lotharsm** [comment]
Considering all the "thumbs up" for this PR - what do you think about backporting this change to `branch-2-6`? It really looks like a nice QoS improvement with no risk of unwanted side effects.

**Comment by SupSuper** [comment]
> I wonder if the THEMERC version needs to be bumped here as well? Or is a version bump only necessary if new widgets/elements are introduced?

The latter, this is just a cosmetic change so it won't break theme compatibility.

> Considering all the "thumbs up" for this PR - what do you think about backporting this change to `branch-2-6`? It really looks like a nice QoL improvement with no risk of unwanted side effects.

I guess @sev- should be the final judge of that. :)
Shouldn't break anything but I'll wanna double-check if all the dialogs match first.

**Comment by bluegr** [comment]
Nice work! I've tested this and it looks great.
Let's merge it in master so that we can test it a bit more, and if there are no regressions, it should be good to go into 2.6.0 as well.

**Comment by sev-** [comment]
I am not a fan of this change as it breaks the design concept we use.

**Comment by sev-** [comment]
Also, how does it look in fullscreen?

**Comment by sev-** [comment]
I am resisting to call it "nice"

Screenshot 2022-06-11 at 19 36 35

**Comment by sev-** [comment]
The setting is fine for the demonstrated 640xY resolution, but at some point, it should be better switched to the previous overlay. You can do it by duplicating the dialog, but restrict it with 'resolution', like for example, here: 
 https://github.com/scummvm/scummvm/blob/master/gui/themes/common/highres_layout.stx#L72

**Comment by bluegr** [comment]
PR #3982 has been opened as a possible solution to address the issue of the large spacing of the option dialogs in high resolutions

**Pull request merged**
