### PR TITLE
📊 Add command line option to print statistics  

### PR DESCRIPTION
**Pull request by criezy**
This adds the `--stats` command line option to print the number of engines, games, game variants, and added targets. This is related to https://bugs.scummvm.org/ticket/13741 that already includes commands to obtain a similar result. But I though an easier way to obtain it would not hurt.

This can be combined with `--engine=` to list statistics for the specified engine. This accepts a list of multiple engines separated by a coma, and the special value `all`.

And while I was at it, I also made separate commits to support specifying multiple engines with `--engine=` for the `--list-games`, `--list-all-games`, and `--list-targets` options as well.

With no engine specified, only a summary is printed:
```
scummvm % ./scummvm --stats                      
--------------- ---------------- ---------------- ----------------
Engines:    102 Games:      8764 Variants:  13070 Targets:     169
```

When specifying one engines, the stats for that engine are printed:
```
scummvm % ./scummvm --stats --engine=ags         
Engine ID        Number of games    Game variants    Added targets
--------------- ---------------- ---------------- ----------------
ags                         3285             4756              113
```

When specifying two or more engines, the stats for those engine as well as the summary are printed:
```
scummvm % ./scummvm --stats --engine=ags,director
Engine ID        Number of games    Game variants    Added targets
--------------- ---------------- ---------------- ----------------
ags                         3285             4756              113
director                    1570             3509                3
--------------- ---------------- ---------------- ----------------
Engines:      2 Games:      4855 Variants:   8265 Targets:     116
```

The special value `all` allows getting the stats for all the engines:
```
scummvm % ./scummvm --stats --engine=all
Engine ID        Number of games    Game variants    Added targets
--------------- ---------------- ---------------- ----------------
scumm                         72              153               11
access                         2                6                0
adl                            7                6                1
agi                           27              398                2
agos                          11              144                1
ags                         3285             4756              113
asylum                         1               21                0
avalanche                      1                1                0
bbvs                           1                5                2
bladerunner                    3               19                0
buried                         1               30                0
cge                            1                9                1
cge2                           1                7                1
chamber                        1                2                0
chewy                          1                5                0
cine                           2               38                0
composer                       9               40                0
cruise                         1               15                0
cryo                           1                7                0
cryomni3d                      2               31                1
director                    1570             3509                3
dm                             1                4                0
draci                          1                4                0
dragons                        1                6                0
drascula                       1               17                1
dreamweb                       1               19                4
efh                            1                2                0
freescape                      6               54                0
glk                         3264                ?                1
gnap                           1                6                0
gob                           36              401                0
griffon                        1                1                1
grim                           2               39                0
groovie                        7               34                0
hadesch                        1                7                0
hdb                            1                8                0
hopkins                        1               12                0
hpl1                           1                2                0
hugo                           3                6                0
hypno                          4               21                0
icb                            2               17                0
illusions                      2                5                0
immortal                       1                1                1
kingdom                        1                3                0
kyra                           6              149                0
lab                            1                4                0
lastexpress                    1                9                0
lilliput                       2                5                0
lure                           1               13                1
macventure                     4               14                0
made                           4               32                0
mads                           4                6                0
mm                             0                0                0
mohawk                        42              219                2
mortevielle                    1                5                0
mtropolis                      7               25                0
mutationofjb                   1                3                0
myst3                          1               33                0
nancy                          7               19                0
neverhood                      1                8                0
ngi                            3                9                0
parallaction                   2                8                0
pegasus                        1                8                0
petka                          2                5                0
pink                           2               28                0
playground3d                   1                1                0
plumbers                       1                2                0
prince                         1                9                1
private                        1               19                0
queen                          1               32                0
saga                           2               61                0
saga2                          2                3                0
sci                           80              603                7
sherlock                       2               18                0
sky                            1               11                1
sludge                        16               40                0
stark                          1               28                1
startrek                       2               16                0
supernova                      2                5                2
sword1                         1               40                1
sword2                         1               29                1
sword25                        1               13                2
teenagent                      1                7                0
testbed                        1                1                1
tetraedge                      3                6                2
tinsel                         3               40                0
titanic                        1                2                0
toltecs                        1               13                0
tony                           1               12                0
toon                           1                8                0
touche                         1                9                0
trecision                      2               17                0
tsage                          5               17                0
tucker                         1                8                0
twine                          3              115                0
ultima                        12               46                2
vcruise                        2               27                0
voyeur                         1                3                0
wage                           9              247                0
watchmaker                     1                1                0
wintermute                   164             1074                0
zvision                        2               14                1
--------------- ---------------- ---------------- ----------------
Engines:    102 Games:      8764 Variants:  13070 Targets:     169
```

### CODE REVIEW

**Comment by lotharsm** [comment]
Very nice! I think having an option to finally count all supported games _properly_ is an awesome achievement. +1 from me.

**Comment by mgerhardy** [comment]
nice - but it looks like it also includes unsupported versions like the lba2 variant which only has unsupported detection entries. not sure if this is an exception though.

**Comment by criezy** [comment]
The result depends on the options used to compile ScummVM. If I compile with release options I get less games (8299 instead of 8764). But it indeed still lists games flagged as unstable (and also those flagged as unsupported).

The issue here is that the flag is set on the detection entries, not on the game ids. So excluding games with no supported variants is not straighforward. It requires building the list of games from the detection entries instead of using the list of games provided by the meta engine. This is not impossible, but this either require exposing the detection entries to outside the meta engine, or delegate the task to the meta engine.

For game variants this would be a lot easier since they are already counted from the detection entries, and that task is delegated to the meta engines. But counting games with no entries marked as stable while not counting their variants would be  bit strange. We probably want to be consistent here.

I will think a bit about this and see what can be done.

**Comment by sev-** [comment]
Merging this

**Comment by lotharsm** [comment]
Just one small question - I tried the new option on the latest master code and I get the following output:

`Engines:    102 Games:      8764 Variants: 16336+ Targets:       3`

What does the "+" in the Variants counter refers to?

**Comment by criezy** [comment]
That is because the glk engine cannot currently provide a number of game variants. In the engine stat it indicates it with a `?`, but in the total it count one variant per gameid, which is a low bound, so it also adds a `+` to indicate this is an approximation. Initially it didn't count any variant, but getting a lower number of game variants than games was strange 😉 
```
scummvm % ./scummvm --stats --engine=sky
Engine ID        Number of games    Game variants    Added targets
--------------- ---------------- ---------------- ----------------
sky                            1               11                1
scummvm % ./scummvm --stats --engine=sky,glk
Engine ID        Number of games    Game variants    Added targets
--------------- ---------------- ---------------- ----------------
glk                         3264                ?                1
sky                            1               11                1
--------------- ---------------- ---------------- ----------------
Engines:      2 Games:      3265 Variants:  3275+ Targets:       2
```

**Pull request merged**
