### PR TITLE
SCUMM: COMI: Disable saving/loading during SMUSH videos

### PR DESCRIPTION
**Pull request by AndywinXp**
This commit prevents an edge case in COMI, in which SMUSH videos were terminated in case of an event of autosaving.
Also, saving and loading was disabled in the original exe, so I guess we're not losing much here...

### CODE REVIEW

**Comment by athrxx** [comment]
What's the reason for preventing the loading?

**Comment by bluegr** [comment]
It would be better to allow loading, if possible

**Comment by AndywinXp** [comment]
Sure! Done :)

**Comment by bluegr** [comment]
Thanks! Merging

**Pull request merged**
