### PR TITLE
AGS: Split detection for The Shivah in shivah and shivahkosher

### PR DESCRIPTION
**Pull request by tag2015**
As Thunderforge suggested on Discord, it seems reasonable to have two different IDs for _The Shivah_ and
_The Shivah: Kosher edition_, which is a significantly improved remake.
The remake is the version that is currently sold on Steam and GOG, the "classic" version is available as extra only on GOG.

### CODE REVIEW

**Comment by eriktorbjorn** [comment]
There was an earlier freeware version of the game, but maybe that's already detected? I don't have it, and I don't think it's legitimately available anywhere.

shivah

**Comment by tag2015** [comment]
> There was an earlier freeware version of the game, but maybe that's already detected? I don't have it, and I don't think it's legitimately available anywhere.

That's the MAGS version, I suppose. It's in the detection tables already
`GAME_ENTRY_EN_PLATFORM("shivah", "shivah.exe", "6e3d6225dee662ff6450a3bfa942773b", 8680174, "MAGS"),
`

**Comment by eriktorbjorn** [comment]
That's probably it. Good!

**Comment by Thunderforge** [comment]
Thanks for doing this!

For completeness, here are the difference:

## _The Shivah_ (2006)

The Shivah

## _The Shivah: Kosher Edition_ (2013)

The Shivah Kosher Edition

**Review by Thunderforge — APPROVED** [review]

**Pull request merged**
