### PR TITLE
SCUMM: Prevent expiration of music while it's playing

### PR DESCRIPTION
**Pull request by eriktorbjorn**
The background to this pull request is that I was playing the Mac version of The Secret of Monkey Island to see if recent work on the Mac GUI had caused any regressions. I got to the part where you have to follow the shopkeeper. The game is supposed to play a particular piece of music all the way up until you reach the swordmaster. But when I got to the island overhead map, the music stopped and was replaced by the regular overhead map theme.

What happened was that the engine decided to expire the music resource. The script checks if the shopkeeper theme is playing, but one of the conditions there is that the resource has to be loaded. Otherwise it starts the overhead map theme.

I don't think we can rely on the music engine keeping its own copy of the resource data, so checking that the resource is loaded _is_ almost certainly the right thing to do. But it shouldn't be allowed to expire sounds while they are still being played. The resource manager will check `isSoundInUse()` and that's where things went wrong. Because the music engine said that no, the sound was not playing.

This change brings `isSoundInUse()` and `isSoundRunning()` closer to each other, while still maintaining the documented differences. That's why it's still calling `_imuse`, even though `_imuse` is - as far as I know - always also the `_musicEngine`.

### CODE REVIEW

**Comment by athrxx** [comment]
I have looked at the MI1 Mac disasm.
For sound resources, the original `IsGlobInUse()` method which is called through `expireResources()` uses the exact same sound status check method as the script opcode `o5_isSoundRunning()`. The sound status check for MI1 Mac only makes one var check: `_curSound == <arg_id>`.  Which is what we do in `LoomMonkeyMacSnd::getSoundStatus(int id)`.

So I would say the changes in lines 1027 and 1028 are correct...

Where did you get the '_mixer->isSoundIDActive(sound)' and  `_vm->_numSounds` checks from, though?

**Comment by eriktorbjorn** [comment]
The `_mixer->isSoundIDActice(sound)` check was there all along. I just moved it a bit to be consistent with `isSoundRunning()`. I wanted to avoid a case where the function returns `false` without having tried every case where it could return `true` first.

The `_numSounds` check is also from `isSoundRunning()`.

**Comment by AndywinXp** [comment]
It looks good to me but I seem to recall that `sound > _vm->_numSounds` might break HE games? Because when a script calls for a sound whose identifier is higher than `_numSounds` it means it's a streamed music track.

Would the issue be fixed even without that `sound > _vm->_numSounds` piece of code?

**Comment by athrxx** [comment]
> The `_mixer->isSoundIDActice(sound)` check was there all along. I just moved it a bit to be consistent with `isSoundRunning()`. I wanted to avoid a case where the function returns `false` without having tried every case where it could return `true` first.
> 
> The `_numSounds` check is also from `isSoundRunning()`.

Okay, just from looking at our code I would think that both the `_numSounds`and `_mixer->isSoundIDActice(sound)` concern later game versions (6+). So, for our candidate here, it shouldn't matter...

**Comment by eriktorbjorn** [comment]
Right. The issue was that we didn't ask `_musicEngine` at all, only `_imuse`. The rest was my attempt at making the two functions work the same, because of the comment for `isSoundInUse()`.

I was also worried about what would happen if `_musicEngine` said no, because then `isSoundIdActive()` would not be consulted at all.

I assumed checking `_numSounds` was some sort of safeguard that had only made it into one of the two functions by oversight.

But for the particular bug, only `_musicEngine` was relevant.

**Comment by eriktorbjorn** [comment]
Here is the savegame I've been using for testing the bug: [savegame.zip](https://github.com/user-attachments/files/17656610/savegame.zip)

There's nothing special with the savegame, though. I can easily reproduce it without doing anything out of the ordinary:

- Get the pot from the SCUMM bar.
- Get the money from the circus.
- Go to the store and buy the sword.
- Ask the shopkeeper who you can use the sword on (or where the sword master is, if you've talked to the pirate leaders).

Or you can use boot param 707.

So a minimal "fix my bug and let the rest of the world burn" patch would be this:

```
diff --git a/engines/scumm/sound.cpp b/engines/scumm/sound.cpp
index a4e29098ab8..05aad421889 100644
--- a/engines/scumm/sound.cpp
+++ b/engines/scumm/sound.cpp
@@ -1019,8 +1019,8 @@ bool Sound::isSoundInUse(int sound) const {
        if (!_vm->_res->isResourceLoaded(rtSound, sound))
                return false;
 
-       if (_vm->_imuse)
-               return _vm->_imuse->get_sound_active(sound);
+       if (_vm->_musicEngine)
+               return _vm->_musicEngine->getSoundStatus(sound);
 
        if (_mixer->isSoundIDActive(sound))
                return 1;
```

But the comment above the function states that there is a reason why we call `get_sound_active()` and not `getSoundStatus()`, which led to this patch instead.

```
diff --git a/engines/scumm/sound.cpp b/engines/scumm/sound.cpp
index a4e29098ab8..fb007a00eaf 100644
--- a/engines/scumm/sound.cpp
+++ b/engines/scumm/sound.cpp
@@ -1021,6 +1021,8 @@ bool Sound::isSoundInUse(int sound) const {
 
        if (_vm->_imuse)
                return _vm->_imuse->get_sound_active(sound);
+       else if (_vm->_musicEngine)
+               return _vm->_musicEngine->getSoundStatus(sound);
 
        if (_mixer->isSoundIDActive(sound))
                return 1;
```

I guess the `else` isn't strictly necessary, I just wanted to make it extra clear that these are two different cases. But now there are even fewer cases where `_mixer->isSoundIDActive(sound)` is called, so I moved it to be like `isSoundRunning()`, and changed it to return `true` instead of `1` because `isSoundInUse()` returns a `bool`, not an `int`.

```
diff --git a/engines/scumm/sound.cpp b/engines/scumm/sound.cpp
index a4e29098ab8..9b62ee37f7d 100644
--- a/engines/scumm/sound.cpp
+++ b/engines/scumm/sound.cpp
@@ -1013,6 +1013,9 @@ bool Sound::isSoundInUse(int sound) const {
        if (sound == _currentCDSound)
                return pollCD() != 0;
 
+       if (_mixer->isSoundIDActive(sound))
+               return true;
+
        if (isSoundInQueue(sound))
                return true;
 
@@ -1021,9 +1024,8 @@ bool Sound::isSoundInUse(int sound) const {
 
        if (_vm->_imuse)
                return _vm->_imuse->get_sound_active(sound);
-
-       if (_mixer->isSoundIDActive(sound))
-               return 1;
+       else if (_vm->_musicEngine)
+               return _vm->_musicEngine->getSoundStatus(sound);
 
        return false;
 }
```

And then `_vm->_numSounds()` was just about the only remaining difference, which led to this pull request.

I'll let you decide which is the correct fix, but we should probably document any remaning difference in the comment above `isSoundInUse()` because the current comment made it seem like `get_sound_active()` was the _only_ intended difference.

**Comment by AndywinXp** [comment]
Okay, this looks good... I'll press the button. Thanks!

**Pull request merged**
