### PR TITLE
GOB: Move Lost in Time non-interactive Demo to Demos

### PR DESCRIPTION
**Pull request by BJNFNE**

### CODE REVIEW

**Comment by tag2015** [comment]
Why is the demo entry duplicated?

**Comment by BJNFNE** [comment]
because i accidently added the demo back then in the section of Pirated, and now i moved it to right Demo section so this may explain why this is get showed as duplicated

**Comment by bluegr** [comment]
@tag2015 is quite right here. The way that the detection entries have been changed, we now have the same demo entry duplicated

**Comment by BJNFNE** [comment]
fixed @bluegr

**Comment by bluegr** [comment]
Thanks, squashing

**Pull request merged**
