### PR TITLE
GUI: Make character validation less ugly

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by BLooperZ** [comment]
Looks good, thanks

**Comment by orgads** [comment]
> Looks good, thanks This also probably fullfills the TODO above `DomainEditTextWidget`

Good point, removed the TODO.

**Review by criezy — APPROVED** [review]
I think the code is indeed cleaner with the proposed change.

**Review by bluegr — APPROVED** [review]
Looks good to me and improves the overall design of the input validation in this widget

**Pull request merged**
