### PR TITLE
OPENGL: Implement scaler support

### PR DESCRIPTION
**Pull request by ccawley2011**
TODO:
- ~Dirty rects don't always redraw correctly~
- ~Cursors aren't yet scaled~
- Needs testing on big endian with GLESv2

Fixes [Trac #12848](https://bugs.scummvm.org/ticket/12848).

### CODE REVIEW

**Comment by sev-** [comment]
In fact, I consider this as a dead end. In my opinion, the proper way would be to add Shader-based scalers to the OpenGL.

Perhaps you would be curious and help @lotharsm finish this work which was started by LordHoto? https://github.com/lotharsm/scummvm/tree/shaderscaler

**Comment by aquadran** [comment]
I second on that, use shaders approach

**Comment by ccawley2011** [comment]
> In fact, I consider this as a dead end. In my opinion, the proper way would be to add Shader-based scalers to the OpenGL.
> 
> Perhaps you would be curious and help @lotharsm finish this work which was started by LordHoto? https://github.com/lotharsm/scummvm/tree/shaderscaler

I'd definitely be interested in looking into shader support at some point. However, I feel it's still worthwhile having CPU scalers for a few reasons:

- Since not all scalers are guaranteed to have shader counterparts, it ensures that the old scalers are always available, even on Android where only the OpenGL graphics manager is supported.
- There has been some discussion in the past suggesting that it would be beneficial to have both scalers and shaders active at the same time in some cases: https://forums.scummvm.org/viewtopic.php?p=88798#p88798
- It can potentially be backported to the 2.5 branch, resolving the confusion caused by the changed defaults on Windows and Mac OS X in the last release.

**Comment by aquadran** [comment]
having both scalers and shaders at same time make no sense for me. shaders can do scale at same time or rendered to proper frame buffer size.

**Comment by sev-** [comment]
Okay, sounds good. In this case, could you please implement the cursor scaling before we merge? Also, please add a note to the NEWS.md as part of this PR right away.

**Comment by ccawley2011** [comment]
> Okay, sounds good. In this case, could you please implement the cursor scaling before we merge? Also, please add a note to the NEWS.md as part of this PR right away.

OK, done.

**Comment by sev-** [comment]
Thank you!

**Pull request merged**
