### PR TITLE
ANDROID: Rewrite to make use of OpenGLGraphicsManager

### PR DESCRIPTION
**Pull request by ccawley2011**
Previously, the Android backend used its own custom OpenGL code for rendering. This PR replaces that with the common OpenGL rendering code.

This is not finished. It's just about usable, but there are still several major caveats regarding this PR:
 - ~Touchpad mouse mode is broken.~
 - ~ScummVM may crash when returning from the background.~ This appears to be an issue with or without this PR.
 - ~D-pad,~ Trackball and Joystick events have not been tested.

However, I'm currently stuck regarding how to fix these issues, so I've opened this PR anyway in the hope that someone else might be able to help with this.

### CODE REVIEW

**Comment by bluegr** [comment]
Overall, great work! It's good that you managed to reuse the common OpenGL code for Android :)

Could you please fix the conflicts in events.cpp?

Have yoy played any games with these changes? (with 320x200 and higher resolutions as well)

**Comment by ccawley2011** [comment]
> Have you played any games with these changes? (with 320x200 and higher resolutions as well)

Yes, I've tested this with a number of games over the last couple of months, and they all work fine.

**Comment by bluegr** [comment]
This looks good to be merged. If there are no objections, I would like to have this merged by next weekend (Sunday, the 1st of September)

**Comment by bluegr** [comment]
I had forgotten about this, thanks for merging it!

**Pull request merged**
