### PR TITLE
I18N: Fixed wrongly translated word in uk_UA.po

### PR DESCRIPTION
**Pull request by Teashrock**
Just fixed the word "Cancel" being translated as "Відміна". Because the former is a verb, and the latter is a noun that means "to change generally or grammatically (as in 'declension')". The correct translation would be "Скасувати", which translates directly as "to cancel something".

### CODE REVIEW

**Comment by bluegr** [comment]
Thanks for your feedback on this :)

Please, use our formatting conventions for your commits. In particular, we prepend all commits with the area that they affect, so in this case, the commit message should be `I18N: Fixed wrongly translated word in uk_UA.po`

**Comment by Teashrock** [comment]
@bluegr 
I fixed the title, thank you very much.

**Comment by bluegr** [comment]
> @bluegr I fixed the title, thank you very much.

Thanks, but I was not referring to the title, but the title of the commit itself :)
Since it's a single commit, we can just squash it and amend the title, just keep it in mind for future changes

**Comment by sev-** [comment]
Ah, good point in regards of the better wording, thank you.

However, I am rejecting this pull request as it is, since it should go via Weblate at https://translations.scummvm.org.

I made this change, and if you would like to help with the Ukrainian translation, be my guest. Дякую!

**Comment by Teashrock** [comment]
@sev- 
Oh, I was wondering if there's a Weblate tracker! I thought there isn't one, and that everyone applies translations through GitHub. But okay, I'll do from there since now! Also, будь ласка (you're welcome)! Thank you very much for accepting my commit.

**Pull request closed without merging**
