### PR TITLE
[WIN32] Migrate to ShellExecuteEx()

### PR DESCRIPTION
**Pull request by carlo-bramini**
I would like to suggest to migrate from `ShellExecute()` to `ShellExecuteEx()`.
That function allows to write a more readable code, without the ugly that needs to test if returned value is greater than 32.
Supported platforms are:

*    Windows 95: Supported.
*    Windows 98: Supported.
*    Windows NT: Required Windows NT 4.0 or later.
*    Windows 2000 and newer: Supported.
*    Windows CE: Requires Windows CE 1.0 or later. 

This fix comes from my port of SCUMMVM for Windows CE/Embedded/Mobile since this family of OSs support `ShellExecuteEx()`, but not `ShellExecute()`. However, this fix will also work on all versions of Windows supported by SCUMMVM.

### CODE REVIEW

**Comment by digitall** [comment]
@carlo-bramini : Thanks for your code contribution. I have reworded the commit message to align with [our code formatting guidelines](https://wiki.scummvm.org/index.php?title=Commit_Guidelines#Commit_message_formatting) and to simplify the phrasing slightly.

**Comment by sluicebox** [comment]
Hello! Thanks for the PR, your Win32 cleanup instincts are spot on. =)

I was looking at the old ShellExecuteEx MSDN page and it says there's only Win9x support if you install the ol' Microsoft Layer for Unicode (MSLU), which is an external component: https://web.archive.org/web/20071030060912/http://msdn2.microsoft.com/en-us/library/bb762154.aspx

That was sort of my distant memory too, but it was a long time ago. I'd be happy to setup a test, could be fun.

Are you still maintaining your port(s)? If it turns out that ShellExecuteEx isn't on default Win9x but you'd benefit from upstream not importing ShellExecute, we could make a wrapper function that GetProcAddress' them both and uses whichever is available.

**Comment by sluicebox** [comment]
Great, thanks for verifying that

**Comment by lotharsm** [comment]
Thanks for your contribution @carlo-bramini and thanks to @sluicebox for diving into the depths of ancient MSDN (again) ;-)

Any objections or open questions before I merge this?

**Comment by bluegr** [comment]
Great work! Just went through this, it's a welcome change. 
+1 from me
@lotharsm I believe it should be OK to merge, it's been 2 weeks that this has been open, and there haven't been any objections

**Comment by lotharsm** [comment]
Alright, let's give it a go. Merging!

**Pull request merged**
