### PR TITLE
SCUMM: Work around DOTT glitch when Bernard looks out of Chron-O-John

### PR DESCRIPTION
**Pull request by eriktorbjorn**
One glitch I noticed recently in the Day of the Tentacle intro is that when Bernard looks out of the Chron-O-John, every time he faces to the left side of the screen part of the Chron-O-John is mirrored, like this:

dott-glitch

This appears to be because part of the Chron-O-John is a limb on Bernard's costume, perhaps so that opening the lid can be handled as part of the character animation. The glitch was fixed in the remastered version, though it's still there when using the original graphics. This pull request attempts to get around that by always keeping that limb mirrored and adjusting the position of Bernard's head slightly. This is the result:

dott-unglitch

I've tested it with my English CD version, and with the English non-interactive demo. (The demo don't show this scene at all.)

### CODE REVIEW

**Comment by eriktorbjorn** [comment]
For comparison, this is what it looks like in the remastered version:

dott-remastered

**Comment by eriktorbjorn** [comment]
It's possible that the isScriptRunning(207) check isn't actually necessary (in which case there needs to be no friendship between ClassicCostumeRenderer and ScummEngine). But I know for a fact that room 61 is  used at least one more time (at the very start of the game), and I don't want the workaround to accidentally trigger when it shouldn't.

**Comment by eriktorbjorn** [comment]
With @athrxx's refinements, it now looks like this:

dott-unglitch-2

**Comment by eriktorbjorn** [comment]
Adjusted it by just one more pixel. That's a bit more symmetrical, I think:

dott-unglitch-3

**Comment by eriktorbjorn** [comment]
Just one more...

dott-unglitch-4

**Comment by bluegr** [comment]
Looks good! I'm squashing these commits before merging to master, I believe the the coordinate tweaking is too fine grained to put it in separate commits.

Thanks again for your work

**Pull request merged**
