### PR TITLE
GOB: Fix crash at startup for Inca version

### PR DESCRIPTION
**Pull request by BJNFNE**
This was the error: intro.tot:00000352: opcodeFunc 2.5 [0x2.0x5] (oInca2_spaceShooter) scummvm: engines/gob/variables.cpp:85: void Gob::Variables::writeOff32(uint32, uint32): Assertion `(offset + 3) < _size' failed. we need for this to fix this, Set the opcode oInca2_spaceShooter to Uint32 and increase to 8, This bug only happens in specific English version as far as we know. With this fix the Game starts up without crashing

### CODE REVIEW

**Comment by lephilousophe** [comment]
Please don't change such values randomly.
What is done here is nonsense: you just move around expecting to match something and pray that nothing will break.

**Comment by BJNFNE** [comment]
> Please don't change such values randomly.
> 
> What is done here is nonsense: you just move around expecting to match something and pray that nothing will break.

I tested it, it didn't crashed after that i can also provide the decompiled script

**Comment by bluegr** [comment]
That's very strange. Which version is this? And why is the variable type different?

I have both the Engliah floppy and CD versions of Inca 2, and they both work fine

**Comment by BJNFNE** [comment]
> That's very strange. Which version is this? And why is the variable type different?
> 
> 
> 
> I have both the Engliah floppy and CD versions of Inca 2, and they both work fine

In the Script oInca_spaceShooter will be used with uint32 but the opcodes uses uint16, so thats why its crash

**Comment by lephilousophe** [comment]
> In the Script oInca_spaceShooter will be used with uint32 but the opcodes uses uint16, so thats why its crash

From where do you take the uint32 stuff? Do you have any disassembly proving this?
And even if it would be uint32, you still read it into an uint16 variable...

Your change will instead break perfectly running game versions.

So, which version of the game is this?

**Comment by BJNFNE** [comment]
I found it with d11 flag it crashes at the offset where the opcodes is used, the assertion happens due to uint problems, since the opcodes is uint16 and it wants to use uint32 it crashes.

**Comment by BJNFNE** [comment]
> > In the Script oInca_spaceShooter will be used with uint32 but the opcodes uses uint16, so thats why its crash
> 
> From where do you take the uint32 stuff? Do you have any disassembly proving this? And even if it would be uint32, you still read it into an uint16 variable...
> 
> Your change will instead break perfectly running game versions.
> 
> So, which version of the game is this?

Its one of the playable demos, with an Demo itself and then you can play the Game

**Comment by BJNFNE** [comment]
> That's very strange. Which version is this? And why is the variable type different?
> 
> I have both the Engliah floppy and CD versions of Inca 2, and they both work fine

I found an other way to fix it without modifying the uint itself: 

void Inter_Inca2::oInca2_spaceShooter(OpFuncParams &params) {
    // TODO: Not yet implemented. We'll pretend we won the match for now
    _vm->_game->_script->skip(4);
    uint16 resVar = _vm->_game->_script->readUint16();
    _vm->_game->_script->skip(4);

    // FIX: This fixes the crash at startup for some Inca2 variants
    // Ensure the offset is within bounds
    if ((resVar + 3) < _vm->_game->_script->getSize()) {
        WRITE_VAR(resVar, 1);
    } else {
        warning("oInca2_spaceShooter: Offset out of bounds: %u", resVar);
    }
}

This prevent the crash and the Game starts without problems, just without changing anything into uint32, I also thinks this option is better as changing it to uint32, so this should not break any game versions

**Comment by BJNFNE** [comment]
I can amend the changes to the commit of this PR if thats better

**Comment by sev-** [comment]
Is it based on disassembly?

**Comment by BJNFNE** [comment]
> Is it based on disassembly?

in degob decompiled script at 00000352 it says this: o2_goblinFunc(200, 0, 62208, 54070, 101); so the script itself does not mention it, it was more related to the assertion which stops the Game to started also the d11 flag prints out that it access the oInca2_spaceShooter opcode which needs this changes from this PR to start the Game without crashing.

**Comment by lephilousophe** [comment]
degob hasn't been adapted for Inca2 (note the missing Inca2 version in the list) so it shouldn't be trusted.
This PR would only hide problems instead of really fixing them.

**Comment by sev-** [comment]
Since it was not based on assembly, we cannot accept this contribution.

Also, if possible, please avoid hacks like this. E.g. either you document Wiki or base things on the real investigation and not just speculations.

This particular thing took noticeable time from several team members for performing this investigation, until we clearly understand that this is pulled out of thin air.

**Comment by sdelamarre** [comment]
Fixed in 071e55756ef714d93f39710b75034e64d9f71950

**Pull request closed without merging**
