### PR TITLE
MORTEVIELLE: added support for DOS system font

### PR DESCRIPTION
**Pull request by chrilith**
Hi,

This is another pull request for DOS System font in Mortevielle. (see #578)
This one is using the common font manager. Now, all engines can make use of the DOS font is needed.

Thanks!

### CODE REVIEW

**Comment by Strangerke** [comment]
Shouldn't bitmapTable use nullptr instead of 0 for non existing characters?

**Comment by chrilith** [comment]
Well, I took inspiration from the existing consolefont.cpp which has 0 too.
I'm preparing a full charset for this EGA DOS font. So wait a bit if you consider to merge please :)

Thanks!

**Comment by chrilith** [comment]
And voila! The full DOS charset (code page 858) which may fit most requirements.

**Comment by chrilith** [comment]
OK, sorry for the delay. I removed the last commits with the bad font data.

Is it OK now?

**Comment by bluegr** [comment]
There's a follow-up to the original post, "Revisiting VGA fonts":
http://zehfernando.com/2015/revisiting-vga-fonts/

The follow-up links to another page with a more complete DOS font, here:
http://laemeur.sdf.org/fonts/

This includes a "More perfect DOS VGA 437" font, with the following licence:

    More Perfect DOS VGA and Less Perfect DOS VGA are both free for all use, commercial and 
    non-commercial. IBM designed the glyphs and Zeh Fernando did most of the work converting 
    them to TrueType, so I don't claim ownership of anything.
    
    If you use either of the fonts in a project, I'd love to hear about it, and I'd be happy to put a 
    hyperlink to your project on this page if you send me a note.

Since this font includes almost all DOS characters, perhaps it would be better to use that instead?

**Comment by sev-** [comment]
@chrilith, any update on this?

**Comment by chrilith** [comment]
Hi @sev,

Well, I did a rollback to use the first commited font last time.
Didn't get time to dup this new font yet, sorry

**Comment by lordhoto** [comment]
This does not merge cleanly anymore. We have DOS font data in the AGI engine. It might make sense to re-use this for Mortevielle too. Please open a new PR if you plan to do this. Closing this as rotten for now.

**Pull request closed without merging**
