### PR TITLE
ENGINES: moved scumm enhancements system into shared engine code

### PR DESCRIPTION
**Pull request by mgerhardy**
This is a first step to move the `scumm` engine enhancement code into the shared engine code.

I tried to move the gui code, too - but that part is not included here - I didn't get it working.

This at least allows engines to use the pre-defined enhancement classes - which is already great.

### CODE REVIEW

**Comment by mgerhardy** [comment]
I tried to move the gui code, too - but that part is not included here - I didn't get it working

**Review by bluegr — APPROVED** [review]
Nice work! LGTM

**Comment by mgerhardy** [comment]
I was only moving it around - the work was done by someone else ;)

**Comment by bluegr** [comment]
Thanks for your work!

I've talked with both @eriktorbjorn and @AndywinXp, and they've agreed on the proposed design.
The functionality itself hasn't changed, and this PR mainly moves the SCUMM enhancements functionality, so that it can be reused by other engines.
I've tested the changes with MI1, MI2, MI3, Loom, Zak, Sam'n'Max, Full Throttle, The Dig, Indy 3, Indy 4 and everything works great.

Merging

**Pull request merged**
