### PR TITLE
JANITORIAL: Correct spelling mistakes - 2

### PR DESCRIPTION
**Pull request by raziel-**
Some little buggers have escaped ;-)

### CODE REVIEW

**Comment by bluegr** [comment]
Thanks!

**Comment by dwatteau** [comment]
from commit 8e2c7715fa601d6eb8ad4e131d340181b07a4279:
> I had to delete and reupload the file, because it's too big to edit from the website

The problem with this approach is that `git blame` is now a bit useless on `engines/sci/engine/script_patches.cpp`.

**Comment by raziel-** [comment]
Oh no, I broke something...I'm sorry :-(

**Comment by dwatteau** [comment]
@raziel- Don't worry, this can be worked around, and if Github's web interface doesn't help with catching that it's nobody's fault here ;) Your fixes are welcome.

But yeah, deleting and importing a file in two separate commits make Git lose track of a few things.

Maybe we should just squash your spelling fix commits into a single one the next time; I'm not sure that having a separate commit for each component is that meaningful when it's about typo fixes, since only comments were changed, and so the risk of a functional regression in a particular component was quite low.

**Comment by AndywinXp** [comment]
Hiya! Like said on the previous PR, please, don't edit files from the web interface 🙏

**Comment by sev-** [comment]
I apologise for intervening. But this IS VERY IMPORTANT.

Destroying traceability of work of number of developers for TWELVE YEARS is the biggest incident in the project I remember.

Raziel, it is not your fault; you did not have the means to act otherwise.

The problem is that this PR was merged in SIX MINUTES, obviously without any significant reveiw.

**Comment by raziel-** [comment]
@all

I am so sorry :-(

**Comment by raziel-** [comment]
Pronlem is my platform is *very* limited when it comes to anything web based, be it browsers, ftps, discord,, irc etc., e.g. sgit (the local git variant) can do some basic stuff like clone, fetch and merge (locally on my hdd) but it cannot create PRs and such, let alone bisect.
So I'm left with doing local changes, test them and create acwrb based PR.

I will mark my PRs with a big fat PLEASE REVIEW FIRST from now on...

sorry again :-(

...back to my happy place

**Comment by digitall** [comment]
@raziel- : Since I know you use AmigaOS 4, I assume you mean this sgit:
https://aminet.net/package/dev/misc/sgit

While bisect is not listed in the supported commands, there are more than enough commands there to clone your repo, create a local patch branch, push it to your repo at raziel-/scummvm i.e. "sgit push origin patch-3". You then create a github PR by using the web interface to open the PR between that branch and scummvm/scummvm:master branch. See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request for details.

**Comment by bluegr** [comment]
> I apologise for intervening. But this IS VERY IMPORTANT.
> 
> Destroying traceability of work of number of developers for TWELVE YEARS is the biggest incident in the project I remember.
> 
> Raziel, it is not your fault; you did not have the means to act otherwise.
> 
> The problem is that this PR was merged in SIX MINUTES, obviously without any significant reveiw.

Since I merged this PR, I just wanted to say again that I'm sorry for missing this. In this case, I went in the files tab, reviewed the changes, which were simple typo fixes, and did not check from the commits that a file was deleted and re-uploaded. From my side, apologies for missing this, will check all commits, even if their changes look to be very simple.

**Pull request merged**
