### PR TITLE
AMIGAOS: Clean up README conversion script

### PR DESCRIPTION
**Pull request by raziel-**
- Obviously AREXX doesn´t feature an ENDIF clause
- Cleaned it up a bit
- Checked and still working

### CODE REVIEW

**Comment by raziel-** [comment]
I don´t really know why those unchanged lines appear altered.
Maybe the github "to UTF-8" converter kicking in?

**Comment by rootfather** [comment]
Seems that some empty lines where removed in this revision of the files, and this is most likely the reason why git marks them as changed.

**Comment by raziel-** [comment]
Oh right, forgot about the blank line shifts, thank you

**Comment by digitall** [comment]
@raziel- : This looks pretty reasonable and AMIGAOS specific, so are you happy for this to merged now?

**Comment by raziel-** [comment]
Yes, i am :-)

Thanks for checking

**Comment by raziel-** [comment]
Great...the utf-8 conversion changed some of my markers, so after a download it now looks like this
line 73 (i.e.)
WRITELN(guide_write,'  @{" 'SUBSTR(working_line,POS('Â°',working_line)+1,LASTPOS('Â°',working_line)-POS('Â°',working_line)-1) '" Link "'SUBSTR(working_line,POS('Â°',working_line)+1,LASTPOS('Â°',working_line)-POS('Â°',working_line)-1)'"} 'COMPRESS(working_line,'*Â°'))

and of course, it errors out

**Comment by digitall** [comment]
@raziel- : Damn. Not sure how to deal with that, but up to you. Either you can try to add this in a branch on your github, or maybe just e-mail me a zip of the amended script file and I can try to commit this directly to the repository?

**Comment by raziel-** [comment]
@digitall

I guess i'll rewrite the script to not use any "utf-8" chars as markers but readable text.
It will grow slightly in size though, but it will also become a little more readable.

**Comment by raziel-** [comment]
@digitall 

New PR is up #1114

**Pull request merged**
