### PR TITLE
ANDROID: Add basic keymapper support

### PR DESCRIPTION
**Pull request by ccawley2011**
This replaces PR #2008.

### CODE REVIEW

**Comment by bluegr** [comment]
This looks to be in a good state to be merged. Are there any pending TODOs?

**Comment by antoniou79** [comment]
I haven't had time to test this. So, from looking at the code, where is the ConfMan bool value for key "swap_menu_and_back_buttons" set now?

**Comment by ccawley2011** [comment]
> I haven't had time to test this. So, from looking at the code, where is the ConfMan bool value for key "swap_menu_and_back_buttons" set now?

It isn't needed any more. The remaining usage of `swap_menu_and_back_buttons` is just for compatibility with older config files. The behaviour of the menu and back buttons is now handled by the keymapper.

**Comment by antoniou79** [comment]
> > I haven't had time to test this. So, from looking at the code, where is the ConfMan bool value for key "swap_menu_and_back_buttons" set now?
> 
> It isn't needed any more. The remaining usage of `swap_menu_and_back_buttons` is just for compatibility with older config files. The behaviour of the menu and back buttons is now handled by the keymapper.

This makes sense. I'm ok with merging this then.

**Pull request merged**
