### PR TITLE
SDL: Add implementation of OSystem::openUrl for SDL 2.0.14

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by mgerhardy** [comment]
Looks good to me.

**Comment by bluegr** [comment]
Nice work, clean and simple implementation. Merging

**Comment by ccawley2011** [comment]
This doesn't occur for me using either MinGW32 or with the MXE Docker image provided by dockerized-bb, which suggests that there may be an issue with your setup.

**Comment by lotharsm** [comment]
Is dockerized-bb already using SDL 2.0.14?

**Comment by ccawley2011** [comment]
Yes, it's using the `build-2021-01-10` tag, which includes SDL 2.0.14.

**Comment by lotharsm** [comment]
Hm, okay - the weird thing is that I initially built SDL 2.0.14 on the system that's failing now. I'm seriously considering dropping support for anything Windows related on my end since I'm starting to get tired of it constantly breaking...

**Comment by lotharsm** [comment]
Wait a second, it's possible that my optimization settings are too strict.

**Comment by lotharsm** [comment]
Yikes.

I have to apologize for making such a fuzz about this issue - as @ccawley2011 suspected, it was an issue on my end, an onld version of the compiled library sitting around in one directory, to be more precise :(

**Pull request merged**
