### PR TITLE
PSP: Implement AbstractFSNode::createDirectory()

### PR DESCRIPTION
**Pull request by ccawley2011**
Originally from PR #1727. This change has not been tested.

### CODE REVIEW

**Comment by rsn8887** [comment]
Where is this used in ScummVM? I would like to test if folder is actually created on the memorystick.

**Comment by ccawley2011** [comment]
PR #1727 adds a test to the TestBed engine that can be used to check that this works.

**Comment by bluegr** [comment]
Any news on this?

**Comment by rsn8887** [comment]
I am about to test it one sec

**Comment by sev-** [comment]
Nice, merging.

**Pull request merged**
