### PR TITLE
GROOVIE/MIDI: Improve MIDI for The 7th Guest

### PR DESCRIPTION
**Pull request by NMIError**
This PR improves the MIDI initialization and playing for The 7th Guest,
mostly for Roland GS devices plus a small MT-32 fix.

- SysEx messages from the General MIDI initialization were not sent 
because the Groovie MusicPlayerMidi class did not implement a sysEx 
function. I've added this.
- The General MIDI initialization video ("loading GM drivers") runs 
faster on ScummVM and it ends before the background "audio" (actually 
GM initialization MIDI messages) has finished playing. I've fixed this 
by looping this video until the "audio" has finished playing.
- Some drumkit change messages in the music use invalid drumkit 
numbers. This relied on a correction mechanism of the Roland SC-55, 
which would correct these numbers to valid selections. This 
mechanism was not present in later GS and GM devices, causing error 
messages and wrong drumkits. I've fixed this by adding code which 
simulates the correction mechanism of the SC-55.
- A couple of SysEx messages during the MT-32 initialization were not 
sent because the Miles MT-32 driver does not implement a sysEx 
function. I've added this.

### CODE REVIEW

**Comment by bluegr** [comment]
The work done here is great, well done! Unfortunately, this has conflicts now. Could you please resolve them?

**Comment by NMIError** [comment]
Thanks; fixed it. I didn't notice before; there's still a green checkmark next to the PR in the list, even if it has merge conflicts...

**Comment by NMIError** [comment]
The CI build has timed out and it doesn't seem to build again automatically. Can you start a new build?

**Comment by bluegr** [comment]
I've re-run the CI build. Since commit 3657db3a7b7bf640edb768f6ffc37df9d5073d22 could not be applied cleanly without squashing all the commits, I've pushed all the commits manually to master.

Closing this, thanks for your work!

**Comment by NMIError** [comment]
Thanks for your help Filippos!

**Pull request closed without merging**
