### PR TITLE
POSIX: Add native file browser via GTK

### PR DESCRIPTION
**Pull request by SupSuper**
Suggested by @lotharsm 

Building on #1414, this adds a native file browser to Linux-based distros that support the GTK3 GUI, falling back to the ScummVM GUI when not available.

File browser on Debian

This is only enabled if the "system dialogs" feature is active and libgtk3-dev is present, similar to the current Ubuntu taskbar feature, so it shouldn't disrupt builds.

I'd appreciate testing on various distros to make sure it works correctly across GUIs and buildsystems.

### CODE REVIEW

**Comment by bgK** [comment]
Hi, I tried the changes, seems to work well.

First thing I tried was to run a game remotely through a sftp connection via Gvfs. To my surprise it worked! (I'm running a full blown Gnome desktop environment on Arch Linux.)

I noticed the GUI option to enable / disable the native dialogs is missing (the backend does not declare `kFeatureSystemBrowserDialog`).

Address Sanitizer complains a bit:
```
==1586055==ERROR: AddressSanitizer: alloc-dealloc-mismatch (malloc vs operator delete []) on 0x603000232360
    #0 0x7fbff00a1b40 in operator delete[](void*) /build/gcc/src/gcc/libsanitizer/asan/asan_new_delete.cc:168
    #1 0x55907724a6e8 in GtkDialogManager::showFileBrowser(char const*, Common::FSNode&, bool) (scummvm/build/scummvm+0x5856e8)
    #2 0x5590771b325c in GUI::BrowserDialog::runModal() (scummvm/build/scummvm+0x4ee25c)
    #3 0x5590770e12dd in GUI::LauncherDialog::addGame() (scummvm/build/scummvm+0x41c2dd)
    #4 0x5590770e3dab in GUI::LauncherDialog::handleCommand(GUI::CommandSender*, unsigned int, unsigned int) (scummvm/build/scummvm+0x41edab)
    #5 0x5590771198ad in GUI::CommandSender::sendCommand(unsigned int, unsigned int) (scummvm/build/scummvm+0x4548ad)
    #6 0x5590771891cb in GUI::ButtonWidget::handleMouseUp(int, int, int, int) (scummvm/build/scummvm+0x4c41cb)
    #7 0x55907718afcf in GUI::DropdownButtonWidget::handleMouseUp(int, int, int, int) (scummvm/build/scummvm+0x4c5fcf)
    #8 0x5590770d1f47 in GUI::Dialog::handleMouseUp(int, int, int, int) (scummvm/build/scummvm+0x40cf47)
    #9 0x5590770da710 in GUI::GuiManager::processEvent(Common::Event const&, GUI::Dialog*) (scummvm/build/scummvm+0x415710)
    #10 0x5590770d7c6a in GUI::GuiManager::runLoop() (scummvm/build/scummvm+0x412c6a)
    #11 0x5590770d0cfe in GUI::Dialog::runModal() (scummvm/build/scummvm+0x40bcfe)
    #12 0x559076e32e7f in launcherDialog() (scummvm/build/scummvm+0x16de7f)
    #13 0x559076e38a5f in scummvm_main (scummvm/build/scummvm+0x173a5f)
    #14 0x559076e2f771 in main (scummvm/build/scummvm+0x16a771)
    #15 0x7fbfedd5d022 in __libc_start_main (/usr/lib/libc.so.6+0x27022)
    #16 0x559076e2274d in _start (scummvm/build/scummvm+0x15d74d)

0x603000232360 is located 0 bytes inside of 28-byte region [0x603000232360,0x60300023237c)
allocated by thread T0 here:
    #0 0x7fbff009efa0 in __interceptor_realloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:163
    #1 0x5590775cdfd7 in Common::Encoding::convertIconv(char const*, char const*, char const*, unsigned long) (scummvm/build/scummvm+0x908fd7)
    #2 0x5590775cd297 in Common::Encoding::conversion(Common::String const&, Common::String const&, char const*, unsigned long) (scummvm/build/scummvm+0x908297)
    #3 0x5590775cce7b in Common::Encoding::convertWithTransliteration(Common::String const&, Common::String const&, char const*, unsigned long) (scummvm/build/scummvm+0x907e7b)
    #4 0x5590775cc0c5 in Common::Encoding::convert(char const*, unsigned long) (scummvm/build/scummvm+0x9070c5)
    #5 0x55907724a658 in GtkDialogManager::showFileBrowser(char const*, Common::FSNode&, bool) (scummvm/build/scummvm+0x585658)
    #6 0x5590771b325c in GUI::BrowserDialog::runModal() (scummvm/build/scummvm+0x4ee25c)
    #7 0x5590770e12dd in GUI::LauncherDialog::addGame() (scummvm/build/scummvm+0x41c2dd)
    #8 0x5590770e3dab in GUI::LauncherDialog::handleCommand(GUI::CommandSender*, unsigned int, unsigned int) (scummvm/build/scummvm+0x41edab)
    #9 0x5590771198ad in GUI::CommandSender::sendCommand(unsigned int, unsigned int) (scummvm/build/scummvm+0x4548ad)
    #10 0x5590771891cb in GUI::ButtonWidget::handleMouseUp(int, int, int, int) (scummvm/build/scummvm+0x4c41cb)
    #11 0x55907718afcf in GUI::DropdownButtonWidget::handleMouseUp(int, int, int, int) (scummvm/build/scummvm+0x4c5fcf)
    #12 0x5590770d1f47 in GUI::Dialog::handleMouseUp(int, int, int, int) (scummvm/build/scummvm+0x40cf47)
    #13 0x5590770da710 in GUI::GuiManager::processEvent(Common::Event const&, GUI::Dialog*) (scummvm/build/scummvm+0x415710)
    #14 0x5590770d7c6a in GUI::GuiManager::runLoop() (scummvm/build/scummvm+0x412c6a)
    #15 0x5590770d0cfe in GUI::Dialog::runModal() (scummvm/build/scummvm+0x40bcfe)
    #16 0x559076e32e7f in launcherDialog() (scummvm/build/scummvm+0x16de7f)
    #17 0x559076e38a5f in scummvm_main (scummvm/build/scummvm+0x173a5f)
    #18 0x559076e2f771 in main scummvm/build/scummvm+0x16a771)
    #19 0x7fbfedd5d022 in __libc_start_main (/usr/lib/libc.so.6+0x27022)

SUMMARY: AddressSanitizer: alloc-dealloc-mismatch /build/gcc/src/gcc/libsanitizer/asan/asan_new_delete.cc:168 in operator delete[](void*)
```

**Comment by lotharsm** [comment]
@SupSuper, thanks again for the really fast implementation of this feature - I greatly appreciate your work and dedication!

The new feature integrates pretty well into KDE too. This screenshot is from Kubuntu 20.04 latest daily.
scummvm-new-launcher

**Comment by SupSuper** [comment]
@bgK Thanks, fixed the missing feature and string allocs.

@lotharsm Nice catch, UTF-8 should be fixed now.

**Comment by lotharsm** [comment]
@SupSuper confirmed, UTF-8 is fixed. Voting for merge.

**Comment by bluegr** [comment]
Nice work! Quite straightforward changes. +1 from me too

**Comment by lotharsm** [comment]
Just found a (very) minor glitch: When adding a new game, then the gtkDialog pops up "in front" of the ScummVM dialog and is in focus, as expected. However, if the gtkDialog is opened from within the "Options" tab for setting paths or choosing a soundfont, then it is opened in the background while the window focus is set to the main ScummVM window.

**Comment by SupSuper** [comment]
@lotharsm I think this is a GTK limitation since there's no parent GTK window to hook to, only the first dialog pops in front. You'll notice the same thing happens with SameBoy. 😉

**Comment by lotharsm** [comment]
Ah, that's whats the warning about missing parent windows I get in SameBoy is about. 😋

Guess we're ready for a merge then.

**Comment by bluegr** [comment]
Nice work! This is in a good state to be merged now

**Pull request merged**
