### PR TITLE
GOB: Code Improvements

### PR DESCRIPTION
**Pull request by BJNFNE**
* Overloads were reported as warnings in VS Code

### CODE REVIEW

**Comment by bluegr** [comment]
Thanks!

**Comment by lephilousophe** [comment]
Could you tell what was the error message?
I don't see it in our Github based MSVC builds.
These changes don't look correct because if you have a problem here, there must be the same problem everywhere this construct is used.

**Comment by BJNFNE** [comment]
i used VS Code as Code Editor and g++ as Compiler under Linux.

hotspots.cpp: no instance of overloaded function "Common::strcat_s" matches the argument list argument types are: (char [256], const char [2])

map_v1.cpp: no instance of overloaded function "Common::strcat_s" matches the argument list argument types are: (char [128], const char [5]) 

2nd warning: no instance of overloaded function "Common::strcat_s" matches the argument list argument types are: (char [19], const char [5]) 

3rd warning: no instance of overloaded function "Common::strcpy_s" matches the argument list argument types are: (char [19], char [19]) 

These were fixed with this PR, there were shown in the PROBLEMS section of VS Code

**Comment by lephilousophe** [comment]
Obviously, it seems that MSVC code analyzer is wrong.
Do you confirm that the build didn't throw any warning?
And, since when these lines were in PROBLEMS?

Making the warnings disappear doesn't mean the problem is fixed.
The initial construct works on every compilers without any trouble and has the advantage to automatically detect the size of the storage where data is written to.

**Comment by BJNFNE** [comment]
Yes i can confirm this build with the new commits do not make any warnings while compiling.
The warnings/PROBLEMS were only printed in VS Code Editor PROBLEMS section see here: Bildschirmfoto vom 2024-07-02 12-29-12

**Comment by BJNFNE** [comment]
Bildschirmfoto vom 2024-07-02 12-32-37

**Comment by BJNFNE** [comment]
it was happen most likely with this commit: https://github.com/scummvm/scummvm/commit/f26ce1e4ffba89d6e23e3957d0dc4aa8907bfa73

**Comment by tag2015** [comment]
This looks more like a problem with the C++ extension in VS Code.
The construct is used in hundreds of other places, try for example `engines/queen/command.cpp` and see it the same "problems" are reported

**Comment by BJNFNE** [comment]
The same "Problems" are also in the queen engine

**Comment by lephilousophe** [comment]
Then, it's a bug with VS Code C++ extension and should be reported here instead.
MSVC compiler is silent, GCC is silent, Clang is silent. Only some broken parser, not even a C++ compiler, is not happy with it.

**Comment by BJNFNE** [comment]
Okay when its only an bug in the extension of C++ for VS Code. What we now do with the commits that has been merged would be it OK them leave them merged or rather reverting them?

**Comment by bluegr** [comment]
Since these changes originated from a false positive, both commits have been reverted in master - commits 2f104415bf60ee6dc9c47aa2479aa5c03633bd8d and ac9ff4b60715982421d8fe88d136ebca76841496

**Pull request merged**
