### PR TITLE
SHERLOCK: Support Chinese version of Rose Tattoo

### PR DESCRIPTION
**Pull request by phcoder**
Complete as far as I can tell. Still needs testing from a Chinese speaker

### CODE REVIEW

**Comment by i30817** [comment]
Can i ask how the name looks inside the scummvm gui, for a libretro thumbnails project purpose?

Is it 'The Lost Files of Sherlock Holmes: Case of the Rose Tattoo (CD/DOS/Chinese)' or is there a chinese name showing.

**Comment by phcoder** [comment]
Le mer. 23 nov. 2022, 14:50, i30817 ***@***.***> a écrit :

> Can i ask how the name looks inside the scummvm gui, for a libretro
> thumbnails project purpose?
>
> Is it 'The Lost Files of Sherlock Holmes: Case of the Rose Tattoo
> (CD/DOS/Chinese)' or is there a chinese name showing.
>

Just 'The Lost Files of Sherlock Holmes: Case of the Rose Tattoo
(CD/DOS/Chinese)'

**Comment by i30817** [comment]
I deleted the message when i realized that i wouldn't have the images (i guess they're in mobygames). Sorry about the noise and confusion that someone else reading it on the web interface may have!

**Review by sev- — APPROVED** [review]
Nice work. I have only one tiny stylistic nitpick.

**Pull request merged**
