### PR TITLE
ANDROID: Update to compile with modern NDKs

### PR DESCRIPTION
**Pull request by ccawley2011**
This will probably require a toolchain update on our current buildbot.

Originally from PR #1128

### CODE REVIEW

**Comment by sev-** [comment]
Could you please specify which toolchain needs to be installed, so I try to take care of it?

**Comment by ccawley2011** [comment]
The new buildbot worker uses SDK version r25.2.5 and NDK version r15c. Details are available [here](https://github.com/csnover/scummvm-buildbot/blob/master/workers/android/Dockerfile).

**Comment by bluegr** [comment]
Any news on this? Has the new toolchain been installed?

**Comment by bluegr** [comment]
We are using Android NDK r9c on buildbot, which dates back to December 2013:

https://developer.android.com/ndk/downloads/revision_history

The latest NDK version is r19c, at the moment, dated January, 2019

**Comment by bluegr** [comment]
According to our wiki, the latest Android NDK supported is r15c (July 2017):

https://wiki.scummvm.org/index.php?title=Compiling_ScummVM/Android-SDL#Install_the_Android_NDK

Perhaps @antoniou79 could have a look at this, since he has a working Android building environment?

**Comment by antoniou79** [comment]
@bluegr , I'm afraid I'm hardly up-to-date with setting up or updating a toolchain for the Android port. 
What I did for the Android-SDL was much simpler; I just had to reproduce the reported issues, experiment a bit with the minimum tools that needed to be installed, implement the fix and then detail a step by step guide for others.

**Comment by bgK** [comment]
I took some time to prepare buildbot for this PR:
* Installed NDK r14b. This version supports both Android 2.3 and ARM64 devices.
* Dropped the MIPS build. Android devices with MIPS CPU were never widespread and are no longers supported by newer NDKs.
* Added a ARM64 build. ARM64 is mandatory for store uploads starting August 2019.
* Compiled liba52, FAAD, FLAC, FreeType, libjpeg-turbo, libmad, libmpeg2, libogg, libvorbis, libtheora, libpng for the armv5 and the arm64 toolchains.

Matching buildbot commit: https://github.com/scummvm/scummvm-sites/commit/fe2f4c06ccba718fb29145e89bfcaa52203ab227

I'll do the merge in a few days if nobody objects.

**Pull request merged**
