### PR TITLE
SCUMM: Fix translation of some system dialog strings

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by orgads** [comment]
CC @BLooperZ

**Comment by orgads** [comment]
@AndywinXp In COMI the strings are `SYS`. Did you have `SYST` in another game?

**Comment by AndywinXp** [comment]
Hi! In my disasm of the multilanguage interpreter for COMI (not the CJK one, but the American/European one), those strings are preceded by `SYST` and they all are correctly translated for French, German, Spanish and Italian (except for the iMUSE one which is untranslated). Which problem is this PR trying to address exactly? Which version are you targeting?

**Comment by orgads** [comment]
I did a clean install from GoG, and have this in `LANGUAGE.TAB`:
```
DS_005	Monkey Island
EC_497	Doyle Gilstrap
EC_498	The Monkeys Are Listening
SYS200	Are you sure you want to quit?
SYS201	Yes
SYS202	No
EC__100a	Based on Characters Created by
EC__100b	Ron Gilbert
...
EC_550	International Credit
EC_551	International Credit
SYST203	iMuse buffer count changed to %d
EC_552	 
```

The only `SYST20` I can find in the sources (using grep), is the iMuse string.

**Comment by orgads** [comment]
Interesting... In the Spanish version I see some additional (duplicated) translations:
```
EC_497	Doyle Gilstrap
EC_498	Los Monos Están Escuchando
SYS200	¿Seguro que quieres abandonar?
SYS201	Sí
SYS202	No
EC__100a	Basado en los personajes creados por 
EC__100b	Ron Gilbert
...
EC_551	^c015Capitán Rottingham y Mort: Salvador Serrano 
SYST203	Contador de Buffer iMuse cambió a %d
EC_552	LA MALDICIÓN DE MONKEY ISLAND
SYST300	s
SYST301	C
SYST302	d
SYST303	i
SYST304	u
SYST305	e
SYST306	h
SYST307	t
SYST200	¿Seguro que quieres abandonar?
SYST201	Sí
SYST202	No
```

**Comment by orgads** [comment]
Anyway, I guess we should just add these additional translatable strings to the Hebrew translation (that's what I wanted to solve here, it is based on the English original file that lacks these entries).

Closing this. Thanks!

**Comment by AndywinXp** [comment]
Oh, I see :)

I can confirm that all the other translated versions of LANGUAGE.TAB have the same strings with the `SYST` prefix, though.

**Pull request closed without merging**
