### PR TITLE
BUILD: Add Travis build target using create_project and CMake

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by sev-** [comment]
And what are the advantages of this change?

**Comment by bonki** [comment]
Indeed, even if this proves to be a desirable change these things should always come with an elaborate commit message explaining why.

**Comment by bgK** [comment]
I'm not opposed to this change, but, as a warning, the CMake project generated by create_project is not complete / production quality (it hardcodes the presence of libraries instead of trying to detect them, ...). It was merged allow the use of IDEs that use CMake projects as their project model (CLion, QtCreator, ...).

**Comment by sev-** [comment]
I have a feeling that this is too early to do this change. CMake needs to be enhanced first. I was not able to compile out of the box with the current create_project.

@ccawley2011 was it tested somehow? Do you have time/energy for fixing create_project?

**Comment by criezy** [comment]
I was able to compile out of the box with create_project to generate a CMake solution used in CLion, however it indeed has some limitations. For example for me it seems to work only if you call create_project from the root of the source code directory (as it done in this PR). Also interestingly on macOS it doesn't compile the mac specific bits (such as using the native file browser) but it otherwise works properly.

But I am also curious about the advantages of this change. What benefit is there to using create_project and cmake over using configure for Travis? Is that purely so that we can use ninja instead of make and hopefully get faster builds? Or is it just to offer the choice of which one is used? Is there other advantages?

**Pull request closed without merging**
