### PR TITLE
SCUMM: Implement Mac graphical features for Mac versions

### PR DESCRIPTION
**Pull request by AndywinXp**
## _What_ is this PR doing?

This PR:
* Implements an in-engine version of the **EPX graphics smoothing filter** for all Mac games: I know we have scalers and shaders on the app, but we need this feature in-engine, so that we filter just the game image and not menus;
* Implements color **gamma correction** for every LEC Mac game (from Indy3 to The Dig): it uses a lookup table which I extracted from a Mac monitor driver; I would say it matches Basilisk II a good 98%, but since I'm using data from an actual monitor driver I'm expecting to be doing just fine;
* Reverts that horrible workaround I wrote for **offsetting the game screen Y position** to have a non-aspect-ratio-corrected 640x480 (the Mac resolution we are modeling), and implements a cleaner one which doesn't need any savegame finnicking;
* Implements the **Mac menu bar** on MI1, MI2 and INDY4, basically all v5 games;

## _How_ is this PR doing?
This will be a draft PR until these tasks are closed:
- [x] _Implement "About" menus_ (with some help from @eriktorbjorn, if he's available and wants to help out);
  - [x] Fix the PICT decoder ([PackBitsRgn](https://github.com/jrk/QuickDraw/blob/6377ec5d89735a11b3f6e1ae728f555936c7583f/Pictures.a#L1012));
- [x] _Fix palette of menu bar in MI2 and INDY4_: I really don't know how to deal with this one;
- [x] _Finish implementing some menu options which I might have forgotten to deal with_;
- [x] Implementing the _'rough' keyboard command_ which toggles EPX;
- [x] Refactor EPX code to avoid cluttering the drawStrip function;
- [x] Adding proper handling for all known STRS resources from all known executables;
- [x] (Nice to have) _Fix edge cases within the EPX code_: since the algorithm is applied piece-wise (dirty rect by dirty rect), as per specs by Eric Johnston/Aaron Giles; the original doesn't show this issue. A visible edge case is during the "These dogs are sleeping" message in MI1, where on the right side of Guybrush there is a vertical strip of two black pixels:
scummvm-monkey-mac-00004

## Something else?
@athrxx pointed out that we don't really need to replicate all functions of the menu bar, particularly referring to the "Window" menu:
image
Apart from the obvious "Hide Desktop" and "Hide Menubar" items, the "Tiny", "Medium" and "Large" controlled the actual size of the game window:
* Tiny sets the game to its native 320x200 resolution;
* Medium applies the EPX filter and scales it down to 480x300;
* Large applies the EPX filter to the native image, resulting in a 640x400 buffer.

We probably have everything needed to replicate this, but I have to agree on the fact that we probably don't need all of that... We just need to add a "Smooth Graphics" toggle which is missing on MI1 and MI2 (and INDY4 floppy) - which I added.

Personally, the way I approached it is: take the menus parsed from resources, add what's needed, and deactivate the entries we don't need.
image

Devs, do you have other opinions on this matter? I personally wouldn't remove unused entries (I'd just deactivate them and maybe add other things on top), but what would you do?

### CODE REVIEW

**Comment by bluegr** [comment]
Great work!

Perhaps we could use our own scaler infrastructure for this, both for the EPX filter and the window size?

i.e. something like:

    g_system->setScaler("<scaler_name>", "<scale_factor>");

**Comment by AndywinXp** [comment]
@bluegr thank you for the question! 

I would rather not do that, and the rationale behind this is is that EPX is an in-engine graphic mode, and must not affect anything outside the engine (the Macintosh menu bar and dialogs). Think of this implementation of EPX as an engine specific graphic mode in the same league as CGA, Hercules, Atari ST/Mac Monochrome.

**Comment by athrxx** [comment]
> @bluegr thank you for the question!
> 
> I would rather not do that, and the rationale behind this is is that EPX is an in-engine graphic mode, and must not affect anything outside the engine (the Macintosh menu bar and dialogs). Think of this implementation of EPX as an engine specific graphic mode in the same league as CGA, Hercules, Atari ST/Mac Monochrome.

Yes, the original MI1 Mac interpreter has that in the drawstrip function, very similar to the way original MI1EGA handles MCGA, EGA, etc. I don't think that MI1 even lets you turn it off... 

But they do use a couple sub routines instead of stuffing it all in one function (hint 😁).

**Comment by AndywinXp** [comment]
> But they do use a couple sub routines instead of stuffing it all in one function (hint 😁).

Hint taken 😉 I will add a task to refactor the EPX code.

**Comment by athrxx** [comment]
Is the smush player actually supposed to use epx? Would seem a bit weird, since you would think that these videos already got all the filtering they need in the production. And the movie player also isn't connected to the strip drawing system.
But I haven't ever seen any SCUMM 7 Mac game, so I definitely don't know...

**Comment by AndywinXp** [comment]
Yes, SMUSH frames have to be post-processed (so that the effect is toggleable); this matches the original functionality. Since I'm still very rough on 68k asm, and since the 2002 WIn32 EXEs contain the same EPX routines, so I could look those in order to understand how they are doing it precisely.

**Comment by AndywinXp** [comment]
Okay, the good news is that my "expand the rectangle to be processed by one pixel for each component" has found confirmation in disasm (for the 2002 versions mentioned above), so at least there's that.

The bad, or neutral, news is that the code they're using is a bit overengineered to be replicated verbatim on our system, so I opted for a clean up of my own code. Now both drawStrip and SMUSH use the same Mac screen processing code, and hopefully I will use one of these newly separated functions for hi-res cursor drawing for v6+.

**Comment by athrxx** [comment]
> Okay, the good news is that my "expand the rectangle to be processed by one pixel for each component" intuition has found confirmation in disasm (for the 2002 versions mentioned above), so at least there's that.
> 
> The bad, or neutral, news is that the code they're using is a bit overengineered to be replicated verbatim on our system, so I opted for a clean up of my own code. Now both drawStrip and SMUSH use the same Mac screen processing code, and hopefully I will use one of these newly separated functions for hi-res cursor drawing for v6+.

Yes, the use of the ` _completeScreenBuffer` seems fine, also from Mac disasm. The source data for the `drawStrip` method gets a pitch of 320 after each 8 pixels strip width, so that indicates that it must be a complete 320 pixels width bitmap.

There are other algorithms besides the "4 directions" algorithm, though. One that only goes to the right and some that only scale or only invert. Currently, I have no idea if/when they're used though. If we do get the correct pixel output, why even bother... I kind of like your small piece of code. Although the annoying part is: how do we know whether we have correct output? I mean you can do memory dumps from the emulator like I did with Indy3 Mac to check the sfx samples, but that is quite unpleasant and time consuming.

**Comment by AndywinXp** [comment]
> There are other algorithms besides the "4 directions" algorithm, though. One that only goes to the right and some that only scale or only invert. Currently, I have no idea if/when they're used though. If we do get the correct pixel output, why even bother...

I'm guessing this is what you are referring to, right? 



So far I only have seen case 0x20/32 being used, on both "smoothed" and "non-smoothed" cases...

As of the comparison part, I manually did lots of them using MI1 and FT as test cases, mostly for checking if I did everything right on the gamma correction part as well... That's how I discovered the (now fixed) glitch in MI1. So yes, I agree that it would be overkill to implement all of them if the output is already correct.

**Comment by athrxx** [comment]
> > There are other algorithms besides the "4 directions" algorithm, though. One that only goes to the right and some that only scale or only invert. Currently, I have no idea if/when they're used though. If we do get the correct pixel output, why even bother...
> 
> I'm guessing this is what you are referring to, right?
>

I would think that this is most likely it, at least the final case in the Mac disasm also checks for a value of 32.

**Comment by athrxx** [comment]
Screenshot 2024-10-10 230008


Just eyeballing it, the `_ds_flag_2` might actually be the epx enable bool. So, in that case it could really only trigger 3 of those algorithms: the 4 directions algo, the "only right" algo and the case 32.

**Comment by AndywinXp** [comment]
It seems we might have a slight mismatch then; not surprising, they're not quite the same codebase; the 0x20 case on my end is the 4 directions algorithm (actually, it seems to also look for the pixel to the left of the left neighbor?), while e.g. case 0x10/16 is a variant using lots of XOR operations.

**Comment by athrxx** [comment]
> It seems we might have a slight mismatch then; not surprising, they're not quite the same codebase; the 0x20 case on my end is the 4 directions algorithm (actually, it seems to also look for the pixel to the left of the left neighbor?), while e.g. case 0x10/16 is a variant using lots of XOR operations.

Yeah, that sounds kind of like the opposite workings of the Mac code. But keep in mind I have absolutely no idea what flag 1 actually is, so in the end, it might be the same... :-)

**Comment by eriktorbjorn** [comment]
Here's most of the MI1 About dialog. The graphics (the LucasArts logo and the monkeys) aren't there because our PICT loader is missing features, making them impossible to load. But all the text and the animated shadow should be working correctly.

[mi1-about.txt](https://github.com/user-attachments/files/17349089/mi1-about.txt)

The corners of the rounded rectangle are not pixel perfect because we don't emulate QuickDraw, I guess, but that's the case with the earlier games as well.

I'll get to work on the other two games later, but I figured this was enough to post this here.

However, we will probably have to rethink how colors are handled by the Mac GUI. It currently assumes that it has a 16 color palette, and refers to colors by indexes into that. (`kWhite`, `kBlack`, etc.) It also assumes that the rest of the palette is unused, so it can use it for its own purposes, e.g. when loading the "IQ" image in Last Crusade. The original would - I assume - map the colors to the 16 color palette. ScummVM uses a different part of the palette instead. But with 256 color games, that's no longer an unused area. (That probably explains why the slider widgets in the options dialog get the wrong color in MI1.)

**Comment by AndywinXp** [comment]
Thank you so much! Please feel free to commit it directly on the branch, I trust you 100% on this kind of things, so don't hesitate on making direct changes

**Comment by eriktorbjorn** [comment]
The remaining "About" pages for MI2 are almost identical to the ones from Fate of Atlantis, so I should be able to commit them later today. Remaining problems:

- I don't know how to render the "Monkey Island 2" header correctly. It's probably another case of drawing the same string several times, slightly offset, but how? The inside of the letters look almost like Times 18 Italic Extended, but that's still not _quite_ pixel perfect.
- The text "LeChuck's Revenge" is drawn in the incorrect font. I think it's supposed to be Times 10 Bold, but the Mac font manager thinks it can do better by supplying a TTF font. I think. And that both looks wrong and has the wrong character encoding.
- The PICT loader is currently unable to load the LucasArts logo (for all three games) and the pile of monkeys (for MI1).

All of these are things I'm going to need help with. After that, I have some ideas for cleaning up the code a bit. Other than that, I think it's good enough.

**Comment by eriktorbjorn** [comment]
Hmm... Something about that patch isn't quite right. In Fate of Atlantis, the screen goes a bit darker (as if there's no longer any gamma correction) before Indy even appears on screen.

**Comment by eriktorbjorn** [comment]
Ok, new attempt. Apparently `paletteColors` is indexed from 0 and up, regardless of which part of the palette is being updated.

```
diff --git a/engines/scumm/palette.cpp b/engines/scumm/palette.cpp
index 2a999801ef5..2cff80dfacc 100644
--- a/engines/scumm/palette.cpp
+++ b/engines/scumm/palette.cpp
@@ -273,9 +273,6 @@ void ScummEngine::resetPalette() {
 		}
 		setDirtyColors(0, 255);
 	}
-
-	if (_macGui)
-		_macGui->setPalette(_currentPalette, 16);
 }
 
 void ScummEngine::setPaletteFromTable(const byte *ptr, int numcolor, int index) {
@@ -1734,17 +1731,14 @@ void ScummEngine::updatePalette() {
 #endif
 
 	if (_game.platform == Common::kPlatformMacintosh && _game.heversion == 0) {
-		for (int i = 0; i < ARRAYSIZE(paletteColors); i += 3) {
+		for (int i = 0; i < 3 * num; ++i)
 			paletteColors[i] = _macGammaCorrectionLookUp[paletteColors[i]];
-			paletteColors[i + 1] = _macGammaCorrectionLookUp[paletteColors[i + 1]];
-			paletteColors[i + 2] = _macGammaCorrectionLookUp[paletteColors[i + 2]];
-		}
 	}
 
 	_system->getPaletteManager()->setPalette(paletteColors, first, num);
 
 	if (_macGui)
-		_macGui->setPalette(paletteColors, 256);
+		_macGui->setPalette(_currentPalette, (_game.id == GID_LOOM || _game.id == GID_INDY3) ? 16 : 256);
 }
 
 } // End of namespace Scumm
```

(Also, now that `updatePalette()` notifies the Mac GUI, the code to do so in `resetPalette()` should be unnecessary.)

**Comment by AndywinXp** [comment]
@eriktorbjorn if it doesn't break gamma correction in any game (please check), then it looks good to me and you can directly commit it 🙂 thanks!

**Comment by AndywinXp** [comment]
(The only sidenote being: the Mac GUI *has* to be gamma corrected)

**Comment by eriktorbjorn** [comment]
> (The only sidenote being: the Mac GUI _has_ to be gamma corrected)

Since the backend gets the gamma corrected palette, that should affect the appearance of the Mac GUI too. I think the GUI mainly uses its own copy of the palette so that it can look up which color to use when it wants to draw white, black, etc. and to find the inverse of a color. And for that, it seems to me that the uncorrected colors should do fine.

**Comment by eriktorbjorn** [comment]
> @eriktorbjorn if it doesn't break gamma correction in any game (please check), then it looks good to me and you can directly commit it 🙂 thanks!

As far as I could tell, gamma correction still works. But it'll be a couple of hours before I'm able to commit. So if anyone wants to double-check that it doesn't break anything, now's the time! :-)

**Comment by eriktorbjorn** [comment]
I think I may have a working patch for the PICT loader. I'll play more with it later (I may have to add clipping to the drawSprite() function), but it looks promising so far.

image

**Comment by eriktorbjorn** [comment]
D'oh! The code I've been mucking with isn't involved with the monkeys at all. That explains why the LucasArts logo is still messed up. But hey, at least the changes @AndywinXp made before fixed the monkeys! ;-)

And the changes I made so far are promising in that Loom and Last Crusade still work, and the LucasArts logo at least doesn't crash ScummVM.

**Comment by eriktorbjorn** [comment]
Well, it's getting better at least... :-)

image

**Comment by eriktorbjorn** [comment]
Nice work on the strings. I'll have to see if I can figure out how to add a table for my floppy version of Fate of Atlantis, because it's not recognized at the moment.

Typing "rough" in Monkey Island 1 crashes the game because it doesn't have that string. (That's why I added a fallback, but maybe we should just disallow using it in MI1?)

**Comment by eriktorbjorn** [comment]
Oh, I see! The decoder for black and white images that I made (ugly!) assumes it's decoding one of the Rgn opcodes, so it skips the region. But this image uses one of the Rect opcodes, so it shouldn't skip. So the decoding part works, if you actually ask it to decode from the beginning of the picture and not somewhere around the "c" in "LucasArts".

image

So either we have to distinguish between these cases, or we have to see if the original Rect decoder (which I don't understand anywhere near as well) can handle black and white images as well. It _looks_ like it might and that would be wonderful, but I'm not sure...

**Comment by eriktorbjorn** [comment]
Unexpected setback: While I have a method that should produce something very close to the desired result for the "Monkey Island 2" text, it doesn't work in ScummVM because apparently we get the character spacing wrong in the Mac font renderer.

According to https://developer.apple.com/library/archive/documentation/mac/pdf/Text.pdf page 4-93 fonts can define an extra character width based on font size, and indeed the Times font does that. But so far I haven't been able to implement that correctly. This is my current attempt:

[macfont-width.txt](https://github.com/user-attachments/files/17435636/macfont-width.txt)

I could of course cheat and draw a bitmap instead. You know... as a last resort.

**Comment by eriktorbjorn** [comment]
It's a bit of a cheat, but the "Monkey Island 2" text looks correct now. It will look wrong if the correct character spacing is ever implemented, but it should be easy to fix then.

So I'm declaring the About dialogs to be done.

**Comment by eriktorbjorn** [comment]
The only thing I can think of now, and it's a bit besides the point of this pull request, is if it's possible to use the `clut` resource for the 16 color games. The format is dead simple. See https://developer.apple.com/library/archive/documentation/mac/pdf/Imaging_With_QuickDraw/Color_QuickDraw.pdf page 4-104. Both Loom and Last Crusade use the same, as far as I can tell. I've only inspected them visually in ResEdit though, I didn't dump and compare them.

| Field | Value | Comment |
|---|---|---|
| Seed | 0x0000 0x0080 | The resource id, 128 |
| Flags | 0x0000 | Identifies this as a color table for a pixel map |
| Size | 0x000F | Number of colors minus 1, i.e. 16 colors. |
| Color | 0x000F 0x0000 0x0000 0x0000 | Color 15 |
| Color | 0x000E 0x1A91 0x40AF 0xB800 | Color 14|
| Color | 0x000D 0x175D 0xA800 0x1922 | Color 13 |
| Color | 0x000C 0x1E3D 0xA800 0xA800 | Color 12 |
| Color | 0x000B 0xB800 0x0EB6 0x1076 | Color 11 |
| Color | 0x000A 0xB7F5 0x109B 0xAEA6 | Color 10 |
| Color | 0x0009 0x6C00 0x40CA 0x058B | Color 9 |
| Color | 0x0008 0x8B4D 0x8B4D 0x8B4D | Color 8 |
| Color | 0x0007 0x4B4D 0x4B4D 0x4B4D | Color 7 |
| Color | 0x0006 0x3A04 0x7B15 0xFFFF | Color 6 |
| Color | 0x0005 0x03CF 0xDBFF 0x085B | Color 5 |
| Color | 0x0004 0x0000 0xFFFF 0xFFFF | Color 4 |
| Color | 0x0003 0xEBFF 0x6589 0x03BF | Color 3 |
| Color | 0x0002 0xEBFF 0x57DC 0xEA63 | Color 2 |
| Color | 0x0001 0xEB56 0xEBFF 0x0CF2 | Color 1 |
| Color | 0x0000 0xFFFF 0xFFFF 0xFFFF | Color 0 |

But I'm not sure exactly how there compare to the EGA palette that we're currently using.

**Comment by bluegr** [comment]
@eriktorbjorn these colors look very similar (if not the same) as the default EGA palette

https://lospec.com/palette-list/color-graphics-adapter

**Comment by AndywinXp** [comment]
@eriktorbjorn 16-bit color components; it will be sufficient to just do:
```
R = (clutR >> 8) & 0xFF;
G = (clutG >> 8) & 0xFF;
B = (clutB >> 8) & 0xFF;
```

After applying that normalization, if we apply the usual gamma correction we obtain this:
image

Which match what you're seeing on the resource explorer.

**Comment by eriktorbjorn** [comment]
That's what I thought/hoped, but it was too late at night to experiment with it. I'll see if I can find good screenshots of Loom and Last Crusade where the difference in palettes should be noticeable.

**Comment by eriktorbjorn** [comment]
It looks like the scenes where it seems there _should_ be a noticeable difference between the EGA and `clut`, ScummVM already matches Basilisk II perfectly, or at least close enough that I can't tell the difference just by looking at them. (E.g. the background for the copy protection screen in Last Crusade is (117, 117, 252) in a screenshot I made from Basilisk II and (115, 117, 252) in a screenshot I made from ScummVM.

So I guess it's probably not worth bothering about?

**Comment by AndywinXp** [comment]
I see, but I would argue it's still better to load the CLUT resource. Just like we did with the STRS strings 🙂

**Comment by eriktorbjorn** [comment]
I'll give it a try, if you don't beat me to it, and post some comparisons later.

**Comment by eriktorbjorn** [comment]
It doesn't look promising. Here's Basilisk II:

image

Here's ScummVM using the EGA palette:

image

Here's ScummVM using the clut palette:

image

**Comment by eriktorbjorn** [comment]
This is my experimental patch, in case anyone wants to debug it:

[clut-palette.txt](https://github.com/user-attachments/files/17451291/clut-palette.txt)

**Comment by eriktorbjorn** [comment]
I have some cleanups that I'm planning on committing later today:

- The V5 and Loom file dialogs are virtually identical. They can be moved into macgui_impl.cpp so that only Last Crusade defines its own versions. (It made sense to have them in macgui_loom.cpp when there were only two games.)
- V5 games don't use `getFontByScummId()`, so that can be made into a no-op. (It's used for in-game Mac fonts.)
- There are some missing `override` keywords in macgui_v5.h.

**Comment by eriktorbjorn** [comment]
I did notice one unimplemented feature: The Speech menu in the CD version of Indiana Jones and the Fate of Atlantis.

It does detect that you select the menu items. It's handled in macgui_impl.cpp, but should perhaps be moved into macgui_v5.cpp instead? It just doesn't do enough to actually work.

**Comment by AndywinXp** [comment]
> The V5 and Loom file dialogs are virtually identical. 

I haven't had time to replicate the V5 dialogs game by game, but for now it's fine for me if you want to move them into macgui_impl.cpp.

> I did notice one unimplemented feature: The Speech menu in the CD version of Indiana Jones and the Fate of Atlantis.

Did I forget to implement that? I remember assigning the options for this menu to the _voiceMode variable.

**Comment by eriktorbjorn** [comment]
Looking a bit closer...

The `syncSoundSettings()` function will update `_voiceMode` based on the `"speech_mute"` and `"subtitles"` setting, so changing that in the menu handler has no effect. The checkmarks in the menu are based on `_voiceMode` so that's why they don't change.

The `_v5VoiceMode` variable is new, I believe. But it only seems to affect what happens when you press Ctrl+T, so I'm not sure how useful that is.

**Comment by eriktorbjorn** [comment]
Based on that, perhaps something like this? I haven't tested it much:

```
diff --git a/engines/scumm/macgui/macgui_impl.cpp b/engines/scumm/macgui/macgui_impl.cpp
index d34505a7c02..af9dda5f43f 100644
--- a/engines/scumm/macgui/macgui_impl.cpp
+++ b/engines/scumm/macgui/macgui_impl.cpp
@@ -20,6 +20,7 @@
  */
 
 #include "common/system.h"
+#include "common/config-manager.h"
 #include "common/enc-internal.h"
 #include "common/macresman.h"
 
@@ -364,18 +365,21 @@ bool MacGuiImpl::handleMenu(int id, Common::String &name) {
 		return true;
 
 	case 500: // Voice Only
-		_vm->_voiceMode = 0;
-		_vm->_v5VoiceMode = 0;
+		ConfMan.setBool("subtitles", false);
+		ConfMan.setBool("speech_mute", false);
+		ConfMan.flushToDisk();
 		_vm->syncSoundSettings();
 		return true;
 	case 501: // Text Only
-		_vm->_voiceMode = 2;
-		_vm->_v5VoiceMode = 2;
+		ConfMan.setBool("subtitles", true);
+		ConfMan.setBool("speech_mute", true);
+		ConfMan.flushToDisk();
 		_vm->syncSoundSettings();
 		return true;
 	case 502: // Voice and Text
-		_vm->_voiceMode = 1;
-		_vm->_v5VoiceMode = 1;
+		ConfMan.setBool("subtitles", true);
+		ConfMan.setBool("speech_mute", false);
+		ConfMan.flushToDisk();
 		_vm->syncSoundSettings();
 		return true;
 	}
```

**Comment by AndywinXp** [comment]
If by extension this updates _voiceMode, _v5VoiceMode and the corresponding SCUMM var, then this looks good to me, thanks!

**Comment by eriktorbjorn** [comment]
It doesn't update `_v5VoiceMode`, though I can see why it perhaps should.

Currently the only thing I can see in master that updates `_v5VoiceMode` is pressing Ctrl+T. Maybe that's the only way to change speech/text in-game in V5 games (until this pull request). But as far as I can tell, it will always starts out as 0, no matter what your speech/text settings are, and that's what I find so odd.

**Comment by AndywinXp** [comment]
The reason why it's the way it is is because v5 doesn't have VAR_VOICE_MODE, hence the separate variable. But yeah, it should be in sync with the game settings from the beginning

**Comment by eriktorbjorn** [comment]
So perhaps `syncSoundSettings()` should update `_v5VoiceMode` as well? It currently only updated `VAR_VOICE_MODE`, if it exists.

**Comment by AndywinXp** [comment]
Probably, but I'll have to check that it doesn't create some sort of cyclic update...

**Comment by eriktorbjorn** [comment]
Nice, but there are some debug leftovers in macwindowmanager.cpp.

**Comment by AndywinXp** [comment]
Whoops... Thanks. Removed them, and I'm about to force push to remove that from history, be warned...

**Comment by eriktorbjorn** [comment]
It looks like the dissolve screen transition is broken, as seen in this bit of the Fate of Atlantis intro.

scummvm-atlantis-mac-00001

**Comment by bluegr** [comment]
> It looks like the dissolve screen transition is broken, as seen in this bit of the Fate of Atlantis intro.
> 
> scummvm-atlantis-mac-00001

@eriktorbjorn I checked this in a youtube video, and it looks like there's no dissolve transition in the Mac version. So this doesn't look to be a regression:

https://www.youtube.com/watch?v=xK4VMwe0Xho#t=5m12s

**Comment by eriktorbjorn** [comment]
It certainly looks that way. I tried the floppy version in Basilisk II, and there was no dissolve transition in that scene for me either. Disabling the graphics smoothing or running the game in "Tiny" mode made no difference. Maybe they just couldn't get it to run at any acceptable speed?

I didn't play far enough to see if it also affects the other scenes with the dissolve effect. I think the next one would be when melting the eel statue out of the ice?

I seem to remember that EGA Loom has some dissolve effects (using larger squares, not pixel by pixel). I don't remember if Mac Loom also has them, and I don't know how the original behaves. But if they're there, I never noticed any problem with them in ScummVM so there would be no reason to disable those.

**Comment by eriktorbjorn** [comment]
Oops, I see I've accidentally broken the default load game dialog. I'll fix that when I'm back home. (When I rewrote the fake widgets, I simplified them to no longer use actual widgets. So now the list box is widget 4, not 6. Perhaps I should have given the widgets proper IDs rather than relying on the number they just happen to get...)

**Comment by bluegr** [comment]
@eriktorbjorn It would be preferable to use defines for these widget IDs rather than absolute values scattered throughout the codebase. The current approach looks to be error prone

**Comment by eriktorbjorn** [comment]
Another approach would be to have an id assigned automatically, and stored in the widget. Then, when adding the widget, you could check which id it got and use that later.

**Review by bluegr — APPROVED** [review]
Overall, this is excellent work, vastly improving the GUI in Mac SCUMM games. I've played almost all Mac games, and didn't notice any issue.

If there are no objections, this is good to be merged

**Comment by eriktorbjorn** [comment]
The things I'm most concerned about right now is that my recent dialog changes may have broken some dialogs (options, save, load, etc.) but hopefully I repaired more things than I broke. Any help testing them is welcomed!

Also, it turns out that MI1 has a slightly different options dialog than MI2 and Fate of Atlantis, but they're all handled by the same function. (MI1 has individual checkboxes for music and sound, while the others have a single checkbox for both.) That's probably going to need some minor adjustments.

So yeah, I think things are in pretty good shape. Of course, I've been saying that for the past couple of days, yet here we are a dozen commits later. :-)

**Comment by bluegr** [comment]
I've talked with both @AndywinXp and @eriktorbjorn, and they confirmed that this is now good to be merged.

Excellent work and kudos to @AndywinXp, @eriktorbjorn and @athrxx for their contribution and work on this.

**Comment by AndywinXp** [comment]
Thank you! Let's press the button 🙂

**Pull request merged**
