### PR TITLE
CLOUD: Fix #11244 crash; do minor changes to GUI

### PR DESCRIPTION
**Pull request by Tkachov**
Changed SaveLoadCloudSyncProgressDialog and SaveLoadChooserDialog to poll CloudMan instead of being updated from another thread -- in order to fix [#11244](https://bugs.scummvm.org/ticket/11244).

Additionally, some minor GUI changes so SaveLoadChooserDialog is redrawn while SaveLoadCloudSyncProgressDialog is modal, and progress is displayed in bytes (more precise than files count).

changed progress

Also, removed `loadTimestamps()` in sync request, because it was not only re-reading the file (which seems excessful), but also invalidating save file manager's cache. I've encountered a segfault or a freeze a few times in `MemoryPool::freeUnusedPages()` while testing the other changes, which seems to happen when `DefaultSaveFileManager::assureCached()` clears a hashmap, so this was an attempt to make it much less frequent.

### CODE REVIEW

**Comment by sev-** [comment]
Please rebase, so the merge commits go away.

**Comment by sev-** [comment]
What about counting _both_ files and bytes? :D, `(100.7K / 248.8K, 23 / 49 files)`

**Comment by Tkachov** [comment]
Struggled with `U32String::format` for a while, and was ready to give up, but then defeated it (=
A little bit weird to use `String::format` to format %llu and %% so it could be put to U32 version.

updated dialog

**Comment by sev-** [comment]
Excellent, thank you!

**Pull request merged**
