### PR TITLE
JANITORIAL: Typo Squashing - Phase 1

### PR DESCRIPTION
**Pull request by raziel-**
Sorry, if i create once more more work than gain (i can't use the git cli command, have to manually type in everything, so...sowwy).

- Most of the typos are comment based
- Two are within the code, variables i think (but i believe i caught all of it's instances)
- Two or three are warning/error outputs
- Two or three are in-game talk lines
- I also added two FIXME comments on create_dat lines, that will change the .dat files as i didn't want to mess up obviously :-)

If i still messed up, please tell, maybe you can cherry-pick what you need otherwise

If i should continue, i'll tackle the engines next
If not, i'll go back to my dark, warm, feel good place...with a blanket...and lots of chocolade

Thank you

### CODE REVIEW

**Comment by sev-** [comment]
While I welcome the changes itself, the commit log messages are not conforming to our commit guidelines:

https://wiki.scummvm.org/index.php?title=Commit_Guidelines

Moreover, some of those commits are matching our "bad examples" section.

**Comment by raziel-** [comment]
@sev- 

so, instead of listing the filenames and the typos, i should better have used
JANITORIAL: Fix typo x in file y
in all messages?

can i edit the commit messages from the Web page?

oh and sorry...i knew i'd mess up

**Comment by sluicebox** [comment]
The typo fixes all look good to me, with the exception of changing "seeked" to "sought". It's true that "seeked" is not a real word, but given the way "seek" is used in software and functions, I think "sought" in comments is confusing and worse. It would not occur to me that "we already sought" in these comments meant "we called seek", but "we already seeked" is clear. I can see myself getting confused by such a comment and changing it to "seeked".

I don't feel strongly about this, but the rest are accidental typo fixes while "seeked" => "sought" is overriding the author's intent, so it had better improve the comment and clarity. I think it makes each of those less clear.

**Comment by raziel-** [comment]
@sluicebox 

would seek'ed be a compromise or should it be revertedall along?

**Comment by raziel-** [comment]
Closed in favour of #5787

**Pull request closed without merging**
