### PR TITLE
GLK/ULTIMA: Disable unstable subengines by default

### PR DESCRIPTION
**Pull request by ccawley2011**
This is necessary on RISC OS to avoid linker errors due to the size of the executable.

### CODE REVIEW

**Comment by raziel-** [comment]
@ccawley2011

Just curious.
How are you planning a release once all the engines are stable (and the executable size exceeds the magical size again)?

I might hit errors due to executable size on my platform aswell (some day) and am looking for workarounds before it bites me seriously.

Thank you

**Comment by ccawley2011** [comment]
The most likely answer is that I'll have to move to the newer EABI based toolchain for newer hardware and disable the heavier engines in builds for older hardware (I haven't done any in depth profiling, but I doubt that engines like sword25, wintermute or fullpipe would perform very well on the RiscPC, Iyonix or A9home). I don't want to make such major changes to my build environment so close to a release, however (since the RISC OS EABI toolchain is still very new), which is why I'm sticking to keeping the executable size down for now.

**Comment by rsn8887** [comment]
If I use this PR, and run configure, the list of built-in engines (incorrectly?) states `Ultima []`. It seems a bit odd. I think the `[]` should probably contain the list of comma-separated stable sub-engine names. The list of skipped engines correctly shows `Ultima [Ultima 1]`.

**Comment by dreammaster** [comment]
rsn8887: I agree, that does seem a bit odd. Ideally, is there a way to list the individual games for the supported engine without requiring the return to having each of the games as it's own sub-engine again.

**Comment by dreammaster** [comment]
Personally, I think it may be simpler to use #ifndef RELEASE_BUILD blocks around the unstable code. That's what I already did in the adrift sub-engine, to exclude detection entries for ADRIFT 6 games that aren't yet supported.

**Comment by sev-** [comment]
There is a nice upcoming alternative, though. Once @aryanrawlani28 work on detection is merged, we finally could safely create split builds which will detect the games but inform the user of using another build, with the engine. This way, you could build scummvm and scummvm-glk...

**Pull request merged**
