### PR TITLE
ENGINES: Fix detection of existing save stored in autosave slot

### PR DESCRIPTION
**Pull request by macca8**
This complements #4350 & #4355.

The issue with retaining the isAutosave() calls in listSaves() is that, with the removal of the bug  in #4355, any regular save that may be stored in the autosave slot will not be properly detected, and will attempt to generate a dummy autosave. 

The common change  in this PR is the removal of the isAutosave() calls in the listSaves() functions of the CINE & SCI engines, and the default listSaves() in ENGINES. replaced by the previous "slot == getAutosaveSlot" type calls relevant to each. I've also reinstated some setAutosave() calls where I thought they wer most relevant (ENGINES, CINE).

### CODE REVIEW

**Comment by bluegr** [comment]
The changes in 73f595aa8d23c092028bc0723b08155b094b0ac4 are confusing to me. If an engine uses the autosave feature, it should ovewrite any save in the autosave slot. Otherwise, what's the point of the autosave feature? If a user has a regular save in the autosave slot, the autosave feature will be blocked from working at all

**Comment by bluegr** [comment]
> The golden rule of autosaving is that an autosave should NEVER overwrite a user’s regular save. The point is to make sure it only overwrites when it's safe to do so.

Well, no, if a user manages to overwrite the autosave slot with a regular save, then that's a totally wrong decision. We are protecting this slot from being overwritten, so the user is *not* supposed to create custom saves on that slot. If he does, the rule is to overwrite the autosave slot with an autosave.
Otherwise, we'll be left in a deadlock where the autosave feature won't be able to create autosaves

**Comment by raziel-** [comment]
I know i'm in the completely wrong place to ask here, but while we are on the subject...i always found a single autosave slot pretty limited.

I know it's outside the scope of this PR, but wouldn't it be better to introduce something new, like modern game engines do today?
Ten or so autosave slots (starting with hexadecimal numbering, like A01, A02 and so on, to not get in the way of the 0-999 save slots most of the games supported by ScummVM use) completely beside the normal save slots (maybe even on it's own GUI tab) that are looped through automatically all five minutes (or whatever time the user has set).
It will autosave to a new slot until it starts to roll-over.
It can manually be load from, but not saved to, so everyone would be happy and the users too lazy to save themselves have the opportunity to go back even more once a false decision was made (especially great in SCI adventures) :-)

And give slot 0 back to the user? ;-)

Sorry for interrupting, thank you

**Comment by bluegr** [comment]
> Going forward, we really should be considering giving the user full access to the autosave slot. Everything is in place. It just needs to be switched around.
Why? What's the reasoning to allow the user to do something completely illogical, and then not only support this, but also try and avoid ending up in all sorts of obscure dead ends and workarounds to support something that _doesn't make any sense to be supported_

> we can't be certain that autosaving was even supported when the regular save was created... there's no time limit here.
That's not really an issue. Old saved games in the autosave slot don't have to be supported. Clean and simple :)

> Maybe in the past, but hasn't been that way since at least Feb 2020 (when https://github.com/scummvm/scummvm/pull/2050 implemented the isAutosave() method (along with the _saveType property) to specifically prevent a regular save from being overwritten by an autosave).
Actually, isAutosave() was initially created to distinguish the autosave slot and disallow it from being overwritten by a regular save

> Also true (an autosave would fail silently in the past), but not since Aug 2021 (when https://github.com/scummvm/scummvm/pull/3261 was implemented), when the in-game warning dialog was introduced
Yes, that warning is in place to warn the user about doing something silly, which is what we're talking about, i.e. overwrite the autosave slot :)

> The reality is that, since https://github.com/scummvm/scummvm/pull/4350 was implemented, a user with access can manually update the autosave file safely, without disrupting regular autosaves from being performed at their scheduled intervals.
Well, no, that PR disallows the user from overwriting saved games named "Autosave"

> The main reason why a user may need to interact with the autosave file is maintenance. For example, if the warning dialog fails its designated task (which has happened previously), then the user needs to complete the task manually.
Again, the user *should not* mess up with the autosave slot. Again, we're talking about an edge case where the user managed to overwrite the slot, and we're trying to help him fix that

> Adds support for manually resolving autosave file issues, improving overall stability.
Stability? I don't see how this feature is related to stability. Could you please elaborate? :)

> The warning dialog makes it safe to do so, since it monitors the results of the user's actions.
Yes, again, the user *is trying to do something illogical (i.e. stupid)* in this case - overwrite an automated saved game with a manual save

> A user can safely overwrite, delete or replace an existing autosave file without interfering with the next scheduled autosave, which automatically creates a new autosave file if none is present.
But why? Why would someone want to do that? What's the benefit?

>If a user renames the autosave file
Again, why? Why would the user want to do that?

>all this is implemented in https://github.com/scummvm/scummvm/pull/3261
Yes, this PR is named "Streamline auto-save write/delete protection". Emphasis on the *protection* part

Overall, it's not clear why we want to allow the user to do something stupid, and then try to fix it. It doesn't make any sense, and we're trying to support edge cases here (old saves written in the autosave slot), which will end up disabling the feature, and we'll get more obscure bugs.

Could you please provide a scenario where this makes sense? Perhaps with screenshots, if it helps to provide more information

**Pull request closed without merging**
