### PR TITLE
SAGA: Fix memory and file handle leak in loadResource

### PR DESCRIPTION
**Pull request by PushmePullyu**
Fixes [#14334](https://bugs.scummvm.org/ticket/14334)

### CODE REVIEW

**Comment by bluegr** [comment]
Has this been tested?

I believe that the file handling semantics in SAGA have been changed now, at least according to 302a5eb0afa248f2c6dbea7a3fbd9c2c73a5a916

**Comment by PushmePullyu** [comment]
> Has this been tested?
> 
> I believe that the file handling semantics in SAGA have been changed now, at least according to [302a5eb](https://github.com/scummvm/scummvm/commit/302a5eb0afa248f2c6dbea7a3fbd9c2c73a5a916)

Nice catch. I'll rework my fix to not call close() if we get the file via context->getFile().

**Comment by dwatteau** [comment]
Still OK on the 3 test environments where I could reproduce this bug – thanks! :)

**Comment by bluegr** [comment]
Clean and straightforward implementation, thanks!

**Pull request merged**
