### PR TITLE
KYRA:EOB Spanish version

### PR DESCRIPTION
**Pull request by macomarivas**
Hi,

This is the Spanish version support for Eye of the Beholder.

Some notes about this version:

_CCARGEN.CPS_ and _CCARGENB.CPS_ are translated graphics in spanish, they corresponds to _CHARGEN.CPS_ and _CHARGENB.CPS_ respectively. What is the best recommendation? just rename the files or change the code in "chargen.cpp"?

Another point is the intro text, English version have "TEXT.CMP" file (bitmap), there is no equivalent for the Spanish version, It can be ok if I create one that would be added latter?, Spanish version Intro text is inside 'INTRO.EXE' file, any suggestion?

In the Spanish version exists a ITEM.DAT file that have English texts for in game items, this file has to be deleted for a proper translation. (the proper Spanish translated version is in EOBDATA3.PAK)

Please feel free to add anything I may have missed.

### CODE REVIEW

**Comment by athrxx** [comment]
Thanks for your work on this.
Is that version a fan translation that gets patched over the English version? Where is the patch available?
I'd want to check that out, so that I might actually understand commits like 7e93f1f500f22b740e0ad3f078d747a535a72651...

**Comment by macomarivas** [comment]
Hi athrxx,

This is based in the official Spanish release I suppose (I don't have the original game, sorry, this can be a legal issue?), with fixed translations, some original spanish translations aren't correct.

The commit that you mention is because the spanish release have the levels in .DRO files, the patch makes preference to the .DRO files (translated to Spanish) instead of the *.INF files (not translated and still in English)

**Comment by athrxx** [comment]
Well, we have a strict no-warez policy. So there should be either an official release or a translation patch that goes over one of the officially available versions.
I don't think that there is an official release, since I've never seen one anywhere. Ebay is full of old original EOB games, but none of it in Spanish (even if you look on Spanish ebay www.ebay.es). I presume that there must be a tanslation patch around for this somewhere, but I haven't found it so far.

I am also asking for a simple practical reason: I am very reluctant to accept hacks to the code base which I can't test/fix/maintain myself. So I'd really need that version...

**Comment by macomarivas** [comment]
I understand your position about this and agree about that.

You can found in ebay the spanish version of the game:

EBO1:
https://www.ebay.es/itm/PC-ADVANCED-DUNGEONS-DRAGONS-EYE-OF-THE-BEHOLDER-VERSION-ESPANOLA-CAJA-GRANDE/392272029604?hash=item5b553c27a4:g:7vEAAOSwCXJbH5TS

EOB2:
https://www.ebay.es/itm/PC-ADVANCED-DUNGEONS-DRAGONS-EYE-OF-THE-BEHOLDER-II-VERSION-ESPANOLA/392272034128?hash=item5b553c3950:g:148AAOSwkjtbH5WH

what you do need exactly? an image of the original floppy's?

**Comment by athrxx** [comment]
Oh wow, this is an official release after all. So this makes it actually more complicated, since I'd have to buy the thing from ebay and hope that it still works... And it is quite expensive and the seller doesn't even accept paypal :-/

If is turns out that this thing is too complicated for me to acquire we could simply add some extra `_flags.lang == Common::ES_ESP` guards to your code changes in scene_eob.cpp and I'll probably be happy with it (or at least I can tweak this to my likes without necessarily having the game).

I assume the CCARGEN.CPS / CCARGENB.CPS naming would also be trivial (just put a `_vm->_flags.lang == Common::ES_ESP ?` with the new names in there.

However, I can't really help you with the intro text and the item names without understanding what the Spanish version is supposed to do there.

Maybe you want to get on our Discord channel and contact me there? That might be the fastest way of getting somewhere...

**Comment by macomarivas** [comment]
I added more links, I agree with you, some of them are quite expensive.

For the intro text, can be ok if I create a "TEXT.CMP" that would be added latter? in kyra.dat maybe? let me to explore a bit more "INTRO.EXE", maybe I found a solution.

Thanks!

**Comment by macomarivas** [comment]
The idea of the game files are that the external files have preference form the internal Packed files (*.PAK).

This is the behavior for the *.DRO level files and for the character generation bitmaps, but the "ITEM.DAT" file, the proper one for the Spanish version is internal, the external is the English version. Any recommendation about this?

**Comment by macomarivas** [comment]
Maybe adding a extra default parameter to **createEndianAwareReadStream** like a constant for INTERNAL or EXTERNAL can be a solution, what do you think about this?

**Comment by athrxx** [comment]
I have cherrypicked your commits (except 8006e3d) and merged them into master together with my own code changes.

Of course, I missed your final commit 3e1241f :-/. I have now cherrypicked and pushed that, too. But it will not be in kyra.dat yet.

**Comment by athrxx** [comment]
Closing this, since the code has been merged. Thanks for the great work!

**Pull request closed without merging**
