### PR TITLE
ALL: HashMap & ConfMan getVal refactoring

### PR DESCRIPTION
**Pull request by henke37**
Refactoring the getVal function as seen in HashMap and ConfMan. It is now an error to try to get the value of an unknown key, with the variant for getting a default being called out by name. There is a separate `getValOrDefault` function for when a default is actually requested.

### CODE REVIEW

**Comment by criezy** [comment]
I didn't look at the details of the changes, but the idea seems good to me. This clarifies the intend of each function and may help to catch errors in the code using those.

**Comment by criezy** [comment]
And I have now tried to use that code, and it crashes immediately when I start ScummVM.
The first crash is in LauncherDialog::updateListing():
```
		String description(iter->_value.getVal("description"));

		if (description.empty()) {
			QualifiedGameDescriptor g = EngineMan.findTarget(iter->_key);
			if (!g.description.empty())
				description = g.description;
		}
```

**Comment by henke37** [comment]
I'm going to try one more tweak to handle `operator []` gracefully.

**Comment by henke37** [comment]
I will be continuing my work on that idea on a separate branch, this PR has been stalled for long enough.

**Comment by sev-** [comment]
okay, merging this

**Pull request merged**
