### PR TITLE
SDL: Warn if the selected joystick does not exist

### PR DESCRIPTION
**Pull request by klusark**

### CODE REVIEW

**Comment by sev-** [comment]
What joystick #0 is supposed to do? Issue a warning?

**Comment by sev-** [comment]
ping?

**Comment by klusark** [comment]
joystick_num = 0 tells sdl to use the 1st joystick.

**Comment by digitall** [comment]
This patch is actually fixing the issue where the reported active joystick is always the Joystick #0 data and there is no validation that the joystick number passed actually exists... But the patch is incorrect as the test for the joystick number is off by one...

**Comment by digitall** [comment]
I think this needs a bit more work... in the warning case, odd things could happen as _joystick is not opened... and the line 58 change is spurious as > -1, is the same as >= 0.... unless I am missing something.

**Comment by digitall** [comment]
Ah ignore my note about the off by one, just that I would reverse the test on line 65 to be "if (joystick_num < SDL_NumJoysticks())" as clearer.

**Comment by digitall** [comment]
OK... this all looks fine to me. It basically fixes the debug output to give the right answer i.e. correctly report the active joystick information, rather than Joystick #0 even when another one is in use, and adds a warning when the joystick number is out of range.

This should be merged.

**Pull request merged**
