### PR TITLE
SYMBIAN : fix compilation

### PR DESCRIPTION
**Pull request by fedor4ever**
This commit fixes compilation error due conflict between builting macro "remove" and various functions named "remove" in engines

### CODE REVIEW

**Comment by wjp** [comment]
Why did you open a new pull request instead of just updating your previous one ( #611 ) ?

**Comment by fedor4ever** [comment]
I'm sorry. I try amend last commit and get detached head. I will glad if someone teatch me how resolve that. Lesson on youtube will be sweet also.

**Comment by wjp** [comment]
Sorry, this slipped my mind. This approach looks good to me now. Did you close it for a reason?

**Comment by fedor4ever** [comment]
I dont understant what I need to do. And why right patches not accepted.
This pull request closed because it lost right patches. I cleaned "detached head" repo to make them like as in pull request #611 . Then I forced this repo to my fork. It looks like in august now. I change files listed in #611 and try git amend -no-commit-message-option in cygwin and get detached head again.
My steps before git amend:
1) edit sherlock/logo.h
2) edit default-saves.cpp and portdefs.h
3) git ament
4) detached head

This work well on test 3 files repo but not now.
Git version - 2.x.x, maybe 2.2.1

Also #611 has source from unknown repo now

**Comment by wjp** [comment]
Detached head just means you're not currently on any branch.

**Comment by fedor4ever** [comment]
I think about this problem and have some idea. I create branch for fix "remove" and merge this branch with master. I should amend commit in my branch, not in master. Before I amend commit in master branch.

**Comment by wjp** [comment]
Sounds good. Make sure to also submit the pull request from the branch.

**Comment by fedor4ever** [comment]
No way. I delete my merge pull request and try amend with --no-edit option. Now history look like:

--a -- R
     \  R'
R - commit to change, R' - changed К commit
WTF? Any Ideas?

**Comment by wjp** [comment]
It's impossible to say what is going wrong, because your comments are very unclear and confusing. You'll have to be much more precise in describing the situation and your actions.

The basic procedure is very simple:

* First, do a hard reset of your master branch to the remote master to ensure you're in a known, correct state. (Because I have no idea what the current state of your local clone is.)
* Then, create a new branch for your pull request, and check out that branch.
* Then, edit the files, commit them, and push it to your fork on github.
* Then, create the pull request.



If you want to change the pull request, make sure you have the branch checked out. Then:
* /either/ create a new commit, and push that,
* /or/ amend a previous commit, and do a force push.

**Pull request closed without merging**
