### PR TITLE
SYMBIAN: Update README for 2.5.1 release.

### PR DESCRIPTION
**Pull request by fedor4ever**

### CODE REVIEW

**Comment by sev-** [comment]
2.5.1 release is already done. We do not have plans to do another release on that branch

**Comment by fedor4ever** [comment]
This file updates with every release. No need backport because installer has that copy.

**Comment by sev-** [comment]
Which installer? There was no 2.5.1 release for Symbian.

**Comment by fedor4ever** [comment]
I upload to sourcefge now. I send mail with link and description

**Comment by sev-** [comment]
Do you have any source changes or build straight from branch-2-5-1?

**Pull request closed without merging**
