### PR TITLE
SCI: PCJr sound driver - added pitchbend feature and major cleanup

### PR DESCRIPTION
**Pull request by athrxx**
I have reorganized the code a bit, fixed deviations from our coding conventions and moved all the version specific sound channel code into sub classes.

And I have added the missing pitch bend feature. The pitch bend is actually used, even by the PC Speaker driver.

### CODE REVIEW

**Comment by bluegr** [comment]
A major improvement. Thanks for your work!

**Comment by eriktorbjorn** [comment]
I spent some time listening to at least part of the PCjr music from all my Sierra games. A few observations that I have not in any way even tried to verify against the original behavior.

- It felt like some notes were missing from fanfare at the very beginning of the King's Quest IV intro, but since this didn't happen in any other game I assume it's like the original.
- In the opening fanfare of Leisure Suit Larry 3, it plays the same note a few times. With PCjr, it sounds like one drawn out note. I don't know if that's something that should (or even could) be fixed.
- The Space Quest 1 intro sounds really bad.
- Many of the later games will trigger an error message when they fail to initialize the sound driver. A clear case of "well, don't do that then!" but maybe there could be a more graceful fallback?

Either way, nicely done! I was surprised how good some of them sounded. Even some that I had assumed came far too late to support this type of music.

**Comment by athrxx** [comment]
> I spent some time listening to at least part of the PCjr music from all my Sierra games. A few observations that I have not in any way even tried to verify against the original behavior.
> 
>     * It felt like some notes were missing from fanfare at the very beginning of the King's Quest IV intro, but since this didn't happen in any other game I assume it's like the original.
> 
>     * In the opening fanfare of Leisure Suit Larry 3, it plays the same note a few times. With PCjr, it sounds like one drawn out note. I don't know if that's something that should (or even could) be fixed.
> 

You were right about the non-perceptible fast/short notes in the LSL 3 fanfare. I have made a fix.

**Comment by eriktorbjorn** [comment]
> You were right about the non-perceptible fast/short notes in the LSL 3 fanfare. I have made a fix.

Thanks, that's much better!

I haven't been able to get Tandy music from Space Quest 1 or King's Quest 4 in DOSBox, so whether or not they're played correctly I guess ScummVM wins by default.

**Comment by athrxx** [comment]
I have made some minor fixes again. The KQ4 opening seems to be okay now compared to DOSBox.

Also, I have checked the SCI0EARLY version in DOSBox. It works fine with PCJr sound. So, maybe it is something with our sound resource loader.

**Pull request merged**
