### PR TITLE
CINE: Fixes to branch-2-2 for #11466, #11617, #11621 and #11625.

### PR DESCRIPTION
**Pull request by karisal**
Hi!
Here are a few bug fixes for Operation Stealth to the branch-2-2.
The fixes are related to the bugs #11466, #11617, #11621 and #11625.

I am not 100% sure how the handling of pull requests and bug fixes
is done with ScummVM related to a particular upcoming release so
please could you inform me of anything relevant. Thank you!

Kari Salminen

### CODE REVIEW

**Comment by criezy** [comment]
Thank you. This looks good to merge. 
Can you please close the corresponding tickets in the bug tracker?

**Comment by karisal** [comment]
> Thank you. This looks good to merge.
> Can you please close the corresponding tickets in the bug tracker?

  Yeah, sure.

Kari Salminen

**Comment by karisal** [comment]
> 
> 
> > Thank you. This looks good to merge.
> > Can you please close the corresponding tickets in the bug tracker?
> 
> Yeah, sure.

  Done.

**Comment by sev-** [comment]
It is done with backporting. E.g. you commit or make a PR to master and then cherry-pick them to the branch.

I'm merging this.

**Pull request merged**
