### PR TITLE
BACKENDS: CURL: Fix Deprecated API Warnings By Removing Usage on v7.4…

### PR DESCRIPTION
**Pull request by digitall**
The current usage of libCURL for backend networking causes a deprecation warning. This fixes this by using the older deprecated API only for libCURL earlier than v7.45.0.

Since this was released in October 2015 and has a large number of issues, we may want to consider enforcing a minimum version in future, but this fixes the immediate issue:
https://curl.se/docs/vuln-7.45.0.html

### CODE REVIEW

**Review by LittleToonCat — APPROVED** [review]
Looks good to me, thank you!

**Comment by sev-** [comment]
Thank you!

**Comment by lephilousophe** [comment]
In fact, the fallback was intended to take into account the case where we build with a new header but run with an old version.
Initially, this commit was done to fix OpenPandora build.

**Comment by digitall** [comment]
@lephilousophe : Ugh. I think this can stay as-is since the OpenPandora build environment should be set to build with the same library / header that it runs with. If this does cause an issue, the build toolchain / environment should be fixed.

**Comment by lephilousophe** [comment]
That was more about the case where we build dynamically and the user has an older version of libcurl but it's true I don't see any other use.
Anyway, I plan to kill OpenPandora buildbot soon.

**Pull request merged**
