### PR TITLE
SCUMM: [RFC] Add feature flag for the "Ultimate Talkie" version of MI1/MI2

### PR DESCRIPTION
**Pull request by eriktorbjorn**
There are so many workarounds where we either want to make sure it's not the "Ultimate Talkie" version or that it is, that it's much nicer to have a feature flag than having to strcmp() the variant.

Note that I have not yet tested that the workarounds still work as intended.

| Tested By | Workaround |
| --- | --- |
| | Some "voice mode" setting in input.cpp |
| eriktorbjorn<br>dwatteau | MI1: The colors of the "important notice" about the sleeping dogs. |
| eriktorbjorn | MI2: Copy protection screen. |
| eriktorbjorn<br>dwatteau | MI1: Jolly Roger flag. |
| eriktorbjorn<br>dwatteau | MI1: Inventory object colors, e.g. at Stan's. |
| eriktorbjorn<br>dwatteau | MI2: Glitch with captain Dread's head. |
| eriktorbjorn<br>dwatteau | MI2: Selling back the hubcap. |
| dwatteau | MI2: Missing spitting contest audio. |
| dwatteau | MI2: Dread going back to Scabb Island when you have the full map. |
| dwatteau | MI1: Lemonhead "Oooh, that's nice." WaitForMessage(). |
| eriktorbjorn<br>dwatteau | MI1: Ghost priest text color. |
| eriktorbjorn<br>dwatteau | MI1: Navigator head text color. |

(I think that's all.)

### CODE REVIEW

**Comment by bluegr** [comment]
Looks to be quite a straightforward change. Do all these workarounds need to be tested again?

**Comment by eriktorbjorn** [comment]
> Do all these workarounds need to be tested again?

To the extent that I want to verify that the talkie versions are excluded/included when they should be. It's easy to mess up. The workarounds themselves should work just as well as before, of course.

**Comment by eriktorbjorn** [comment]
I think I've checked the ones I know right away what they're about.

That still leaves a little over half of them. :-)

**Comment by dwatteau** [comment]
This PR is a good idea, looks good to me.

I'll recheck them again just in case, too.

**Comment by AndywinXp** [comment]
Hiya! I can't check it right now, but if you press CTRL-T and it shows a banner message with either "Voice only" "Text only" "Voice & Text" (or something like that) in the Ultimate Talkies of MI1 and MI2, then we're good!
(And codewise, it looks correct)

**Comment by bluegr** [comment]
Any update on this @eriktorbjorn?

**Comment by dwatteau** [comment]
I think we can merge this.

I'm working on a new small enhancement for Monkey1 and I'll test all its existing enhancements again just to be sure (probably tomorrow). So everything will be tested twice and that's probably very reasonable since the change itself is mostly mechanical.

**Comment by dwatteau** [comment]
So I've tested the following enhancements again, with this PR:

MI1: The colors of the "important notice" about the sleeping dogs.
MI1: Jolly Roger flag.
MI1: Inventory object colors, e.g. at Stan's.
MI1: Lemonhead "Oooh, that's nice." WaitForMessage().

and they all seem to behave as expected in the Ultimate and non-Ultimate releases.

**Comment by bluegr** [comment]
Thanks! Now  the detection tables have a conflict. Can you please rebase that file, so that we can merge this?

**Comment by eriktorbjorn** [comment]
> Thanks! Now the detection tables have a conflict. Can you please rebase that file, so that we can merge this?

I don't know? What is the actual correct way of doing that, because ever time I've tried in the past Git has done terrible things to me or my version history.

**Comment by dwatteau** [comment]
> > Thanks! Now the detection tables have a conflict. Can you please rebase that file, so that we can merge this?
> 
> I don't know? What is the actual correct way of doing that, because ever time I've tried in the past Git has done terrible things to me or my version history.

That should do it. I'm considering that `origin` is the name of your `scummvm/scummvm` upstream, but adjust that if you've called it `upstream` or something else.

```sh
git fetch origin # make sure that the latest upstream changes are known to Git
git checkout scumm-talkie-flag # go back to this PR branch
git pull --rebase origin master # rebase your branch on top of the latest upstream changes
$EDITOR engines/scumm/detection_tables.h # fix the conflicts by hand (pick the upstream, except for the ultimate talkie lines, where you need to merge both changes)
git add engines/scumm/detection_tables.h # tell Git that you're done with your conflicts resolution for this file
git rebase --continue # finish the rebase
git log # check that everything looks OK
git push --force # force push your branch, since the rebase created non-forward changes
```

(unfortunately, the Git Fork GUI hasn't been ported to Linux yet, but it's very nice, otherwise)

**Comment by eriktorbjorn** [comment]
Thanks! I hope I did it right.

**Comment by bluegr** [comment]
Thanks for your work @eriktorbjorn! And thanks for the detailed instructions @dwatteau!

This is good to merge now. Well done!

**Pull request merged**
