### PR TITLE
SHERLOCK: added yet another german version for scalpel

### PR DESCRIPTION
**Pull request by mgerhardy**

### CODE REVIEW

**Comment by bluegr** [comment]
Where did you get this version from?

**Comment by mgerhardy** [comment]
If only I could answer this. I found it on one of my old disk-to-cdrom collections. But I throw away all my boxes (I know.... silly from todays standpoint)

**Comment by dreammaster** [comment]
Thanks as well. What kind of CD collection is it? Is this an official game compilation disc? If so, the publisher details should be on it, I imagine.

**Comment by mgerhardy** [comment]
No, it's a private one where I "rescued" my box floopy discs. All I know is that it must have been a box version on 3,5" floppy discs. Otherwise it should not have been on that cdrom.

**Pull request merged**
