### PR TITLE
CONFIGURE: Add amigaos to the plugins family

### PR DESCRIPTION
**Pull request by raziel-**
I would have used the linux entry, but -ldl does not exist on amigaos4 and i still need -use-dyn-ld

### CODE REVIEW

**Comment by raziel-** [comment]
This is just for my understanding, as i'm completely puzzled as to what the correct usage of linker flags is now.
This
PRE_OBJS_FLAGS  := -Wl,-export-dynamic -Wl,-whole-archive
is sometimes done with one dash after the -Wl, and sometimes with two
PRE_OBJS_FLAGS  := -Wl,--export-dynamic -Wl,--whole-archive

I guess both work?
But why is that?
Is ld smart enough to pick the one it knows or doesn't it matter at all how many dashes there are?

**Comment by sev-** [comment]
Well, as the ld(a) manual states:

> For options whose names are multiple letters, either one dash or two can precede the option name; for example, -trace-symbol and --trace-symbol are equivalent.

So, that is just a matter of personal preference.

**Comment by raziel-** [comment]
@sev-

Awesome, thanks for the answer

**Comment by sev-** [comment]
Merging. I'll be branching today, so it is important to have these things merged before that.

**Pull request merged**
