### PR TITLE
ANDROID: Add an on-screen menu button

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by bluegr** [comment]
Could you please add a screenshot?

**Comment by ccawley2011** [comment]
> Could you add a screenshot please?

Screenshot_2021-06-18-12-06-52

**Comment by antoniou79** [comment]
I'm ok with the addition of an extra icon for menu, though, as far as I can tell, it will be only for bringing up the in-game ScummVM Global Main Menu, and will therefore not differentiate between long and short press as is the behavior intended for the system Menu button on Android (for those few remaining or old devices that still have a Menu button). That's ok, since our Menu long press default action was to bring up the keyboard, and there's the other icon for that already.

However, we should update the documentation about the new icon too, so as not to confuse the user (section Controls / Default control mapping):
https://docs.scummvm.org/en/latest/other_platforms/android.html
Ideally the update should be integrated in this PR. 

This PR also changes the format for the keyboard icon (?) to xml. @ccawley2011 could you explain this change? It seems like it's using vector graphics, which should be the best way to deal with scaling. But is it supported on older devices?

**Comment by sev-** [comment]
This is an excellent addition. And while it seems to be a duplicating behaviour, it is (a) more user-intuitive (b) lets work on devices where the back button is virtual.

Our Android port controls are not intuitive at this moment, unfortunately. It would be awesome to have that idea of an initial wizard explaining controls present, but that is a long shot.

Merging this happily.

**Comment by sev-** [comment]
And yes, the documentation changes need to follow.

**Pull request merged**
