### PR TITLE
BLADERUNNER: Add detection for Italian version

### PR DESCRIPTION
**Pull request by Zibri**
Added italian version detection

### CODE REVIEW

**Comment by rootfather** [comment]
Thanks Zibri. 

Please note that currently the commit message doesn't follow our guidelines. I recommend using something like "BLADERUNNER: Add detection for Italian version".

**Comment by Zibri** [comment]
Why this has not been merged yet? I am not a github guru..

**Comment by Zibri** [comment]
I deleted the fork. I really HATE GITHUB.

How the hell do I do this correctly???

**Comment by raziel-** [comment]
@Zibri
See comment from @rootfather

You need to change the name of your PR to something like this:

BLADERUNNER: Added Italian Version Detection

**Comment by rootfather** [comment]
And not only the name of the PR, but also the commit message itself should be changed according to our guidelines.

**Comment by digitall** [comment]
Closed via manual cherry-pick and commit fixup as a1b9b0c0a1943ae7c1fe4d66ec72801b4dc17d81

**Pull request closed without merging**
