### PR TITLE
COMMON: updates to built-in help dialog content

### PR DESCRIPTION
**Pull request by cadihowley**

### CODE REVIEW

**Comment by cadihowley** [comment]
@sev- I've tried something - I removed the screenshots in the Android "Adding Games" help tab, I found it wasn't displaying very well on my phone. But I did add a link to the docs for anyone who needs more. What are your thoughts? I guess it would be fine on a tablet/TV/bigger devices running android... is that something we could include or not include depending on screen size?

I've also generally simplified the content, hopefully the formatting is all correct as I'm not sure how to build it to have a look. I'll have a think about what else we could add, but won't be able to work on it for at least another week unfortunately

**Comment by sev-** [comment]
Could you please elaborate a bit regarding screenshots not displaying very well? I wanted to add them there specifically so they are more visual. Maybe we could just redo them and make them better?

Also, in parallel, I am working on adding table rendering so I can make the keyboard shortcuts screen more neat.

**Comment by sev-** [comment]
You have to rebase your fork, because now you included someone else's commits

**Comment by cadihowley** [comment]
@sev- 
I think I've fixed my branch now...

As discussed on Discord, screenshots have been amended and added back in - also I've updated the Android documentation for consistency. 

I took the liberty of doing the same for the popup message you get when you first run on Android - can I confirm that Markdown formatting works in this instance too? If not I'll need to make a couple of changes. Otherwise I think this should be ready to merge, if you're happy with it all

**Comment by sev-** [comment]
Awesome!

**Pull request merged**
