### PR TITLE
GRAPHICS: Use emmintrin.h for SSE2 intrinsics

### PR DESCRIPTION
**Pull request by ccawley2011**
This just includes the SSE2 intrinsics without the ones from later CPUs.

### CODE REVIEW

**Comment by bluegr** [comment]
Here's a thread about all the instristic related includes:
https://stackoverflow.com/questions/11228855/header-files-for-x86-simd-intrinsics/11228864#11228864

The change looks good, according to that thread

**Comment by sev-** [comment]
The branch needs to be rebased.

**Comment by elasota** [comment]
This PR should be closed, the same change was already rolled into PR #5581.

**Comment by bluegr** [comment]
> This PR should be closed, the same change was already rolled into PR #5581.

That is true for graphics/blit/blit-sse2.cpp, but the same change needs to be applied to engines/ags/lib/allegro/surface_sse2.cpp as well, which is the other part of this PR

**Comment by bluegr** [comment]
Thanks for your work!
I've removed the change to blit-sse2.cpp, will commit the change to surface_sse2.cpp in AGS

**Pull request merged**
