### PR TITLE
KEYMAPPER: Introduce custom engine actions

### PR DESCRIPTION
**Pull request by bgK**
Custom engine actions are a new type of event the Keymapper can produce.
When an engine declares its keymap, it can declare it wants to receive
custom action events when the corresponding key is pressed, instead of
the remapped hardware input events.

This system allows:
* Key bindings to be specified only once when declaring the keymap,
  instead of twice (when handling the events).
* To truly rebind keys in the keymap dialog. When using traditional
  event mapping, the keymapper remaps the user keypress to the keypress
  expected by the game engine to perform the action. However, the engine
  still accepts the original keys.

The new concept of 'standard actions' defines a set of engine actions
that are commonly available in the games supported by ScummVM. Backends
can define default bindings for the standard actions to hardware
specific input devices.

Of course, this scheme cannot be applied everywhere. Some engines have script-managed input handling. However in the game engines with engine-managed input, I think it is a very nice improvement.

As an example, the Riven engine is updated to use custom actions.

This PR builds on top of #2009, #2012 and #2015, and includes their commits.

### CODE REVIEW

**Comment by sev-** [comment]
Could you please briefly describe how to set up these actions for a random engine? What is the format and approach?

**Comment by bgK** [comment]
> Could you please briefly describe how to set up these actions for a random engine? What is the format and approach?

To define a keymap for a target, the `MetaEngine::initKeymap(const char *target)` method needs to be implemented. If keymap is found for a target then a default (not very good) keymap is used.

A keymap is made of actions. Using the remap dialog users can associate these actions to events generated by the backends. When defining actions engine developers decide what happens when the action is executed. There two options (hybrids are possible):
* Generate events that match what the existing event handling in the engine expects. That's easy to do. Just declare the keymap and it's done. There are no other changes to do to the engine. However there are issues with this approach. An user who changes the default binding for an action does not expect the original binding to still work. Depending on how the engine is structured this also may cause key handling to be defined twice. Once in the keymap, and once in the event loop.
* Generate custom actions events with meaning private to the engine.

Example when reusing the existing input handling:
```c++
Common::Keymap *MyEngine::initKeymap(const char *target) {
	Keymap *engineKeyMap = new Keymap(Keymap::kKeymapTypeGame, "my-engine");

	Action *act;

	act = new Action("TALK", _("Talk"));
	act->setKeyEvent(KEYCODE_t);
	act->addDefaultInputMapping("t");
	act->addDefaultInputMapping("JOY_X");
	engineKeyMap->addAction(act);

	act = new Action("USE", _("Use"));
	act->setKeyEvent(KEYCODE_u);
	act->addDefaultInputMapping("u");
	act->addDefaultInputMapping("JOY_Y");
	engineKeyMap->addAction(act);
}

void MyEngine::doInput() {
	Common::Event event;
	while (_system->getEventManager()->pollEvent(event)) {
		switch (event.type) {
			case Common::EVENT_KEYDOWN:
				switch (event.kbd.keycode) {
					case Common::KEYCODE_t:
						doTalk();
						break;
					case Common::KEYCODE_u:
						doUse();
						break;
				}
		}
	}
}
```

Example when using custom engine actions:
```c++
enum MyEngineAction {
	kMyActionTalk,
	kMyActionUse
}

Common::Keymap *MyEngine::initKeymap(const char *target) {
	Keymap *engineKeyMap = new Keymap(Keymap::kKeymapTypeGame, "my-engine");

	Action *act;

	act = new Action("TALK", _("Talk"));
	act->setCustomEngineActionEvent(kMyActionTalk);
	act->addDefaultInputMapping("t");
	act->addDefaultInputMapping("JOY_X");
	engineKeyMap->addAction(act);

	act = new Action("USE", _("Use"));
	act->setCustomEngineActionEvent(kMyActionUse);
	act->addDefaultInputMapping("u");
	act->addDefaultInputMapping("JOY_Y");
	engineKeyMap->addAction(act);
}

void MyEngine::doInput() {
	Common::Event event;
	while (_system->getEventManager()->pollEvent(event)) {
		switch (event.type) {
			case Common::EVENT_CUSTOM_ENGINE_ACTION_START:
				switch ((MyEngineAction)event.customType) {
					case kMyActionTalk:
						doTalk();
						break;
					case kMyActionUse:
						doUse();
						break;
				}
		}
	}
}
```

Obviously the second approach is hard / impossible to use for engines where input handling is script-driven. It's up to the engine developer to choose which is the best in each specific context.

**Comment by bluegr** [comment]
After merging the changes in PR #2012, this can no longer be merged cleanly. Could you please fix the conflicts?

**Comment by bgK** [comment]
Merged manually as df4bf6556cb4cba62f390b1d0089c641c8e7696e...0995f40677521268476785c617ff97b5b46c2413

**Comment by bluegr** [comment]
Nice work!

Some documentation will be needed in our wiki for the new user actions feature

**Pull request closed without merging**
