### PR TITLE
Sword25 video fix

### PR DESCRIPTION
**Pull request by ottogin**
SWORD25: Fix frozen/flickering title menu movie
Fixes bug #6978.
And then corrected code formatting..

### CODE REVIEW

**Comment by raziel-** [comment]
I can confirm this fixes bug #7062 (and related #6978) for me

**Comment by sev-** [comment]
The bugfix is great, however, there is a mess with the commits. They must be squashed into one.

**Comment by sev-** [comment]
@raziel- Does it by chance also fix #7063?

**Comment by raziel-** [comment]
@sev- 

I checked of course, but unfortunately not.
There is still this short "hiccup" in sound and video playback and after that the video playback is stuck.

**Comment by sev-** [comment]
Thanks for squashing. Merging now.

**Comment by ottogin** [comment]
lordhoto, Ok =) Thank for the piece of advice

**Pull request merged**
