### PR TITLE
SCI: Script patch for LB2 crate room bug #10701

### PR DESCRIPTION
**Pull request by sluicebox**
Fixes a lockup in the original game

### CODE REVIEW

**Comment by dafioram** [comment]
Nice work.

I've tested that this resolves the bug.

Can you update your comments so it includes the acts that this occurs in (Act 5?). Can you brake up your two paragraphs into more so that it is easier to read.  Like after the first sentence, Can you add which rooms this concerns in the comments?

How do you know that this also happens in the original? Viewing the scripts/disassembly or actually playing the game (dosbox)?

**Comment by sluicebox** [comment]
I've updated the comments. Yes, I confirmed the bug in the original in dosbox.

**Comment by dafioram** [comment]
Can you combine your two commits into one (Using rebase interactive or amend)? You will have to force push, but that is fine.

**Comment by digitall** [comment]
@dafioram : This looks good now. OK to merge?

**Comment by dafioram** [comment]
I think it is fine. it might be good to let some time pass in case @bluegr wants a chance to look at this.

**Comment by digitall** [comment]
@dafioram : OK Thanks. Better to do an explicit request for review from him though, rather than just hope he sees this. Will do that. If he is happy / indifferent, we can then merge.

**Comment by bluegr** [comment]
Nice work on the patch!

I really liked the way you used the eq operator here - basically, you add its result (0 or 1).

I reviewed your patch, and tested your changes. It all works fine. Well done, merging

**Comment by digitall** [comment]
@sluicebox : Does this patch fix this bug as well, or is this a different script issue?
https://bugs.scummvm.org/ticket/10702

**Comment by sluicebox** [comment]
That one is different. I haven't looked closely at it but it's in a different room and unrelated.

**Pull request merged**
