### PR TITLE
GOB: sorted POTFILES

### PR DESCRIPTION
**Pull request by BJNFNE**

### CODE REVIEW

**Comment by bluegr** [comment]
What is the sorting used here? Wouldn't it be simpler to sort these alphabetically?

**Comment by bluegr** [comment]
> > What is the sorting used here? Wouldn't it be simpler to sort these alphabetically?
> 
> So First sort after Numbers and then After the Alphabet?

No, because "v" is after "g" and "p". So, alphabetical order would be like this:

    engines/gob/inter_geisha.cpp
    engines/gob/inter_playtoons.cpp
    engines/gob/inter_v2.cpp
    engines/gob/inter_v5.cpp
    engines/gob/inter_v7.cpp

**Comment by BJNFNE** [comment]
updated

**Comment by BJNFNE** [comment]
@coderabbitai review

**Comment by bluegr** [comment]
Thanks!

**Pull request merged**
