### PR TITLE
AGS: Update engine to 3.6.1.29

### PR DESCRIPTION
**Pull request by tag2015**
This big PR includes most of the commits relevant to ScummVM to bring the AGS engine up-to-date
with the latest stable release.

The skipped commits are related to:
* Resource Cache: this feature was introduced to consolidate the Sprite/Texture/Sound caches, but scummvm uses its own code for sound playback and the Texturecache is only used for the HW accelerated renderers (which we don't support). The Spritecache is already implemented
* DirectoryIterator/RecursiveIterator - these are related to file access and ScummVM uses its own code
* Loading external plugins (since we don't support those)

There are still about a dozen commits that I need to review and add (related to the mouse and input 
queue refactoring), but those are not really that urgent and the PR can already be merged as is.
NOTE: The commits don't match upstream chronologically because I initially skipped some commits that I eventually
had to implement.

Some of the 3.6.1 games that are now supported (screenshots captured in ScummVM):

Stranger in Utopia
scummvm-strangerutopia-00001

The Phantom Fellows (just released!)
scummvm-phantomfellows-fallback-00000

Old Skies (for the betatesters...)
scummvm-oldskies-00004

It takes 2 to tangle
scummvm-takes2tangle-00005

### CODE REVIEW

**Comment by criezy** [comment]
That's an impressive amount of work 😮 
@tag2015 is there also some changes you would like me to look at in particular?

**Comment by tag2015** [comment]
> That's an impressive amount of work 😮 @tag2015 is there also some changes you would like me to look at in particular?

Hey @criezy , nothing in particular (I realize it's a big PR to review), but if you want to try building the PR and test some old games, that'd be great!
Besides the games I indicated, I only briefly tested the blackwell games, unavowed and some freewares

**Comment by tag2015** [comment]
Thanks @criezy , I fixed the operand and the missing override, I'll have a look at the other warnings later

**Comment by tag2015** [comment]
@criezy should be ok now, do you still get clang warnings?

**Comment by bluegr** [comment]
@tag2015 overall, very nice work!

Just a reminder to submit the changes done in this PR to the AGS project :)

**Comment by criezy** [comment]
Nice work. Only two warnings remaining, both in the age_controller plugin.
```
engines/ags/plugins/ags_controller/ags_controller.cpp:47:12: warning: declaration requires a global destructor [-Wglobal-constructors]
Controller ctrlInterface;
           ^
engines/ags/plugins/ags_controller/ags_controller.cpp:48:11: warning: declaration requires a global destructor [-Wglobal-constructors]
ConReader ctrlReader;
          ^
```
For those moving them to the `Globals` class doesn't seem totally right, but maybe they can be moved as member of the `AGSController` class? The code compiles if I do that, but I don't have Perfect Tides to check that it works.

**Review by bluegr — APPROVED** [review]
Nice work! Overall, this is in a good state to be merged :)

**Comment by tag2015** [comment]
Sorry for the force push, I rebased to current master, should be ready for merge now

**Comment by bluegr** [comment]
Thanks!

**Pull request merged**
