### PR TITLE
GUI: fix compilation error.

### PR DESCRIPTION
**Pull request by fedor4ever**
And style fix.

I wonder how long that error lives?
GCC output:
/Symbian/Projects/SDL/scummvm/gui/KeysDialog.cpp: In constructor 'GUI::KeysDialog::KeysDialog(const Common::U32String&)':
/Symbian/Projects/SDL/scummvm/gui/KeysDialog.cpp:62:25: error: no matching function for call to 'GUI::ListWidget::setList(GUI::ListWidget::StringArray&)'
  _actionsList->setList(l);
                         ^
In file included from /Symbian/Projects/SDL/scummvm/gui/KeysDialog.h:32:0,
                 from /Symbian/Projects/SDL/scummvm/gui/KeysDialog.cpp:23:
/Symbian/Projects/SDL/scummvm/gui/widgets/list.h:101:7: note: candidate: void GUI::ListWidget::setList(const U32StringArray&, const ColorList*)
  void setList(const U32StringArray &list, const ColorList *colors = nullptr);
       ^~~~~~~
/Symbian/Projects/SDL/scummvm/gui/widgets/list.h:101:7: note:   no known conversion for argument 1 from 'GUI::ListWidget::StringArray {aka Common::Array<Common::String>}' to 'const U32StringArray& {aka const Common::Array<Common::U32String>&}'

### CODE REVIEW

**Comment by sev-** [comment]
Shouldn't KeysDialog be killed completely and the currently implemented Keymapper is used?

**Comment by fedor4ever** [comment]
That be done in migration from actions system, right?

**Comment by sev-** [comment]
I do not understand your question. Old Symbain keymapper should be better fully removed and the global keymapper used. Otherwise, in the GUI there will be two keymappers.

**Comment by fedor4ever** [comment]
When I asked, I thought about that pr - https://github.com/scummvm/scummvm/pull/2367, which deprecates action system for symbian.

**Comment by sev-** [comment]
Yes, see this warning: https://github.com/scummvm/scummvm/blob/master/gui/KeysDialog.cpp#L27

So, instead of fixing the compilation, this file should be just removed completely. It was not done in the initial PR because of the build subsystem for Symbian.

**Comment by fedor4ever** [comment]
Other files with that warnig should be removed too?

**Comment by fedor4ever** [comment]
Other files with that warnig should be removed too?

**Comment by fedor4ever** [comment]
Commit updated. Rewiew ASAP, please.

**Comment by sev-** [comment]
gui/KeysDialog.* files are still there. You just ignored my comments.

**Comment by fedor4ever** [comment]
@sev- Done!

**Comment by fedor4ever** [comment]
pr #2709 SYMBIAN: Global Main Menu called with asterisk depends now from that pr. So I add pr #2709 changes here. Feel free to close #2709 after merge that pr.

**Comment by sev-** [comment]
This requires rebase after another PR merge

**Comment by sev-** [comment]
@fedor4ever Any updates?

**Comment by sev-** [comment]
Okay, I merged it manually.

**Comment by sev-** [comment]
And of course, much more work required as this particular PR broke the whole translation subsystem, and bunch of other remnants of the feature stayed uncleaned.

Very low-quality work.

**Pull request closed without merging**
