### PR TITLE
MORPHOS: Added CAMD MIDI driver support

### PR DESCRIPTION
**Pull request by BeWorld2018**
Merge with AmigaOS4 camd.cpp

To confirm if Raziel is OK

### CODE REVIEW

**Comment by raziel-** [comment]
Need to test if compiler errors are still there.

Unfortunately that will take some time, back at work

**Comment by BeWorld2018** [comment]
no problem :-)

**Comment by raziel-** [comment]
@BeWorld2018 

I´m afraid, i still get some errors on compiling
[Bug.txt](https://github.com/scummvm/scummvm/files/5918237/Bug.txt)

**Comment by BeWorld2018** [comment]
it's possible to view define on g++ ?
(on config.mk file put VERBOSE_BUILD = 1)

else i can create new file just for MorphOS and dont touch your part.

**Comment by raziel-** [comment]
@BeWorld2018

Are you looking for this line (verbose)?
I can do a complete verbose compile upto the errors, if needed.

mkdir -p backends/midi/.deps
g++ -MMD -MF "backends/midi/.deps/camd.d" -MQ "backends/midi/camd.o" -MP -Wall -std=gnu++11  -U__STRICT_ANSI__ -W -Wno-unused-parameter -Wno-empty-body -fno-operator-names -std=c++11 -pedantic -Wno-long-long -Wno-format -O3 -Wuninitialized -I/SDK/local/common/include/freetype2 -Wno-long-long -Wno-multichar -Wno-unknown-pragmas -Wno-reorder -Wpointer-arith -Wcast-qual -Wshadow -Wnon-virtual-dtor -Wwrite-strings -fno-exceptions -fcheck-new -DHAVE_CONFIG_H -DRELEASE_BUILD -DPPC_TARGET -DSDL_BACKEND -DDATA_PATH=\"/usr/local/share/scummvm\" -DPLUGIN_DIRECTORY=\"/usr/local/lib/scummvm\" -DENABLE_SCI=STATIC_PLUGIN -I. -I. -I./engines -I/SDK/local/newlib/include/SDL2 -D_REENTRANT             -I/SDK/local/newlib/include   -c backends/midi/camd.cpp -o backends/midi/camd.o

Does your code feature any additions, fixes, speed-ups or even readability enhancements?
I wouldn't want to miss out of those.

Then again i don't know how maintainable the code will be in the future, if it merges MorphOS and AmigaOS(4).
There are only few errors left, i'm sure you can tackle them (sorry to be of so little help)

**Comment by BeWorld2018** [comment]
Ok dont worry, i close this PR and i create a specfic MorphOS camd.
thanks

**Comment by raziel-** [comment]
Sorry, work still delays things.

Will get back to you once I'm back home

**Comment by raziel-** [comment]
Checked now, compiles again on AmigaOS4 and MIDI output is still working here too.

Sorry again for the awful long delay

**Comment by BeWorld2018** [comment]
Thanks, ScummVM team.. you can merge if ok ok for you. Thanks

**Comment by criezy** [comment]
@BeWorld2018 Your second commit message does not respect our commit message formatting guidelines (it is missing the subsystem prefix). Once this is fixed this can be merged.
Or should the two commits be squashed? In which case this does not matter.

**Comment by BeWorld2018** [comment]
> @BeWorld2018 Your second commit message does not respect our commit message formatting guidelines (it is missing the subsystem prefix). Once this is fixed this can be merged.
> Or should the two commits be squashed? In which case this does not matter.

I "amend" my commit, but you can create only one commit on master if you want.

**Comment by criezy** [comment]
Thank you. I ended up merging manually to squash, rebase, and remove the merge commit.

**Pull request closed without merging**
