### PR TITLE
JANITORIAL: HPL1: Fix typos in code

### PR DESCRIPTION
**Pull request by raziel-**
Separate PR since it touches code

QUESTION, please:

Angelscript, Newton and TinyXML are upstream libraries (iiuc)
Are typo fixes for those desirable in-tree?
Or should i drag them to their up-stream versions (not sure if all of them are still maintained, though)?

Thank you

### CODE REVIEW

**Comment by raziel-** [comment]
is there still a conflict?

**Comment by raziel-** [comment]
ok, help?

if i resolve the remaining "conflict" i reintroduce the typo and that will break building

**Comment by raziel-** [comment]
@bluegr 

thank you

**Comment by bluegr** [comment]
@raziel- You're welcome :)
Awaiting for the builds to finish, before squashing
Don't make changes to external libraries, otherwise they'll be lost if these libraries are updated in the future

**Comment by raziel-** [comment]
i see.
so rather change them in their original repo

**Comment by bluegr** [comment]
Thanks! Squashed

**Pull request merged**
