### PR TITLE
SYMBIAN: Minor fixes for comments and code.

### PR DESCRIPTION
**Pull request by huhungahuru**
Most of the corrections are from comments, a minor fix has been made to the code (Only a few lines were ordered).
These fixes apply to most Symbian files.

### CODE REVIEW

**Comment by digitall** [comment]
@huhungahuru : I assume that you are resubmitting this for review as you have finished the required changes. Firstly, could you use interactive rebase i.e. rebase -i and force push to remove the various merge commits and squash the various comment only changes into a single commit for SYMBIAN/SRC, SYMBIAN/BUILDER, KEYMAPPER, SDL,  LOG etc.

**Comment by huhungahuru** [comment]
I don't have the knowledge to do that for now.

**Comment by digitall** [comment]
@huhungahuru : You should read the relevant parts of the git book on how to use rebase and branches to clean up a commit history into a set of logical changes prior to Pull Request:
https://git-scm.com/book/en/v2/Git-Branching-Rebasing

I have cleaned up your Pull Request commits and reordered them so that the SDL, LOG and KEYMAPPER change commits are separately from the SYMBIAN specific changes which I have squash down to a smaller number of logical commits and pushed this to this PR branch (sending a PR gives people with push access to the upstream repository the ability to edit your branch which you pushed from... hence why you should use a feature branch).

I did not specifically close this PR, but I think since you did this from the master branch, when I editted your commits it has caused Github to close this. I can't reopen this so you will need to resubmit this from the new fixed up commit as a new branch.

**Comment by digitall** [comment]
@huhungahuru : Ah, I think the push caused the reset of your master to even with scummvm:scummvm. I will push the fixed up commits to a branch and open a new PR... https://github.com/scummvm/scummvm/pull/3170

**Pull request closed without merging**
