### PR TITLE
DOCS: GSOD Documentation Portal 

### PR DESCRIPTION
**Pull request by cadihowley**

### CODE REVIEW

**Comment by mgerhardy** [comment]
This needs a rebase as some other commits slipped in. If you need help with it, please let me know

**Comment by cadihowley** [comment]
> This needs a rebase as some other commits slipped in. If you need help with it, please let me know 

I was trying to sort that out today but ran into some technical difficulties.... I would love some help!

**Comment by mgerhardy** [comment]
If you could give me write access to your repository, I could directly do that in your repo.

**Comment by cadihowley** [comment]
> If you could give me write access to your repository, I could directly do that in your repo.

Done!

**Comment by mgerhardy** [comment]
Rebase is done - please verify that nothing is missing. I've made a backup here: https://github.com/mgerhardy/scummvm/commits/doc-portal-2-backup

**Comment by cadihowley** [comment]
@mgerhardy That looks fine to me. I really appreciate your help, thanks again!

**Comment by Mataniko** [comment]
Thanks, merging!

**Pull request merged**
