### PR TITLE
COMMON: Add SeekableReadStreamEndianWrapper

### PR DESCRIPTION
**Pull request by ccawley2011**
This is intended as a replacement for `Common::SeekableSubReadStreamEndian` - since most engines using it don't actually need a partial substream, the new class is simpler and avoids unpredictability when directly accessing the parent stream.

There are a few places in the Director, Kyra and mTropolis that do need a substream, however since adapting those cases is a bit more involved, I've simply marked the old class as deprecated for now.

### CODE REVIEW

**Comment by bluegr** [comment]
I'm confused... why do we need a wrapper, when we can use `SeekableReadStreamEndian` directly?
All these cases that have been changed can just be adjusted to use SeekableReadStreamEndian

**Comment by ccawley2011** [comment]
> I'm confused... why do we need a wrapper, when we can use `SeekableReadStreamEndian` directly? All these cases that have been changed can just be adjusted to use SeekableReadStreamEndian

`SeekableReadStreamEndian` on it's own doesn't implement all of the required stream functions, so using a wrapper allows it to be easily used with other streams without requiring them to inherit from it.

**Comment by bluegr** [comment]
> > I'm confused... why do we need a wrapper, when we can use `SeekableReadStreamEndian` directly? All these cases that have been changed can just be adjusted to use SeekableReadStreamEndian
> 
> `SeekableReadStreamEndian` on it's own doesn't implement all of the required stream functions, so using a wrapper allows it to be easily used with other streams without requiring them to inherit from it.

In this case, since the implementation of these functions is pretty basic, it would be easier IMHO to create a default implementation for the required stream functions (but still allow them to be overriden), instead of creating another wrapper.

**Comment by ccawley2011** [comment]
> In this case, since the implementation of these functions is pretty basic, it would be easier IMHO to create a default implementation for the required stream functions (but still allow them to be overriden), instead of creating another wrapper.

That's not really doable for streams created via the FileSystem or Archive APIs, though.

**Comment by sev-** [comment]
I understand the need, as this wrapper will avoid potential problems with side effects of seeking of the parent stream.

If there are no objections, I'll merge it in couple of days.

**Comment by sev-** [comment]
OK, merging.

**Pull request merged**
