### PR TITLE
BACKENDS: OPENGL: Support aspect ratio correction for Hercules games

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by bluegr** [comment]
@ccawley2011 Are you sure that a Hercules resolution will fit into a 4:3 ratio? Hercules has a resolution of 720×350, which yields an aspect ratio of 2.07:1

https://nerdlypleasures.blogspot.com/2014/02/monochrome-hercules-graphics-aspect.html?m=1#:~:text=The%20Hercules%20Graphics%20Card%20is,pixels%2C%20is%202.07%20%3A%201.

**Comment by ccawley2011** [comment]
Wikipedia suggests that it should be corrected to 4:3, which should give a corrected resolution of 720x540: https://en.wikipedia.org/wiki/Hercules_Graphics_Card

The article you linked instead suggests 720x435 instead, with an aspect ration of 1.66:1. I can get screenshots of both resolutions for comparison.

**Comment by bluegr** [comment]
> Wikipedia suggests that it should be corrected to 4:3, which should give a corrected resolution of 720x540: https://en.wikipedia.org/wiki/Hercules_Graphics_Card
> 
> The article you linked instead suggests 720x435 instead, with an aspect ration of 1.66:1. I can get screenshots of both resolutions for comparison.

Yes, screenshots would help a lot :) Thanks!

**Comment by ccawley2011** [comment]
OK, here are some screenshots without correction, with the correction applied in this PR, and with correction to a 5:3 aspect ratio.

Maniac Mansion:

| No correction | Corrected to 4:3 | Corrected to 5:3 |
| --- | --- | --- |
| scummvm-maniac-v2-demo-00000 | scummvm-maniac-v2-demo-00001 | scummvm-maniac-v2-demo-00002  |

Laura Bow:

| No correction | Corrected to 4:3 | Corrected to 5:3 |
| --- | --- | --- |
| scummvm-laurabow-demo-00000 | scummvm-laurabow-demo-00001 | scummvm-laurabow-demo-00002 |

**Comment by athrxx** [comment]
When comparing the visuals, you also want to keep in mind what the engines actually do to the data. SCUMM v1/2 does a horizontal and vertical 2x scaling of the main virtScreen (the one with the actual scene graphics). SCI 0 scales only 1,5x vertically, but 2x horizontally. So that's why MM seems to fit best into 5:3, while LB might fit better into 4:3...

**Comment by bluegr** [comment]
So what can we do about the games that need a 4:3 vs 5:3 aspect ratio correction?
We could proceed with this PR to handle aspect correction in all games as 4:3, and then perform additional steps in a separate PR for the 5:3 ones

**Comment by athrxx** [comment]
Yes, the PR is fine per se, since it just enables the aspect ratio correction for Hercules which is currently disabled. It can be fine tuned later... (I'd probably go for the 5:3 ratio, but that may be one of these topics where everyone has a different opinion)

**Pull request merged**
