### PR TITLE
Update AndroidManifest.xml

### PR DESCRIPTION
**Pull request by Raa007**
Remove second activity in MAIN filter causing black screen lockup on some Android devices.

### CODE REVIEW

**Comment by digitall** [comment]
@sev- : This has been open for several months without action. It seems a pretty small change and self-contained change, so do you know who should review this from Android platform team or just merge?

**Comment by fuzzie** [comment]
This seems to have been added deliberately (for Android TV support), so it would be nice to know why it's a problem on some devices.

**Comment by digitall** [comment]
@Raa007 : Can you explain as per @fuzzie 's query? If not, should we commit this as-is?

**Comment by csnover** [comment]
I’m closing this for now due to no feedback from the OP for several months and a lack of clarity regarding what “some Android devices” means, and how this change does not negatively impact platforms for which this activity was deliberately added. @Raa007 if you are able to provide this information in the future then this PR can be revived and looked at again.

**Comment by dafioram** [comment]
I believe Raa007 is forum user mac_es and this PR was done to resolve the issues mentioned in http://forums.scummvm.org/viewtopic.php?t=14177&highlight=android+black and Trac#10024. Since mac_es cites this as a solution to Trac#10024. I believe this PR should stay open until someone with an android build can test this.

**Comment by spinktvis** [comment]
I am one of the users who experience this issue (http://forums.scummvm.org/viewtopic.php?p=84520#84520). If somebody can build this i am more than willing to test it. It would be a waste to close this because the only build that works for me is the 1.9.0.1 test build sev uploaded. The rest give black screens, and the 1.9.0 Play Store version has the SD card bug.

**Comment by csnover** [comment]
I’ve posted some updated Android builds on the corresponding ticket in the bug tracker at https://bugs.scummvm.org/ticket/10024#comment:6. Please try these builds and report on the bug tracker if they work. Make sure to enter your email address in preferences after logging into the bug tracker or you will not see replies.

**Comment by spinktvis** [comment]
Thanks, I've replied with logs, hopefully they'll be if help

**Pull request closed without merging**
