### PR TITLE
FULLPIPE: Shift loadGameState() and saveGameState()

### PR DESCRIPTION
**Pull request by harshbawari**

### CODE REVIEW

**Comment by sev-** [comment]
What is the purpose of this exercise? The code change makes no sense.

**Comment by harshbawari** [comment]
https://github.com/scummvm/scummvm/commit/0ae4cb1ea7907c7d558cb89ad101f762a0d64c8c

**Comment by sev-** [comment]
352915aa?

**Comment by harshbawari** [comment]
Can you provide the link? I can't find the commit

**Comment by harshbawari** [comment]
I have spent this whole week figuring out what you want me to do exactly. I read the wiki, saw the code, and what I could make out is that you've already implemented MetaEngine in fullpipe. I don't understand what else you want me to do. Problem is 'what to do' not 'how to do'. And you are most welcome to block me on GitHub too

**Comment by sev-** [comment]
The task was the following: We need to move Fullpipe engine save system to the new MetaEngine extended saves format, similarly like I did so for the HDB engine. I implemented the extended saves format precisely after fullpipe, so this should be a relatively straightforward task of removing code and reusing the MetaEngine parts.

This code covers nothing from it. Closing.

**Pull request closed without merging**
