### PR TITLE
SWORD1: Switch to AdvancedMetaEngineDetection

### PR DESCRIPTION
**Pull request by ccawley2011**
This will require the detection table to be fleshed out a bit before this can be merged.

### CODE REVIEW

**Comment by orgads** [comment]
Any progress with this?

**Comment by lotharsm** [comment]
I'm currently working on adding the necessary/missing detection entries - should be finished soon.

**Comment by criezy** [comment]
Currently my mac French version is detected as the mac demo English version. We will need to add some files to the detection to detect properly the full game.  And from what I remember the only way to detect the language is with the speech files are other files are identical. I can provide detection entries for the French mac version of the game if needed, but I don't have access to other versions.

One thing I noticed when trying this pull request is that we lost the ability to play the game with speech in one language and the interface and subtitles in another language. For example in the 2.6.0 release I can play my French mac version with menu and subtitles in English and speech in French.

image

Indeed all the versions released have the speech for only one language but have the subtitles for all the languages (except Brazilian Portuguese that is missing from some versions).  Which is why we get that ability to use the subtitles for a different language. The original game did not allow that, and this is an enhancement in ScummVM. And I think it would be a shame to lose that.

**Comment by lotharsm** [comment]
@ccawley2011 I added some variants to the detection table. Would it be possible that you add me as contributor to this PR so I can submit it here?

**Comment by bluegr** [comment]
> One thing I noticed when trying this pull request is that we lost the ability to play the game with speech in one language and the interface and subtitles in another language. 

This will hopefully be resolved once all the relevant entries are added in the detection table. We can also use ADGF_ADDENGLISH here, but there's no equivalent for all languages, AFAIK

**Comment by criezy** [comment]
I will backtrack a bit from my previous comment, and maybe the solution is indeed to add detection for all the languages, but without including the speech file so that they all have the same entries. I think that should let the user select the language. And that would help to get all versions detected, included rare localised Mac versions for which getting the speech file hash could be difficult.

**Comment by sev-** [comment]
Thank you, this is great stuff.

@criezy you may resolve your issue right in the master.

**Pull request merged**
