### PR TITLE
COMMON: fix String::rfind for default value of pos (max value of size_t)

### PR DESCRIPTION
**Pull request by sergio256256**

### CODE REVIEW

**Comment by bluegr** [comment]
Can you provide a bit more info on this?

**Comment by sergio256256** [comment]
Sure,

Default value for pos is npos:
size_t rfind(char c, size_t pos = npos) const;

So if default value is used, after its cast to int a very big negative value appears in the right part of MIN((int)_size - 1, (int)pos), then MIN returns this negative value and for loop is never executed. I replaced (int) with cast to (size_t) to avoid this issue. There is still potentially an issue for strings longer than max int32, because I cast the whole result of MIN to int, but at least it works for strings of reasonable length. rfind is very rarely used in code of scummvm games so I think it was the reason why it wasn't fixed before.

**Comment by criezy** [comment]
I guess we could also make the test with `npos` explicit so that we do not have to make any assumptions on what is the actual value of `npos`:
```c++
for (int idx = (pos == npos ? (int)_size - 1 : (int)pos); idx >= 0; --idx) {
```

**Comment by mgerhardy** [comment]
it would be nice to a unittest in `test/common/str.h`

**Comment by lephilousophe** [comment]
> I guess we could also make the test with `npos` explicit so that we do not have to make any assumptions on what is the actual value of `npos`:
> 
> ```c++
> for (int idx = (pos == npos ? (int)_size - 1 : (int)pos); idx >= 0; --idx) {
> ```

I do agree with this proposal just not inlined in the for loop. :smile:

**Pull request closed without merging**
