### PR TITLE
GSOC 2012 Scaler Plugins (updated)

### PR DESCRIPTION
**Pull request by ccawley2011**
This is a rebased version of PR #1255, with a number of additional bug fixes, as well as some (but not all) of the changes from LordHoto's [gsoc2012-scalers-cont](https://github.com/lordhoto/scummvm/commits/gsoc2012-scalers-cont) branch.

Note that the use of scalers in the iOS 7 backend has been removed, as well as the downscaling code in the GPH and Dingux backends.

### CODE REVIEW

**Comment by Mataniko** [comment]
I actually commented in the original PR instead of this one:

So a lot of work has been put into this, but today we can get better scalers using shaders. They achieve a much better effect at much lower cost of performance.

In 2012 this PR may have made sense, but now with OpenGL being available across most ports is this worth the effort to get it to work and maintain?

**Comment by sev-** [comment]
In fact, since it is in this good shape, I think, it could make sense for me to resume my review and merge it.

@ccawley2011 Thank you very much for putting your effort into this.

@Mataniko Not all platforms have OpenGL. "most ports" is not a very valid argument for ScummVM, as we try to embrace as many platforms as possible.

And another, much more important argument, is that I do not see a PR with Shader support. There is a half-started work by LordHoto, https://github.com/lordhoto/scummvm/tree/libretro-shader 4 years old...

**Comment by djwillis** [comment]
@ccawley2011 great to see work done on this, that is very cool. Can I ask about the thinking on dropping the scale down support? I suspect I know why but your reasoning would be interesting.

@Mataniko As an aside, a lot of work is going on 'under the hood' to get the toolchains and supporting infrastructure updated for a number of the older ports and ones that have fallen just outside of support (behind by a release or two). This is being done with a view to getting them all back on the build servers and in a good state for future releases. That includes a number of ports that run ScummVM very well but will never support the OpenGL render paths for reasons of capability or shocking OGL drivers (OpenPandora, early Pi's and anything running on 'older' OMAP boards spring to mind).

While I agree with your sentiment on OpenGL shaders I feel ScummVM is a few years away from that point and I wonder how much maintenance overhead this scaler work will really add when it is in tree and stable.

**Comment by ccawley2011** [comment]
>Can I ask about the thinking on dropping the scale down support? I suspect I know why but your reasoning would be interesting.

I dropped the downscaler code because it wouldn't work as is with the new scaler code. In the long run, it should be possible to support a scaler factor of 0.5 in one of the existing scaler plugins, but for now I don't want this PR to get bitrot like the previous two did while waiting for the other ports to be adapted to use the new API. While ideally it would be good to support downscaling, IMHO I'd much prefer just losing support for highres games in the GPH and Dingux ports than to lose those ports entirely. I might look into this at a later date, but for now my priority is getting this PR into a merge-able state so that I can continue to refactor `SurfaceSdlGraphicsManager` once it's merged.

Scaler support in the iOS 7 backend was removed for the same reason, however in the long run, it really should be using the common OpenGL graphics code in `OpenGLGraphicsManager` instead of its own custom code.

>While I agree with your sentiment on OpenGL shaders I feel ScummVM is a few years away from that point and I wonder how much maintenance overhead this scaler work will really add when it is in tree and stable.

With some minor exceptions, any maintenance overhead should be contained within `SurfaceSdlGraphicsManager`. At some point, though, I do want to add support for using scalers with OpenGL so that they can be used on Android and Tizen, plus [this forum post](https://forums.scummvm.org/viewtopic.php?p=88798#p88798) mentions using both scalers and shaders simultaneously, which means that it would be beneficial regardless of whether or not we add support for shaders.

**Comment by sev-** [comment]
I am really looking forward to finally merging this. @ccawley2011 Could you please rebase this?

**Comment by ccawley2011** [comment]
> I am really looking forward to finally merging this. @ccawley2011 Could you please rebase this?

OK, done.

(The Xcode failure appears to be unrelated.)

**Comment by bluegr** [comment]
This has been rebased now. We got votes for merging this from @sev-, @aquadran, @djwillis and @bluegr  (me).

So, after 9 years, this can be finally merged. Kudos to all people who made this possible, including @singron, @lordhoto, @ccawley2011 and @sev-!

**Pull request merged**
