### PR TITLE
Various GLK detection tables updates

### PR DESCRIPTION
**Pull request by MarcoBorrini99**
This PR mainly adds:
- about 200 new zcode entries
- about 80 new glux entires

### CODE REVIEW

**Comment by sev-** [comment]
Thank you!

**Comment by digitall** [comment]
@sev- : While these entries are needed, the very large detection tables in GLK and AGS especially are breaking these on embedded platforms with limited RAM. We could do with a solution for this to dynamically load the detection table and unload after detection to avoid the RAM usage.

**Comment by sev-** [comment]
@digitall It was discussed many times on Discord and @somaen even wrote a prototype. The proper solution is to export these tables into external files, JSON or XML. Perhaps, you would like to give a helping hand? We truly may start small, with supporting only GLK engine

**Comment by tag2015** [comment]
@sev- I'd gladly help with the task, preferably for the AGS entries but also GLK if needed

**Pull request merged**
