### PR TITLE
[GRIM] Fix subtitle alignment for OpenGL with shaders

### PR DESCRIPTION
**Pull request by somaen**
This is a quick attempt at trying to fix the broken positioning of text in Grim when using the OpenGL shader renderer.

@eriktorbjorn noted that this may stem from the OpenGL (with shaders)-renderer lacking a proper implementation of getScreenBoundingBox, so I went ahead and adapted one.

This was done by comparing the getScreenBoundingBox implementations for EFMI/Grim in the OpenGL-renderer, and noticing that those were only different in how they got at their data, as there was already an implementation for EFMI in the shader-renderer, I copy pasted that code, and adapted the differences I found when comparing the OpenGL-implementation, which seems to improve things.

### CODE REVIEW

**Comment by somaen** [comment]
There, fixed the rebasing.

**Comment by eriktorbjorn** [comment]
Either I screwed up, or this still puts the subtitles at the bottom of the screen with the OpenGL with shaders renderer. (Though with the release branch, this is an improvement since there I don't get any subtitles at all without the patch. Perhaps because I compiled it in release mode, i.e. with optimizations? I seem to recall that I came to the tentative conclusion that the current behavior might be undefined.)

**Comment by aquadran** [comment]
I checked that, this is not correct. model and projection matrix is different

**Comment by aquadran** [comment]
let's merge this for now, and fix it later with another PR

**Pull request merged**
