### PR TITLE
Palette color distance definitions

### PR DESCRIPTION
**Pull request by OMGPizzaGuy**
These changes define the methods currently used for palette color matching. I have no immediate plans to support additional methods.

For reference: https://en.wikipedia.org/wiki/Color_difference

### CODE REVIEW

**Comment by bluegr** [comment]
Do you have a use case for these methods? Can you show the difference when using each method visually (e.g. by using a reference image)?

**Comment by OMGPizzaGuy** [comment]
> Do you have a use case for these methods? Can you show the difference when using each method visually (e.g. by using a reference image)?

I do not have examples. This is clarification of the existing methods - "redmean" is the existing default, and "naive" only used in the Scumm engine.

I could try to add something to testbed to show and image reduced to RGB 332 palette with each method.

**Comment by mduggan** [comment]
I used this function by chance in something I wrote yesterday, so I appreciate the clarification of what `useNaiveAlg` actually means :)

**Comment by bluegr** [comment]
Thanks!

**Pull request merged**
