### PR TITLE
MADE: Add Manhole detect and separate out detections list

### PR DESCRIPTION
**Pull request by dafioram**
1. Add an unstable manhole version (gog)
2. Move MADE detection list into separate file.

I tested the changes by running return to zork.

### CODE REVIEW

**Comment by bluegr** [comment]
The Masterpiece Edition is not based on the MADE engine, but on another, HyperCard-like engine:
https://wiki.scummvm.org/index.php/The_Manhole

Thus, please do not add this version in this engine

**Comment by dafioram** [comment]
scummvm autodetected this as MADE based on the dat file, is there a good way to inform the user that this version shouldn't be added as I have done? I imagine someone in the future will do the same as I have done.

**Comment by bluegr** [comment]
You can comment this version out, and add a comment that it's not supported, since it's not using the MADE engine. This way, people won't try to re-add it

**Comment by dafioram** [comment]
How that look?

**Comment by bluegr** [comment]
Looks good, thanks! :) Merging

**Pull request merged**
