### PR TITLE
AMIGAOS: rename/update install_deps.rexx/amigaos.mk

### PR DESCRIPTION
**Pull request by raziel-**
install_deps.rexx

- tidying up the variables
- more readable (i believe)
- fixed some spelling
- added one more path to search for dependant libraries
(vanilla AmigaOS4 SDK doesn't hold libpthread.so)

amigaos.mk

- adapt the script to the new install_deps.rexx

### CODE REVIEW

**Comment by bluegr** [comment]
Please, rename the file instead of deleting and re-adding it. This way, we can preserve its history of commits

**Comment by raziel-** [comment]
but...i did.

just like @sev- showed me yesterday.

edit in place
rename the file
add the changes

**Comment by lephilousophe** [comment]
Git doesn't track renames.
It only detect similarities between files when deleting/adding files.
Here, the file got renamed (ie. deleted and added again) but also heavily modified so Github doesn't consider this as a rename.
Using git diff you could use the -M argument to tune the similarity threshold.
Here is some [confirmation](https://stackoverflow.com/a/7941544).

What could be done is commit the rename then change the file contents.

**Comment by raziel-** [comment]
ok...do i need to split the pr up, or can it be cherry picked?

**Comment by sev-** [comment]
The problem is that Raziel does not have access to the command line git. I think, we have no choice but accept it...

**Comment by raziel-** [comment]
i could still split it up

first rename and changes in amigaos.mk

then a second pr with changes to newly renamed script file

if that is preferred?

**Comment by lephilousophe** [comment]
I have done it in one PR

**Comment by raziel-** [comment]
@lephilousophe 

thank you

**Comment by sev-** [comment]
Thank you

**Pull request merged**
