### PR TITLE
JANITORIAL: Fix repetitive warnings about template-id in constructor/destructor

### PR DESCRIPTION
**Pull request by peter277**
Fix repetitive warnings about template-id in constructor/destructor and ensure C++20 compatibility. Warnings encountered when compiling with GCC 14.

### CODE REVIEW

**Comment by bluegr** [comment]
Thanks!

Please, reduce the length of the commit message to 72 characters, and add the rest to the description

E.g:

"JANITORIAL: Fix GCC 14 warnings
Fix repetitive warnings about template-id in constructors and destructors. This ensures C++20 compatibility.
Warnings are encountered when compiling with GCC 14."

**Comment by bluegr** [comment]
Also, ideally this should be split into different commits, one for common code, and separate ones per engine, i.e:

- COMMON: Fix GCC 14 warnings
- ADL: Fix GCC 14 warnings
- STARTREK: Fix GCC 14 warnings
- TITANIC: Fix GCC 14 warnings

**Comment by peter277** [comment]
Thanks @bluegr - I've amended the commit message as requested and also tweaked the change to file 'engines/startrek/fixedint.h' which should hopefully help the CI build succeed with VC++.

Will bear in mind splitting the commits for future (initial thought was not to crowd the commit history with small changes).

**Comment by bluegr** [comment]
Thanks!

**Pull request merged**
