### PR TITLE
SOFTSYNTH/PCSPK: fix overflow for sounds longer than 97 ms (at 44100 Hz)

### PR DESCRIPTION
**Pull request by chillywillysoft**

### CODE REVIEW

**Comment by bluegr** [comment]
Thanks! Do you have a use case where this problem can be observed?

**Comment by chillywillysoft** [comment]
I'm reverse engineering a game that seems to have been written in Turbo Pascal. To reproduce TP's Sound function which could only produce a single tone at a time on the PC speaker, I thought scummvm's pcspk would be a good fit. (Is there a better fit? I'm very new to the scummvm code base.) It was cutting a lot of the tones short and that's how I noticed the issue. I'm on a 64-bit MacBook if that helps.

**Comment by bluegr** [comment]
@chillywillysoft we have the same issue in `play()` and `stop()`, as well, although they use ms for the length.

Another potential solution would be to convert length inside `readBuffer()` to ms first, and then do the same calculation as done in `play()`, i.e.

    uint32 length = command.length / 1000;
    _remainingSamples = (_rate * length) / 1000;

If needed, we may need to perform casting in this case, as well

**Comment by NMIError** [comment]
The playQueue function was added specifically for a use case where timing with higher precision was required. So I'd rather have the command length remain in microseconds.
I'm in favor of implementing this change as proposed, but I'm not sure if using 64 bit integers is a problem for some of the less-capable platforms we have ports for. Otherwise, we can limit the command length so the multiplication doesn't overflow.

**Comment by chillywillysoft** [comment]
> Otherwise, we can limit the command length so the multiplication doesn't overflow.

At 44100 Hz that limit is 97 ms. In most music, every single note is longer than that. Looking at the code, adding two notes in series to get a longer note would result in an audible stitch where one ends and the other begins. We could not clear _oscSamples between notes but it still seems like an unnecessary hassle to have to have to add multiple notes in 97 ms increments.

**Comment by bluegr** [comment]
> Edit: I haven't analyzed the math but maybe using a float would give adequate results without having to use 64-bit integers.
> 
> Edit: I'm new here and I don't mean to be a meanie straight out of the gate :) but in what use case is ms precision not enough for audio?

@chillywillysoft this functionality was added by @NMIError in commit 5362b1b302ef63daa1129673086039f61cf586ab, where the reasoning for using better precision than ms is explained

**Comment by chillywillysoft** [comment]
> @chillywillysoft this functionality was added by @NMIError in commit [5362b1b](https://github.com/scummvm/scummvm/commit/5362b1b302ef63daa1129673086039f61cf586ab), where the reasoning for using better precision than ms is explained

Followed the link but did not see an explanation. It will be a couple more months before the new engine is ready. You guys will have this sorted out bye then :)

**Comment by bluegr** [comment]
Will proceed with merging this, after talking internally. Thanks again for your work!

**Pull request merged**
