### PR TITLE
SYMBIAN: Allow usage by default OSystem_SDL_Symbian::openUrl() 

### PR DESCRIPTION
**Pull request by fedor4ever**
Fix printf() usage for logging

### CODE REVIEW

**Comment by bluegr** [comment]
So why don't we want to use the USE_CLOUD define here?

**Comment by fedor4ever** [comment]
I have no time to port  properly curl. Also Symbian lacks tls 1.2+, limited devices support tls 1.1. So I planned add local sync only for 2.3.0.
Fiodar Stryzhniou

исходное сбщ
Тема: Re: [scummvm/scummvm] SYMBIAN: Allow usage by default OSystem_SDL_Symbian::openUrl()  (#3286)
От: Filippos Karapetis ***@***.***>
Дата: 18.08.2021 21.55

So why don't we want to use the USE_CLOUD define here?

**Comment by fedor4ever** [comment]
In  #3236 @criezy says "It is not tied to the cloud storage access and is used for various features...". So I decide allow usage for that.

**Comment by bluegr** [comment]
Yes, that is correct, it's not tied to the cloud storage.

Does this work in all Symbian-based phones? Because you removed the #ifdef __S60_3X__ check

**Comment by fedor4ever** [comment]
Maybe. Code itself compatible from Symbian 6.1 upwards but devices too numerous.

**Comment by bluegr** [comment]
Right. Thanks for your work and feedback! Merging

**Comment by fedor4ever** [comment]
@bluegr , @criezy , what game has local help files in html?

**Comment by sev-** [comment]
Many, but so far, it was implemented in Pink Panther. Why?

**Comment by fedor4ever** [comment]
@sev- , because test app and real life may differ. I don't know what arg comes to browser. They should come in right form. 

For opening local files exist more robust way.

**Comment by sev-** [comment]
Then I do not understand why you did not run `git grep openUrl`

**Comment by fedor4ever** [comment]
@sev- , I hear it for the first time.

**Pull request merged**
