### PR TITLE
MOHAWK: RIVEN: Don't allow autosaving during credits

### PR DESCRIPTION
**Pull request by dafioram**
Fixes Trac#10635.

### CODE REVIEW

**Comment by bgK** [comment]
Maybe we can disable saving when `_gameEnded` is true instead to avoid duplicating the state.

**Comment by dafioram** [comment]
setGameEnded is called at the end of RivenStack::runCredits so it can be called earlier, now the while loop that plays the credits won't play the credits because of the endgame check so we could remove that check.

The endgame setting to true looks like it only happens in a few places in the code only associated with the demo (besides runCredits).

MohawkEngine::run also checks it to keep running, but I think that won't be checked until the credits loop is done.

**Comment by bgK** [comment]
Saving is already disabled during the credits because they are started by a script. It's just for a frame after the credits that autosaving has a chance to trigger. During that frame, `_gameEnded` is true.

**Comment by dafioram** [comment]
Let me see what happens if I use _gameEnded instead...

**Comment by dafioram** [comment]
Yeah that worked.

**Comment by bgK** [comment]
Thanks !

**Pull request merged**
