### PR TITLE
SDL: Refactor OpenGLSdlGraphics3dManager to inherit from SdlGraphicsManager

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by sev-** [comment]
I am sooo afraid it will clash with my HiDPI branch.

**Comment by aquadran** [comment]
👍 good for me

**Comment by bluegr** [comment]
Looks good to me as well 👍

**Comment by bluegr** [comment]
@ccawley2011 could you please resolve the conflict, so that this can be merged? Thanks!

**Comment by ccawley2011** [comment]
> @ccawley2011 could you please resolve the conflict, so that this can be merged? Thanks!

OK, done.

**Comment by sev-** [comment]
Merging, thank you!

**Pull request merged**
