### PR TITLE
ANDROID: Add a button to show the virtual keyboard

### PR DESCRIPTION
**Pull request by ccawley2011**
This is loosely based on residualvm/residualvm#825. The icon used currently is intended as a placeholder. I'm open to suggestions regarding a better icon.

### CODE REVIEW

**Comment by Kawa-oneechan** [comment]
Oh, yes please! Maybe then ScummVM will actually be usable on my phone.

**Comment by bluegr** [comment]
Nice! Could you please add a screenshot if how this looks?

**Comment by ccawley2011** [comment]
> Could you please add a screenshot of how this looks while running ScummVM?

Sure.

This PR only:
Screenshot_2019-08-19-12-09-02

This PR plus PR #1695:
Screenshot_2019-08-19-12-07-35

**Comment by bluegr** [comment]
Very nice :)

For the icon, a free android keyboard icon would look good, e.g:
https://www.iconfinder.com/icons/352464/keyboard_icon

**Comment by ccawley2011** [comment]
> For the icon, a free android keyboard icon would look good, e.g:
https://www.iconfinder.com/icons/352464/keyboard_icon

Cool. I used a slightly modified version of that icon. New screenshot:
Screenshot_2019-08-19-22-23-39

**Comment by bluegr** [comment]
Great work!

So, where will this be used? Are there cases where the use needs to open the virtual keyboard in an ad-hoc manner? (i.e, when no text input widget is selected)?

Also, it would be nice to have a GUI checkbox to turn this off, as some people might find it distracting, or it could interfere with gameplay in some
games (e.g games with an icon bar on top, like Sierra’s games)

**Comment by ccawley2011** [comment]
> So, where will this be used? Are there cases where the use needs to open the virtual keyboard in an ad-hoc manner? (i.e, when no text input widget is selected)?

Not all engines support automatically opening the virtual keyboard, and even with the ones that do, it's possible to close the virtual keyboard using the Back button and not be able to reopen it. 

>Also, it would be nice to have a GUI checkbox to turn this off, as some people might find it distracting, or it could interfere with gameplay in some
games (e.g games with an icon bar on top, like Sierra’s games)

This is already possible by unchecking the "Show On-screen control" checkbox in the "Control" tab of the options dialog.

**Comment by bluegr** [comment]
> This is already possible by unchecking the "Show On-screen control" checkbox in the "Control" tab of the options dialog.

Indeed, I forgot about that one (I did see it when I read the full diff).

Thanks for your work on this! Merging

**Pull request merged**
