### PR TITLE
COMMON: Add a signed version of uintptr

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by AndywinXp** [comment]
Haha, I'm totally up for it :P

**Comment by bluegr** [comment]
I'm not sure I understand the usage of this. When does it make sense to use signed integers as pointers?

**Comment by dreammaster** [comment]
In AGS, for example, the intptr_t type is used for generic value storage that can be either a number or a pointer, depending on which opcodes get encountered. Similarly, the passing of parameters to plugin methods also uses it generically, and it's casted as desired by the individual plugin methods.

**Comment by AndywinXp** [comment]
> In AGS, for example, the intptr_t type is used for generic value storage that can be either a number or a pointer, depending on which opcodes get encountered. Similarly, the passing of parameters to plugin methods also uses it generically, and it's casted as desired by the individual plugin methods.

I have the same exact situation with DiMUSE_v2 with its command handler

**Review by Die4Ever — APPROVED** [review]
Seems good to me

**Review by bluegr — APPROVED** [review]

**Comment by bluegr** [comment]
Thanks for the explanation everyone! So, this will be a useful feature indeed.

I'm merging this, as it'll be used in a handful of places

**Pull request merged**
