### PR TITLE
SLUDGE: Fix build for Symbian.

### PR DESCRIPTION
**Pull request by fedor4ever**
This allow use remove() function.

### CODE REVIEW

**Comment by lephilousophe** [comment]
remove function shouldn't be used by the engine.
This PR would be useless then.

**Comment by fedor4ever** [comment]
scummvm/engines/sludge/builtin.cpp: In function 'Sludge::BuiltReturn Sludge::builtIn_deleteFile(int, Sludge::LoadedFunction*)':
/Symbian/Projects/SDL/scummvm/engines/sludge/builtin.cpp:2084:32: error: 'remove' was not declared in this scope
  fun->reg.setVariable(SVT_INT, remove(nam.c_str()));
                                ^~~~~~
/Symbian/Projects/SDL/scummvm/engines/sludge/builtin.cpp:2084:32: note: suggested alternative: 'wremove'
  fun->reg.setVariable(SVT_INT, remove(nam.c_str()));
                                ^~~~~~
                                wremove
make.exe: *** [\Symbian\S60_5th_Edition_SDK_v1.0\EPOC32\BUILD\Symbian\Projects\SDL\scummvm\backends\platform\symbian\S60v3\SLUDGE\GCCE\UREL\builtin.o] Error 1

**Comment by sev-** [comment]
@fedor4ever what is your point?

**Comment by fedor4ever** [comment]
@lephilousophe , @sev- , build error say there is remove().

**Comment by sev-** [comment]
Your patch is curing the symptroms, not the real problem.

**Pull request closed without merging**
