### PR TITLE
JANITORIAL: Correct some spelling mistakes (mostly in comments)

### PR DESCRIPTION
**Pull request by raziel-**
my-god-its-full-of-stars-quote

Since i can't really do much to contribute to the code (but i really want to), i can at least look for typos...which i did...and i *tried* to fix them too :-)

There will be mistakes on my end, there will be questionable fixes (i think?)

Please advise if you are not ok with any change.

**Notes:**

1. I mostly touched comments, so there shouldn' t be any impact to the code itself, with *one* exception:

In
`audio/softsynth/opl/mame.cpp`
there is a variable misspelled "rythm".
I changed that as well and hope i didn' t break anything.

2. I'm unsure about the whole "calender" file and variable naming in
`engines/saga2/calender.cpp`
`engines/saga2/calender.h`
It's definitely spelled wrong (it should be `calendar`), but since so much of the code is affected i let it slip.
If anyone wants to tackle those, be my guest. :-)

Oh and i cannot rename any files from the website, so even if i tried, i couldn't :-)
otoh maybe the naming was intended?

**And a call for help:**
`engines/sci/engine/script_patches.cpp`
is 1.1 MB in size and the github webpage won't let me edit it, since it tells me the file is too big to be displayed (yet)

If anyone would be so kind to fix two typos in there, please?
line 4224 `accomodate` should be `accommodate`  and
line 6465 `fiery` should be `firey`

Thank you

...if this is a mess and if i produced work due to reviewing this that would have gone into more elaborate things, like writing actualy usable code, then
I'm sorry :-(

### CODE REVIEW

**Comment by sev-** [comment]
Dude, this is aweseome!

Merging

**Comment by sev-** [comment]
Hmm, this cannot be merged due to conflicts :/

**Comment by sev-** [comment]
Next time pleaae make it smaller. GitHub has choked on amount of commits. I'll try to merge it manually

**Comment by raziel-** [comment]
I plan to do this once or twice a year or so, since the arexx script I wrote to check for the most common spelling errors need 20+ hours on my machine to parse over the whole source :-)

I guess tge next potdntial typo PR will be measurably smaller anyway

Thank you

**Comment by AndywinXp** [comment]
@raziel- thanks for your work! Please note though that one of the commits (the one related to AUDIO which replaced `rythm` with `rhythm` broke the builds, since it wasn't consistently renamed along all its references.

From what you wrote it seems that you're using a web editor to edit the files. I suggest you to begin using an IDE (like Visual Studio, or whatever is supported on your machine): this will help you rename variables consistently and will also let you compile ScummVM (so you can check for build errors).

**Comment by raziel-** [comment]
@AndywinXp

I'm truly sorry for the inconvenience.
I'll check them more closely the next time

**Pull request closed without merging**
