### PR TITLE
MYST3: Add detection for Xbox prototype

### PR DESCRIPTION
**Pull request by Zapeth**
Saw the recent commit about PS2 prototype and thought I'd add this here.

Actually there seem to be two different preview builds available (both uploaded yesterday on archive.org), but they have the same checksum for RSRC.m3r file.

### CODE REVIEW

**Comment by einstein95** [comment]
Judging by the other Xbox entries in the file, do the language files have different checksums between the builds?

**Comment by Zapeth** [comment]
It seems so. These are the language files (with md5sum and size) that I could find in the builds, I wasn't sure whether to use the .m3t or the .m3u file so I didn't include them in the PR:

Mar 26, 2002:
`ENGLISHjpX.m3t, D3FA13B052C02B1296881A27DE4722F2, 4799732`
`JAPANESEX.m3t, D18E49916BD789B877A3131E076E0AC4, 6647239`
`JAPANESEX.m3u, BC2DE2CB42C1144612A32FA7D905A8C7, 2286432`

Jun 16, 2002:
`ENGLISHX.m3t, 846C888C545560A1F7736DF89602A8A1, 4847156`
`ENGLISHX.m3u, 24C280F97065E8129F03B22CA9B278CF, 2096874`

**Comment by einstein95** [comment]
As the other Xbox entries use the `.m3t` file, I'd say to use that.

**Comment by Zapeth** [comment]
Alright, then should I create three explicit entries or a separate MYST3ENTRY macro for the different language entries (suffix _PREVIEW or _PROTOTYPE)?

Also should I use `Common::EN_ANY`, `Common::JA_JPN` or `Common::UNK_LANG` for the `ENGLISHjpX.m3t` entry?

**Comment by sev-** [comment]
No, the unreleased prototypes are not accepted. The PS2 prototype should've not be added in the first place.

**Pull request closed without merging**
