### PR TITLE
BBVS: Add another Loogie demo variant

### PR DESCRIPTION
**Pull request by raziel-**
Fixes bug tracker #13068 https://bugs.scummvm.org/ticket/13068

This is only the detection part.
As mentioned in the bug tracker, the demo suffers from missing updates to the main window, see screenshot there.

Should i open a new tracker item for this bug?
Where should i upload the demo data?

Thanks

### CODE REVIEW

**Comment by aquadran** [comment]
yes, new bug for issue

**Comment by aquadran** [comment]
@lotharsm are able uploaded demo to FRS?

**Comment by raziel-** [comment]
@lotharsm

I'm going to close the bug item that belongs to this PR.
https://bugs.scummvm.org/ticket/13068

You can always visit it to find the installed zip package (Not the original zip since it's too big to add to the tracker) and/or the webarchive link to get an .iso of the Sampler CD.

If you need i can also prepare one and send it to you directly?

**Comment by lotharsm** [comment]
Thanks, I'll upload the installed ZIP package to our FRS. I wonder if we want the original ZIP file as well? In this case, I can extract it from the ISO file.

**Comment by raziel-** [comment]
The original is not a .zip (sorry, my bad, i was talking about the .zip i produced to be able to upload it) but the original .exe binary install package.

Looking like this on the CD:

list DATI:VIRGIN/BEAVIS/ 
Directory "DATI:VIRGIN/BEAVIS/" on Friday 12-Nov-21
DATA.Z                         1726293 ---arwed 15-Jan-96 15:52:16
SETUP.EXE                       393216 ---arwed 11-Jul-95 09:50:00
SETUP.INS                         3610 ---arwed 15-Jan-96 15:35:18
UNINST.EXE                      155648 ---arwed 12-Jul-95 16:23:56
_SETUP.DLL                        6656 ---arwed 05-Jun-95 20:26:00
_SETUP.LIB                       23831 ---arwed 12-Jul-95 17:09:46
6 files - 1135 blocks used

**Comment by lotharsm** [comment]
I wonder - what is the difference between the version added here and the one that got uploaded to FRS back in August 2020?

https://downloads.scummvm.org/frs/demos/bbvs/bbvs-demo-loogie.zip

**Comment by raziel-** [comment]
At least BBLOOGIE.000 is a little bit bigger with  the new version.

**Comment by lotharsm** [comment]
Alright, uploaded as

https://downloads.scummvm.org/frs/demos/bbvs/bbvs-demo-loogie-2.zip

:-)

**Pull request merged**
