### PR TITLE
JANITORIAL: Fix sargent typos in darkseed.cpp

### PR DESCRIPTION
**Pull request by raziel-**
I'm not sure about this one

sargent is obviously mispelled (sergeant), but maybe there is a character called "sargent"?

### CODE REVIEW

**Comment by bluegr** [comment]
Thanks, it's just a misspelling. Squashing

**Comment by raziel-** [comment]
What about the sergent spellings in the sherlock engine?
I'm not sure if they are spelled correctly in other languages or also simply misspellings?

**Comment by digitall** [comment]
> What about the sergent spellings in the sherlock engine? I'm not sure if they are spelled correctly in other languages or also simply misspellings?

While "Sergeant" is the accepted standard spelling in modern English, the spelling has varied over time. Please be careful with changing anything associated with game data rather than just comments as the impact will need to be assessed:
https://en.wikipedia.org/wiki/Sergeant#Police_5

**Comment by raziel-** [comment]
understood

thank you

**Pull request merged**
