### PR TITLE
CREATE_PROJECT: fixed cmake generator

### PR DESCRIPTION
**Pull request by mgerhardy**
With these patches I'm now able to configure, compile and link with cmake

* Support for pkg-config was added
* Shortened the CMakeLists.txt by more than 4000 lines
* Added macro for feature detection
* Configure stage is reporting missing libs as error now (they were reported as compile errors during the build before)
* Link the scummvm-detection lib (this was missing before)
* Added missing defines like `DETECTION_STATIC` and `USE_SDL2`
* Added the generated `CMakeLists.txt` to `.gitignore`

### CODE REVIEW

**Comment by lotharsm** [comment]
I ran into similar issues when I played around with create_project. +1 from me.

**Comment by mgerhardy** [comment]
With the latest commit I'm now able to not only configure the build system - but also compile and link the binary. But

```
 ~/dev/scummvm/build   remotes/mgerhardy/pr/create-project-cmake-pkgconfig ? ⍟53  ./scummvm --list-engines                                                                                                                                                               ✔  17:31:09
Engine ID       Engine Name                                           
--------------- ------------------------------------------------------
```
There are also no shared objects created. So I suppose there is some define missing here?

**Comment by mgerhardy** [comment]
This also fixes some missing defines since the detection plugin rework.

**Comment by mgerhardy** [comment]
[CMakeLists.txt](https://github.com/scummvm/scummvm/files/5506068/CMakeLists.txt)

Attached a generated cmake script

**Pull request merged**
