### PR TITLE
SCUMM: Fix a dead-end in Monkey Island 2 and restore a reaction from Dread

### PR DESCRIPTION
**Pull request by dwatteau**
Yes, there is a dead-end in Monkey Island 2! But it only happens in the [Ultimate Talkie Edition](http://gratissaugen.de/ultimatetalkies/monkey2.html), because another bug in the original game prevented an intended scene from being triggered… so I'm fixing both issues in this PR (in separate commits).

Thanks to Ninou for discovering this dead-end, last summer. I also see that someone [recently reported this problem on Reddit](https://www.reddit.com/r/MonkeyIsland/comments/u7065m/monkey_island_2_glitch_help/). Spoilers ahead…

## Restoring an untriggered reaction from Captain Dread

Whenever you acquire one of of the four map pieces during Part 2, one SCUMM Bit is set so that the other scripts may know about this:

- `Bit[366]` (Rapp's)
- `Bit[55]` (Elaine's)
- `Bit[70]` (Antiques dealer's)
- `Bit[69]` (Rum Roger's)

Then, if you go back to Captain Dread's ship, the following check is done by script 22-202:

```
if (Bit[366]) {
  if (Bit[55]) {
    if (Bit[70]) {
      if (Bit[69]) {
        print(4,[Text("Mon, I gotta take you back to Scabb Island." + wait() + "I got goods I gotta deliver.")]);
        WaitForMessage();
        goto xxx;
      }
    }
  }
}
```

Yes, Captain Dread is supposed to bring you back to Scabb Island and leave you there, once you have the full map (probably so that the player knows where to focus in order to finish the second part of the game).

If you don't remember this, that's because… you've played the original game, which forgets to properly set `Bit[70]` when you get the map piece from the antiques dealer on Booty Island. The 2009 Special Edition dubbed the reaction line from Captain Dread, but yet it didn't fix setting `Bit[70]`, so you wouldn't hear it. Only the Ultimate Talkie Edition fixed this, so I'm borrowing this content restoration of theirs to the other versions.

That's not the way people remember playing the game, though, so this is marked as an Enhancement if you prefer disabling it in the game settings (I've written this workaround so that you can enable/disable just before you go back to Dread's ship). But it really looks like this scene was an original intent of the game authors, and only a small oversight prevented it from being triggered (a bit like the restored content in Grim Fandango and Blade Runner?).

But… restoring this content introduces a possible dead-end to the game!

## Preventing a possible dead-end in Monkey Island 2

Until now, this dead-end could only happen in the Ultimate Talkie Edition, because it's related to the restored reaction from Captain Dread. Since the Enhancement above restores it in all versions of the game, this dead-end must be fixed in all versions too.

If you:

- play Monkey Island 2 in Regular Mode (not in Lite Mode, where this dead-end is not possible AFAIK)
- play the Ultimate Talkie Edition, or any other version with the new enhancement above enabled
- get the four map pieces
- but forget to pick up the lens from the model lighthouse (in Phatt City Library)
- and then go to Captain Dread's ship

then, Dread will force you to go back to Scabb Island, leave you there and disappear. But then, since you stole Wally's monocle in Part 1, Wally won't be able to read the map, and you can't go back to Phatt Island to pick up the lens, since Dread is gone. Dead-end!

To fix this in ScummVM, I'm adding some checks when Dread's reaction is about to be triggered: if you're playing in Lite mode, but the model lighthouse lens isn't in your inventory, and the bit that's set when Wally receives a new monocle isn't set, then we detect a possible dead-end and we don't trigger Dread's reaction yet. You can still navigate between the 3 islands as in the original game.

This is intentionally *not* marked as an Enhancement; this fix is always applied, since you never want a dead-end in a Monkey Island game :)

## How to test

I couldn't find any useful boot param for this...

It's probably best to test the Ultimate Talkie Edition and an original game version, both with and without the Enhancement game setting.

1. Load a save where you've just found the last map piece on Phatt Island, but haven't picked up the model lighthouse lens yet. You can use [this save](https://github.com/scummvm/scummvm/files/9181286/monkey2.s12.zip) for the original DOS/English release of the game.
2. Go back to Captain Dread's ship
3. If you've enabled the Enhancement setting, Captain Dread should play his "I gotta take you back to Scabb Island" **only** when you have the model lighthouse lens (or if you already gave it to Wally).

(The change to `o5_notEqualZero()` is based on the workaround for `o5_equalZero()` just below.)

I've tested the original DOS English, DOS French, Macintosh English, and Amiga English releases, and then the Ultimate Talkie Edition.

### CODE REVIEW

**Comment by eriktorbjorn** [comment]
I have not tried this, I just wanted to confirm that room-22-202 uses the exact same bit variables (366, 55, 70, and 69) in my Mac version of the game. I guess it would be good if someone could check the Amiga and FM Towns versions as well?

**Comment by dwatteau** [comment]
> I have not tried this, I just wanted to confirm that room-22-202 uses the exact same bit variables (366, 55, 70, and 69) in my Mac version of the game. I guess it would be good if someone could check the Amiga and FM Towns versions as well?

Thanks. I have checked the Amiga version, too, it's OK. I don't have the FM-TOWNS version, though, so if someone has it… but from my experience, v5+ games are very close on all their ports.

**Comment by AndywinXp** [comment]
> Thanks. I have checked the Amiga version, too, it's OK. I don't have the FM-TOWNS version, though, so if someone has it…

Got you covered:
```c++
[0032] (A8) if (Bit[366]) {
[0037] (A8)   if (Bit[55]) {
[003C] (A8)     if (Bit[70]) {
[0041] (A8)       if (Bit[69]) {
[0046] (14)         print(4,[Text("Mon, I gotta take you back to Scabb Island." + wait() + "I got goods I gotta deliver.")]);
[0093] (AE)         WaitForMessage();
[0095] (18)         goto 095F;
[0098] (**)       }
[0098] (**)     }
[0098] (**)   }
[0098] (**) }
```

It's all good!

**Comment by bluegr** [comment]
Very well explained, and nicely implemented workaround for an unintentional dead end!
Thanks for your work, merging

**Pull request merged**
