### PR TITLE
AMIGAOS: Cleanup and free signals via atexit(), 2nd attempt 

### PR DESCRIPTION
**Pull request by PushmePullyu**
Second attempt at fixing [#6956](https://bugs.scummvm.org/ticket/6956) "ScummVM returned with unfreed signals (AmigaOS4)".

This only runs the cleanup code if the OSystem_AmigaOS instance has not been destroyed already.

Should prevent crashes after calls to error(), which on AmigaOS already cleans up via OSystem_SDL::fatalError().

### CODE REVIEW

**Comment by raziel-** [comment]
wait, what about the wrap-exit branch?
https://github.com/PushmePullyu/scummvm/tree/wrap-exit

i did all the testing on the wrap-exit branch, not on this one

**Comment by PushmePullyu** [comment]
@raziel- 
This is basically the same as the amigaos-free-signals-fixup-pr branch you tested previously. I was under the impression that the wrap-exit branch did not change anything about the crashes. There is no need to abandon the atexit approach then. But maybe I misunderstood something?

**Comment by raziel-** [comment]
take into account that i can't code :-)

the prevous test, as you may remember, rendered some stuff unstable, your wrap branch was fine from the start.

since i switched to the wrap branch immediately after you created it, there has not been any more testing done with the previous one.

since i can only compare between the old (now obsolete) fix and the wrap branch, i can say that the overall stability improved greatly on the wrap branch.

be it because of subtle changes or the overall impact your addition brought i can't say...just that I'd love to work with the wrap branch further, since it really made a difference

of course, you decide, but i wouldn't want to dismiss yet another of your additions just because of another regression due to lack of testing

you already helped so much

**Comment by PushmePullyu** [comment]
@raziel- 
I'd prefer to try and get this PR merged first and then debug the AGS crash in a new ticket.
If necessary, we could then still switch to a wrap-exit like strategy.

The reasoning behind this is that the wrap-exit branch is more invasive (although this could be reduced by using the preprocessor to replace exit()), while the atexit approach is contained to AmigaOS.

Would that be acceptable?

**Comment by raziel-** [comment]
of course...as long as you dont suddenly vanish :-)

**Comment by bluegr** [comment]
Thanks for your work @PushmePullyu! Much cleaner implementation

@raziel-, have you had time to test this new approach?

**Comment by raziel-** [comment]
yes, working great

thank you @PushmePullyu

**Comment by bluegr** [comment]
Great, thanks!

**Pull request merged**
