### PR TITLE
TUCKER: Fix alleyway cellar location hotspot bug

### PR DESCRIPTION
**Pull request by bonki**
Fixes Trac#6645.

I'm pretty confident about this one but this should be tested a bit more in other places.

/cc @raziel- (you reported this bug)

### CODE REVIEW

**Comment by sev-** [comment]
Current code matches the original. Maybe a more thorough testing could be helpful.

**Comment by bonki** [comment]
Thanks for checking, I'll look into it.

**Comment by sev-** [comment]
Merging in the meantime.

**Comment by bonki** [comment]
Just FYI, I checked a while ago and the bug does exist in the original so it's not surprising current code matches disassembly. I still believe this is the right fix and I plan on testing the whole game before next release so I'm OK with you having merged this now. Thanks!

**Pull request merged**
