### PR TITLE
ALL: Pause Token

### PR DESCRIPTION
**Pull request by henke37**
This PR introduces a new system for managing the pause counter in engines. By using RAII errors with forgotten or duplicate calls to `Engine::pause` wont happen.

In particular, this appears to solve the issue in PINK where opening the save and load dialogs from the menu fails to correctly resume the engine.

### CODE REVIEW

**Comment by henke37** [comment]
As a bonus, it also cleans up several engine specific functions that duplicate existing code.

**Comment by henke37** [comment]
Codacy has clearly never heard of variables whose very lifetime is semantically important.

**Comment by henke37** [comment]
Took care of the conflict that happened.

**Comment by sev-** [comment]
A simple glimpse at the code shows that you do not follow our code formatting guidelines in many places. Please fix.

**Comment by sev-** [comment]
...and not following the code naming conventions. This needs to be fixed as well.

**Comment by henke37** [comment]
Hopefully this should take care of all the stupid violations.

**Comment by sev-** [comment]
Thanks! merging, great change!

**Pull request merged**
