### PR TITLE
SCI: Fix typo in script_patches.cpp comment

### PR DESCRIPTION
**Pull request by amytant**
SCI: Fix typo in a comment

In a comment related to patch for CotL, "Marian" is misspelled as "Marion"

### CODE REVIEW

**Comment by sev-** [comment]
Could you please change your commit log message to conform with our commit guidelines? https://wiki.scummvm.org/index.php?title=Commit_Guidelines  like

> SCI: Fix typo in a comment

**Comment by amytant** [comment]
> Could you please change your commit log message to conform with our commit guidelines? https://wiki.scummvm.org/index.php?title=Commit_Guidelines like
> 
> > SCI: Fix typo in a comment

Done, thanks for the example. Guidelines weren't fully clear to me.

**Comment by bluegr** [comment]
> > Could you please change your commit log message to conform with our commit guidelines? https://wiki.scummvm.org/index.php?title=Commit_Guidelines like
> > > SCI: Fix typo in a comment
> 
> Done, thanks for the example. Guidelines weren't fully clear to me.

There is no fix applied yet - parhaps you didn't push it?

**Comment by amytant** [comment]
See the changed file, it's only a comment change to fix a misspelling.

**Comment by raziel-** [comment]
@amytant 

what @bluegr means is that you need to change the PR title to include the engine the fix is done

your title is
Fix typo in script_patches.cpp
but it needs to be either
SCI: Fix typo in script_patches.cpp
or
JANITORIAL: Fix typo in SCI script_patches.cpp

**Comment by sev-** [comment]
Not the PR, but the commit log message

**Comment by amytant** [comment]
Closing this PR and recreating because git is refusing to let me amend the commit message.

**Pull request closed without merging**
