### PR TITLE
fix termux build

### PR DESCRIPTION
**Pull request by john-peterson**
we have to distinguish between gradle and termux builds for android

this works in termux but i am not certain POSIX is unset in gradle

this might break the gradle build

### CODE REVIEW

**Comment by bluegr** [comment]
Please follow our [commit guidelines](https://wiki.scummvm.org/index.php?title=Commit_Guidelines) and [code formatting conventions](https://wiki.scummvm.org/index.php?title=Code_Formatting_Conventions)

**Comment by lephilousophe** [comment]
`POSIX` is defined in configure for all POSIX platforms and Android is amongst them.
This change is not valid at all and I don't understand what it tries to solve.
`__ANDROID__` is defined by the Android NDK. I don't see why it would be defined by other toolchains where the Android API is not available.

**Comment by bluegr** [comment]
This PR makes no sense at all, as @lephilousophe mentioned

The Android file system code is selectively disabled, mainly for the SAF permissions warning, but it's included in the rest of the backend code, e.g. `backends/platform/android/android.cpp`.

It's not clear why these parts of the code have been disabled for termux... is there an issue with the SAF warning? What is the issue that we're trying to solve in termux?

**Comment by lephilousophe** [comment]
Closing in favor of #6087

**Pull request closed without merging**
