### PR TITLE
SCUMM: Label v6+ subops

### PR DESCRIPTION
**Pull request by BLooperZ**
This labels the sub opcodes in switch cases of SCUMM v6+ (including HE) games

### CODE REVIEW

**Comment by AndywinXp** [comment]
Been meaning to do that for a while now, thanks 🫶

**Comment by AndywinXp** [comment]
Everything seems fine to me (I still have to test it though).

Just a curiosity: was there a specific reasoning behind e.g. in SCUMM v8 naming op 103 to `SO_ANIMATION_DEFAULT` instead of `SO_ACTOR_ANIMATION_DEFAULT`?

**Comment by BLooperZ** [comment]
Thank you!
Yes, I have tried to match the names with the mode(?) of other engine versions as much as I could,
so it'll easier for us to connect them for comparison.

**Comment by BLooperZ** [comment]
I am undecided about the force-pushed fix (renaming SO_SHADOW to SO_SPECIAL_DRAW)
SO_SHADOW is the common name that match the behaviour in all other engine versions
but it appears it might actually was renamed SO_SPECIAL_DRAW since V7 (`shadow %1` -> `special-draw %1`)
According to the SCUMM tutorial

**Comment by AndywinXp** [comment]
I thought some more time about it; from my point of view it would be prettier (but not mandatory of course!) to keep the original names when applicable, maybe with a comment next to it, e.g. we could use `SO_SPECIAL_DRAW` in v7 and keep a comment next to it which says `SO_SHADOW`.

The reasoning behind this is that IMHO it'd be better have code labeled in a way that it's self explanatory.

This applies to v8 in particular which is almost its own thing, with its high number of features which were reworked from previous versions.

Again, this is not mandatory at all, I already like the changes if you do too. 😄

**Comment by AndywinXp** [comment]
Needless to say, excellent work as always! Merging!

**Pull request merged**
