### PR TITLE
SDL: Use the name of the running target as a base for screenshot files

### PR DESCRIPTION
**Pull request by bgK**
Makes it a bit easier to recognize files in the screenshot folder, IMO.

### CODE REVIEW

**Comment by tsoliman** [comment]
How about always prefixing `scummvm` and then adding the target as a suffix if the target name is available?

So for example `scummvm-sq4-001.png`

**Comment by bgK** [comment]
> How about always prefixing scummvm and then adding the target as a suffix if the target name is available?

I don't mind either way. I'll change it if that's what people prefer. My reasoning for not having the `scummvm` prefix is that on Windows and Linux the screenshots are saved by default in a folder named `ScummVM Screenshots`. However it's true they are saved on the desktop on macOS and a `scummvm` prefix is kind of nice there. (Is saving screenshots on the desktop an accepted practice on macOS?)

**Comment by tsoliman** [comment]
Thanks!

> Is saving screenshots on the desktop an accepted practice on macOS?

Yes.
I am not an expert. That's the behavior I've observed in the built-in OS screenshot function.

**Comment by criezy** [comment]
> 
> 
> Thanks!
> 
> > Is saving screenshots on the desktop an accepted practice on macOS?
> 
> Yes.
> I am not an expert. That's the behavior I've observed in the built-in OS screenshot function.

Indeed, the macOS shortcuts to take screenshots (e.g. Crtl+Shift+3) saves them on the Desktop as well. See https://support.apple.com/en-us/HT201361 for reference.

For those I think prefixing with `scummvm-` and not just using the target would be better.

**Comment by bgK** [comment]
> For those I think prefixing with scummvm- and not just using the target would be better.

Ok, changed it.

**Comment by bluegr** [comment]
Nice work!
I do agree on the scummvm prefix, since we got that behavior on OSX.

@bgK: You mentioned that you changed the behavior, as requested, but there's no relevant commit? Perhaps you forgot to push your changes?

**Comment by bgK** [comment]
> Perhaps you forgot to push your changes?

Right.

**Comment by bluegr** [comment]
Nice work! Merging

**Pull request merged**
