### PR TITLE
COMMON: Upgrade InstallShield archive code

### PR DESCRIPTION
**Pull request by fracturehill**
This PR adds support for InstallShield cabinets with files split across
volumes. It should, in theory, also add support for format v5
cabinets with multiple volumes, but I don't have any on hand
to test with.

Code is based on unshield.

### CODE REVIEW

**Comment by sluicebox** [comment]
SCI has one game where we use InstallShield, the Polish version of Leisure Suit Larry 7. With this change, it now errors and isn't able to read the file `55200.AUD` from `DATA1.CAB`.

```
WARNING: Failed to read split file 55200.AUD!
WARNING: ResourceManager::processPatch(): failed to open 55200.AUD!
```

I confirmed that `55200.AUD` is correctly read by the prior code. I don't know anything about the InstallShield code or format; this is just the one file I could test.

**Comment by fracturehill** [comment]
@sluicebox Fixed the issue, can confirm the game boots correctly now. Thanks for testing :)

**Comment by sluicebox** [comment]
Re-tested and it works now, thanks!

**Comment by sev-** [comment]
Thank you, good stuff!

**Pull request merged**
