### PR TITLE
GOB: add loadIMG to surface

### PR DESCRIPTION
**Pull request by BJNFNE**

### CODE REVIEW

**Comment by bluegr** [comment]
Where is this used?

**Comment by BJNFNE** [comment]
its used in DEV7 games like Adibou3, but i saw other formats like BRC are also added as TODO, could we add IMG aswell to the list?

**Comment by bluegr** [comment]
Yeah but what kind of format is this image? The code you've written here will never be triggered, as no heuristic is added in `Surface::identifyImage()`

**Comment by BJNFNE** [comment]
the file format is called IMG (Image i believe) its known aswell as IMG10 (version 1.0) and IMG1.0.1 for version 1.0.1, IMG's are aswell sometimes TGA's

**Comment by sev-** [comment]
This makes no sense as it is now. It has to be (a) used (b) tested.

**Pull request closed without merging**
