### PR TITLE
Update detection_tables.h

### PR DESCRIPTION
**Pull request by Galaxy13**
Add detection for Russian version

### CODE REVIEW

**Comment by criezy** [comment]
Please see our commit guidelines on http://wiki.scummvm.org/index.php/Commit_Guidelines and change the commit message to comply with them.

Also mobygames does not list any Russian release of the game (http://www.mobygames.com/game/windows/blade-runner/release-info). Can you confirm if this is an official release or if it uses a fan translation? And if this is a fan translation it would be useful to know where we can get the patch for the translation.

**Comment by Galaxy13** [comment]
Well, it is not the offical release, but it was made by the "Fargus" company in 2000. So, there is no patch, the translated game was contributing in our country only by them, so this version is the only version on russian language.

**Comment by dreammaster** [comment]
I just happened to review this, and I'm somewhat concerned. You say it wasn't an official release.. If so, without a patcher for an official version being available on the Internet, it should be considered a pirated version, and shouldn't be supported. Indeed, whilst I can't find any marketing blurbs or anything for Fargus, one of the commenters in the following thread seems to indicate that they were reselling games they'd pirated and patched with Russian text: [thread](url=https://www.vogons.org/viewtopic.php?f=5&t=55231)

**Comment by dreammaster** [comment]
https://www.vogons.org/viewtopic.php?f=5&t=55231

**Comment by Galaxy13** [comment]
Also, they've had a studio with some voice acting, so as i understood you properly, it was like their own patch

**Comment by Galaxy13** [comment]
You can find here the information (on russian language)
https://www.old-games.ru/wiki/Blade_Runner_(переводы)

**Comment by sev-** [comment]
We do support Fargus, as they were working legally on the local market. We have dozens of their translations already in ScummVM.

The thing is that this commit does not conform to our standards, so it must be fixed before merging.

Please see http://wiki.scummvm.org/index.php/Commit_Guidelines

**Comment by dreammaster** [comment]
Ah, good that that's an issue then.

**Comment by criezy** [comment]
@sev: Thank you for confirming there is no legal issue with supporting this version.

@Galaxy13: Let us know if you need help to change the commit message.

**Comment by peterkohaut** [comment]
Sorry about that, but I was looking for a place where I can find/buy/confirm this version, because I've never seen Russian version.

**Comment by sev-** [comment]
Only on some local auctions like this one: https://meshok.net/?related=%D0%A0%D0%B0%D1%80%D0%B8%D1%82%D0%B5%D1%82+%D1%80%D0%B5%D1%82%D1%80%D0%BE+%D0%B8%D0%B3%D1%80%D0%B0%21+Blade+Runner%3A+%D0%91%D0%B5%D0%B3%D1%83%D1%89%D0%B8%D0%B9+%D0%BF%D0%BE+%D0%BB%D0%B5%D0%B7%D0%B2%D0%B8%D1%8E+%D0%B1%D1%80%D0%B8%D1%82%D0%B2%D1%8B+%284+CD%2C+%D0%A4%D0%B0%D1%80%D0%B3%D1%83%D1%81%29

**Comment by csnover** [comment]
Is the only remaining issue here the commit message, or is someone also waiting to have a copy of the Russian version to verify the table entry?

**Comment by digitall** [comment]
Closed via cherry-pick and manual fixup as ddb4c8bfd2dc89283a5a024cb716eed69913eae7.
If there is any issue with verifying / amending or blacklisting the table entry for this Russian version, it can be done later when this engine is playtested for stable.

**Pull request closed without merging**
