### PR TITLE
SCUMM: Bring the Jolly Roger fix from Monkey1 VGA to the other releases

### PR DESCRIPTION
**Pull request by dwatteau**
Monkey Island 1 has a small continuity error which was only fixed in the (quite rare) VGA floppy release.

## Explanation

At the start of Part 2, you see the Sea Monkey ship in the middle of the sea, with its Jolly Roger (pirate flag). You see this scene again when you complete the voodo recipe, and when Guybrush uses the cannon. But the Jolly Roger shouldn't be visible on the ship anymore at this point, since Guybrush must pick it in order to complete the recipe.

That's a small continuity error that the VGA v4 releases (**EDIT:** only *some* of them, see below) actually fixed. But that fix was lost when the game was ported to SCUMM v5. (The Special Edition has this error too. The Ultimate Talkie Edition fixed it.)

In that scene, the flag is drawn by the entry script of room 87. In the EGA release, it's done unconditionally:

```
[0000] (48) if (VAR_VIDEOMODE == 4) {
[0007] (33)   RoomColor(0,3)
[000D] (**) }
[000D] (0C) Resource.lockCostume(49);
[0010] (0C) Resource.loadCostume(49);
[0013] (13) ActorOps(9,[Init(),Costume(49),Palette(0,6)]);
[001C] (5D) setClass(9,[150,148]);
[0026] (11) animateCostume(9,248);
[0029] (13) ActorOps(9,[Elevation(-108)]);
[002F] (2D) putActorInRoom(9,87);
[0032] (01) putActor(9,156,0);
[0038] (11) animateCostume(9,9);
[003B] (00) stopObjectCode();
```

but some VGA v4 releases added a condition:

```
[0000] (48) if (VAR_VIDEOMODE == 4) {
[0007] (33)   RoomColor(0,3)
[000D] (**) }
[000D] (68) VAR_RESULT = isScriptRunning(119); # <==
[0011] (A8) if (VAR_RESULT) {
[0016] (13)   ActorOps(9,[Init(),Costume(49),Palette(0,6)]);
[001F] (5D)   setClass(9,[150,148]);
[0029] (11)   animateCostume(9,248);
[002C] (13)   ActorOps(9,[Elevation(-108)]);
[0032] (2D)   putActorInRoom(9,87);
[0035] (01)   putActor(9,156,0);
[003B] (11)   animateCostume(9,9);
[003E] (**) }
[003E] (00) stopObjectCode();
```

Script 119 (or 122 in v5 releases) is the script printing the narrative description during the very first scene of Part 2 ("The crew begins to plan their voyage"…). 

So this PR just tries to replicate this check.

⚠️ **HOWEVER** ⚠️ I'm calling `stopObjectCode()`, since I just want to skip all the (different) opcodes until the end of that script (there's no safe/easy value to increment `_scriptPointer` with, as there are so many variants of that game). I don't know enough about the SCUMM engine to know if it's safe to `stopObjectCode()` in the middle of `o5_actorOps()`, though! It seems to work, but if someone with enough SCUMM experience can tell whether this is OK…

## How to test

Ideally, play the whole Part 2, if you know it well (it's not very long). Unfortunately, the closest boot params appear to miss the very first scene of this chapter…

You could also:

* `room 14`
* for v4: `script 105 run`, or for v5: `script 108 run` (all of this in the debugger)
* make sure that there's no visible Jolly Roger in the next scene
* complete the cannon puzzle, and check again that there's no flag when Guybrush flies to Monkey Island.

but that shortcut is not the real thing (so the Ultimate Talkie test will fail, since it does a different kind of check), and you'll miss the first scene where the flag *should* appear.

I've tested the DOS/EGA, DOS/VGA, DOS/CD, Ultimate Talkie and Amiga releases. FM-TOWNS and Macintosh tests would be welcome, although v5+ games are usually almost identical on all ports.

### CODE REVIEW

**Comment by eriktorbjorn** [comment]
I should be able to test the Mac versions, but it may be a couple of days. (I have two of them, but I don't know if there are any scripting differences between them.)

**Comment by dwatteau** [comment]
Funny thing: my English VGA floppy release already had a fix for this continuity error, but my French VGA floppy release didn't… yet another case of an original script error only being fixed in some very specific releases! That's also something I've seen in Loom (with the shepherds) and Sam & Max (some actions at the Savage Jungle Inn).

Anyway, I'm not excluding MONKEY1\_VGA anymore, then.

**Comment by eriktorbjorn** [comment]
The Loom bit of the second commit is just indentation, right?

**Comment by eriktorbjorn** [comment]
I've tried it with one of my Mac versions now, and it seems to work: With the patch, the flag is visible when you sail from Mêlée Island, but not when you pass out from the voodoo recipe.

Without the patch, the flag is visible in both cases.

Here's what room 87's entry script looks like in this version:

```
[0000] (0C) Resource.lockCostume(49);
[0003] (0C) Resource.loadCostume(49);
[0006] (13) ActorOps(9,[Init(),Costume(49),Palette(0,6),IgnoreBoxes(),NeverZClip()]);
[0011] (11) animateCostume(9,248);
[0014] (13) ActorOps(9,[Elevation(-108)]);
[001A] (2D) putActorInRoom(9,87);
[001D] (01) putActor(9,156,0);
[0023] (11) animateCostume(9,9);
[0026] (00) stopObjectCode();
```

I don't know either what calling stopObjectCode() in mid-script does. If the size of the script resource is known, I guess another way would be to modify scriptPointer to point to the one at the end of the script, but is that better? I don't know.

**Comment by dwatteau** [comment]
> The Loom bit of the second commit is just indentation, right?

Yes, but it's been fixed in the master branch in the meantime, so I can remove that from this PR.

> I've tried it with one of my Mac versions now, and it seems to work: With the patch, the flag is visible when you sail from Mêlée Island, but not when you pass out from the voodoo recipe or when you use the cannon.
> 
> Without the patch, the flag is visible in all three cases.

OK, thanks for this test!

> I don't know either what calling stopObjectCode() in mid-script does. If the size of the script resource is known, I guess another way would be to modify scriptPointer to point to the one at the end of the script, but is that better? I don't know.

The problem is that the size of this script appears to change a bit in every version. And in the floppy VGA French version it's smaller than in the VGA English version, so maybe it changed at some point between the 1.0/1.1/1.2 releases…

So yeah, if one of our SCUMM lords know if calling `stopObjectCode();` is legal in this case, that would be very nice! 😅

**Comment by BLooperZ** [comment]
IIRC, I've seen conditional `stopObjectCode();` in some script either on MI or MI2.
I'll check which script was it

**Comment by dwatteau** [comment]
> IIRC, I've seen conditional `stopObjectCode();` in some script either on MI or MI2.
> I'll check which script was it

Thanks! Yes, I believe it's legal to have it in the middle of a script, but I'm wondering if our own SCUMM parsing process is OK if I call our `stopObjectCode()` method there 🤔 It looks OK, but I'm not sure of all the possible side-effects.

**Comment by BLooperZ** [comment]
Checked the game scripts, it seems the canonical way is by calling `stopScript(0)`
which in turn does call to `stopObjectCode()`
https://github.com/scummvm/scummvm/blob/master/engines/scumm/script_v5.cpp#L2745-L2765

example from FOA:
```
Script# 207
[0000] (A8) if (Bit[224]) {
[0005] (1A)   Bit[224] = 0;
[000A] (A8)   if (Bit[17]) {
[000F] (2D)     putActorInRoom(2,0);
[0012] (**)   }
[0012] (18) } else {
[0015] (36)   walkActorToObject(1,36);
[0019] (43)   Var[445] = getActorX(36);
[001E] (23)   Var[446] = getActorY(36);
[0023] (1A)   Bit[16] = 0;
[0028] (80)   breakHere();
[0029] (A8)   if (Bit[16]) {
[002E] (62)     stopScript(0);
[0030] (**)   }
[0030] (D6)   VAR_RESULT = getActorMoving(VAR_EGO);
[0035] (28)   unless (!VAR_RESULT) goto 0028;
[003A] (C3)   Var[351] = getActorX(VAR_EGO);
[003F] (A3)   Var[352] = getActorY(VAR_EGO);
[0044] (AC)   Exprmode Var[442] = (Var[445] - Var[351]);
[004F] (AC)   Exprmode Var[443] = (Var[446] - Var[352]);
[005A] (78)   if (Var[442] < 0) {
[0061] (AC)     Exprmode Var[442] = (0 - Var[442]);
[006C] (**)   }
[006C] (78)   if (Var[443] < 0) {
[0073] (AC)     Exprmode Var[443] = (0 - Var[443]);
[007E] (**)   }
[007E] (1A)   Var[444] = 0;
[0083] (04)   if (Var[442] <= 10) {
[008A] (04)     if (Var[443] <= 10) {
[0091] (1A)       Var[444] = 1;
[0096] (**)     }
[0096] (**)   }
[0096] (A8)   unless (Var[444]) goto 014C;
[009B] (48)   if (Bit[17] == 1) {
[00A2] (36)     walkActorToObject(2,36);
[00A6] (AE)     WaitForActor(2);
[00A9] (2D)     putActorInRoom(2,0);
[00AC] (**)   }
[00AC] (48)   if (Bit[74] == 1) {
[00B3] (A8)     if (Var[233]) {
[00B8] (48)       if (Bit[210] == 0) {
[00BF] (42)         chainScript(213,[]);
[00C2] (**)       }
[00C2] (**)     }
[00C2] (**)   }
[00C2] (**) }
[00C2] (40) cutscene([2]);
[00C7] (32) setCameraAt(550);
[00CA] (2D) putActorInRoom(1,0);
[00CD] (2E) delay(15);
[00D1] (4C) soundKludge([269,44,0,240]);
[00DF] (1E) walkActorTo(5,575,112);
[00E5] (AE) WaitForActor(5);
[00E8] (C0) endCutscene();
[00E9] (1A) Var[315] = 2;
[00EE] (48) if (Bit[210] == 1) {
[00F5] (1A)   Var[316] = 2;
[00FA] (1A)   Bit[87 + 8] = 0;
[0101] (1A)   Bit[87 + 0] = 0;
[0108] (1A)   Bit[87 + 3] = 0;
[010F] (1A)   Bit[87 + 1] = 0;
[0116] (1A)   Bit[87 + 2] = 0;
[011D] (1A)   Bit[87 + 4] = 1;
[0124] (1A)   Bit[87 + 5] = 1;
[012B] (2D)   putActorInRoom(2,0);
[012E] (72)   loadRoom(75);
[0130] (**) }
[0130] (48) if (Bit[74] == 1) {
[0137] (1A)   Var[316] = 2;
[013C] (1A)   Bit[87 + 8] = 1;
[0143] (72)   loadRoom(75);
[0145] (**) }
[0145] (1A) Var[316] = 1;
[014A] (72) loadRoom(75);
[014C] (A0) stopObjectCode();
END
```

**Comment by eriktorbjorn** [comment]
I've tested my other Mac version now. The workaround appears fine there too.

I don't know what the difference between the two versions actually are.

One is from the "LucasArts Mac CD Game Pack" and has six data files named MONKEY1.000 through MONKEY1.005. This version requires the copy protection code wheel (which unfortunately I did not get with my second-hand copy of the disc).

The other is from the "LucasArts Mac CD Game Pack II" and has two data files named MONKEY1.000 and MONKEY1.001. This version does not require the copy protection code wheel. Actually, none of the games on that disc is copy protected. I guess they wanted to save on printing cost for it.

**Comment by bluegr** [comment]
Nice and clean workaround for this continuity error! Thanks, merging

**Pull request merged**
