### PR TITLE
TONY: Fix unaligned accesses

### PR DESCRIPTION
**Pull request by lephilousophe**

### CODE REVIEW

**Comment by eriktorbjorn** [comment]
Speaking of type discrepancies, one thing that struck me as odd when I tried (and failed) to make a similar change was that _num in Expression is defined as "int", but in in some (not all) places it's assumed to be int32. Should that be changed as well?

**Comment by lephilousophe** [comment]
Indeed, the type is strange.
I didn't look at this type because it was not tied to the problem.

This is now fixed.

**Comment by dwatteau** [comment]
Thank you for your work on this!

Unfortunately, I'm still hitting a SIGBUS with this PR, on the impacted mips64el system:
[tony-gdb.txt](https://github.com/scummvm/scummvm/files/11994945/tony-gdb.txt)

However, the coroutine.h change alone appears to help the Tinsel engine which has similar alignment issues on this device (see https://bugs.scummvm.org/ticket/11972). I'd need more time to test my various Discworld games & demos to see how far it improves things, though.

**Comment by dwatteau** [comment]
@lephilousophe Here you go for the updated GDB output asked over Discord
[tony-gdb-disassemble-and-print-this.txt](https://github.com/scummvm/scummvm/files/11995042/tony-gdb-disassemble-and-print-this.txt)

FWIW it's a `-O0 -g` build.

**Comment by lephilousophe** [comment]
Merging now

**Pull request merged**
