### PR TITLE
AGS: Implementation of upstream Freetype 2.1.3

### PR DESCRIPTION
**Pull request by tag2015**
This PR adds the upstream AGS implementation of Freetype (v. 2.1.3) to finally solve the font differences found in Maniac Mansion Deluxe, Zniw Adventure, Dreams in the Witch House and others.

Thanks to @antoniou79 for his implementation in https://github.com/antoniou79/scummvm/tree/ags-with-freetype-2-1-3!

There are no functional differences compared to upstream. The changes are as follow:
- Moved base freetype .h/.cpp files to main dir
- Moved modules .h/.cpp files to /modules
- Astyled / added ScummVM license to most files
- Disabled some optional drivers (these should cover 99% of games and could be easily reenabled)
- Removed unused cache and memory debugging facility
- Added namespaces
- Added casts to fix warnings

Tested with no problems on Win/Linux, also tried PowerPC Ubuntu through qemu.

Should be tested on Amiga, which may require some fixes. I left the original platform-specific files in /build if needed.

### CODE REVIEW

**Comment by tag2015** [comment]
For anybody testing the PR, here are some screenshots of how the fonts look in current master and how they should look after the PR is applied:

Maniac Mansion Deluxe - see "k" and "v" letters
scummvm-maniacmansiondeluxe-00000
(correct)
scummvm-maniacmansiondeluxe-00001
All games using this font should be fixed as well (there are many)

Shards of God (available on itch.io)
scummvm-shardsofgod-00000
(correct)
scummvm-shardsofgod-00001

Suspicious Mind [link](https://www.adventuregamestudio.co.uk/site/games/game/2337-suspicious-mind/)
scummvm-suspiciousmind-00000
(correct)
scummvm-suspiciousmind-00001
Dreams in the Witch House, Broken Windows... use the same font and should be fixed as well

**Comment by criezy** [comment]
There are a bunch of symbols that are defined in the global namespace and conflict with those from the free type library used to compile ScummVM.

On iOS (with freetype 2.10.4) this causes a crash when starting ScummVM as it jumps from the external free type library to the one in the AGS engine:
image
Steps 2, 3, and 4 are in the external freetype library, while step 1 is in the one in the AGS engine.

On macOS, building with the dynamic freetype library seems to work, but when we create a bundle it links with the static freetype library, and this results in many linkage errors of the type:
```
duplicate symbol '_FT_MulDiv' in:
    /usr/local/lib/libfreetype.a(ftbase.o)
    engines/ags/libags.a(ftcalc.o)
```

This gives us a list of the symbols defined in the global namespace and that either need to be moved to the `AGS3:: FreeType213` namespace, or need to be renamed (e.g. changing `FT_` to `FT213`).
Here is the list of those symbols: [freetype_symbols.txt](https://github.com/scummvm/scummvm/files/12233203/freetype_symbols.txt)

**Comment by tag2015** [comment]
Thanks. could you try again now? The namespace should work properly now and the methods shouldn't clash with the system ones

**Comment by elasota** [comment]
I tested this on Windows and it is crashing.  The problem appears to be that ftinit.cpp is defining FT_USE_MODULE to use `extern "C"` which causes it to use the symbols in the global C namespace instead of `AGS3::FreeType213` which is in turn causing it to use the symbols in the latest-version FreeType instead of 2.1.3, and incompatibilities between the two are causing it to crash.

**Comment by larsamannen** [comment]
@tag2015 I've tested your latest changes but that still resulted in a crash (a bit different one). However, adding the commit by @elasota in https://github.com/tag2015/scummvm/pull/1 made it run on my iOS simulator device and I was able to test this PR. The result is looking good.
image

**Comment by bluegr** [comment]
Out of curiosity, why do we need a different FreeType version for AGS? Can't we use the one we got in common code?

**Comment by antoniou79** [comment]
> Out of curiosity, why do we need a different FreeType version for AGS? Can't we use the one we got in common code?

FreeType 2.1.3 is the version that upstream AGS uses (integrated to their code). It's as of yet the last version of FreeType that renders the glyphs exactly as intended in AGS and has no side-effects (eg. to text wrapping). Every version of FreeType after 2.1.3 up to 2.13.0 (tested) has some issue with glyphs rendering and we have a few bug reports about those issues (most consolidated to one afaik here: https://bugs.scummvm.org/ticket/12940 )

Upstream AGS has an open discussion about migrating to a newer FT but this seems to be a goal for the AGS 4 version:
https://github.com/adventuregamestudio/ags/issues/1528

To be honest, I've looked into this issue for as much as time I'm willing to spend on it, checking multiple more recent versions of FreeType, testing with flags and settings that could potentially fix issues (they did not), debugging to spot the main source of the issue (in the most recent FT some metrics for a few of the glyphs are calculated differently) and finally going with an experimental integration of FT 2.1.3 in parallel with the external (my work was put together quickly and was rather preliminary but the tests showed that the outstanding issues were resolved that way). 

This PR is a more methodical approach to the same solution.

Another ScummVM developer (OneEightHundred) has written that they may look into the matter further, separating and re-using only the FT 2.1.3 autohinter (see Discord: https://discord.com/channels/581224060529148060/808781947002290256/1136313441267753030) and maybe they'll have some luck with that.

**Comment by tag2015** [comment]
I'm still waiting for feedback on Amiga, but Mac/iOS should be fine now, @criezy when you have time could you give it a test?

I hope to have this PR merged (it may need some more polishing) for various reasons:
1. We are almost in sync with branch 3.6.0 of upstream AGS (which is only getting minor bugfixes now). Including this Freetype version we can match upsteam's behavior almost perfectly in ScummVM 2.8.0
2. Using the AGS Freetype version or the system one can simply be toggled using the USE_FREETYPE2_213 define
3. OneEightHundred's idea is interesting, but it will require testing and with AGS's huge library it will take time (and some of the font issues aren't immediately noticeable in all games). And we'll probably need to spend some time to test PR [5144](https://github.com/scummvm/scummvm/pull/5144) too if it has to go in 2.8.0

**Comment by sev-** [comment]
Awesome work! I just tested on macOS, compiles, links and works great. I tested with gobliiins5.

There are only several warnings:

```
engines/ags/lib/freetype-2.1.3/ftcalc.cpp:243:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register FT_UInt32 lo, hi, max;
        ^~~~~~~~~
engines/ags/lib/freetype-2.1.3/ftcalc.cpp:243:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register FT_UInt32 lo, hi, max;
        ^~~~~~~~~
engines/ags/lib/freetype-2.1.3/ftcalc.cpp:243:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register FT_UInt32 lo, hi, max;
        ^~~~~~~~~
3 warnings generated.
engines/ags/lib/freetype-2.1.3/ftobjs.cpp:532:3: warning: cast from 'const char *' to 'void *' drops const qualifier [-Wcast-qual]
                FT_FREE(face->internal->postscript_name);
                ^
./engines/ags/lib/freetype-2.1.3/ftmemory.h:106:28: note: expanded from macro 'FT_FREE'
#define FT_FREE(_pointer_) FT_MEM_FREE(_pointer_)
                           ^
./engines/ags/lib/freetype-2.1.3/ftmemory.h:75:57: note: expanded from macro 'FT_MEM_FREE'
#define FT_MEM_FREE(_pointer_) FT_Free(memory, (void **)&(_pointer_))
                                                        ^
1 warning generated.
engines/ags/lib/freetype-2.1.3/modules/cff/cffcmap.cpp:173:5: warning: cast from 'const char *' to 'void *' drops const qualifier [-Wcast-qual]
                                FT_FREE(gname);
                                ^
engines/ags/lib/freetype-2.1.3/modules/sfnt/sfdriver.cpp:151:8: warning: cast from 'const char *' to 'void *' drops const qualifier [-Wcast-qual]
                if (!FT_ALLOC(result, name->stringLength + 1)) {
                     ^
./engines/ags/lib/freetype-2.1.3/ftmemory.h:104:50: note: expanded from macro 'FT_ALLOC'
#define FT_ALLOC(_pointer_, _size_) FT_SET_ERROR(FT_MEM_ALLOC(_pointer_, _size_))
                                                 ^
./engines/ags/lib/freetype-2.1.3/ftmemory.h:74:75: note: expanded from macro 'FT_MEM_ALLOC'
#define FT_MEM_ALLOC(_pointer_, _size_) FT_Alloc(memory, _size_, (void **)&(_pointer_))
                                                                          ^
engines/ags/lib/freetype-2.1.3/modules/sfnt/sfdriver.cpp:157:5: warning: cast from 'const char *' to 'void *' drops const qualifier [-Wcast-qual]
                                FT_FREE(result);
                                ^
engines/ags/lib/freetype-2.1.3/modules/sfnt/sfdriver.cpp:184:8: warning: cast from 'const char *' to 'void *' drops const qualifier [-Wcast-qual]
                if (!FT_ALLOC(result, len + 1)) {
                     ^
./engines/ags/lib/freetype-2.1.3/ftmemory.h:104:50: note: expanded from macro 'FT_ALLOC'
#define FT_ALLOC(_pointer_, _size_) FT_SET_ERROR(FT_MEM_ALLOC(_pointer_, _size_))
                                                 ^
engines/ags/lib/freetype-2.1.3/modules/sfnt/sfdriver.cpp:192:5: warning: cast from 'const char *' to 'void *' drops const qualifier [-Wcast-qual]
                                FT_FREE(result);
                                ^
```

I think, it is ready to be merged. Please ping me when you feel like it.

**Comment by tag2015** [comment]
Thanks a lot for reviewing @sev- ! I think the PR can be merged, the remaining warnings (and possible problems with Amiga) can be addressed in-tree

**Comment by elasota** [comment]
I think the one thing that may be worth holding off on this is that, based on the analysis I've done, I think we may be able to do this by pulling in FreeType 2.1.3's autohint module instead of the entire thing.

The auto-hint process is, basically, load the glyph with hinting disabled, and then process it using the auto-hint module, with later rendering done in monochrome mode.

The loading and rendering parts are defined quite strictly and unlikely to vary across versions.  However, the auto-hinting algorithm has undergone some changes, some of which are responsible for the difference in behavior that we're seeing.  It is, unfortunately, not possible to replicate the 2.1.3 behavior with 2.10.4 because some of the information needed to do so is lost.

I'm going to investigate doing that later this week whether this is merged or not.

**Comment by tag2015** [comment]
I can't really say if this approach is feasible or not. But if it's just a matter of using the old autohinter module with the newer freetype releases, I wonder why upstream haven't done so already. Maybe it would be a good idea to contact them through Discord?
In any case when you have something ready I can help testing with various games (commercial or freeware)

**Comment by raziel-** [comment]
Sorry for the massive delay.

Tested on AmigaOS4
Builds perfectly fine
i only quickly tested "Suspicious Minds" and the font is nor broken in any way

**Comment by sev-** [comment]
@elasota I am just thinking, is the FreeType hinting system pluggable? E.g. is there a technical API for replacing just that part?

**Comment by sev-** [comment]
As discussed on Discord, there is a way. So, awaiting more progress...

**Comment by tag2015** [comment]
@elasota's wip is here
https://github.com/elasota/scummvm/tree/ags_freetype_213
I got it to build (with minor changes) on mingw. 
So far I couldn't notice relevant differences, but I tested only some games (the screenshot - spot differences - repeat process is quite time consuming)

The initial idea was to bring in the entire freetype to rule out any possibile incompatibiliy, but the partial implementation is fine i guess (hoping it doesn't lead to bugs that are hard to spot and fix)
Leaving the final decision to the leads...

**Comment by sev-** [comment]
I do not understand that branch with hinting. E.g. it is too WIP for me to evaluate now.

Indeed, I am a bit concerned what will happen if FreeType tomorrow breaks something else again. On the other hand, 5k lines are much better than 85k lines, if I understood @elasota's patch correctly.

**Comment by elasota** [comment]
> I do not understand that branch with hinting. E.g. it is too WIP for me to evaluate now.

The parts in "ftah213" are the parts intended to keep, those are pulled from the FreeType 2.1.3 autohinter module.  I believe the future breakage risk is low because of how it works.

The 2.1.3 autohinter is only using types from the public FreeType API except for the subglyph things.  However, the subglyph code is actually unused, because it requires setting the `FT_LOAD_NO_RECURSE` flag, and the code path that would do that in `ah_hinter_load_glyph` is disabled.  Instead, it is forcing the load flags to `FT_LOAD_NO_SCALE | FT_LOAD_IGNORE_TRANSFORM`

The way it works is that it loads the glyph with all transformations disabled, which I think will have to stay stable because that case loads everything verbatim from the TrueType file, then applies its own hinting algorithm and replaces the metrics and outline points with that.

Later, it feeds it to the monochrome renderer, which also has well-defined behavior required for proper rending.

Because the outline loading and rendering are so rigidly-defined in their behavior, I don't see much room for them to potentially break in future versions of FreeType.

**Pull request closed without merging**
