### PR TITLE
GRAPHICS: Allow specifying separate xdpi and ydpi values in loadTTFFont

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by bluegr** [comment]
Is there a use case for this? Are there fonts out there with multiple DPI values?

**Comment by ccawley2011** [comment]
> Is there a use case for this? Are there fonts out there with multiple DPI values?

This is for a work in progress engine to support screen modes with non-square pixels.

**Comment by bluegr** [comment]
Do we need to support such screen modes at the engine level? Can't we use OpenGL's aspect ratio functionality for such cases?

**Comment by ccawley2011** [comment]
The [Noot engine](https://github.com/ccawley2011/scummvm/tree/noot) currently supports four screen resolutions. The medium (640x256) resolution uses non-square pixels, which matches the aspect ratio of the animations (since most games were designed for modes 12 or 15 on RISC OS). By selecting medium resolution, animations can be rendered without scaling and the backend can take care of aspect ratio correction, which is useful for lower end platforms.

**Comment by sev-** [comment]
Thank you!

**Pull request merged**
