### PR TITLE
SAGA: Fixes for IHNM and ITE after switch to common macbinary parser

### PR DESCRIPTION
**Pull request by phcoder**

### CODE REVIEW

**Comment by dwatteau** [comment]
@phcoder Thanks, with this change (and PR #4592 applied too), [Trac#14002](https://bugs.scummvm.org/ticket/14002) is not triggered anymore, but I now get a crash after choosing a character:

```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x0000000100085b14 scummvm`Saga::SndRes::load(Saga::ResourceContext*, unsigned int, Saga::SoundBuffer&, bool) + 584
    frame #1: 0x0000000100086fac scummvm`Saga::SndRes::getVoiceLength(unsigned int) + 96
    frame #2: 0x000000010002dbdc scummvm`Saga::Actor::handleSpeech(int) + 700
    frame #3: 0x00000001000390ec scummvm`Saga::Actor::direct(int) + 172
    frame #4: 0x000000010006eea0 scummvm`Saga::SagaEngine::run() + 3416
    frame #5: 0x0000000100011a78 scummvm`runGame(Plugin const*, Plugin const*, OSystem&, Common::String const&) + 2576
    frame #6: 0x0000000100010220 scummvm`scummvm_main + 4424
    frame #7: 0x000000010000c37c scummvm`main + 204
    frame #8: 0x000000010066908c dyld`start + 520
```

(it's the release from GOG which triggers the SAMPLE.AD/SAMPLE.OPL warning)

**Comment by einstein95** [comment]
From reading the comments you refer to a "name resource fork" and "name fork", shouldn't these just be "resource fork"?

**Comment by phcoder** [comment]
> From reading the comments you refer to a "name resource fork" and "name fork", shouldn't these just be "resource fork"?

Just a missing comma. There is a name field in macbin header

**Comment by dwatteau** [comment]
…and with your new commit it all looks good now! Thanks.

**Pull request merged**
