### PR TITLE
KYRA: Add support for Chinese LoL

### PR DESCRIPTION
**Pull request by phcoder**

### CODE REVIEW

**Comment by athrxx** [comment]
Very nice. At first glance, I don't see any issues, but of course we have to test it a bit...
Fortunately, the changes are much less than with EOB II.

**Review by sev- — CHANGES_REQUESTED** [review]
Looks good, it just has to be rebased now

**Comment by phcoder** [comment]
> Looks good, it just has to be rebased now

Rebased but master is broken. Will rebase again after it's fixed

**Comment by athrxx** [comment]
I did not encounter any regressions, so I guess this can be merged...

**Pull request merged**
