### PR TITLE
Cloud: [GSOC] Pull request for the cloud API

### PR DESCRIPTION
**Pull request by rsk1coder99**
Hi,
I was informed issuing a PR is compulsary according to GSOC rules, so I am creating one.
Thanks and regards,
Rupinder Singh

### CODE REVIEW

**Comment by lordhoto** [comment]
Pretty cool idea to start directly with your project. But I think this makes the chances of this getting merged at this point less likely since this requires more in-depth API discussion (and of course there is still a chance another student might work on this who would go for a different approach).

On a general note:
Please take another look at our http://wiki.scummvm.org/index.php/Code_Formatting_Conventions and http://wiki.scummvm.org/index.php/Commit_Guidelines.
For example, we usually prefer one precise module. And FS and SAVE are rather non-standard module names.
Also, please do not include unnecessary merge commits in your pull request.

**Comment by rsk1coder99** [comment]
Hi,
Thanks a ton for looking into the work and giving valuable feedback:
1) Peter made it clear that any work done would be possibly merged only toward the end of GSOC.
2) I made sure coding conventions are followed everywhere. I even had feedback from Eugene to correct these kinds of errors.
3) I made changes to multiple backends in a single commit. So, while naming the commits, I had to include names of all modules where changes were made. Please let me know if this is wrong, & should be done in another way.
4) I merged master onto my branch to ensure there was no merge conflict to the pull request. This demonstrates that anyone trying to merge this branch onto master wouldn't have to go through the hassle of resolving the merge conflicts.

**Comment by lordhoto** [comment]
> 2) I made sure coding conventions are followed everywhere. I even had feedback from Eugene to correct these kinds of errors.

There still are some very obvious mistakes. You use spaces for indentation, your include guard names don't match the rest of our code base, in virtual function declaration if you use "=0" i.e. you miss the spaces, you sometimes align the star in pointers to the type name.

> 3) I made changes to multiple backends in a single commit. So, while naming the commits, I had to include names of all modules where changes were made. Please let me know if this is wrong, & should be done in another way.

I can't you see to make changes to any specific backend to be honest. At any rate, if you touch code for a specific purpose mark the mainly affected module here or use "BACKENDS" (or similar more generic names) to suggest this is a generic change.

> 4) I merged master onto my branch to ensure there was no merge conflict to the pull request. This demonstrates that anyone trying to merge this branch onto master wouldn't have to go through the hassle of resolving the merge conflicts.

You can do this locally to test whether it's working, but do not push this into your branch unless you use actual changes from master or you need to fix things based on differences from master.

**Comment by rsk1coder99** [comment]
Hi again @lordhoto ,
> There still are some very obvious mistakes. You use spaces for indentation, your include guard names don't match the rest of our code base, in virtual function declaration if you use "=0" i.e. you miss the spaces, you sometimes align the star in pointers to the type name. 

I fixed these in an additional commit. My .vimrc was not upto the mark :) Let me know if the include guard names are still not correct. I couldn't find any rules regarding it.

> I can't see you make changes to any specific backend to be honest. At any rate, if you touch code for a specific purpose mark the mainly affected module here or use "BACKENDS" (or similar more generic names) to suggest this is a generic change.

Ok, I'll take care of that in the future. Currently, a rebase is creating total mess due to diverging merged branches :_| .

> You can do this locally to test whether it's working, but do not push this into your branch unless you use actual changes from master or you need to fix things based on differences from master.

Yes, I merged it precisely for the reason to fix things based on differences from the master.

PS: I am currently on a vacation upon a hilltop, desperately trying to get mobile Internet signals for a git push :_D

**Pull request closed without merging**
