### PR TITLE
COMPOSER: Support GMM saving/loading and load from launcher

### PR DESCRIPTION
**Pull request by upthorn**
Adds fairly robust savegame support to the composer engine module.

### CODE REVIEW

**Comment by bluegr** [comment]
Any updates on this?

**Comment by sev-** [comment]
Fuzzie, I think we may merge it, so the code will not get rot. Any objections?

**Comment by sev-** [comment]
@upthorn Could you please update so it merges cleanly and I finally merge? Thanks for your good work!

**Comment by sev-** [comment]
Closing for the sake of #851

**Pull request closed without merging**
