### PR TITLE
ANDROIDSDL: fixed switching to capital letter

### PR DESCRIPTION
**Pull request by lubomyr**

### CODE REVIEW

**Comment by wjp** [comment]
It looks like you may have left some remnants of debugging code in there.

**Comment by lubomyr** [comment]
Fixed, debugging code was deleted.

**Comment by bluegr** [comment]
It would be good if you added a small comment, explaining why this implementation is different from the default one.

**Comment by lubomyr** [comment]
In compare with original implementation of mapKey function were removed two lines, which with unknown reason broken switching to capital letter in text input.

removed lines:
	} else if (unicode) {
return unicode;

**Pull request merged**
