### PR TITLE
GOB: added wdemo.scn to kScriptSourceFile

### PR DESCRIPTION
**Pull request by BJNFNE**

### CODE REVIEW

**Comment by bluegr** [comment]
Which demo has this game file?

**Comment by BJNFNE** [comment]
> Which demo has this game file?

A Game demo of Urban Runner

**Comment by bluegr** [comment]
Thanks! Can you provide a link to that demo?
Is it playable with this change?

**Comment by BJNFNE** [comment]
@bluegr  http://sierrahelp.com/Files/Demos/UrbanRunnerDemoWin(URBANDEMO).zip

**Comment by sev-** [comment]
Is it playable with this change?

**Comment by BJNFNE** [comment]
> Is it playable with this change?

i am closing this,  i didn't check properly the text of the Script, it wants to open a VMD that not exists, so it fails to start over the SCN Script, i realized that the main part is done by wdemo.s24.

**Pull request closed without merging**
