### PR TITLE
CI: Move Linux builds to GitHub Actions, and remove Travis CI builds

### PR DESCRIPTION
**Pull request by ccawley2011**
~~This includes the changes from PR #2957.~~

### CODE REVIEW

**Comment by aquadran** [comment]
I though we support c+11 now

**Comment by SupSuper** [comment]
Looks good to me. Travis support for OSS has been precarious, once you get migrated to travis-ci.com you get heavily limited by the "free tier": https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works
And Github Actions can cover the platforms our buildbot can't (native MSVC, XCode, etc).

**Comment by sev-** [comment]
I really wonder, why using GitHub facilities when we have our own buildbot? E.g. it is nice of them providing this service, but our project is really heavy and in my opinion, our needs for CI are covered by ourselves.

Since you guys are spending time on updating these, it looks that I am missing the point. Could you please help me to understand?

**Comment by criezy** [comment]
To me it seems to nicely complement our buildbot:
 - I assume it does (or can do) builds on pull requests before they are merged.
 - It has compilation with Visual Studio and Xcode, which we don't have on buildbot.

**Comment by SupSuper** [comment]
Right, it's purely a complement, not a replacement. Our buildbot doesn't support native Windows/OSX machines, and doesn't test create_project, so it's frequently broken.

**Comment by orgads** [comment]
Suggestion: You can pre-build a docker container with all the dependencies, and use it for building.

**Comment by ccawley2011** [comment]
> Suggestion: You can pre-build a docker container with all the dependencies, and use it for building.

I'd prefer to keep the workflow as simple as possible, and installing the needed packages only takes 20-30 seconds, so I don't think this would be worthwhile.

**Comment by SupSuper** [comment]
Travis builds are dead as of June 15th, so this should probably be merged if we wanna replace it.

**Pull request merged**
