### PR TITLE
ANDROID: Bundle CA certificates and cleanups

### PR DESCRIPTION
**Pull request by lephilousophe**
Bundle CA certificates and make use of it instead of not verifying peers.

Cleanup configure to not define macros pointing to `/usr/local` and remove the `ANDROID_PLAIN_PORT` define which is not used anymore.

### CODE REVIEW

**Review by antoniou79 — APPROVED** [review]
Looks good to me. I haven't tried building it, but it seems good to merge. 

I guess my only question is, where will we be defining DIST_ANDROID_CACERT_PEM? Will it be in the docker image with the android toolchain or external to that (downloaded by the one who builds the apks?)

**Review by LittleToonCat — APPROVED** [review]
Just tested SCUMM HE lobby connection with it, works beautifully. Thank you!

Good to merge. :+1:

**Comment by lephilousophe** [comment]
> I guess my only question is, where will we be defining DIST_ANDROID_CACERT_PEM? Will it be in the docker image with the android toolchain or external to that (downloaded by the one who builds the apks?)

In the buildbot, it's (already) defined in the platform definition as an environment variable.

In the toolchain you can use `export DIST_ANDROID_CACERT_PEM="/etc/ssl/certs/ca-certificates.crt"` before building: this will use Debian certificates.
If you don't define this variable, the `cacert.pem` from curl is downloaded (coming from Mozilla).
It can be refreshed later (if you don't run `make clean`) by running `make androidcacert`.

This way, we avoid fetching from Internet the certificates if we don't need to, but it's also possible for those who prefers it.

**Comment by antoniou79** [comment]
Thank you for clarifying.

**Pull request merged**
