### PR TITLE
WINTERMUTE: Detect more games

### PR DESCRIPTION
**Pull request by lolbot-iichan**
1. WINTERMUTE: Add detection for Italian version of thelostcrowngha

Fixes https://bugs.scummvm.org/ticket/11383

2. WINTERMUTE: Add detection and keymap for "Myth: A Guff's Tale"

"Myth: A Guff's Tale" is a cutscene-rich point and click game about a troll fixing a labyrinth in a dreamworld. 
SOLO DESIGN decided to distribute "Myth: A Guff's Tale" for free since game's co-creator Phil Argent passed away...
Download it here: https://www.kartridge.com/games/solodesign/myth-a-guffs-tale
UPD: game can be download without installing Kartridge appstore, see https://www.gameboomers.com/forum/ubbthreads.php/topics/1180355/re-myth-a-guffs-tale#Post1180355 for details

### CODE REVIEW

**Comment by raziel-** [comment]
@lolbot-iichan

It would probably be better to not be forced download, install and register to yet another app (kartridge in this case), but go with a direct link (as long as available) from the other main developer from SOLO Design (it's a MS OneDrive link)
See here for reference:
https://www.gameboomers.com/forum/ubbthreads.php/topics/1180355/re-myth-a-guffs-tale#Post1180355
I'm not posting the link as it can be reached from the linked forum post.

Thank you for bringing attention to this game, can t wait to try it out through ScummVM :-)

**Comment by lolbot-iichan** [comment]
@raziel- , thanks for more direct download link, I thought Kartridge was the only option to get this game officially!

Developer's website is down, only info that I found was half-dead thread at http://forum.dead-code.org/index.php?topic=6060 and it's reposts to other sites. 

It makes me really happy to see that game found live community feedback at this GameBoomers site.

**Comment by raziel-** [comment]
You´re welcome.

I despise having to install apps just to get or play one game :-)
Unfortunately, as you pointed out already, another indie developer died due to the passing on of one of it´s founders...sad

**Comment by bluegr** [comment]
Nice work! Merging

**Pull request merged**
