### PR TITLE
PSP: Make the PspTimer class a subclass of DefaultTimerManager

### PR DESCRIPTION
**Pull request by ccawley2011**
This has been briefly tested using PPSSPP, but has not been tested on real hardware.

### CODE REVIEW

**Comment by rsn8887** [comment]
How do I test this? What should I look out for?

**Comment by ccawley2011** [comment]
> How do I test this? What should I look out for?

This PR is intended as just code simplification rather than any major change in behaviour, so it should be sufficient to check that ScummVM initialises correctly on real hardware and try with a few games.

**Comment by bluegr** [comment]
The refactored code is much cleaner. Since this has been tested on an emulator, we could merge it for now, and check for any possible regressions on actual hardware using the daily builds.
@rsn8887: OK to merge this?

**Comment by rsn8887** [comment]
Yes it is much easier for me to test buildbot builds at the moment since I would have to reinstall the sdk locally to test this otherwise. Please merge!

**Comment by bluegr** [comment]
Thanks for your work @ccawley2011, and the review @rsn8887.

Merging

**Pull request merged**
