### PR TITLE
WINTERMUTE: Add some public demos

### PR DESCRIPTION
**Pull request by aviloria**
Add public demos for several wintermute games

### CODE REVIEW

**Comment by sev-** [comment]
It would be nice, if you could also provide these demos, so we could upload them to our servers.

**Comment by aviloria** [comment]
@sev: What do you prefer, origial URLs or a shared folder with all of them?

**Comment by sev-** [comment]
Either. Shared folder is more convenient. Also, you could help with renaming the archives to scummvm format, and perhaps extracting those which are packed in .exe if any, so we could have multiplatform .zip files.

For the scummvm format naming, see the current demos page. Basically, it is named after autodetected target.

**Comment by lolbot-iichan** [comment]
@aviloria, great job collecting all those, thank you!

>It would be nice, if you could also provide these demos, so we could upload them to our servers.
@sev- @aviloria Please note that right now IMHO only 2D games worth uploding, since 2.5D WME games are out of ScummVM's scope and are currently not supported by ResidualVM.

**Comment by aviloria** [comment]
A shared folder with the wintermute demos in 2 flavours: original files and scummvm-cooked files
https://mega.nz/#F!PENWjAAR!guQofHCAz4lqLDQFp2IjJQ

I also have added 2 german demos for "Art of Murder" not in my previous commit... I'll add them later to the repository

**Comment by bluegr** [comment]
Thanks for your work, and for finding these demos!
Merging

Uploading the demos is a separate task, and can be done independently of this PR

**Pull request merged**
