### PR TITLE
AUDIO: Add support for RetroWave OPL3

### PR DESCRIPTION
**Pull request by NMIError**
This PR adds support for the SudoMaker RetroWave OPL3 sound card
(https://www.tindie.com/products/sudomaker/retrowave-opl3-sound-card/).
This requires the retrowave library to build. I've attached Windows and 
linux x64 builds; other platforms will have to build their own 
(source at https://github.com/SudoMaker/RetroWave/tree/v0.0.9).
I've added a build feature --enable-retrowave to configure and build_project.
It would be great if someone could check if I've done that right, as I'm not 
very familiar with the build system.

On the off-chance that someone has one and wants to test it, add the following 
settings to scummvm.ini:

retrowaveopl3_bus=serial
retrowaveopl3_port=<port> f.e. COM3 or ttyACM0

We could maybe add options to the GUI for this, but for now I think this is 
fine as this is a bit of a niche device anyway.

### CODE REVIEW

**Comment by NMIError** [comment]
[libretrowave_linux_x64.zip](https://github.com/scummvm/scummvm/files/7654631/libretrowave_linux_x64.zip)
[scummvm-libs-retrowave.zip](https://github.com/scummvm/scummvm/files/7654632/scummvm-libs-retrowave.zip)

**Comment by yuv422** [comment]
I have a RetroWave. I'll give this branch a go on Mac soon. :)

**Comment by ccawley2011** [comment]
I've had a go at adding the RetroWave library to the buildbot for MXE and Win9x builds, but I haven't tested it much beyond making sure the executable still starts with it enabled.

**Comment by NMIError** [comment]
Thanks! I'm not sure it will work on Win9x, as that platform is not targeted by RetroWave, but it's a good sign that it builds and runs.

**Comment by laurence-myers** [comment]
@NMIError Thank you for adding support for the RetroWave OPL3. 🙂

I was keen to try it out, following the README, but I didn't have the option for RetroWave OPL3 in the Adlib emulator dropdown. It seems like the official 2.7.0 binaries for Windows x64, and the GitHub CI builds for all platforms that I looked at, do not have RetroWave support enabled. Can I only use it if I make my own build of ScummVM?

This makes the current docs a bit misleading, as they assume ScummVM was built with `--enable-retrowave`.

```
ScummVM 2.7.0 (Feb 14 2023 14:26:43)
Features compiled in: Vorbis FLAC MP3 RGB zLib MPEG2 FluidSynth Theora AAC A/52 FreeType2 FriBiDi JPEG PNG GIF taskbar TTS cloud (servers, local) TinyGL OpenGL (with shaders)
```

2023-04-15 19_14_12-ScummVM 2 7 0 (Feb 14 2023 14_26_43)

2023-04-15 19_11_49-COMMON_MATH_ Add some constexpr constructors to Array_List_String_Rect and the M

2023-04-15 19_12_12-COMMON_MATH_ Add some constexpr constructors to Array_List_String_Rect and the M

2023-04-15 19_12_39-COMMON_MATH_ Add some constexpr constructors to Array_List_String_Rect and the M

**Comment by lephilousophe** [comment]
Please try Windows binaries from https://buildbot.scummvm.org/#/dailybuilds
They should have RetroWave library built in.

**Pull request merged**
