### PR TITLE
ANDROID: Clean up the text conversion code

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by antoniou79** [comment]
Maybe someone else who's followed recent changes in the String encoding systems would be more suitable to review this code but, can you provide some more detailed description of what has changed and why. 

And what should someone testing this on devices and emulators should look for. Eg. it seems that this would affect localized versions of UI text and OSD messages, correct?

**Comment by lephilousophe** [comment]
If I understand code correctly, merging this would mean that Android doesn't need libiconv anymore which is a good thing as it's not available readily.
In addition, that makes the code using Common::String on C++ side and String in Java size with the conversion between them done at one place.
Looks good but may need testing.

**Comment by criezy** [comment]
I can't really comment on the code specific to Android, but the changes seem to make sense to me.
And the implementation of `convertEncoding` in `OSystem_Android` in 33e2e6c, if reliable, indeed means using iconv might become unnecessary.

**Comment by antoniou79** [comment]
From what testing I've made, this looks good -- I mostly tested the arm64-v8a with the Greek language to see if there would be crashes or any other unexpected behavior. Currently, freetype is not supported (because we have to provide the cross-compile libs and that's coming soon (I hope), so the bdf fonts were used. 

I did not test for issues with Android OSD messages (our own popups work ok, the OSD are different), but I think it's ok to merge this now. 

If there are no objections or further comments, and since others commented on the benefits of the PR (albeit I'd still prefer some more descriptive text in the PR), I can merge this on the weekend (Saturday July 18th).

**Pull request merged**
