### PR TITLE
DIRECTOR: XOBJ: Update MiscX stub

### PR DESCRIPTION
**Pull request by Nevon**
Backpacker now seems to run well, where before it was crashing after the first scene.

### CODE REVIEW

**Comment by einstein95** [comment]
Did you forget to rename the .h file when you renamed `miscx.cpp` to `misc_x.cpp`?

**Comment by Nevon** [comment]
> Did you forget to rename the .h file when you renamed `miscx.cpp` to `misc_x.cpp`?

Not sure I follow. Because the content of miscx.ccp and misc_x.cpp wasn't the same, Git doesn't seem to consider it a move, unlike the header file where it's showing up as a move. So it's one move, one deletion and one creation.

**Comment by sev-** [comment]
I would say it would be better just to enhance the existing `miscx.cpp` file instead of renaming it to `misc_x.cpp`. That will make this change as minimal.

**Comment by Nevon** [comment]
Figured it was preferable to stick as close as possible to what the stub generator spat out, so that it would be easier to update in the future. But I went back and re-generated it and then hand-massaged it to make it as close as possible to the old manual stub, to make the change as small as possible.

One suspect thing that came out of that was that I noticed the old stub has a method called `m_prefsFolder` which is not in the stub that's auto-generated. The game I'm generating the stub from is using director 4.0.4, so I suppose it's a possibility that the method was dropped between those versions - or it's a mistake that it was there in the first place. Either way, I added it back manually to avoid breaking any existing compatibility. I also don't know which methods (if any) are new in 4.0.4 and which should be supported in older versions, since I don't have an older version to test with. I added them all to 400 just to be safe.

**Comment by sev-** [comment]
Thank you! Merging.

The Xtra is not tied to Director release, and it is a separate thing. E.g. I assume, there could be more than one version of this thing at the time, and it looks like other titles were using a later version of this Xtra.

It is safe to add _more_ methods that are unused, so you did the right thing.

Thank you again!

**Comment by einstein95** [comment]
> One suspect thing that came out of that was that I noticed the old stub has a method called `m_prefsFolder` which is not in the stub that's auto-generated.

That's because the function was from a Mac version of MiscX and wasn't included in the Windows version. It'd point to the OS's "System Preferences" folder (basically Mac OS's version of `C:\WINDOWS`)

**Pull request merged**
