### PR TITLE
ACCESS: Work on Martian Memorandum

### PR DESCRIPTION
**Pull request by bluegr**
The Access engine, created by @dreammaster and @Strangerke , based on work by @johndoe123, has been merged into master with pull request #548, on the 19th of December, 2014. The initial pull request was to add support for one of the games that used this engine, Amazon: Guardians of Eden.

Overall, the engine was used by the following games:
- Countdown
- Martian Memorandum
- Amazon: Guardians of Eden
- Noctropolis

After the merge date, a lot of work has been done on the engine by Strangerke in order to support another game using that engine, Martian Memorandum. The idea was to get that branch merged once work on supporting Martian Memorandum was completed.

However, the two branches have got out of sync, so the idea here is to merge these commits into master, before the differences become too big to bridge. Since the engine is still WIP, merging the two codebases is probably the best option.

The original branch can be found in dreammaster's github:
https://github.com/dreammaster/scummvm/tree/mm/

This branch has been created by merging the master branch on it. I have then fixed any conflicts I found in the merge commit, i.e. 96db3bd18. Subsequent fixes after the merge have been made in commit 0c3b486f70.

Commit ee9143da4 introduced unwanted changes outside the engine, which have been reverted with commit 5fb934c486.

Any comments are welcome.

### CODE REVIEW

**Comment by wjp** [comment]
Do you want me to fix up the merge commits?

**Comment by bluegr** [comment]
If you could, that would be great, thanks!

**Comment by bluegr** [comment]
@wjp I've made you a collaborator in that branch. So, you could either work on the branch itself, or make a fork, whatever suits you better. Thanks again! :)

**Comment by wjp** [comment]
Force-pushed an update:

* fixed up the merge (and made it a merge with current master while I was at it)
* removed the change to dists/msvc9 from history retroactively
* fixed MSVC-isms that broke compilation with gcc (BubbleBox:: prefixes in the class definition...) in history

**Comment by dreammaster** [comment]
Thanks for that

**Comment by bluegr** [comment]
Thanks for your help wjp! After discussing this through, it's good to be merged in its current state. Further work can be done in-tree.

Merging

**Pull request merged**
