### PR TITLE
SCUMM: Implement original GUI for v0-1-2-3 and FM-Towns games

### PR DESCRIPTION
**Pull request by AndywinXp**
Yes, it's that time _again_. 😝 

This PR aims to be the last chapter of my SCUMM GUI journey, containing the following changes:
- GUI and save menus support for Maniac Mansion v0 (C64);
- GUI and save menus support for v1-2-3 games (DOS versions);
- GUI and save menus support for FM-Towns games.

As usual with my PRs, I'm getting this one out while it's still a WIP, so I can motivate myself to finish it up sooner rather than later and so that I can already get some feedbacks.

Here's the current status:
- v0-2 should be feature complete (I even added some small quality of life improvements, like exit confirmation and text speed keys for games which don't have those things); I don't know how to stop mouse inputs during engine pause (so that the little snail cursor stays still), but this is not a blocker frankly 😂 
- This one is a blocker though: v3 is missing save/load support because it appears to save the games correctly, but then loading any of them crashes ScummVM and I currently have no idea about how to fix that. v0-2 games appear to work fine with the "prepared savegames" mechanism (see `ScummEngine_v4::prepareSavegame()` and `ScummEngine_v4::savePreparedSavegame(int slot, char *desc)` for more info about this), but this doesn't seem to be what is done in the disasm: the code just saves and loads the game normally and then lets a save or load script handle some side quirks. If I remove the prepared savegames mechanism, I get the same exact crash as I get in v3 games. I sense that this potentially affects all v3 FM-Towns games, and speaking of which...
- I haven't even remotely touched FM-Towns games for this PR (but v5 games should already have pause banners from the previous PR)

Now, here are a couple of pictures 🙂 
scummvm-maniac-v2-it-00000
scummvm-zak-v1-00000
scummvm-loom-ega-00000
scummvm-indy3-vga-it-00003

### CODE REVIEW

**Comment by athrxx** [comment]
The difference between the savegames created with prepareSavegame() and the ones from the original interpreters is that prepareSavegame() makes the savestate before running the save script. The original will do it differently: it saves right in the middle of the save script and will continue that savescript at that precise offset when restoring.

So, the savegames from prepareSavegame() are probably compatible with our normal save/load process, but not with the original one and vice versa.

**Comment by AndywinXp** [comment]
Hmm, I see. This could potentially cause cross-compatibility issue between saving/loading within the GUI and loading/saving within the GMM, at least for games which make heavy usage of save scripts (e.g. LOOM v3, of course). I'm going to need to look at those save scripts when I get the chance, just to be sure.

**Comment by dwatteau** [comment]
I love this! Thank you very much for this!

I can't speak on the code itself, but here are some tests with my baguette versions…

## Indy3

In Indy3 EGA FR, when trying to exit the game, it looks like a V2-encoded string is used:

scummvm-indy3-ega-fr-00000

(`s~r` should be a `sûr` in French)

I think that's because `getStaticResString()::strMap1` is used in v3 for this case (because of the added exit confirmation that the original didn't have?), but AFAICS the encoding for European games switched from "arbitrary" to (almost-)CP850 in v3, so I don't think you can reuse the v1/v2 table as-is.

Also (at least for French), in Indy v3 the "Do you want to restart" sentence changed a bit more (the hyphen and and question mark have been removed, which is worse IMO, but…) and so if we maintain our "Do you want to quit" translations, the string would be `"Etes vous s\x96r de vouloir quitter (O/N)O"` in Indy V3.

(AFAIK, Indy3 EGA and Loom EGA are the only v3 games with an official French translation, and Loom already embeds its own exit string in the scripts.)

## Zak v2, Maniac v2

My French and English versions look alright, but:

* is there are reason why the Quit message is not printed on the same place as the Restart message? (i.e. Restart is on the top, in red, while the Quit message in the verb bar, in bright magenta).
* I wonder how we are going to deal with the 10 save slots limitation in the old UI? If we enable the original UI by default, some users could report a regression in that some of their saves appear to be "lost".

Zak v3 doesn't work (can't exit the game), but that's related to the v3 save limitations and WIP status regarding the FM-TOWNS versions, I suppose :) 

## Maniac NES

This is with the French version:

* If, by pure luck, my cursor is right where a button will appear (yeah, that happened on my first try 😁) before bringing the save menu, this button will be immediately and automatically clicked when the menu appears. That's not the behavior on Mednafen.

(It also looks like we don't properly handle going to the next line in the verb bar, when the sentence we're building is about to overflow it, compared to the original NES interpreter. And that happens a lot in the French version. But that's completely unrelated to this PR, it's just that it's the first time I realise this 🙃 ).

**Comment by AndywinXp** [comment]
Thanks for the tests @dwatteau! 🙏 

> In Indy3 EGA FR, when trying to exit the game, it looks like a V2-encoded string is used:
> I think that's because getStaticResString()::strMap1 is used in v3 for this case (because of the added exit confirmation that the original didn't have?), but AFAICS the encoding for European games switched from "arbitrary" to (almost-)CP850 in v3, so I don't think you can reuse the v1/v2 table as-is.

Correct; I was under the assumption that there is no resource string for this one. The difficulty of this particular thing is that I only have access to Indy3 ENG (EGAand VGA) and an EGA ITA fan translation, and I have no idea how the official translation handled these things. I definitely want to fix this though, so let's put a pin on that until the major features are finished, so that we can research all these cases.

> is there are reason why the Quit message is not printed on the same place as the Restart message? (i.e. Restart is on the top, in red, while the Quit message in the verb bar, in bright magenta).

This was the result of a classic case of: "do I keep things consistent or user friendly?" 😛

I put the quit message on the sentence line, because _any_ ScummVM quit signal (e.g. clicking the X on the window, even accidentally!) will get transformed into a SCUMM quit prompt.
Okay, keeping this in mind: chances are that if a user clicks the X without too much thought (or, again, accidentally), he/she is not going to see a dark red message on the top of the game screen, and he/she will keep pressing the X while wondering whether the app is frozen or not. But chances are that a bright magenta message on the center of the screen and a snail cursor will probably get the attention necessary for the user to press "Y" or "N" to confirm quitting the game.

On the other hand it's less probable that a user is going to accidentally push F8 during a playthrough (also, I have to replicate exactly how it is handled in the original, so... top message in dark red it is)

Of course this is not final and I would like to know what are the opinions on this topic. 😄 

> Maniac NES

Hoooold on! Hold on! Haha😂 I have to disable any trace of original GUI support for the NES version, as I think I'm not going to work on it, at least at this time. Thanks for making me notice that 😂

**Comment by dwatteau** [comment]
> Correct; I was under the assumption that there is no resource string for this one. The difficulty of this particular thing is that I only have access to Indy3 ENG (EGAand VGA) and an EGA ITA fan translation, and I have no idea how the official translation handled these things. I definitely want to fix this though, so let's put a pin on that until the major features are finished, so that we can research all these cases.

OK thanks. My EGA French version comes from an official Ubisoft CD. Feel free to ping me if you need some information or tests from it :)

I think the "real" encoding in what has been drawn into the `CHAR` resources (98.LFL and 99.LFL in v3). For Indy3, it looks like the official European translations followed CP437, but with a smaller subset and some local changes (I said CP850 above, but I think that was for some later games). For the official Japanese releases (at least until v6), I've been told it's Shift JIS.

> I put the quit message on the sentence line, because _any_ ScummVM quit signal (e.g. clicking the X on the window, even accidentally!) will get transformed into a SCUMM quit prompt. Okay, keeping this in mind: chances are that if a user clicks the X without too much thought (or, again, accidentally), he/she is not going to see a dark red message on the top of the game screen, and he/she will keep pressing the X while wondering whether the app is frozen or not. But chances are that a bright magenta message on the center of the screen and a snail cursor will probably get the attention necessary for the user to press "Y" or "N" to confirm quitting the game.
>
> On the other hand it's less probable that a user is going to accidentally push F8 during a playthrough (also, I have to replicate exactly how it is handled in the original, so... top message in dark red it is)
> 
> Of course this is not final and I would like to know what are the opinions on this topic. 😄

OK, no problem with the quit message being in either place, and I agree that in any case, it's hard to miss it!

> > Maniac NES
> 
> Hoooold on! Hold on! Haha😂 I have to disable any trace of original GUI support for the NES version, as I think I'm not going to work on it, at least at this time. Thanks for making me notice that 😂

Oh sorry 😂 Well most of it appeared to work! But yeah, sorry if this was unintended and out of scope 😛

**Comment by AndywinXp** [comment]
> I think the "real" encoding in what has been drawn into the CHAR resources (98.LFL and 99.LFL in v3). For Indy3, it looks like the official European translations followed CP437, but with a smaller subset and some local changes (I said CP850 above, but I think that was for some later games). It also looks like the Macintosh v3 releases used some other encoding. For the official Japanese releases (at least from v3 to v5), I've been told it's Shift JIS.

I see. Operatively what would I need to do to support the correct encoding in this case? Do we already have something in place for this?

> Oh sorry 😂 Well most of it appeared to work! But yeah, sorry if this was unintended and out of scope 😛

Haha, don't worry, it's good that you reminded me of that!



In other news, I found out that I had the Loom save script workaround by athrxx still in place when testing savegames. Removing that seemed to fix crashes at first. Emphasis on _at first_ 😛

The proper solution would be to rewrite the saving/loading routine, because as it currently is, I have no idea of what I'm doing wrong with it. Of course this is unfeasible since it would break compatibility with the current savegames, so it's a no-go.
I'm still puzzled about how to proceed from here, but I'm sure I will eventually figure out something...

**Comment by eriktorbjorn** [comment]
Here is an attempt at getting the pause dialog right for the Mac versions of Indy 3 and Loom. I'm sure it can be cleaned up a bit, since some of the is copied and pasted from your code. Though note in particular that I restore to old charset 0 afterwards, since that's a valid id. So I figured that might be important.

Diff against current pull request: [mac-boxes.txt](https://github.com/scummvm/scummvm/files/9791744/mac-boxes.txt)

Pause dialog from Indy 3 in Basilisk II:

indy3-pause-orig

Pause dialog from Indy 3 in ScummVM:

indy3-pause-scummvm

Pause dialog from Loom in Basilisk II:

loom-pause-orig

Pause dialog from Loom in ScummVM:

loom-pause-scummvm

For the quit dialog, though, I'm not even going to try. Basilisk II:

indy3-quit-orig

ScummVM:

indy3-quit-scummvm

**Comment by eriktorbjorn** [comment]
Oops, I forgot to free my temporary surfaces. New attempt: 
[mac-boxes-take-2.txt](https://github.com/scummvm/scummvm/files/9791762/mac-boxes-take-2.txt)

**Comment by AndywinXp** [comment]
> Oops, I forgot to free my temporary surfaces. New attempt: [mac-boxes-take-2.txt](https://github.com/scummvm/scummvm/files/9791762/mac-boxes-take-2.txt)

Thanks @eriktorbjorn! 🙏 Looks good to me: could you please commit it into [my branch](https://github.com/AndywinXp/scummvm/tree/SCUMMv1-2-3GUI) so that you retain authorship and so that it's quickier for me to test it?

**Comment by sev-** [comment]
Mac style boxes are implemented as part of MacGUI and WAGE engine
Screenshot 2022-10-15 at 23 17 26

**Comment by AndywinXp** [comment]
That's great! 😄 Given my complete ignorance about anything Mac-related I think it'll be for another PR, but knowing that we already have something to reliably support these message boxes is great.

**Comment by eriktorbjorn** [comment]
> Mac style boxes are implemented as part of MacGUI and WAGE engine

It's a pity so few have access to the Mac versions (I'm not parting with mine!) because I have to admit that my personal interest in implementing the remaining bits of the Mac GUI is pretty low. I'm happy to see the gameplay aspects of them work as well as they do.

Of the two, I'm most interested in Loom and the only remaining gameplay issues there that I'm aware of there are some minor text positioning inaccuracies (no idea how to fix that), and unlike the original we don't allow the player to move the practice mode notes window around. I didn't even know about that feature until there was a bug report about it.

One thing I forgot to mention is that for historical reasons we still allow playing the Mac versions in low-resolution mode if the Mac executables are missing. That may bitrot in the future (particularly if we do add support for the Mac verb interface.) But for now, it works and the standard GUI elements will be used for them as well:

indy3-pause-lowres
loom-pause-lowres

**Comment by eriktorbjorn** [comment]
Oh, and we don't emulate the lower resolution of a 9" screen (Mac Plus, and such) either, just as we don't emulate the slightly higher resolution of the TurboGrafx-16 version of Loom. (Funnily enough, that higher resolution causes glitches at the end of the game.)

loom-minivmac

But this is getting off-topic. Sorry.

**Comment by dwatteau** [comment]
@AndywinXp 

> > I think the "real" encoding in what has been drawn into the CHAR resources (98.LFL and 99.LFL in v3). For Indy3, it looks like the official European translations followed CP437, but with a smaller subset and some local changes (I said CP850 above, but I think that was for some later games). It also looks like the Macintosh v3 releases used some other encoding. For the official Japanese releases (at least from v3 to v5), I've been told it's Shift JIS.
> 
> I see. Operatively what would I need to do to support the correct encoding in this case? Do we already have something in place for this?

I'm not sure we have anything better than `ScummEngine::getDialogCodePage()` (which isn't accurate, but good-enough). I *think* that for European languages (at least ≤ v6), most of the time we just treat the original strings as-is, and just act as a pass-through until the game itself does the final mapping by drawing each corresponding character from the CHAR resources. (Just saying this from empirical observation, though.)

So if we want to insert a few hardcoded strings (such as the `Are you sure you want to quit?` in-game translations), I think the simpler approach is just to continue using hardcoded strings, as long as their encoding is adjusted for the v1-v2/v3+/v7+ differences.

i.e. continue using this for v1/v2:

https://github.com/scummvm/scummvm/blob/dc3f4b4f6d4f05bb9ceb8cfd7c2d928a9596ec39/engines/scumm/dialogs.cpp#L561-L579

and then have a new v3+ table (I don't think we'd need a v7+ table since we don't hardcode any string in v7+ games AFAIK).

Currently, this function does a v2 > v3 mapping:

https://github.com/scummvm/scummvm/blob/dc3f4b4f6d4f05bb9ceb8cfd7c2d928a9596ec39/engines/scumm/dialogs.cpp#L465-L473

but I wonder if it wouldn't be simpler to have a a new v3+ table, since these sentences have been rephrased in the v3 games anyway, so it's not just a matter of fixing their encoding.

And by "v3+ table", I mean "Indy3 `Do you really want to quit?` translation table" 😁  since I don't think there's any other string we would hardcode in that game; and later v3+ games appear to properly a localised sentence for this inside their game scripts.

**Comment by eriktorbjorn** [comment]
I mentioned this on Discord recently, but just so that it doesn't get lost in the shuffle...

The Mac versions of Indy 3 and Loom currently do not do anything when you press F5. Unless the resources for the DOS version's save/load dialogs are still hidden in there somewhere, it'd probably be most sensible to fall back on ScummVM's save/load dialog.

(Unless someone really wants to introduce the Mac file dialogs here. Don't look at me! :-)

**Comment by AndywinXp** [comment]
@dwatteau forgive me for my late reply! I've had some very busy days...
Anyhow, thanks for the thorough explaination! Given what you've said, I agree that a specific INDY3 table is probably the way to go for those hardcoded strings, so I will begin constructing that.

**Comment by eriktorbjorn** [comment]
There's something weird about the FM Towns versions.

In Loom there is a slight "flash", as if the screen goes black for a split second, when I unpause the game. This can be repeated by pausing/unpausing the game.

In Zak, the same thing happens the first time. The second time I pause the game, the screen goes completely black. Though there's something weird here, because _sometimes_ it still works like in Loom. I don't know...

These are the only FM Towns versions I have (and I only have Zak through GOG), and I have only tried the English versions.

**Comment by AndywinXp** [comment]
> In Loom there is a slight "flash", as if the screen goes black for a split second, when I unpause the game. This can be repeated by pausing/unpausing the game.

Yes, I fixed that after fixing the crash, but I didn't push the commit yet because of...

> In Zak, the same thing happens the first time. The second time I pause the game, the screen goes completely black. Though there's something weird here, because _sometimes_ it still works like in Loom. I don't know...

...This bug. I haven't been able to figure out why that happens, and why only sometimes.

**Comment by AndywinXp** [comment]
And it's gone 😄 It was a workaround of mine which had returned to bite me

**Comment by AndywinXp** [comment]
All right, apart from:
* Menus in FM-Towns games (currently absent);
* Quit query message in v3 games (I still have to rewrite the message for all languages, this does not apply to LOOM);
* Saving/loading not working properly on v3 games on their original menu (there are still crashes on game load);
* Amiga snail cursor not yet implemented;

The bulk of the PR (the banners, basically) should be glitch-free on all supported games. Is someone else able to confirm that?

**Comment by eriktorbjorn** [comment]
> * I don't know how to stop mouse inputs during engine pause (so that the little snail cursor stays still), but this is not a blocker frankly joy

I suppose that instead of changing the cursor to a snail, you could draw the cursor image to the screen and hide the cursor while the game is paused?

**Comment by AndywinXp** [comment]
> > * I don't know how to stop mouse inputs during engine pause (so that the little snail cursor stays still), but this is not a blocker frankly 😂
> 
> I suppose that instead of changing the cursor to a snail, you could draw the cursor image to the screen and hide the cursor while the game is paused?

Thanks.

The difficulty of doing that, when stamping the cursor on top of the game screen, is that I should be accounting for all the virtual screens in which the cursor could end up on (including situations in which the cursor is on top of two virtual screens, or part of the cursor is off-screen). 

This thing might lead to out of bounds writes if we're not careful when splitting the cursor throughout the various virtual screens. Personally, since this is already a pretty big PR, I would prefer going through those gates of hell 😂 after this one is stable and merged.

**Comment by eriktorbjorn** [comment]
> The difficulty of doing that, when stamping the cursor on top of the game screen, is that I should be accounting for all the virtual screens in which the cursor could end up on (including situations in which the cursor is on top of two virtual screens, or part of the cursor is off-screen).

Ah, right, I had forgotten about that particular nightmare...

**Comment by eriktorbjorn** [comment]
> The bulk of the PR (the banners, basically) should be glitch-free on all supported games. Is someone else able to confirm that?

My experience with it, from a quick test:

- Maniac Mansion DOS v1. Pausing, quitting, saving and loading all seem to work. (Though I'm grateful that you can still use the ScummVM save/load dialog with Ctrl+F5. Perhaps not the most convenient, but...)
- Maniac Mansion DOS v2. Pausing, quitting, saving and loading all seem to work.
- Zak McKracken DOS v2. Pausing, quitting, saving and loading all seem to work. Though loading a saved game sometimes seem to draw actors before the screen effect shows the rest of the screen?
- Loom DOS EGA. Pausing, quitting, saving and loading all seem to work. Though in the original you can apparently change the name of a savegame before loading it? ScummVM lets me type, but the name remains unchanged. (I assume this happens in other games as well?)
- Indiana Jones and the Last Crusade DOS VGA. Pausing, quitting, saving and loading seem to work... but after I loaded a savegame and then quit, ScummVM crashed for me. Seems to happen with at least all of my old savegames.
- Indiana Jones and the Last Crusade, Mac. Pausing seems to work. Quitting works, but is different than the original. Saving and loading uses the ScummVM dialogs.
- Loom, Mac. Pausing seems to work. Quitting works, but is different than the original. Saving and loading uses the ScummVM dialogs.
- Zak McKracken, FM Towns (English). Pausing doesn't work. The banner isn't removed, and I've seen it drawn in different spots. Quitting doesn't work. Loading crashes ScummVM. (I didn't bother trying to save.)
- Loom, FM Towns (English). Pausing, quitting, saving and loading all seem to work.
- Loom, FM Towns (Japanese). Pausing, quitting, saving and loading all seem to work. I have no idea if the displayed text is correct, but it looks cool.
- Loom, PC Engine (English). Pausing and quitting crashes. Nothing happens when I press F5.

**Comment by AndywinXp** [comment]
Thanks! I fixed the regression for FM-Towns banners and explicitly maked Loom PC-Engine as unsupported (I forgot to do that... sorry)

> Though loading a saved game sometimes seem to draw actors before the screen effect shows the rest of the screen?

Nice catch, I'll have to see why that happens, but I think I'll be hacking the save room to explicitly use our save/load routines. Even though this might not be the cleanest solution, it theoretically allows for:
* Fix all those crashes related to loading a game;
* Stay consistently crosscompatible between the original menus and the GMM (this is practically non-negotiable, of course)

> Though in the original you can apparently change the name of a savegame before loading it? ScummVM lets me type, but the name remains unchanged. (I assume this happens in other games as well?)

This is a strange one. Those menus are entirely script controlled, so I wonder what's happening there...

**Comment by eriktorbjorn** [comment]
> Thanks! I fixed the regression for FM-Towns banners and explicitly maked Loom PC-Engine as unsupported (I forgot to do that... sorry)

Thank you! Pausing/unpausing Zak FM Towns works again. Quitting still doesn't though, as the game says "Demo mode, Save/Load disabled". Even quitting from the ScummVM menu doesn't work.

(FM Towns Loom is still fine, so no regressions there.)

**Comment by AndywinXp** [comment]
> > Thanks! I fixed the regression for FM-Towns banners and explicitly maked Loom PC-Engine as unsupported (I forgot to do that... sorry)
> 
> Thank you! Pausing/unpausing Zak FM Towns works again. Quitting still doesn't though, as the game says "Demo mode, Save/Load disabled". Even quitting from the ScummVM menu doesn't work.
> 
> (FM Towns Loom is still fine, so no regressions there.)

Yes, that's part of the hardcoded strings "restructuring"; right now if you want to quit, you have to press `.`, which is the last character in the `Demo mode, Save/Load disabled` string. But since I have some spare time this morning, I'll give that task a try.

**Comment by AndywinXp** [comment]
The correct v3 banner strings are now implemented (thanks dwa!), give it a try 🙂 One task down, I guess it's time for the v5 FM-Towns menus to make an appearence...

**Comment by eriktorbjorn** [comment]
I didn't even remember to test "Restart", but it seems to work in everything I've tried. Except in Mac Loom, where I haven't been able to find the key for it. F8 just shows the version information. ("Release Version 1.2  25-JAN-9", in case anyone was curious.)

**Comment by eriktorbjorn** [comment]
> I see. I suppose the original used a standard Mac menu for restarting the game?

Unfortunately, my second-hand copy of the game did not include the manual. But it seems likely.

loom-1 loom-2

**Comment by AndywinXp** [comment]
There. 🙂 FM-Towns v5 done!

scummvm-monkey2-fm-ja-00000
scummvm-monkey-fm-00000

**Comment by AndywinXp** [comment]
I'm sick of these snail cursors :') The Amiga one is done!

scummvm-maniac-v2-amiga-00001

**Comment by AndywinXp** [comment]
Ahoy, I'm not dead 🙂 I have figured out how to fix the savegame issue for v3 games: we were missing a script update call at the end of the SaveLoad opcode.

It will be a while until I commit that change though: I want to make sure that savegames remain crosscompatible between the GMM and the original menu, even if that's going to need additional flags saved in our savestate (along with a bump of the save version).

**Comment by AndywinXp** [comment]
There, the saving and loading from the original menus is fixed, it even works for saves made within the GMM. 
One thing which still needs ironing is loading saves made within the original menu from the GMM... it works, but since the save is made in the menu room, the user has to manually press "Play", to return to the game. I have been looking at this for several days but I haven't been able to find a fix for this, so this might count as a call for help. 😵‍💫 

Other than that, last two TODO items:

- [ ] Fix a very minor graphical glitch when quitting the game;
- [ ] Fix LOOM Towns save menu, using the wrong box size for graphical elements and not displaying any savestate.

**Comment by AndywinXp** [comment]
Okay, apart from the following thing...

> One thing which still needs ironing is loading saves made within the original menu from the GMM... it works, but since the save is made in the menu room, the user has to manually press "Play", to return to the game. I have been looking at this for several days but I haven't been able to find a fix for this, so this might count as a call for help. 😵‍💫

...the PR is done, so bring the reviews in, if you feel like doing so 🙂

**Comment by tag2015** [comment]
Great 😄 ! Everything seems to work, these are the only issues I found:
* In Loom FM-TOWNS, if you click "load" when you have no savegames, scummvm crashes to debugger with ERROR: (70:42:0x114): String 22 does not exist!
* The Japanese Sega CD version is glitchy ( but save/load works) , the biggest issue is the fact that you can't quit, the confirmation message is corrupted and does not seem to detect anything (or maybe it expects some weird keystroke)

**Comment by AndywinXp** [comment]
Thanks, great catches! I have fixed the LOOM issue, and I'll be looking at the Sega CD issues in a moment!

**Comment by sev-** [comment]
Outstanding work! Merging. Also, thanks to everyone for reviewing and testing it thoroughly.

**Comment by AndywinXp** [comment]
Thank you for the merge! 🙏 ❤️

**Comment by sev-** [comment]
@AndywinXp please check ca37dccb5af6309d913aca382682704a03198b35 I had to do it post-merge

**Comment by AndywinXp** [comment]
> @AndywinXp please check [ca37dcc](https://github.com/scummvm/scummvm/commit/ca37dccb5af6309d913aca382682704a03198b35) I had to do it post-merge

This is correct, thanks 🙏

**Pull request merged**
