### PR TITLE
DGDS: add english variants of china

### PR DESCRIPTION
**Pull request by BJNFNE**

### CODE REVIEW

**Comment by mduggan** [comment]
Thanks! Do you have any more information about these versions? eg, version, disk type, etc?  I believe there were 3.5" (1.44MB) and 5.25" (1.2MB) disk releases, and probably a few different versions of each.

**Comment by BJNFNE** [comment]
The first is 720kb Floppy version
The 2nd one is 1.2MB Floppy version

**Comment by bluegr** [comment]
Thanks! Please update the detection entries accordingly

**Comment by BJNFNE** [comment]
is this good?  or would it be better to move this into the extra title?

**Comment by bluegr** [comment]
That's fine, thanks!

**Pull request merged**
