### PR TITLE
WINTERMUTE: [GSoC] Make Wintermute games show the right save date

### PR DESCRIPTION
**Pull request by Hurricos**
The TimeDate format stores year relative to 1900, and month relative to 1.

### CODE REVIEW

**Comment by fuzzie** [comment]
You should remove the irrelevant commits and squash the 'removed file listing' commit into the 'fix' one. (Also, add quotes around "the the" in the commit description?)

**Comment by Hurricos** [comment]
Ho boy.  I have no idea how to remove commits, actually.  I only managed to revert them.

**Comment by Hurricos** [comment]
Remember how I said I had no idea how to remove commits?  Scratch that.

**Comment by Hurricos** [comment]
I won't bother leaving in the 'the the' commit - I can always do that in a later, more central pull request.

**Comment by somaen** [comment]
As a general tip for future Pull Requests, I'd suggest creating your own topic branches in your fork, and pushing from those, that way it's possible to do more than one PR at a time without irrelevant changes. (Personally I tend to let master of my fork simply match upstream's master, but I guess that's a matter of taste)

**Comment by Hurricos** [comment]
Yeah, I learned that a little too late :D

But now I know how do that now.  git checkout -b thethe would have been a
good start.

On Fri, Mar 25, 2016 at 6:49 AM, Einar Johan Trøan Sømåen <
notifications@github.com> wrote:

> Merged #723 <https://github.com/scummvm/scummvm/pull/723>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/scummvm/scummvm/pull/723#event-602896646>
>



-- 
-Martin

**Pull request merged**
