### PR TITLE
SCUMM: Remove direct use of Graphics::Surface from ARM code

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by digitall** [comment]
@ccawley2011 : Could you resolve the conflicts on this and rebase?

**Comment by digitall** [comment]
@sev- : I don't know who should review this ARM code as the previous developers who have touched this all seem to be retired. @ccawley2011 seems to know what he is doing so OK to merge or do you want to check this?

**Comment by sev-** [comment]
I see that the last platform which was using ARM code was Symbian, but even there we have it now commented out.

Shall we perhaps just remove this file altogether?

**Comment by bluegr** [comment]
I agree that this could be removed, as it's no longer used - USE_ARM_COSTUME_ASM is no longer enabled anywhere
Same goes for USE_ARM_SOUND_ASM and its associated code

Both features have been disabled and are unused and no longer maintained for at least 5 - 6 years

**Comment by digitall** [comment]
I would suggest accepting this change then and merging... then removing the usage of the ARM code in a further commit thus this is still in the history if this is reverted later.

**Comment by sev-** [comment]
Good point. Merging.

**Comment by sev-** [comment]
Oh, it requires rebase. @ccawley2011 could you please do it?

**Comment by bluegr** [comment]
Thanks for your work!
I've solved the conflict, it was just whitespace. I'm squashing this.

**Pull request merged**
