### PR TITLE
Symbian: fix incorrect return type in SymbianActions::actionName().

### PR DESCRIPTION
**Pull request by fedor4ever**
Symbian: silence more warnings from SDK headers.
Symbian: add new project files.

### CODE REVIEW

**Comment by sev-** [comment]
Thanks, however, I cannot backport it to branch-2-2, could you please provide a patch for that branch?

Also, it would be nice to follow to our git log guidelines.

**Comment by sev-** [comment]
Actually, I resolved the conflict but please check that the branch-2-2 compiles well.

**Comment by fedor4ever** [comment]
> Thanks, however, I cannot backport it to branch-2-2, could you please provide a patch for that branch?
Where send this patch?
> Also, it would be nice to follow to our git log guidelines.
Ok.

**Comment by sev-** [comment]
As I've explained in my following comment, I've backported your change to branch-2-2, but I obviously cannot test it.

Could you please test that branch-2-2 compiles and is ready for the release for you?

**Comment by fedor4ever** [comment]
I'm building engines now. Still. I hope build them today. That need a lot time because several engines build too long. Ultima engine builds over 40 mins. It will be good to build engines as static libs at CI server to test if something wrong.

**Comment by sev-** [comment]
Did you try parallel builds? Like `make -j6` for a 4 CPU machine.

**Comment by fedor4ever** [comment]
Short answer - it's impossible.

Symbian SDK comes with own build system named abld build system. It written in artificial perl 5.6 and over 20 years old. Paralell builds lol. 
There are many perl scripts. Several related to abld build.

I wrote python script to dump .mmp(symbian project files) and wish to store as ninja project files.

**Pull request merged**
