### PR TITLE
I18N: Add script to generate translated android strings.xml, automatically generates fake cpp file

### PR DESCRIPTION
**Pull request by ankushdutt**
### Description
Fixes: https://trello.com/c/EiKn4pYx/36-error-warning-and-info-messages-in-stringsxml-should-be-translate-able-via-the-weblate

This PR adds a python script that generates the translated strings.xml as per this specs: https://developer.android.com/guide/topics/resources/providing-resources#AlternativeResources

Also, this script automatically generates the fake cpp for the gettext (to make it translatable for weblate) using `res/values/strings.xml`.

Relevant translated strings.xml file will be automatically used based on the android system's language.

### Testing
For testing, I manually added the string for the permission denied toast in the original and some generated XML (I also edited the relevant code to use string resource instead), and it works as expected. 

Here are some screenshots of the android app:

Default:
Default

Using Catalan system's language (same build):
ca

Using Japanese system's language (same build):
ja

### CODE REVIEW

**Comment by lephilousophe** [comment]
Wouldn't it better to modify weblate configuration? (using https://docs.weblate.org/en/latest/formats.html#aresource)
If something is changed, it has to be in the CPP file which will never be modified using Android Studio.
This looks really fragile.

**Comment by ankushdutt** [comment]
> Wouldn't it better to modify weblate configuration? (using https://docs.weblate.org/en/latest/formats.html#aresource) If something is changed, it has to be in the CPP file which will never be modified using Android Studio. This looks really fragile.

Yes, you are right. If something is changed in strings.xml, that fake cpp file must be modified to reflect those changes in weblate. 
Indeed, modifying weblate configuration to also support [Android string resources](https://docs.weblate.org/en/latest/formats.html#android-string-resources) seems better solution than using [gettext](https://docs.weblate.org/en/latest/devel/gettext.html) in a hacky way here.

Thanks, I will look more into it.

**Comment by sev-** [comment]
@lephilousophe, the idea was similar to this PR: #4826 

E.g. we turn the strings.xml into a generated file and the original will sit in a Python script. That script will merge in translations from the Weblate.

Unless, of course, you have an idea of how we can mark up the strings.xml file in a way that the `gettext` utility is happy about it and able to extract/merge back strings

**Comment by sev-** [comment]
@ankushdutt do you intend to follow out commit guidelines?

**Comment by ankushdutt** [comment]
> @ankushdutt do you intend to follow out commit guidelines?

Sorry yes, I have now squashed the commits with an updated commit message.

**Comment by sev-** [comment]
Okay, rebasing and merging this

**Pull request merged**
