### PR TITLE
NEWS: Add MOHAWK changes

### PR DESCRIPTION
**Pull request by dafioram**
There are more changes than this, but these are the more noticeable changes.

### CODE REVIEW

**Comment by sev-** [comment]
Are we going to enlist every bugfix in the NEWS file? We never did it before, and it is quite verbose.

I would write just something like: "fixed numerous bugs and general stability improvements", then I would describe "support for 25th Anniversary rereleases".

**Comment by criezy** [comment]
I agree with @sev- 
I think we might want to be more selective in what is listed in the NEWS file or group multiple items together so that important changes are not drown under a big number of changes.

**Comment by Kroc** [comment]
If a particular crash was stopping a player from completing the game, they may be very happy to be notified of they're particular pain point.

**Comment by bgK** [comment]
> If a particular crash was stopping a player from completing the game, they may be very happy to be notified of their particular pain-point. By all means merge some items, but spell out show-stoppers directly.

There were no progress blocking bugs.

Thanks for updating the news file! I've added the new features of the 25th anniversary edition and reworded some of the news items before merging.

**Pull request closed without merging**
