### PR TITLE
COMMON: Avoid Quicktime parsing crash on early EOF

### PR DESCRIPTION
**Pull request by mduggan**
In parseStream, atom.size is initailized to uint32 max.  If the loop in readDefault then never executes because the stream has hit EOF, that size is passed as-is to seek.  This can cause a crash eg in SeekableSubReadStream because of an int overflow.

If nothing has been read just skip seeking at the end of readDefault. parseStream will correctly return false in this case as no MOOV will be found.

### CODE REVIEW

**Comment by mduggan** [comment]
Doing this as a PR as I'm not 100% sure of my fix - @elasota I think you've touched this code recently(ish), not sure if you have any thoughts?

**Comment by elasota** [comment]
Couldn't you just check the err/eos functions on `_fd` to figure out if one of the reads failed? Should probably check if the seek failed too.

**Comment by mduggan** [comment]
> Couldn't you just check the err/eos functions on `_fd` to figure out if one of the reads failed? Should probably check if the seek failed too.

I think the loop on line 184 can fall through the first time even if there is no particular error, that's why I was trying to check something about the output - but then I wasn't fully sure if `total_size` was the right thing to check.. would it be better to instead check `atom.size != 0xffffffff`?

**Comment by elasota** [comment]
Would it make more sense to initialize the atom size to `stream->size()` in `QuickTimeParser::parseStream` then?  I'm not sure why that is initialized to 0xffffffff in the first place...

**Comment by sev-** [comment]
@mduggan any updates?

**Comment by mduggan** [comment]
Thanks for the ping

I think @elasota's suggestion right about changing the initialization of `atom.size`, but I'm also a little afraid to make that change without some more testing as this whole code base is a little complex and I don't want to break anyone else's stuff. I think I will write some unit tests first and then I can reduce the chance of breaking something, but it might take me a little while.

**Comment by mduggan** [comment]
Ok, I switched to using stream size, and added some simple tests which previously crashed and now pass.

**Comment by bluegr** [comment]
@sluicebox has worked on the QT code, so perhaps he could also share some feedback on this?

**Comment by sluicebox** [comment]
I would rather see this fixed in `readDefault`; that function doesn't seem to be fulfilling its obligations if it's returning no-error when given a truncated stream. This change is an non-obvious workaround for `readDefault` not doing that.

If it's valid for the `readDefault` loop to do no iterations under some circumstances, then can we add an initial `_fd->err()` / `_fd->eos()` check and return -1? Is it a problem that `err` isn't checked at all?

If we don't know these answers, I think it's better to do nothing for now than complicate the caller code. `readDefault` is in need of basic documentation if nothing else. Name is unclear, how does the struct parameter affect things, what state does it alter, what are the return values...

Although this issue was uncovered by a corrupt file that's been replaced, it is still worth improving the error handling. Parsers that crash (possibly with an assert?) instead of returning an error is a wide problem in the codebase; see [#2486](https://github.com/scummvm/scummvm/pull/2486)

**Comment by mduggan** [comment]
Thanks for the suggestion @sluicebox.  After some thought I've realized there should always be at least 8 bytes to read in `readDefault`, otherwise there is no atom there to read.  I added checks for the eos and err condition in a few more places and reverted the change in `readStream`.  I think I prefer it now.

**Comment by sev-** [comment]
Excellent work and research. Thank you! Merging.

**Pull request merged**
