### PR TITLE
Groovie2 work

### PR DESCRIPTION
**Pull request by Die4Ever**
SUBSYSTEM: Groovie2

* some work for The 11th Hour and Tender Loving Care

### CODE REVIEW

**Comment by criezy** [comment]
@Die4Ever are you the same person as @Alphard-o?

If not, did you discuss with him to check what the status of his work his, what remains to be done, what his plans are, and that it is fine to merge it now? It is unusual to open a pull request with somebody else's fork. Are you planning to start working on this yourself?

**Comment by Die4Ever** [comment]
> @Die4Ever are you the same person as @Alphard-o?
> 
> If not, did you discuss with him/her to check what the status of their work his, what remains to be done, what their plans are, and that it is fine to merge it now? It is unusual to open a pull request with somebody else's fork. Are you planning to start working on this yourself?

I'm not them, I just found work on Groovie2 that was falling behind master and I wanted to get it merged in sooner rather than later, I probably will contribute to it eventually I do want to get The 11th Hour working

Alphard-o seems to be MIA since like 2020, no activity on their github

**Comment by digitall** [comment]
@Die4Ever : This will not merge cleanly currently and there is a duplicated commit causing a merge commit. My guess is that @Alphard-o had problems untangling his git history at that point and that probably contributed to stopping work on this.

I can fix this with interactive rebase, but I don't think it is possible to push to his master branch to fix this PR i.e. as per contributors access... If it was, it would be a helluva hole in Github's security model.

I will push my untangled version to a branch on my github fork and reopen a new PR for this so this can be worked on and hopefully merged.

**Comment by digitall** [comment]
@Die4Ever : Right... Done as PR #3307 . Closing this so further work can be done there to fixup and get the code mergeable.

**Pull request closed without merging**
