### PR TITLE
GLK/GLULX: Add multiple entries to detection table from ifdb.org

### PR DESCRIPTION
**Pull request by MarcoBorrini99**
GLK/GLULX: Add multiple entries to detection table from ifdb.org

This PR add all the missing entries from ifdb.org for GLK/GLULX subengine; scummvm compiles so it should be merged.

### CODE REVIEW

**Comment by tag2015** [comment]
Could you please fix the "alabaster" duplicate? The rest is fine!

**Comment by MarcoBorrini99** [comment]
> Could you please fix the "alabaster" duplicate? The rest is fine!

Fixed!

**Comment by tag2015** [comment]
Thanks!

**Comment by MarcoBorrini99** [comment]
> Hello Marco, Very happy to see that you continue to update other engines detection after Adrift ! I think there is a confusion between two games in your Glulx update :
> 
> The following entry seems to be linked to the R1 version of "Ein später Besuch" and not to "Der onirische Garten" : DT_ENTRYL1("deronirischegarten", Common::DE_DEU, "r1/190626", "b201ade8eb29a64892cf1370de3c9131", 9562670),

I'll put in the todo list; actually I'm working on zcode detection table and then a second run on glux subsystem will follow (the first one was very very poor).

Meanwhile thanks for noticing it!

**Pull request merged**
