### PR TITLE
 IPHONE/IOS7: Make use of ModularMutexBackend

### PR DESCRIPTION
**Pull request by ccawley2011**
This has not been tested, but it should help to reduce code duplication and make future refactoring simpler.

### CODE REVIEW

**Comment by criezy** [comment]
Thank you. The change looks good.

The only difference between using the `PthreadMutexManager` and the current code is that the curent code uses malloc/free to allocate and deallocate the mutex and the `PthreadMutexManager` uses new/delete, and I don't see how that could break things. But I will give this a spin anyway before merging just to make sure it works.

**Review by criezy — CHANGES_REQUESTED** [review]
These changes break the compilation with Xcode because the pthread-mutex files are not included in the solution by `create_project`.

**Comment by ccawley2011** [comment]
This PR should work now, and builds correctly with GitHub Actions.

**Comment by criezy** [comment]
Indeed, I confirmed it now compiles properly with Xcode. I think it's good to merge.

**Pull request merged**
