### PR TITLE
BASE: Show SDL1.2/SDL2 in the About dialog

### PR DESCRIPTION
**Pull request by dwatteau**
This tweaks the build system a bit, so that the About dialog will now show whether SDL1.2 or SDL2 (or later) is used.

The idea is to have a quick way of figuring out when an official port still uses SDL1.2, just after starting it. Knowing it from memory or from the build logs is not always convenient.

### CODE REVIEW

**Comment by lotharsm** [comment]
Nice idea, especially since we'll see the SDL2->SDL3 migration happening in the foreseeable future.

**Comment by digitall** [comment]
These changes look pretty good to me, fairly clear. If @sev- is happy as well, then I would suggest merging.

**Comment by criezy** [comment]
Shouldn't the `USE_SDL2` define be added to `scummvmOSX_defines` in `devtools/create_project/xcode.cpp` as well?

Otherwise the change looks good.

**Comment by sev-** [comment]
Thank you, very useful

**Comment by sev-** [comment]
> Shouldn't the `USE_SDL2` define be added to `scummvmOSX_defines` in `devtools/create_project/xcode.cpp` as well?

And I added it in 43d7792d4eb8213889d5275094da081dcbdfd957. Please check that it is correct

**Comment by raziel-** [comment]
I'm too late to the party...but would it makes sense to also add the used SDL version to the version information when one triggers --version (right now all the compiled in dependancies are already displayed?

Like so:
ScummVM 2.8.0git (Mar  8 2023 08:13:58)
Features compiled in: Vorbis FLAC MP3 RGB zLib MPEG2 Theora AAC A/52 FreeType2 FriBiDi JPEG PNG GIF cloud (servers, local) ENet TinyGL OpenGL (with shaders)  ... SDL2(?)

That way bug reports would also hold the information without the reporter having to add it manually (if he/she chooses to use the --version switch, that is)

**Comment by dwatteau** [comment]
> Shouldn't the `USE_SDL2` define be added to `scummvmOSX_defines` in `devtools/create_project/xcode.cpp` as well?
> 
> Otherwise the change looks good.

`create_project.cpp` already had:

```c++
                setup.defines.push_back("USE_SDL2");
```

and so the resulting `scummvm.xcodeproj` already has the `USE_SDL2` define, and it appears to be OK as-is, from a quick Xcode build test. But having it explicitly listed in `xcode.cpp` too shouldn't hurt.

> I'm too late to the party...but would it makes sense to also add the used SDL version to the version information when one triggers --version (right now all the compiled in dependancies are already displayed?
> 
> Like so: ScummVM 2.8.0git (Mar 8 2023 08:13:58) Features compiled in: Vorbis FLAC MP3 RGB zLib MPEG2 Theora AAC A/52 FreeType2 FriBiDi JPEG PNG GIF cloud (servers, local) ENet TinyGL OpenGL (with shaders) ... SDL2(?)
> 
> That way bug reports would also hold the information without the reporter having to add it manually (if he/she chooses to use the --version switch, that is)

Yes, I only mentioned the About dialog, but `base/version.cpp` is also used for the `--version` switch in CLI, so the SDL1.2/SDL2 value also appears there, now :)

**Comment by lotharsm** [comment]
Uh, this is interesting, I didn't even notice.

It looks like that at least on MSYS2/mingw64 and MXE, this change doesn't work properly, I see no SDL related output in the About dialog or in the command line output. However, if I apply #4793, I do get the proper version reported in the command line, so USE_SDL2 and SDL_BACKEND seem to be correctly reported.

Sadly I have no idea why this doesn't work :/

**Comment by lotharsm** [comment]
Yep, fix confirmed :-)

**Pull request merged**
