### PR TITLE
SYMBIAN: Update help/ScummVM.rtf

### PR DESCRIPTION
**Pull request by fedor4ever**

### CODE REVIEW

**Comment by huhungahuru** [comment]
@fedor4ever : You can enable the Broken Sword 2.5 engine, in S60v5 the performance is limited but in the latest phones (603, 700, 701, 808) they have more capacity. It could be tested.

**Comment by fedor4ever** [comment]
@huhungahuru, I tried long ago. It closes because phone has lower resolution than game needed.
I always try push Symbian port to phone limits and beyond 😁

**Comment by Mataniko** [comment]
Our build files have checks for Pandoc, which should be able to convert to whatever format you need for packaging. Worth considering for simplifications and having a more readable format in the repository

**Comment by fedor4ever** [comment]
That file will converted by Symbian SDK tools to OS-specific help file.
It will be good to use open format by I have no idea how format for Symbian help file inside.
Fiodar Stryzhniou

исходное сбщ
Тема: Re: [scummvm/scummvm] SYMBIAN: Update help/ScummVM.rtf (#3172)
От: Matan Bareket ***@***.***>
Дата: 19.07.2021 15.20

Our build files have checks for Pandoc, which should be able to convert to whatever format you need for packaging. Worth considering for simplifications and having a more readable format in the repository

**Comment by sev-** [comment]
Merging

**Pull request merged**
