### PR TITLE
SKY: Decrease cursor redraw delay in menu

### PR DESCRIPTION
**Pull request by lotharsm**
Currently, there's a very noticeable mouse cursor lag in the save/load/settings dialog in Beneath a Steel Sky. I noticed that for whatever reason the redrawing delay is set to 50ms which causes this behavior. By reducing the redrawing delay to 20ms I achieved a very smooth cursor behavior which now matches the behavior of the original interpreter (tested with the latest DosBox release).

Even though this change seems to be quite trivial, I'm submitting this patch as a pull request since I am not familiar with the engine code at all. I couldn't spot any unwanted side effects.

### CODE REVIEW

**Comment by bluegr** [comment]
Since the delay is the same in all places that it’s used, it should be placed in a define at the top of control.cpp

**Comment by lotharsm** [comment]
@bluegr, there's a delay of 150ms that's used in `void Control::animClick`.

**Comment by bluegr** [comment]
@lotharsm: the 150ms delay is applied when a mouse click event occurs. The other delays of 20ms are applied during control panel animations. Thus, these two delays can be defined on top, as follows:

    #define ANIM_DELAY 20
    #define CLICK_DELAY 150

**Comment by lotharsm** [comment]
@bluegr, I added the #defines as you suggested.

May I ask why you voted for a #define here instead of using `const int`? Just curious about it.

**Comment by bluegr** [comment]
Thanks! Well, there's no real reason, really. In this case, a const int can be used just as well, or you could just use an enum

**Comment by lotharsm** [comment]
Thanks for your feedback! Ready to go now? :)

**Comment by bluegr** [comment]
Your patch is correct, as the delay is applied in all the graphics update loops in the control panel, so the 50ms delay is a bit high. The lag isn't THAT noticeable, IMHO, but it's there, and indeed this patch reduces it.

Merging

**Pull request merged**
