### PR TITLE
AMIGAOS4: RM2AG.rexx rewrite

### PR DESCRIPTION
**Pull request by raziel-**
Complete rewrite of the (AmigaOS4-only) RM2AG.rexx script to cover the change to markdown.

I´d like to ask for review and some questions before it gets merged.

- Is there some kind of list where someone could add this file regarding "automatic" version updates?
I have added a version information (line 33) to the script (amongst other things) but would refrain from doing a manual change everytime a new version appears.

There are of course other options:
1) I could drop the whole line.
2) I could stick with the scripts version (0.20 right now e.g.)

- Lines 163-166 add a conversion from the markdown/html in-readme link (of the files NEWS.md and AUTHORS) to an AmigaGuide specific one, which will open the given files locally from within the installed archive (if available).
I don´t really like the solution i have now, i´d rather do it in the sed conversion script beforehand, but i´ve got no idea whatsoever how to achieve that. I don´t speak sed.
So, if anyone can lend me a hand and help me find the correct sed syntax to change the following lines, i´d be grateful.

I want to change
Please refer to our extensive Changelog [here](NEWS.md).
to
Please refer to our extensive Changelog {@"[here]" link NEWS.md/main}.
and
Please refer to our extensive Credits list [here](AUTHORS).
to
Please refer to our extensive Credits list {@"[here]" link AUTHORS/main}.

- For some reason neither README.md nor NEWS.md gets copied on a full installation build.
I do have cp $(DIST_FILES_DOCS) $(AMIGAOSPATH) in amigaos.mk, but they doesn´t seem to get picked up?

Thank you and sorry for the mistakes i surely made and the noise

### CODE REVIEW

**Comment by lotharsm** [comment]
>     * Is there some kind of list where someone could add this file regarding "automatic" version updates?
>       I have added a version information (line 33) to the script (amongst other things) but would refrain from doing a manual change everytime a new version appears.

Have a look at ./devtools/update-version.pl. This script allows it to easily replace version numbers. You basically include a placeholder in the appropriate .in file and update-version.pl will do the rest.

**Comment by raziel-** [comment]
Thanks a lot, i thought there might be something similar.

Will have a look at it soon

**Comment by raziel-** [comment]
@lotharsm 

Like so?

@sev- 

Can you maybe help with sed?

**Comment by lotharsm** [comment]
You are almost there. However, please rename the file .rexx file to .rexx.in. The Perl script will pick up the .rexx.in file, process it and write the output with the correct version information in the .rexx file.

**Comment by raziel-** [comment]
Could you do it, please?
I don´t seem to be able to rename a file from the web interface.

**Comment by lotharsm** [comment]
Sorry, I should have been more precise. Leave the .rexx file in its previous state (with the version hard-coded in it) and then create a new file called .rexx.in with the placeholder string.

**Comment by raziel-** [comment]
@lotharsm 

Does that look right to you?

**Comment by lotharsm** [comment]
Looks good to me :)

**Comment by lotharsm** [comment]
To make things easier to maintain, I recommend to make all further changes during this PR in the .in file and then if you think this is ready to get merged run the Perl script once to synchronize the .rexx file.

Of course if you want me to I can generate the rexx file after merging if you don’t feel comfortable using the Perl script. :)

**Comment by raziel-** [comment]
Yes, please.
I speak Perl as perfectly as Python, to say the least...so, not at all :-)

**Comment by lotharsm** [comment]
Alright, ping me when it's ready to get merged!

**Comment by raziel-** [comment]
Will do, thanks a lot

**Comment by raziel-** [comment]
@lotharsm

K, since nobody steps up regarding the sed part, i guess it's fine for me that this gets merged...if nobody objects, of course.

Tested on local tree and working

**Comment by lotharsm** [comment]
Okay then, I'll merge this later today and the run the Perl script to sync everything as I promised earlier. :)

**Comment by raziel-** [comment]
@lotharsm

Thanks a lot

**Comment by lotharsm** [comment]
No problem!

Can you verify that https://github.com/lotharsm/scummvm/commit/e380e6e0be69935e71af043f1e000b1936b0fda5 introduced no issues before I do the final push?

**Comment by raziel-** [comment]
All fine, thanks again

**Pull request merged**
