### PR TITLE
SYMBIAN: Update Symbian/README.

### PR DESCRIPTION
**Pull request by huhungahuru**
It mentions the versions that were available for Symbian and other minor fixes.

### CODE REVIEW

**Comment by bluegr** [comment]
But why did you update the port-specific README with the content from the main README? The port-specific file contains information relevant to the port itself

**Comment by huhungahuru** [comment]
Most characteristics of the versions were only repeated. So the games compatible with each new version were added, except those that have a higher screen resolution at 640x480 as Broken Sword 2.5.
Ultima 4 & 6 also also also compatible due to a conflict with the compiler.
The 3D games that work with ResidualVM are very slow in Symbian, so they are not mentioned in the list of compatible games.
The web addresses were updated in the rest of the description.

**Comment by aquadran** [comment]
it should only contain port specific information

**Comment by ccawley2011** [comment]
It would probably be better to get rid of the port-specific README file and replace it with a section in the [documentation portal](https://docs.scummvm.org/en/v2.5.1/), similarly to what is done for many other ports.

**Comment by lotharsm** [comment]
I second this - the platform specific README file(s) should be moved to the documentation portal, since we encourage to ship the current version of the manual with new release builds.

In case this is not possible on a specific platform, the README file should _only_ contain platform-specific changes while the rest of the documentation should be left untouched.

**Comment by fedor4ever** [comment]
Do not merge!!! This README shows to user while ScummVM installation. It shows port-specific changes only.

**Comment by sev-** [comment]
We cannot accept this.

**Pull request closed without merging**
