### PR TITLE
WINTERMUTE: Add new reversion Steam releases

### PR DESCRIPTION
**Pull request by aviloria**
Added new reversion1 and reversion3 Steam releases.
Also added support for a new language: Serbian

### CODE REVIEW

**Comment by somaen** [comment]
Thanks. Something looks odd with the Serbian-language patches, would you mind merging them together into a single patch?

**Comment by sev-** [comment]
@aviloria ?

**Comment by aviloria** [comment]
Sorry, I overlooked the message...
What do you mean? Do you want me to isolate Serbian language changes from the new game additions?
What's the problem with the Sebian patch?

**Comment by Mataniko** [comment]
It looks like your commits are duplicates because some of them have the same commit message.

You don't need to commit one file, or one line at a time, please make all of the relevant changes into 1 commit and update the PR.

**Comment by aviloria** [comment]
Sorry about that... I mixed web and command-line commands when commiting... so result was a bit weird.
I hope all looks better now

**Comment by sev-** [comment]
Looks fine now besides some small issues with indentations which I will fix after the merge.

**Pull request merged**
