### PR TITLE
GRAPHICS: Reduce the size of the YUV to RGB tables

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by bluegr** [comment]
@ccawley2011 Please, amend the last commit's title, there's a stray tilde. It should be "GRAPHICS: ...", not "~GRAPHICS: ..."

**Review by bluegr — APPROVED** [review]
LGTM

**Comment by ccawley2011** [comment]
> @ccawley2011 Please, amend the last commit's title, there's a stray tilde. It should be "GRAPHICS: ...", not "~GRAPHICS: ..."

Good catch, fixed.

**Comment by sev-** [comment]
Thank you!

**Pull request merged**
