### PR TITLE
WIN32: Fix embedding disabled engine files

### PR DESCRIPTION
**Pull request by sluicebox**
Fix Windows builds (msvc and mingw) including data files from disabled
engines as embedded resources in executable. Bug #10878

### CODE REVIEW

**Comment by sluicebox** [comment]
I copied the pattern used by internal_version.h for factoring out definitions that scummvm.rc needed to include.

Short version of this bugfix: scummvm.rc has been using STATIC_PLUGIN without it being defined. To make it available for including it needs to be in a simple header file, otherwise including plugins.h brings in a world of c++ that the mingw resource compiler chokes on.

**Comment by ccawley2011** [comment]
You may want to move `PLUGIN_ENABLED_STATIC()` and `PLUGIN_ENABLED_DYNAMIC()` into `base/internal_plugins.h` as well and use those to check for enabled engines in the resource script.

I also suggest that PR #1445 is merged alongside this one, as without it, `scummm.rc` won't be rebuilt when configure is re-run, which could result in some datafiles being missing if the list of engines changes.

**Comment by digitall** [comment]
Since PR #1445 has been open for some time without any argument, I am going to merge that now since it looks pretty self-contained and the Win32 / WinCE porter will need to do some testing / feedback anyway to catch any issues.

**Comment by sluicebox** [comment]
`PLUGIN_ENABLED_STATIC` would be more readable in the resource script but it depends on `DYNAMIC_MODULES`. Is `DYNAMIC_MODULES` defined for the resource compiler when dynamic modules are used? I don't know, but if it isn't, then we're back where we started.

I don't have real opinions about the resource script layout as long as it works, but you want to keep things simple for the poor unloved resource compiler, so as soon as you have to think about macro dependencies you're in trouble. I barely trust the thing to compare symbols.

I'm unfamiliar with setting up or testing dynamic module scenarios so I wouldn't be confident making changes myself that could affect those beyond this bug fix.

**Comment by sluicebox** [comment]
Since PR #1445 adds a line to `win32.mk` that references `internal_version.h`, do I need to update that line to also include `internal_plugins.h` since it's a new `scummvm.rc` dependency? (I don't know make files well)

**Comment by ccawley2011** [comment]
> `PLUGIN_ENABLED_STATIC` would be more readable in the resource script but it depends on `DYNAMIC_MODULES`. Is `DYNAMIC_MODULES` defined for the resource compiler when dynamic modules are used? I don't know, but if it isn't, then we're back where we started.

`DYNAMIC_MODULE` is defined in `config.h`, which the resource script already includes. As such, this is unlikely to be an issue in this case.

> Since PR #1445 adds a line to `win32.mk` that references `internal_version.h`, do I need to update that line to also include `internal_plugins.h` since it's a new `scummvm.rc` dependency? (I don't know make files well)

You can, but it's not required since `internal_plugins.h` is less likely to change often like the other two headers are.

**Comment by sluicebox** [comment]
Okay, I'm sold, I'll add that in a bit.

**Comment by bluegr** [comment]
Well done! This does indeed make the RC compiler work correctly in this cass. Since this got a lot of upvotes already, it’s a straightforward change, and it’s been open for 9 days already, it’s fine to be merged.

Merging

**Pull request merged**
