### PR TITLE
Call idle timer changes on main thread

### PR DESCRIPTION
**Pull request by jonnyijapan**
http://forums.scummvm.org/viewtopic.php?p=86277

### CODE REVIEW

**Comment by digitall** [comment]
These proposed code changes look fairly self-explanatory and reasonable given the described bugs and are limited to the IOS port so this looks good.

However, the commit messages do not conform to our http://wiki.scummvm.org/index.php/Commit_Guidelines so I don't want to merge this as-is. Also, the extra merge commit is not required.

I will cherry pick these commits, amend the commit messages and rebase them onto the master branch shortly to close this out.

@jonnyijapan : Thanks for providing this code fix.

**Comment by digitall** [comment]
Committed as 58f3aac49ece050ddd3f5a51b4033a1bcadc08a7 ... Closing.

**Comment by criezy** [comment]
@digitall You didn't leave me much time to review before merging :-P
Or was asking for my review a misclick?
In any case the change seems fine to me and I see you fixed the commit message when cherry-picking. And buildbot seems happy with it as well. So it''s all good.

**Comment by digitall** [comment]
@criezy : Yes, sorry about that. It was intentional. The code change was logical given the described issue so I was happy to merge and close, but since I don't have any IOS devices to test with and not the OSX/IOS porter, I thought that you should take a look for "second opinion" to make sure I hadn't just broken older IOS builds or something. :) Anyway, will put a comment to explain in future :)

**Pull request closed without merging**
