### PR TITLE
XEEN: Fix dismiss button and character selection visual glitches

### PR DESCRIPTION
**Pull request by FrostyHitoshura**

### CODE REVIEW

**Comment by dreammaster** [comment]
Thanks for the fixes. I've reviewed and already pushed the first two commits into master. As for the third one, could you edit the commit and bump up the create_xeen's VERSION_NUMBER, and the corresponding check in the Xeen engine when it loads it? This is needed to help prevent any potential case of new code accidentally using old data.

**Comment by FrostyHitoshura** [comment]
Thanks for the code review. I'm willing to do the change you requested but I'm unsure how to do it efficiently with github. What consider doing is to start a new branch based on latest master, cherry pick the last commit, do the modification and amend the commit and finally create a new pull request with it and close this one. Is it the best approach?

**Comment by dreammaster** [comment]
Using the existing branch should be fine. Just make the changes to the version and regenerate the xeen.ccs, and then use git commit --amend -a to update the final commit with your changes. Then use push -f to push the commit from your local branch to your one on github.

**Comment by FrostyHitoshura** [comment]
Happy to hear that this is simple to do with GitHub, I've had bad experience with GitLab in this regard.

**Comment by dreammaster** [comment]
Thanks for the further change. I've reviewed it and manually cherry-picked the final commit. So closing the pull request now.

**Pull request closed without merging**
