### PR TITLE
SCUMM: RFC: (Obsolete?) Make certain workarounds optional

### PR DESCRIPTION
**Pull request by eriktorbjorn**
Based on some posts in https://forums.mixnmojo.com/topic/200399-scummvm-versus-native-interpreters/ it seems that there are those who feel like ScummVM should offer some option to _not_ fix certain bugs. Well, that opens up a can of worms since a) I doubt ScummVM is _ever_ going to play every game pixel-perfect compared to the original, and b) that would be a _lot_ of options that hardly no one would ever want to touch. The SCI engine alone, where script patching is down to a fine art, there appear to be hundreds of them.

I mean, are there actually players who _want_ the green goo in Sam & Max's Hall of Oddities to be slightly misaligned, or want Sam and Max to sometimes appear in colour when noir mode is activated? I doubt it.

But let's say we make some concessions to those who want the see the original behavior without breaking out DOSBox? This patch adds four such settings to the SCUMM engine:

- An option for whether or not to restore the animated cigar smoke in the MI1 captain Smirk close-up. _The Art of Point-and-Click Adventure Games_ by Bitmap Books show a screenshot without the cigar smoke, so that's something people might notice.
- An option for whether or not to restore the original MI1 clock tower behavior. There was some discussion about whether or not to make it optional when this was worked around.
- An option for whether or not to restore the missing MI1 Lemonhead lines.
- An option for whether or not to fix the Chaos/Choas typo in VGA Loom. The typo was mentioned by Brian Moriarty in his GDC Loom retrospective, so that's something people may be aware of.

Is this a good idea or not?

The patch also forces the SCUMM engine to update the "extra" field in the config file, if it isn't set already, since it's needed to tell certain versions apart. So even if nothing else from this pull request is merged, that may still be a good idea?

### CODE REVIEW

**Comment by AndywinXp** [comment]
While I personally strive for ScummVM best accuracy compromises, I'm also convinced that the original interpreters/scripts had bugs and/or occasional glitches which were certainly not intended to be there :P (and I know you agree with me on this).

That being said... players with the obsession of having even the ugliest glitch replicated in ScummVM DO exist. But IMHO they're a small minority, and (still IMHO) they should not have the power to impact decisions which might prevent us from giving the rest of the playerbase a better experience overall.

That being said™ (part 2), I really like the idea of having options (after all, this is exactly one of the reasons ScummVM is frankly cooler than the original EXEs), but I personally would suggest leaving the fixes _on_ as per the default setting :)

**Comment by lephilousophe** [comment]
> EDIT: Also, what would your personal stance be on grouping all fixes in a single on/off toggle? I'm sure there are going to be many more to be added in the future and doing so could help avoiding a long GUI list of checkboxes.

I second this proposal.

**Comment by raziel-** [comment]
I'm just a mere user, so i don't know if i have any say in this, but

a) I can see a mountain of bug reports avalanching in with people reporting bugs that are none (do you really want to ask every single bug reporter if he/she/it has turned the fixes off?)
b) There is ScummVM and there is DosBox, do we need to compete with them?
If someone wants the game emulated (with warts and all) they can use DosBox, if they want the best user experience, they can use ScummVM (imho)
c) Just like @eriktorbjorn mentioned, this will open a huge can of worms which might need a whole lot more time to take care of than imagined today.
I d rather see *your* precious time go into more of the awesome original bug fixing, enhancing and developing new engines and bells & whistles...

But, of course, these are just my two cents :-)

**Comment by AndywinXp** [comment]
>  b) There is ScummVM and there is DosBox, do we need to compete with them? 

This is also a really good point

**Comment by eriktorbjorn** [comment]
> That being said™ (part 2), I really like the idea of having options (after all, this is exactly one of the reasons ScummVM is frankly cooler than the original EXEs), but I personally would suggest leaving the fixes _on_ as per the default setting :)

The options I added here should be on by default. If they're not, I did something wrong.

> EDIT: Also, what would your personal stance be on grouping all fixes in a single on/off toggle? I'm sure there are going to be many more to be added in the future and doing so could help avoiding a long GUI list of checkboxes.

I thought about it, and it might make sense. Perhaps we should simply add a single toggle for the three MI1 settings here and call it "Restore some features from earlier versions" or something like that, and drop the Loom Chaos/Choas toggle? (And hope pepole won't then expect to see the EGA sunset, or the stump joke.)

Either way, I don't see any reason to have _every_  bug fix affected by settings. I haven't heard anyone clamoring for ScummVM to reintroduce the infamous Broken Sword 2 "pyramid bug", for instance. (A bug where if you exhausted the dialog options for a certain character, an object in the same room would no longer be possible to pick up.)

**Comment by AndywinXp** [comment]
> > That being said™ (part 2), I really like the idea of having options (after all, this is exactly one of the reasons ScummVM is frankly cooler than the original EXEs), but I personally would suggest leaving the fixes _on_ as per the default setting :)
> 
> The options I added here should be on by default. If they're not, I did something wrong.

My bad, I admit I didn't check the whole code but just snippets.

**Comment by somaen** [comment]
My 2 cents is that I'd prefer ScummVM to prioritize the best player experience over perfect archival reproduction. 

That is to say that I think we should present the games close to the original representation, but where improving the game doesn't detract from the original experience, such as mouse support in some older Sierra games, or fixing bugs such as the plot-breaking Domino-bug in Grim Fandango we clearly should fix those bugs.

I wouldn't vote against a "purist-mode" though, but then you get the entire question of whether such a mode should drop ALL bug fixes, or whether we should be selective. If we are to be selective then there's suddenly a bit more work involved whenever we fix issues vs the original game.

At the end of the day ScummVM serves two target audiences, people that played the games in their original release, and people that missed out on them originally but want to pick them up now. The closest experience to true purism is probably best served by DosBox/WinUAE/SheepShaver (if not the actual hardware). We're in a position where we can serve both mentioned audiences to some degree, but I'd put a slight priority on the "improved experience" approach over purism, just because we probably never can achieve 100% DosBox-parity.

**Comment by sev-** [comment]
I agree, that some users would want the _authentic_ experience. This is the reason why we keep adding relatively small things like Mac or CGA rendering, pixel-perfect text rendering etc.

However, I wonder, does it make sense to add a separate option for every feature, versus a general one, something like: "Keep the original behaviour" with the tooltip "ScummVM fixes some inconsistencies and graphical glitches, this option lets you keep the original behaviour"?

**Comment by eriktorbjorn** [comment]
The problem I see with a catch-all "keep the original behavior" option is that there are probably plenty of cases where we never implemented the original behavior (e.g. we don't implement the original bugs in the Sam & Max "noir" mode), or where the original behavior broke the game. That's why I limited my examples to some of the more intrusive changes. (However, since I'm the one who added those changes - I think I added the Loom one at least, but I could be wrong - I'm not exactly unhappy about the hesitance against making them optional so far. :-)

And some things are so small that I didn't think it worth it to make them optional. I used Sam & Max as an example of things I see no reason to have an option for. Here's what I meant:

sam-and-max-goop

Note how in the left image (from DOSBox), the green contents of the tank is slightly misaligned, allowing some pixels of Max's head to shine through it without a green tint. ScummVM (on the right) fixes that. Other things I can think of is the recent [partial workaround](https://github.com/scummvm/scummvm/pull/3732) for an animation glitch in VGA Loom.

**Comment by dwatteau** [comment]
As a simple, humble ScummVM user, who's also quite obsessive with all the SCUMM games, I also think that the best compromise would be to have a single "Fix some original bugs and glitches" toggle which is on by default. Having too many checkboxes would make the UI KDE-like and really confusing for the vast majority of users, in my opinion.

**Comment by eriktorbjorn** [comment]
I don't know which workarounds are actually bugs in the original, and which ones are bugs that only appear in ScummVM. Ones I do know of are:

- The positioning of the goo in Sam & Max. (See picture above.)
- The animation when Mandible is  using the distaff in VGA Loom. In the original, it appears to only light up three times, not four.
- Examining the dragon's pile of gold a second time in the TurboGrafx-16 version of Loom prints no message. (ScummVM works around the bug, but disabling the workaround produces a _different_ buggy behavior than the original.)
- At least one Mac version of Monkey Island 2 doesn't have a difficulty selection screen.
- Guybrush doesn't say anything when receiving the map piece from Rapp in Monkey Island 2. (Apparently the special edition still plays the speech here?)
- The Mac version of Monkey Island 2 is missing some music. (ScummVM works around this by playing the Roland MT-32 music instead, since the Mac instruments is a subset of the MT-32 instruments.)

But there are plenty of other cases in the code that's also commented as bugs in the original. So it's not exactly trivial to produce a complete list.

**Comment by bluegr** [comment]
Closing this one in favor of #3757

**Pull request closed without merging**
