### PR TITLE
M4: Avoid unaligned memory access

### PR DESCRIPTION
**Pull request by ccawley2011**
This fixes [Trac #15148](https://bugs.scummvm.org/ticket/15148).

### CODE REVIEW

**Comment by dwatteau** [comment]
Thanks @ccawley2011, this does fix the SIGBUS on the OpenBSD/loongson mips64el device for which I've reported the Trac issue above!

Strangely, though, now that I can play Orion Burger on this machine, I'm seeing the following problem with dialogue options in the French release:

scummvm-burger-fr-00000
scummvm-burger-fr-00001

i.e. `Qui êtes-vous` becomes `Qui jtes-vous`, `protéines` becomes `protiines`, `Où` becomes `Oy`…

the same files on my regular macOS x64 machine don't show this issue, even after applying this PR on it as well.

**Review by dwatteau — APPROVED** [review]
@ccawley2011 it's actually all good to me when applying this PR on the affected device

The character issue above actually came from an OpenBSD bug with strchr/strrchr and signed characters on mips64: https://ftp.openbsd.org/pub/OpenBSD/patches/6.9/common/011_strchr.patch.sig

So it's all good now! Thanks

**Comment by bluegr** [comment]
Thanks for your work @ccawley2011 and for testing it @dwatteau!

This is a straightforward implementation, which fixes the actual issue.
Merging

**Comment by dwatteau** [comment]
Hi @ccawley2011,

FWIW, it looks like the switch to `uintptr` in commit 39f0c165c30118919ba082372acdd18ea72f2b3d  caused a regression on big-endian systems:  
https://bugs.scummvm.org/ticket/15513

**Pull request merged**
