### PR TITLE
Use parallel build on travis

### PR DESCRIPTION
**Pull request by janisozaur**
According to https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments, container-based
jobs offer two cores, which should provide quicker turnaround times.

Check times against first-ever travis build:
https://travis-ci.org/scummvm/scummvm/builds/147974521

### CODE REVIEW

**Comment by janisozaur** [comment]
Timings from builds
* `#1`: https://travis-ci.org/scummvm/scummvm/builds/147974521
* `#2` (this PR): https://travis-ci.org/scummvm/scummvm/builds/147976295

| **times**       | `gcc`  | `clang` |
|-----------------|--------|---------|
| `-j1` (default) | 10m25s | 7m33s   |
| `-j2`           | 7m3s   | 4m42s   |

**Comment by sev-** [comment]
Great, thanks! Merging.

**Comment by sev-** [comment]
Hmm.. I just noticed. Could you please change to commit log message in accordance with our policies, e.g. "BUILD: Use parallel build on travis"

**Comment by janisozaur** [comment]
@sev- can you please squash-merge this? GitHub will give you an option to rename my commit for me, as I do not have access to anything else other than web UI right now.

**Pull request merged**
