### PR TITLE
 BUILD: Use C++14 / C++11 by default

### PR DESCRIPTION
**Pull request by ccawley2011**
Originally from PR #1128

### CODE REVIEW

**Comment by sev-** [comment]
This switched to C++14 compilation by default, which needs to be discussed with the porters on -devel first.

**Comment by bluegr** [comment]
Renaming for brevity

**Comment by lotharsm** [comment]
Any news on this?

**Comment by sev-** [comment]
So, in order to have a newer C++ standard enabled by default, so we could start relying on it, somebody needs to add in a separate file a series of tests for all the desired functionality, just calling is fine, and make a separate configure key for enabling it.

Then, at the time of release, we will ask all porters to try to compile it and report. This way we will understand any potential losses or complications.

In the meantime, closing this.

**Pull request closed without merging**
