### PR TITLE
SCI: Script patch for LB2 desk lamp, bug #10706

### PR DESCRIPTION
**Pull request by sluicebox**
Fixes a broken message in floppy version

### CODE REVIEW

**Comment by dafioram** [comment]
Works well. Good fix.

**Comment by m-kiewitz** [comment]
Very good, thanks for also finding this original game bug.

But please add the following 3 lines to your comments.
// Applies to at least: English floppy
// Responsible method: deskLamp:<noname300>(39), which is really doVerb
// Fixes bug: #10706

I own at least 1 localized floppy version. Will check that one, if it has the same issue.
If that's the case, I can verify if the patch also applies to that one.

**Comment by m-kiewitz** [comment]
// Applies to at least: English floppy
should mention 1.000 too of course. I missed that.

**Comment by sluicebox** [comment]
I've updated the comment.

I have quite a few of the localized floppy versions, possibly all, and you should find that all of them are based on version 1.1 which fixes the bug. Extremely interested if you find otherwise!

**Comment by bluegr** [comment]
Very good work! Thanks for your patch. I've tried it and it works great :)
The floppy version of LB2 did not have a selector dictionary (i.e. dictionary 997), which is why most object methods don't have names.

Merging, thanks!

**Pull request merged**
