### PR TITLE
Update ios.rst

### PR DESCRIPTION
**Pull request by SLSX**
--disable-theoradec leads to ERROR: "theoradec" is not a feature! 
--disable-theora allows to successfully compilation

### CODE REVIEW

**Comment by criezy** [comment]
Are you sure you didn't try to use those instructions with the 2.5 branch? Using `--disable-theora` would be correct for that branch, and this is correctly used in the 2.5.1 documentation (https://docs.scummvm.org/en/v2.5.1/other_platforms/ios.html). However it looks like the feature was renamed theoradec two months ago in 52dcac9fc6. So I would expect `--disable-theoradec` to be correct with the latest code.

**Comment by SLSX** [comment]
No, you're absolutely right. I followed https://docs.scummvm.org/en/latest/other_platforms/ios.html, which leads to an older Version (2.2.0). A bit confusing.

**Comment by criezy** [comment]
Oh right. The clone command for the latest doc probably needs to be changed!

**Comment by sev-** [comment]
Yes, I changed it to `theoradec` last week because in 2.6.0 this library name was changed.

**Pull request closed without merging**
