### PR TITLE
PINK: fixed pausing when menu bar disappears

### PR DESCRIPTION
**Pull request by whiterandrek**
This pull request makes pink panther scenes to resume correctly after using menu bar

### CODE REVIEW

**Comment by henke37** [comment]
This is a "yiekes" from me. This is steamrolling over a counter to get a desired result without regards to the count being correct.

**Comment by henke37** [comment]
If anything, the best solution in my eyes is to rewrite the engine pause system from the ground up. No more manual pause/unpause. Use RAII to automatically increment and decrement the counter based on object lifespans.

**Comment by whiterandrek** [comment]
The problem is not in pause system itself, but in menu which pauses the engine 2 times, but  unpauses 1 time
E.g
Menu appeared -> engine paused 1 time
Mouse button down -> engine paused 2 time
Mouse button up -> engine unpaused 1 time

**Comment by henke37** [comment]
Then the menu system should be fixed. The engine is innocent and should not be attempting to cover for the menu system.

**Pull request merged**
