### PR TITLE
SDL: Implement first person gamepad mode, toggle with R+L

### PR DESCRIPTION
**Pull request by rsn8887**
The new mode is useful for Dungeon RPG games like Lands of Lore.
When pressing R+L to switch control modes, a message pops up saying either
`Gamepad Mode - First Person RPG`
or
`Gamepad Mode - Regular`.

The message is displayed using `g_system->displayMessageOnOSD()`.

More details, using Switch as example.

Note, on Switch, B,A,Y,X are bottom,right,left,top buttons, and Plus is Start and
Minus is Select.

Compared to Switch, SDL Gamecontroller standard uses swapped A<->B and Y<->X button names.

Old regular controls (default, as before)

|Input          |Effect                                                            |
|---------------|------------------------------------------------------------------|
|Left stick     |Mouse                                                             |
|R + Left stick |Slow Mouse                                                        |
|B              |Left mouse button                                                 |
|A              |Right mouse button                                                |
|DPad           |Keypad "Cursor" Keys (useful for character motion in Sierra games)|
|R + DPad       |Diagonal Keypad "Cursor" Keys                                     |
|L Trigger      |Game menu (F5)                                                    |
|R Trigger      |Shift (used to enable Mass Add in menu)                           |
|Y              |Period '.' (used to skip dialog lines)                            |
|R + Y          |Space ' '                                                         |
|X              |Escape (used to skip cutscenes)                                   |
|R + X          |Return                                                            |
|Plus           |ScummVM's global in-game menu                                     |
|Minus          |Toggle virtual keyboard                                           |
|R + Minus      |AGI predictive input dialog                                       |
|R + L          |Toggle first person mode on/off                                   |

New first person controls, useful for Lands of Lore style games. Toggle via R+L.

|Input          |Effect                                                            |
|---------------|------------------------------------------------------------------|
|Left stick     |Mouse                                                             |
|Y + Left stick |Slow Mouse                                                        |
|B              |Left mouse button                                                 |
|A              |Right mouse button                                                |
|DPad           |Keypad keys up/down/diagonal (walk/turn in Lands of Lore)         |
|Y + DPad       |F1/F2/F3/F4 (useful to attack in Lands of Lore)                   |
|L Trigger      |Keypad left (strafe left in Lands of Lore)                        |
|R Trigger      |Keypad right (strafe right in Lands of Lore)                      |
|Y              |Shift (used to enable Mass Add in menu)                           |
|X              |Escape (used to skip cutscenes)                                   |
|Y + X          |Return                                                            |
|Plus           |ScummVM's global in-game menu                                     |
|Y + Plus       |Game menu (F5)                                                    |
|Minus          |Toggle virtual keyboard                                           |
|Y + Minus      |AGI predictive input dialog                                       |
|R + L          |Toggle first person mode on/off                                   |

### CODE REVIEW

**Comment by ccawley2011** [comment]
While providing alternative controls for games like Lands of Lore seems like a good idea, I'm not fond of the fact that this game-specific control mode is hardcoded into the SDL backend. What would perhaps be a better idea would be if the backend returned gamepad events instead, and then the engine handles remapping if needed. ResidualVM already does this, so that could be used as a reference for how to implement this.

**Comment by tsoliman** [comment]
@ccawley2011 I think remapping should be handled in the EventMapper layer with cooperation from the engine (providing what engine-events are expected) and the backends (providing what hardware-events can be emitted).

**Comment by rsn8887** [comment]
So I guess this is a no-go for this PR then? Because I will not have time to do the major changes mentioned in your comments.

**Comment by rsn8887** [comment]
Note the modifier key is changed between control schemes... making treatment in the engine hard I think but I don’t know much about engine event handlers.

**Comment by tsoliman** [comment]
> So is this is a no-go for this PR then?

Not my intention at all. Just a suggestion is all.

**Comment by rsn8887** [comment]
@ccawley2011 since you are not fond of this. 

I suggest to merge this for now pending that rewrite of engine event handling with controller events? I think the mentioned re-write would be quite a major change re-visiting all engine input (and menu input) remappings. 

With this PR at least Lands of Lore becomes more playable with a game controller for the next release.

**Comment by rsn8887** [comment]
@ccawley2011 : Some additional request came in via Discord to also remap Starship Titanic etc.

Can you maybe point me to the places in engine/menu code where events are mapped, where this re-mapping should be done?

I guess I have to define new scummvm events like GAMECONTROLLER_X etc. similar to how there are already events like the game menu event, and then handle those events somewhere down the road?

**Comment by rsn8887** [comment]
Note to self: this should be done in the lol engine using the same method as used for Pegasus in https://github.com/scummvm/scummvm/pull/1681

**Comment by bluegr** [comment]
Any news on this?

**Comment by rsn8887** [comment]
No. This has to be done completely differently by modifying the Kyra Engine code itself, similar to what has been done in the Journeyman Game. However, the Kyra Engine input loop looks completely different to me than the Journeyman input loop. So at the moment I wouldn't know where to start.

**Comment by rsn8887** [comment]
I forgot I had this sitting as a PR from my master.

I force-pushed to my master. Then committed to official master.

So now this PR is closed and shows up merged, but what was actually merged is different code.

**Pull request merged**
