### PR TITLE
DRASCULA: fix crash/graphic glitch at castle towers

### PR DESCRIPTION
**Pull request by norbertbajko**
Fix bug #5903 DRASCULA-IT: Crash/graphic glitch at castle towers
http://sourceforge.net/p/scummvm/bugs/5903/

The problem was that if you looked at the tower Hacker's head started flying on the screen with the subtitle and the game crashed.
Now I fixed it: the game is not crash, there is no flying head and the subtitle is fixed on the screen upper-center.

withoutheadpluscenter

### CODE REVIEW

**Comment by wjp** [comment]
Thank you for taking a look at this.

Can you explain why your patch is the correct way of solving this problem?

**Comment by norbertbajko** [comment]
I fixed the character's coordinates because that caused the crash. The game thought the character is sill moving and when the character went out the screen an array was indexed with a negative index. Because that the array get corrupted and a memcpy function crashed the game. I talked with Sev a lot about the head problem and we came to the conclusion the logical solution is hiding the unnecessary head. And finally I think upper-center is the best place for the subtitles without Hacker's head.

**Comment by wjp** [comment]
How did this scene behave in the original Drascula game in DOS?

**Comment by norbertbajko** [comment]
I played it to the towers and it has the bug too.

dos

**Comment by wjp** [comment]
Ok, thanks.

Could you add some source code comments explaining that too?

**Comment by norbertbajko** [comment]
What do you think of exactly?

**Comment by wjp** [comment]
Some comments that explain what the code and checks you're adding are doing, and which bug they solve.

I realise the drascula engine is pretty poorly commented, but it's never too late to start.

**Comment by norbertbajko** [comment]
I wrote some comments in the code to my changes, is it enough?

**Comment by wjp** [comment]
Yes, I think so. Thanks for the rapid responses and changes.

**Comment by bluegr** [comment]
I just tried your changes, and they are indeed the correct way to solve this issue. Thanks for your work! Merging

**Comment by norbertbajko** [comment]
My pleasure

**Pull request merged**
