### PR TITLE
SCUMM: Implement timing handling from the original interpreters

### PR DESCRIPTION
**Pull request by AndywinXp**
Ciao! This PR implements the handling of game timers done by the original interpreters:
* By using [eriktorbjorn's work](https://github.com/scummvm/scummvm/pull/3754) as a basis, whose waitForTimer function is scaringly accurate, so thank you for that!
* By using quarter frames as a base unit instead of milliseconds (nicknamed piffies, by the way), so that screen effects can behave as they should;
* By using four quarter frames (one jiffie!) per game tick;
* By using the [Intel 8253/54 PIT](https://en.wikipedia.org/wiki/Intel_8253) as a reference for the timings, which is the one referenced by the DOS versions of each game;
* By implementing what SCUMM exactly expects from VAR_MUSIC_TIMER (now the Monkey Island logo appears in sync with the music on MI1 Floppy!) and from the speech timer (which now is not simulated by 60Hz ticks on the audio file current position, but by an actual timer);
* By fixing some version specific stuff here and there and removing previous timing workarounds where obsolete.

This PR of course takes inspiration from (but it's not limited to) some of the UrQuan's changes but every single change he made has been re-researched and verified from scratch, and rewritten by me (and turns out that some assumptions made in that fork were not correct in the first place).

My whole PIT related research and reasoning can be found here: [https://bugs.scummvm.org/ticket/13354](https://bugs.scummvm.org/ticket/13354)

I think there are a couple of things left before this PR can be deemed as complete:
* Implement ~~Amiga~~ and FMTowns timings for the correspondent games; for now the frequency adjustments only apply to DOS games, every other game runs at a 240Hz quarter frame fallback rate (so 60Hz, just as before);
* ~~Check if INSANE and SMUSH need these kind of timing adjustments (IIRC, we currently run some FT videos slower than intended, being that the framerate is fixed at 10 for every video).~~

As usual, even though this is partially WIP, I'd love to get some reviews and opinions on it, so please go nuts.

### CODE REVIEW

**Comment by eriktorbjorn** [comment]
> (which now is not simulated by 60Hz ticks on the audio file current position, but by an actual timer)

That alone makes me happy, since it would get rid of one of the oldest hacks in the SCUMM engine. :-)

**Comment by AndywinXp** [comment]
Here we go: I checked for what needed adjustments in SMUSH and INSANE domain and I only changed one thing in the latter that we were previously missing in our current implementation; if we have to be ultra-precise, there are some video timer quirks which we're not implementing (something about changing the framerate mid callback, used when switching to certain scenes without an explicit startVideo()).

But frankly I don't want to touch it more than I did for now. INSANE already works great and it's almost a 1:1 reproduction of the original system; so, until any serious reason comes up, it's just not worth to change anything else in the infrastructure if it's not connected to a game breaking problem or if it doesn't yield a visibly wrong framerate.

Being that I have worked towards a easy-to-extend timing setup code, and being that I have no skills (or literally the games) for the other remaining task, I'd be okay with the FMTowns and Amiga stuff being added afterwards as separate commits. So I'm ready for a last review.

**Comment by AndywinXp** [comment]
Amiga support is now implemented, thanks to... you guessed it, athrxx! :-P

**Comment by bluegr** [comment]
Very nice work overall! The changes done are very well documented and researched, and the timing looks to be improved in the games I tried (Zak V1, MI1 floppy, MI1 CD, MI2, DOTT, Sam'n'Max, MI3, FT, Dig).

It's good that there is a fallback to the old behavior for the games that haven't been addressed yet (e.g. Zak Towns).
This PR has been open for almost 3 weeks now without any further feedback, so we can merge this, and any further work can be done in-tree.

Thanks again for your work! Merging

**Pull request merged**
