### PR TITLE
GUI: Account for the scroll bar size in ScrollContainerWidget objects

### PR DESCRIPTION
**Pull request by ccawley2011**
This currently works for `ScrollContainerWidget`s created using XML layouts, but not ones created using `TabWidget::addTab()` or `OptionsContainerWidget`.

Before:
scummvm-00003

After:
scummvm-00001

### CODE REVIEW

**Comment by sev-** [comment]
So far, looks proper to me

**Comment by sev-** [comment]
Merging this because it is already an improvement

**Comment by tag2015** [comment]
After this PR merge, scrollbars don't show up anymore in the Keymaps and Achievements tabs (on my windows build). Can anyone confirm?

**Comment by ccawley2011** [comment]
> After this PR merge, scrollbars don't show up anymore in the Keymaps and Achievements tabs (on my windows build). Can anyone confirm?

I haven't checked this since the PR was merged, but that was the main reason why I'd originally left this as a draft. I was hoping that someone else would be able to figure out how to get that working, but if this isn't possible in the near future it might be best to revert these changes for now. Sorry for not being more clear about the state of this PR in the initial post.

**Comment by schmurtzm** [comment]
I confirm : no more scrollbar on x86 Windows or on ARM linux. 
Really annoying on handhelds which doesn't have mouse wheel to scroll 😞

**Comment by mikrosk** [comment]
Slightly (?) related to https://bugs.scummvm.org/ticket/14458, posting it in hope that you could look at that as well. :)

**Pull request merged**
