### PR TITLE
KYRA: LoK - Fix chat duration

### PR DESCRIPTION
**Pull request by akorotkov**
When both subtitles and voice are enabled use voice duration as in the original game.

### CODE REVIEW

**Review by bluegr — APPROVED** [review]
LGTM

**Comment by athrxx** [comment]
I have just checked the disassembly: The orginal code has one code path where it will query the sound status when the text display is disabled and the speech has started and another code path which will measure the time according to the text speed setting when the text display is on. So our code seems to be correct and behave exactly as the original.

**Comment by akorotkov** [comment]
I didn't disassemble the code, but currently, the behavior doesn't match the original game.  Please, check the two video files. The first one is the CD-version of the game under dosbox-x.  The text duration and speech animation duration exactly match the duration of the voice.
https://github.com/scummvm/scummvm/assets/5437829/b4c72b5d-b3e5-44d0-944e-f67b4020b350
The second is the game under scummvm.  Both text duration and speech animation are much longer than the voice.
https://github.com/scummvm/scummvm/assets/5437829/f432c412-31c5-48af-9e07-afb3e9127b9c

I've shown this in the example of a single voice. But it's most annoying on dialogs which becomes full of lengthy pauses under scummvm.

**Comment by athrxx** [comment]
I have looked at it again, since I noticed that we were definitely ignoring the text speed setting here. We can merge your commit. I'll probably just have to add something...
Thanks!

**Comment by akorotkov** [comment]
Great, thank you @athrxx!

**Pull request merged**
