### PR TITLE
ACHIEVEMENTS: Allow Disabling Of Unlocked Achievement OSD Using Config Option

### PR DESCRIPTION
**Pull request by digitall**
This is designed to allow disabling of the unlocked achievement OSD message as per https://forums.scummvm.org/viewtopic.php?p=99672#p99672 ...

### CODE REVIEW

**Comment by bluegr** [comment]
Thanks!

It would be good to add this option to the GUI as well

**Comment by tag2015** [comment]
> Thanks!
> 
> It would be good to add this option to the GUI as well

Maybe a checkbox could be added to disable ALL the non-critical OSD messages (the "screenshot" message, the MT32 messages etc), just for the achievements seems a bit overkill

**Comment by digitall** [comment]
@tag2015 : I get your point of view, but I don't think that is necessary or desirable. The screenshot message only appears just after a screenshot is taken triggered by the user, the MT32 messages are fairly sparse in games and generally at scene changes, thus these are not really annoying or problematic for a player / user. However, the achievements unlocked popup is jarring and I have wanted to disable this in various AGS games i.e. Excavation at Hob's Barrow ... However, I would still like to leave this feature compiled and available to check the achievements list in the relevant tab, so this feature would be useful to me.

**Comment by digitall** [comment]
If we do end up adding options and GUI for disabling these non-critical messages, I would suggest these are separate options and not arbitarily grouped i.e. some people may want to disable the screenshot OSD, but not achievements OSD ...

**Comment by digitall** [comment]
> Thanks!
> 
> It would be good to add this option to the GUI as well

Will look at doing this. Can you suggest a similar option that has had GUI checkbox added to act as implementation reference? I can probably work this out, but good to follow an example.

**Comment by bluegr** [comment]
> > Thanks!
> > It would be good to add this option to the GUI as well
> 
> Will look at doing this. Can you suggest a similar option that has had GUI checkbox added to act as implementation reference? I can probably work this out, but good to follow an example.

PR #2737 would be an example (although the changes contain noise from padding amendments)

**Comment by tag2015** [comment]
> The screenshot message only appears just after a screenshot is taken triggered by the user, the MT32 messages are fairly sparse in games and generally at scene changes

I agree regarding the MT32 messages, but the screenshot OSD is annoying not because of the message per se, but because of bug [12846](https://bugs.scummvm.org/ticket/12846).
Anyway, if you want to add only a checkbox for the achievements OSD, maybe it could be placed in the Achievements tab in game options? Just above the "unlocked achievements" counter

**Comment by bluegr** [comment]
> p.s. that makes it a per-game option. obviously. But there aren't that many games that feature achievements so changing it shouldn't be much of a hassle for the user

In that case, the implementation of a per-engine/game checkbox will be much simpler, i.e. something like PR #5481

**Comment by bluegr** [comment]
Since we do have a separate config option for toggling screenshot OSDs, we can merge this to add an option for toggling achievement OSDs, and we can worry about adding a GUI option for both in a separate PR.

Thanks!

**Pull request merged**
