### PR TITLE
Support 4-bit windows cursors

### PR DESCRIPTION
**Pull request by phcoder**

### CODE REVIEW

**Comment by henke37** [comment]
You missed to update the comment right above the if statement that checks for support. Might as well remove the maintenance hazard there.

**Comment by phcoder** [comment]
> You missed to update the comment right above the if statement that checks for support. Might as well remove the maintenance hazard there.

Updated

**Comment by sev-** [comment]
Thanks, do you have any game or target which uses it?

**Comment by phcoder** [comment]
> Thanks, do you have any game or target which uses it?

Hades Challenge by Disney's Interactive

**Pull request merged**
