### PR TITLE
fix music in "Draci Historie" (use MIDI channel 16)

### PR DESCRIPTION
**Pull request by kmar**
DH uses MIDI channel 16 for percussion instead of the common 10

### CODE REVIEW

**Comment by kmar** [comment]
anybody competent around here?

**Comment by tobiatesan** [comment]
@kmar thanks for contributing. 
If I understand, it is the case that _without_ this patch music is played back incorrectly, right?

**Comment by kmar** [comment]
You're welcome.
Yes that's correct. It can be verified easily by installing Anvil studio, load "hudba2.mid" and change channel 16 to channel 10 (and compare how both sound).
Actually I know this because back in '95 or so I helped the guys with music playback using OPL
and a friend of mine actually wrote the music for the game so I know how it should sound.
I also rebuilt scummvm and verified that the patch indeed works.

**Comment by rspalek** [comment]
hi,

On Mon, Jul 10, 2017 at 12:17 PM, kmar <notifications@github.com> wrote:

> Actually I know this because back in '95 or so I helped the guys with
> music playback using OPL
> and a friend of mine actually wrote the music for the game so I know how
> it should sound.
>
thank you for the patch. nice to hear from a friend of a friend :))  I'm
one of the co-authors of both the original game and its scummvm
reimplementation.

-- 
Robert Špalek | software engineer | rspalek@gmail.com | +1 (408) 359-7434

**Comment by kmar** [comment]
hi, I believe we haven't met (so nice to meet you), but I remeber Lukas and Pavel (and his orange Skoda 120:)

**Comment by digitall** [comment]
Since this is a pretty small and self-contained change and appears to be uncontroversial, can this now be merged?

**Comment by sev-** [comment]
Merged, thanks a lot!

**Pull request merged**
