### PR TITLE
SCUMM: Add Explore the Farm Mac version to detection

### PR DESCRIPTION
**Pull request by antoniou79**
The new entry uses the "The Farm" pattern, the existing entry uses "farm"

The existing entry was also updated to refer to the Dutch version, for which it was added
(https://github.com/scummvm/scummvm/commit/2e497bb9f83d0435e88bcd283b636c4e2c9043e3).
This commit fixes the issue reported in https://bugs.scummvm.org/ticket/13483
Related forum thread is here: https://forums.scummvm.org/viewtopic.php?t=16585
and Discord discussion here: https://discord.com/channels/581224060529148060/581224061091446795/975285829696102410

### CODE REVIEW

**Comment by eisnerguy1** [comment]
I'm the one who originally submitted the bug report and posted on the forums. This is the Mac version from 1995. I sourced the files from a disc image I made from the original disc.



The US/English Mac files are named this:

- The Farm
- The Farm (0)
- The Farm (1)
- The Farm (2)
- The Farm (4)
- The Farm (9)

This game is version 1.0.

**Comment by bluegr** [comment]
OK so we went through the contents of the CD again.
There are two separate sets of files, one visible on PCs and one visible on Macs.
The PC ones are named "farm" whereas the Mac ones are named "The Farm". All are on the same disk!
That's why it's so confusing.

So, this line is actually the Dutch PC version, and can be removed:

    { "farm", "farm", kGenHEMac, Common::NL_NLD, Common::kPlatformMacintosh, 0 },

**Comment by antoniou79** [comment]
> So, this line is actually the Dutch PC version, and can be removed:
> 
> ```
> { "farm", "farm", kGenHEMac, Common::NL_NLD, Common::kPlatformMacintosh, 0 },
> ```
Sorry, I've somehow missed this comment. This change is now pushed in this PR.

**Comment by eisnerguy1** [comment]
Thanks for the help all! I really appreciate it!

**Pull request merged**
