### PR TITLE
SCUMM: [RFC, WIP] Fix Valgrind warnings when saving

### PR DESCRIPTION
**Pull request by eriktorbjorn**
Currently, ScummVM will print a lot of Valgrind warnings when saving, at least in The Dig, Full Throttle and The Curse of Monkey Island. This is my attempt at fixing some of these. Most of the warnings I've seen so far are caused by uninitialized data in Digital iMUSE, and while these warnings are _probably_ harmless they do potentially obscure more serious ones. (E.g. there's a warning in the thumbnail code when saving in Curse of Monkey Island.)

This isn't complete by any means. Full Throttle in particular has lots of warnings about data that looks like it should already be initialized to me, so I guess it's then overwritten with uninitialized data?

I don't know if this is important enough to go into 2.9.0 or not. I welcome any help. (I haven't even tried the earlier games, nor the HE ones yet.)

### CODE REVIEW

**Review by AndywinXp — APPROVED** [review]
LGTM!

**Review by bluegr — APPROVED** [review]
LGTM ^ 2

**Comment by eriktorbjorn** [comment]
I probably won't have any time to look at the remaining warnings until Sunday at the earliest.

**Comment by bluegr** [comment]
Closing in favor of #6242

**Pull request closed without merging**
