### PR TITLE
COMMON: Fix BASESTRING::contains()

### PR DESCRIPTION
**Pull request by lolbot-iichan**
There is a mistake in current `contains()` implementation - it does not backtrack after partial match, which causing wrong results.
For example, with current implementation word "Russian" contains "ssian", but does not contain "si".

This PR fixes this, however it proposes the simpliest algorithm possible.
Do we need something more clever and efficient here?

### CODE REVIEW

**Comment by lephilousophe** [comment]
Your patch indeed fix a bug in contains.

For the optimization part, as a start we could specialize contains method for chars by using strstr.
No idea for U32String.

**Comment by lephilousophe** [comment]
LGTM!

**Comment by lolbot-iichan** [comment]
@lephilousophe 
Thanks for the review, merging.

**Comment by mgerhardy** [comment]
it would be nice to get `test_contains` extended by this particular error case.

**Pull request merged**
