### PR TITLE
MTROPOLIS: internal ref linking for aliases and compounds

### PR DESCRIPTION
**Pull request by meekee7**
This change gives alias and compound variable modifiers the same privilege as variable modifiers and qualifies them for internal reference linking.

Seemingly this is required for mTropolis 1.1 titles, which otherwise run into the  ``"VarReference referenced a non-variable"`` error. This effect can be observed with _MindGym_ and the Albert/Ernest trilogy.

### CODE REVIEW

**Comment by elasota** [comment]
It looks like the problem here is basically that the current implementation of `VarReference` is wrong.  Testing confirms that using a variable modifier as a value source doesn't send the contained value, it sends an object reference to the variable modifier, and coercion to the expected type happens later.  (Fortunately, late coercion has already been implemented in most other places due to a similar problem.)

I'll look into this some more in a bit but I think this is probably not the right solution by itself, `DynamicValueSource` needs to be refactored somewhat.

**Comment by meekee7** [comment]
I will admit that I have no real idea what I am doing with this change. 
When I was trying to make some games boot, I ran into this error with _MindGym_ and the Albert/Ernest games. Dissolving the references solved it for me.
I think there was some other error from simply ignoring aliases and compounds here. I will check if I can reproduce it, or if that effect has vanished upon further refinement.

**Comment by elasota** [comment]
I'd be interested what the situation is for when it needs to reference an alias too, i.e. what the scene hierarchy looks like where the reference is being resolved.  `linkInternalReferences` is not supposed to be seeing aliases, it's supposed to be called when all aliases visible in the resolution scope have already been converted into object copies, so if it is seeing aliases, that's a bug.

For the compound var case, I need to just refactor it, I'll take care of that sometime soon.  I don't think this PR should be merged one way or another, the proper solution is just something completely different.

**Comment by meekee7** [comment]
Only _MindGym_ (both English and German variants) has the problem with an AliasModifier.
image

**Comment by elasota** [comment]
Fixed the actual problem in bba278db34b51c3e223c3514400bed851ff522cc

**Pull request closed without merging**
