### PR TITLE
GUI: Don't redraw whole dialog stack with kRedrawTopDialog

### PR DESCRIPTION
**Pull request by mikrosk**
This is something I wanted to fix for a long time: https://bugs.scummvm.org/ticket/14364

Not only it drastically speeds up button and scrolling redraws ~~but it makes tool tips pleasant to watch -- without this patch every tooltip freezes my backend for about 500 ms. You can imagine that user experience, one has to literally run away with mouse to avoid showing tooltips. ;)~~ (EDIT: actually, I got carried away here -- tool tips of course still redraw the background upon closing; I've had another optimization implemented but it's not suitable for a PR yet).

As I'm not a GUI expert, putting this for review whether I haven't overlooked something obvious.

From what I could see, there is only one potential risk: if there is a dialog which has the Apply button which updates something in the parent dialog. I haven't found any case like that but maybe you know better. IMHO even with this limitation this optimization is worth it on any lowend platform (content of the parent dialog would be updated on close of the child).

### CODE REVIEW

**Comment by sev-** [comment]
Immediately, I was thinking about tooltips overlapping the current dialog, but upon testing your code change, I was not able to catch a case when there is garbage left on the screen.

As for the top dialog changing underneath, this is never the case.

So, merging this. Thanks!

**Comment by sluicebox** [comment]
This breaks the smooth animation when dismissing the debug console. It doesn't redraw as it scrolls back up

image

**Comment by mikrosk** [comment]
@sluicebox will take a look, good catch!

**Comment by mikrosk** [comment]
Fixed in master.

**Pull request merged**
