### PR TITLE
GLK: Improved detection of Blorb files

### PR DESCRIPTION
**Pull request by ccawley2011**
This PR improves the detection of Blorb files by checking if the file contains a FORM type instead of looking at the file extension, as well as a more in-depth check to determine what interpreter the file should be used by.

### CODE REVIEW

**Comment by bluegr** [comment]
At a first glance, the changes are geared towards a good direction. Encapsulating logic inside separate functions is good.

Overall, +1 from me, although dreammaster will have the final say on this

**Comment by dreammaster** [comment]
Whilst I do like the cleanup within the Blorb class, the pull request has a fundamental problem due to introduced slowness. As it stands, each of several sub-engines are now opening up every file irrespective of it's extension and doing md5 calculations and checks for whether it's a Blorb file. This will add way too much processing time, even on fast systems when a Mass Add is used. And on slower console systems, even scanning the folder for a single game that has lots of files may end up being significantly slower as well. Which is why I relied on checking for specific extensions for Blorb files in the first place.

You're welcome to submit in the clean-ups for the Blorb class as a separate PR, but I'm going to have to reject this one as it stands.

**Comment by ccawley2011** [comment]
I updated this so that it will only check the format of a file if it has a valid file extension.

**Comment by dreammaster** [comment]
Looks good now. The detection code methods code probably use a bit more cleaning at some point, but the overall logic is sound.

**Pull request merged**
