### PR TITLE
DOCS: Update the Android documentation

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by sev-** [comment]
Looks like you got also makefile changes slipped in this PR. Was this intended?

**Comment by ccawley2011** [comment]
> Looks like you got also makefile changes slipped in this PR. Was this intended?

It's related to the removal of the old README file.

**Comment by antoniou79** [comment]
The updated information for the docs looks accurate to me and I agree that it's better to move it to docs and skip the distro specific readme file entirely. We copied it but didn't make use of it, so it's only purpose would be for reference for developers who found it in our code tree. The docs portal is more suitable for that, now.

I am just not 100% certain about the Dpad stuff, and "Dpad center" in particular -- I admit not having tested that one; how does one press Dpad center on a gamepad? 

If people have checked that and it's accurate, then I see no further issues.

**Comment by ccawley2011** [comment]
> I am just not 100% certain about the Dpad stuff, and "Dpad center" in particular -- I admit not having tested that one; how does one press Dpad center on a gamepad?

As far as I can tell, "D-pad" in this context refers to the ones found on older phones like the [original Samsung Galaxy](https://en.wikipedia.org/wiki/Samsung_Galaxy_(original)), which has an OK button in the centre of the D-pad, rather than the ones found on game controllers.

**Comment by bluegr** [comment]
The changes to the documentation done here are good to be merged, and @antoniou79 also agrees.
I too agree that moving the port-specific README to the main documentation is the right way to go here, since the README has gone out of sync, and it's incomplete.

Thanks again. Merging

**Pull request merged**
