### PR TITLE
COMMON: Pass U32String format params by reference and fix warnings about passing a non-trivial class to va_start.

### PR DESCRIPTION
**Pull request by elasota**

### CODE REVIEW

**Review by lephilousophe — APPROVED** [review]
This looks good to me.
As a side note, we are not doing this perfectly as it would require && type for param and the use of std::forward to pass parameters to formatInternal.
As we don't want std function, we could reimplement it ourselves.
But as we use this with good old C data (printf doesn't handle anything else) I think it should work great without all of this.

As a result, this change avoids to call U32String::format with a copy of the format string and removes an implementation-defined behavior (passing a complex class as last argument of a variadic function)

**Comment by lephilousophe** [comment]
One more note: normally C++ variadic templates are supported by all our toolchains according to the [wiki](https://wiki.scummvm.org/index.php?title=Compiling_ScummVM/C%2B%2B11_Readiness)

**Comment by sev-** [comment]
looks good

**Comment by lephilousophe** [comment]
Let's go!
Thanks

**Pull request merged**
