### PR TITLE
AGS: Preliminary implementation of ags_consoles plugin

### PR DESCRIPTION
**Pull request by tag2015**

### CODE REVIEW

**Comment by sev-** [comment]
Looks good to me as a stub

**Comment by bluegr** [comment]
I'm a bit confused here: this stub returns true for ALL console types (PS4, PS Vita, Switch and Xbox One). So, this will enable all console checks. Do we want that? What is the impact?

Perhaps we should stick to one of these consoles, or just return false for all?

**Comment by tag2015** [comment]
> I'm a bit confused here: this stub returns true for ALL console types (PS4, PS Vita, Switch and Xbox One). So, this will enable all console checks. Do we want that? What is the impact?
> 
> Perhaps we should stick to one of these consoles, or just return false for all?

It should return false for all cases, in fact. I don't have games to test this with (yet), that's why I left it as draft

**Comment by tag2015** [comment]
> I'm a bit confused here: this stub returns true for ALL console types (PS4, PS Vita, Switch and Xbox One). So, this will enable all console checks. Do we want that? What is the impact?
> 
> Perhaps we should stick to one of these consoles, or just return false for all?

After some tests, I changed the stubs to return false in all cases. Also added a few more methods that are used in a newer game (Quest for Infamy)

The PR should be ready for merge

**Comment by sev-** [comment]
Thank you

**Pull request merged**
