### PR TITLE
SYMBIAN: Simplify access to file server session.

### PR DESCRIPTION
**Pull request by fedor4ever**
This fixes bug #12728 too.

### CODE REVIEW

**Comment by digitall** [comment]
Since this PR only changes code associated with the SymbianOS port and @fedor4ever is the SymbianOS porter, then I think this is fine to merge as-is.

**Comment by sev-** [comment]
Well, the code is not conformant to our code formatting guidelines. It was not a great idea to merge it as is :/

**Comment by digitall** [comment]
@sev- : Sorry about that. I can't spot any major deviation from the code formatting guidelines here, at least compared to the code prior to the change. What part of https://wiki.scummvm.org/index.php?title=Code_Formatting_Conventions ?

**Comment by sev-** [comment]
@digitall For example, `RFs& fs = FsSession();` instead of `RFs &fs = FsSession();` and couple of other instances of the similar formatting

**Comment by digitall** [comment]
@sev- : OK. Fixed in https://github.com/scummvm/scummvm/commit/4cbbabf1a2e88bb53334144226a207cee162b46a , though that incorrect formatting was present prior to this PR i.e. https://github.com/scummvm/scummvm/pull/3157/commits/f0afa0ccbe03f9b2438d3f55fbf19a791acc3c47#diff-8666146c0bb6b2539e251a8d7ce9dc3fcac6101db56eef94e58c44b982e1673fR129

I think we could do with adding a github Action or similar to do an automatic style check on PRs against astyle or similar?

**Comment by fedor4ever** [comment]
@digitall , @sev- , It's good to automate style checking.

**Pull request merged**
