### PR TITLE
SCI: Add City's fan Russian translation support

### PR DESCRIPTION
**Pull request by phcoder**
This PR has 2 commits. One to tolerate a slightly invalid image and another adds the hashes

### CODE REVIEW

**Comment by sluicebox** [comment]
Which specific resources have problems? Where can I find this fan translation?

I'd prefer that we use the resource patcher (resource_patcher.cpp) on the broken images instead of allowing the uncompressed version of getRow() to ignore invalid requests. That keeps game-specific workarounds out of the engine code, and I think that is even more important for fan stuff. That way we also have built-in documentation of which image/game/version is the problem. Right now this begs the question "why does the uncompressed reader allow this this but the compressed one doesn't?"

Separately, this is a good example of code that shouldn't be an assertion, since it's validating external data. I think it should be an error() if not a warning(), and should be the same in all the getRow() methods, but that can happen later.

**Comment by bluegr** [comment]
I agree with @sluicebox here. Since there are broken resources in this version, we should either try and patch them, or ignore specific errors for specific resources, not all of them.

**Review by bluegr — CHANGES_REQUESTED** [review]
Overall, the corrupt graphics should be identified and corrected, instead of silently dropping the errors. Perhaps it is possible to identify all the offending resources with external tools, e.g. SCI Companion, or SV

**Comment by bluegr** [comment]
Excellent, thanks for addressing the issues! Merging

**Review by bluegr — APPROVED** [review]

**Pull request merged**
