### PR TITLE
QUEEN: Add tables for German Amiga floppy version

### PR DESCRIPTION
**Pull request by cyxx**

### CODE REVIEW

**Comment by sev-** [comment]
Fantastic! Could you also please commit the updated kyra.dat right as part of this PR?

**Comment by raziel-** [comment]
@cyxx 

Welcome back :-)

**Comment by cyxx** [comment]
> Fantastic! Could you also please commit the updated kyra.dat right as part of this PR?

Sure, done.

**Comment by sev-** [comment]
Thanks! Much appreciated!

**Pull request merged**
