### PR TITLE
SCUMM: DIMUSE: Implement low latency audio mode

### PR DESCRIPTION
**Pull request by AndywinXp**
Hola! This fixes bug [#13462](https://bugs.scummvm.org/ticket/13462). It also adds a new checkbox for FT, DIG and COMI for toggling this feature.

This low latency mode is implemented by only making code changes in:
* The internal mixer (`dimuse_internalmixer.cpp`);
* The waveOut module (`dimuse_waveout.cpp`);
* The audio callback (I created a variant of the `IMuseDigital::tracksCallback()` function, `IMuseDigital::tracksLowLatencyCallback()`).

The rest of the audio system is of course left unchanged and knows nothing about these modifications 🙂

The rationale behind this feature was inspired by the previous implementation of the audio engine, by aquadran: if we create (and contextually dispose) a new stream at real time for each sound that the game engine requires us to play, then we don't have to wait for all the other sounds to be processed and mixed, but we can play the sound data right away.

Suffice to say, this mode produces audio which is audibly correct, but _not accurate_: the original mixes all sounds, voices and music together in a single stream in a non linear manner. With this mode we handing the mixing work to the backend mixer, so there might be slight sonic differences between the original interpreter audio and this mode. 

This is why this feature _doesn't replace the original audio mode, and is therefore disabled by default_.

If you want a more verbose explaination, I suggest reading the comment in [`IMuseDigital::tracksLowLatencyCallback()`](url) 🙂

Please @rsn8887, test it on PSP if you can and let me know if this solves your original issue. I have personally tested this on Windows, Ubuntu and MacOS, and I'll be testing this on Android in the next hours.

### CODE REVIEW

**Comment by AndywinXp** [comment]
Tested on Android too, and made a couple of adjustments.

**Comment by rsn8887** [comment]
I am trying to test it, but where do I enable the new mode?

**Comment by rsn8887** [comment]
Ok I force enabled low latency mode in the code to test it and it works on PSP!

**Comment by rsn8887** [comment]
Now I found the GUI option as well. Everything seems to be working.

**Comment by AndywinXp** [comment]
I'm really glad to hear that, thanks for testing it!

**Comment by AndywinXp** [comment]
Very well, after further testing I think I can safely merge this and close the bug ticket

**Pull request merged**
