### PR TITLE
CI: emscripten deployment to Github pages

### PR DESCRIPTION
**Pull request by neuromancer**
This small PR deploys to Github pages using the Github action that we already use for CI tests. This code is based on @chkuendig demo deployment (https://github.com/chkuendig/scummvm-demo/).

Before merging, there a few important points to discuss: 
* As expected, it will require to enable the Github pages for the main scummvm (I don't have permissions to do it). The deployment should be available at: http://scummvm.github.io/scummvm.html 
* The Github action runs at every commit and this is too often to redeploy. I think it could be once per day as we have the nightly builds.
* The selection of demos is arbitrary, we should try to prioritize the ones from the games that should be tested for the upcoming releases.

### CODE REVIEW

**Comment by ccawley2011** [comment]
It would likely to be better to use the buildbot for this and host this on our own infrastructure rather than relying on GitHub Actions/Pages. I made an unfinished attempt at adding an Emscripten toolchain to the buildbot some time ago if anyone's interested in picking this up: https://github.com/ccawley2011/dockerized-bb/tree/emscripten

**Comment by neuromancer** [comment]
I can take a look to the buildbot scripts, but I'm not a docker expert :disappointed:. The best advantage that we have regarding using Github Action instead is the fact that demos will be hosted in Github, which is literally free for scummvm, as opposed of using scummvm.org hosting (perhaps @lotharsm can give more details about that).

**Comment by chkuendig** [comment]
> The selection of demos is arbitrary, we should try to prioritize the ones from the games that should be tested for the upcoming releases.

I would recommend to actually do the inverse and host games which we know are stable. This port itself isn't the most stable thing, so more likely than not issues found might be caused by the emscripten port not the engine code.

> It would likely to be better to use the buildbot for this and host this on our own infrastructure rather than relying on GitHub Actions/Pages. I made an unfinished attempt at adding an Emscripten toolchain to the buildbot some time ago if anyone's interested in picking this up: https://github.com/ccawley2011/dockerized-bb/tree/emscripten

My current build script actually bootstraps the toolchain, mostly because it currently only works on a patched version of emscripten. (see https://github.com/chkuendig/scummvm/blob/emscripten/dists/emscripten/README.md#emscripten-asyncify-optimizations )

**Comment by lotharsm** [comment]
> I can take a look to the buildbot scripts, but I'm not a docker expert 😞. The best advantage that we have regarding using Github Action instead is the fact that demos will be hosted in Github, which is literally free for scummvm, as opposed of using scummvm.org hosting (perhaps @lotharsm can give more details about that).

Unfortunately, I'm not familiar with GitHub Actions or Emscripten at all. Regarding hosting on our infrastructure for scummvm.org, I can make some room, so we don't have to use github.io if there are any drawbacks.

**Comment by neuromancer** [comment]
@ccawley2011 should we close this issue then?

**Comment by sev-** [comment]
I recommend putting it on our servers as we will easily hit GitHub limits and get capped.

Apologies, for closing this PR, as so much work was put in it. But I am sure, this work is not wasted.

We need to turn it into a buildbot instructions and run nightly. Please, work with @lephilousophe and @lotharsm on how to do it.

**Pull request closed without merging**
