### PR TITLE
WINTERMUTE: Debugger for WME

### PR DESCRIPTION
**Pull request by tobiatesan**
This is a barebones debugger for WME that allows breaking and stepping inside scripts, like the original, dumping vars, like the original, and setting them too.

As far as debuggers go it's a bit of a hack, since we don't have symbol tables and stuff, so we hack around the special II_DBG_LINE instruction; as detailed in a separate document, the next logical step would be to improve on the compiler.

### CODE REVIEW

**Comment by bluegr** [comment]
Reminder: This still can't be merged cleanly anymore. And the commits most likely need some squashing

**Comment by sev-** [comment]
A really nice thing. @tobiatesan, do you have time for bringing this patch up-to-date so it could be merged?

**Comment by tobiatesan** [comment]
@sev-I'm super uber swamped ATM, but I promise I'll try to get it ready during the Christmas holidays.

**Comment by tobiatesan** [comment]
(Wait, are you telling me that one year has already passed since @bluegr first poked me? in Enya's immortal words, "my my time flies". Sorry about that.)

**Comment by tobiatesan** [comment]
I am closing this for the time being, expect a new PR sometime.

**Pull request closed without merging**
