### PR TITLE
GUI: fix game item coloring bug

### PR DESCRIPTION
**Pull request by robnanarivo**
Pass only one list to GroupedListWidget::setList so that content and color will not go out of sync. The new list items are formatted as `\001cRRBBGG#game_name` or `\001C{#color_mode}#game_name` where `#color_mode` is either `normal` or `alternate`.

### CODE REVIEW

**Comment by sluicebox** [comment]
Does this address the coloring of disabled items being out of sync? https://bugs.scummvm.org/ticket/13096

**Comment by robnanarivo** [comment]
> 

Yes

**Comment by robnanarivo** [comment]
> Does this address the coloring of disabled items being out of sync? https://bugs.scummvm.org/ticket/13096

Yes

**Comment by sev-** [comment]
Any updates? This is absolutely incomplete

**Comment by robnanarivo** [comment]
> Any updates? This is absolutely incomplete

Will resume after final exams

**Comment by bluegr** [comment]
I don't understand why stripGUIformatting() has been created. It's the largest chunk of the changes in this PR, yet it's not really used anywhere.

**Comment by sev-** [comment]
Closing this as incomplete

**Pull request closed without merging**
