### PR TITLE
JANITORIAL: Update all scummvm.org URLS to use https

### PR DESCRIPTION
**Pull request by ccawley2011**
Most of this was done using the following command:
```
find . -type f -not -path "./.git/*" -exec \
	sed -i 's/http:\/\/\([a-z.]*\)scummvm\.org/https:\/\/\1scummvm.org/g' {} +
```

### CODE REVIEW

**Comment by digitall** [comment]
@ccawley2011 : Thanks for this update... but @lotharsm, it would have been better to leave this open for a day or so so others could comment and review. While scripted fixups like this are good, they are prone to mistaken changes and should be human reviewed before merging.

Most of these are changing the wiki URLs which is not surprising as that was one of the last of the subdomain sites to get moved to HTTPS, preceded by the forums... as both of these took some work to do.

Unfortunately, as I suspected there is at least one incorrect change i.e. The dists/debian/changelog has had older entries modified which is not correct i.e.
https://github.com/scummvm/scummvm/pull/1530/commits/5ce8d8bfa2ce4ceb39f48cce178ad238975fdc27#diff-921810f539247c69acd12db0569ef9bf

**Comment by ccawley2011** [comment]
>Unfortunately, as I suspected there is at least one incorrect change i.e. The dists/debian/changelog has had older entries modified which is not correct i.e.
5ce8d8b#diff-921810f539247c69acd12db0569ef9bf

I had a feeling that might not have been correct. Nonetheless, PR #1531 fixes that.

**Comment by digitall** [comment]
@ccawley2011 : Thanks. See my comment on that new PR

**Comment by digitall** [comment]
P.S. I should say that some of the other changes in dists to various distributions scripts such as the Amiga RX script _should_ be fine... but not sure how well the more niche platforms deal with HTTPS / SSL so those may need a revert, but the various porters / platform users should report that in time.

Thanks again for this fix generally which is good tidy up.

**Pull request merged**
