### PR TITLE
BASE: Added --engine=ID for --list-all-games and --list-games

### PR DESCRIPTION
**Pull request by scureuil**
For the command line, lists games only for the specified engine.
(optional)

Usage:

--list-all-games --engine=sci 
--list-games --engine=ags

### CODE REVIEW

**Comment by criezy** [comment]
Also I just tried it and it works nicely. I think this is a good addition.

And I forgot to write that the two commits should also be squashed. But Github has an option to do that when merging the pull request, so it's up to you if you want to do it or let us do it.

**Comment by bluegr** [comment]
+1 from me too, nice work, and I agree with the feedback provided by @criezy

**Comment by scureuil** [comment]
Thanks for the feedback. 

I did the modifications: rebasing, fixing alignments, and squashing the commits, so it should be cleaner.

**Comment by criezy** [comment]
It is indeed cleaner. However it looks like you fixed the alignment for only one of the two I commented on (it is now correct in `listAllGames` but the issue is still there in `listGames`).

**Comment by scureuil** [comment]
Done. (I remember doing this line too, but I think I wrongly reversed a local commit.) 

Changed (engineID=="") to engineID.empty() too.

As it's not using a default engineID like "all" (who could conflict with a future engine, like an engine named "global" would conflict with --list-debugflags), empty() is more true to the meaning of "no engine specified".

**Review by criezy — APPROVED** [review]
Thank you. It looks all good now.

**Pull request merged**
