### PR TITLE
BACKENDS: search also for track_x and track_xx audio cd tracks

### PR DESCRIPTION
**Pull request by mgerhardy**
this allows us to use the unmodified version of dotemu lba1 enhanced music track paths

see 1b67a288abbed4e130fac8507d8f66940fcc0530

### CODE REVIEW

**Comment by mgerhardy** [comment]
Maybe the buffer should get increased or snprintf should be used. `track_2147483648` would overflow the buffer by 1 byte

**Comment by mgerhardy** [comment]
Using `Common::String::format` now - still fits into the internal buffer, so no mem allocations - `openStreamFile` was converting it into a `Common::String` anyway. Also replaced the hardcoded arraysize.

**Comment by bluegr** [comment]
This looks good, we don't need to add any extra logic for these tracks, other than their naming template, so there is no impact, and the dotemu version will work out of the box.

I propose to merge this this week, unless there are any objections.

**Comment by bluegr** [comment]
Merging as mentioned. Thanks for your work!

**Pull request merged**
