### PR TITLE
GRAPHICS: Use target pragmas instead of compiler flags to prevent ODR problems

### PR DESCRIPTION
**Pull request by elasota**
This removes the compiler command line arch specifications from the SIMD blit code and replaces them with pragmas that only affect the blit code functions.

This prevents the functions defined in the headers from being compiled with instruction set extensions, which in turn prevents them from replacing definitions of the same functions defined in other modules due to the C++ one definition rule.

### CODE REVIEW

**Comment by elasota** [comment]
Adding configure line to disable the SIMD extensions on GCC versions under 4.9 due to lack of support for `#pragma GCC target`

**Review by bluegr — APPROVED** [review]
LGTM

**Comment by sev-** [comment]
Thank you!

**Comment by lephilousophe** [comment]
This pull request broke support for Clang.
Indeed, Clang reports a GCC compatibility version of 4.2, hence completely disabling support.
This can been checked on the buildbot where all Clang based platforms (Apple, Android and Debian clang) all have their SIMD code disabled.

I tried to fix it by myself but failed. My attempt can be found here: [lephilousophe/scummvm:fix-cpu-ext](https://github.com/lephilousophe/scummvm/tree/fix-cpu-ext)
I changed the configure code to get Clang version, added a check on Clang version and added the needed pragmas in the blitting code.

Problem: for ARM NEON, Clang guards the file using a preprocessor definition (__ARM_NEON) and typedefs in the `arm_neon.h` generate `error: 'neon_vector_type' attribute is not supported for this target`.
This is related to issue https://github.com/llvm/llvm-project/issues/56480.
Some commits were done to fix this issue, but they are not enough. Even the latest snapshots of Clang exhibit the issue.

**Pull request merged**
