### PR TITLE
KYRA: Add detection for Polish fan translation of kyra1

### PR DESCRIPTION
**Pull request by xeros**
Add checksum of "GEMCUT.PAK" for Polish text translation to kyra1 engine.

### CODE REVIEW

**Comment by sev-** [comment]
Thanks, could you please fix the commit log message in accordance with our [Commit Guidelines](https://wiki.scummvm.org/index.php?title=Commit_Guidelines)?

**Comment by xeros** [comment]
Is it better now?

**Comment by lotharsm** [comment]
Please use something along the lines of `KYRA: Add detection for Polish fan translation of kyra1` for the commit message. Please note that you should change the commit message itself, not only the PR title.

**Comment by raziel-** [comment]
@xeros

Take a look at the other PR's

Something like this should fit:
KYRA: Add detection for Kyrandia 1 polish fan translation

**Comment by xeros** [comment]
Done, thank you.

**Comment by lotharsm** [comment]
Please change the commit message itself, not the PR title.

**Comment by athrxx** [comment]
Have you tested this? Does it work as expected?

Having this detected as English will lead to various strings (including the intro) being displayed in English. Setting it to Polish won't work, since we don't have that language resources. But maybe this fan translation is supposed to be like that anyway?

**Comment by xeros** [comment]
Yes, I have tested it and played most of game locations on PlayStation Classic, having ScummVM compiled as RetroArch core.

Everything works fine for me, but you're right about having some strings not translated.
Intro dialogs and item names are in English (Polish translation for them is integrated in MAIN.EXE file), but game dialogs & location names, loaded from PAK files are in Polish.

It's a fan translation where translated strings to Polish language are mapped to "ENG" and it's different than official Polish version of Legend of Kyrandia 2: Hand of Fate, where Polish strings are properly mapped as "POL". I've started some work on this version too, but it has to be handled differently due many differences to English version.

**Comment by xeros** [comment]
Commit message corrected.

**Comment by sev-** [comment]
Thanks, merging.

**Pull request merged**
