### PR TITLE
BACKENDS: Remove the Windows CE port

### PR DESCRIPTION
**Pull request by ccawley2011**
The Windows CE backend is now heavily bitrotten due to a number of reasons, which makes it hard to make large scale improvements to the SDL backend, amongst other problems. It doesn't help that it hasn't received any real maintenance since 2011, beyond basic attempts to fix compilation errors. If it's still desirable to support Windows CE, it would be more beneficial to rewrite the backend from scratch rather than trying to keep the old one alive.

### CODE REVIEW

**Comment by sev-** [comment]
Yay, this is awesome! I'll wait for couple of days for the reaction of other team members, and if there are no major objections, I'll merge it.

Thank you for your work!

**Comment by lotharsm** [comment]
No objections from my side at all :)

**Comment by digitall** [comment]
No major objection, though always a bit disappointing to lose a port... though in this case, I suspect we have relatively few users or target devices still in active usage.

However, @sev- might be best to drop a message onto the scummvm-devel mailing list in case there are any WinCE developers / porters still active and so no-one can say they did not get a fair warning / notification.

**Comment by sev-** [comment]
Merging this.

**Pull request merged**
