### PR TITLE
SWORD25: set new md5 and size of heb patch

### PR DESCRIPTION
**Pull request by ShaharAriel**
heb patch changes:

- translation of two letters in the game
- improvment of some of the fonts and the menu graphichs

### CODE REVIEW

**Comment by ShaharAriel** [comment]
@sev-  here is the heb patch (shared via google drive, for sharing it in ScummVM website):
https://drive.google.com/file/d/18C3trmEwIJvmynE1_8JNOl9-H3wV6dk6/view?usp=sharing

**Comment by lotharsm** [comment]
Instead of removing (or "updating") the old detection entry, you should create a new one for the updated version you want to add.

Otherwise, detection will fail for users that only have access to the old version and might even break old game entries that are already present in the launcher.

**Comment by ShaharAriel** [comment]
> Instead of removing (or "updating") the old detection entry, you should create a new one for the updated version you want to add.
> 
> Otherwise, detection will fail for users that only have access to the old version and might even break old game entries that are already present in the launcher.

The patch hasn't been released yet, so no one (except the dev team) has the patch, so it's better to update the entry than add a new entry.

**Comment by BLooperZ** [comment]
old version was not released publicly, so I think here is better to remove

**Comment by orgads** [comment]
> @sev- here is the heb patch (shared via google drive, for sharing it in ScummVM website): https://drive.google.com/file/d/18C3trmEwIJvmynE1_8JNOl9-H3wV6dk6/view?usp=sharing

Is it public? I get Access Denied.

**Comment by ShaharAriel** [comment]
> > @sev- here is the heb patch (shared via google drive, for sharing it in ScummVM website): https://drive.google.com/file/d/18C3trmEwIJvmynE1_8JNOl9-H3wV6dk6/view?usp=sharing
> 
> Is it public? I get Access Denied.

Not yet (only @sev- ), the patch will release in ScummVM website and in Hebrew Adventure group in facebook

**Comment by BLooperZ** [comment]
@ShaharAriel can you please squash both commits? (as one effectively cancel the other)

**Comment by lotharsm** [comment]
> The patch hasn't been released yet, so no one (except the dev team) has the patch, so it's better to update the entry than add a new entry.

What about modifying the existing entry to something like "(Unreleased)"? I don't remember if we ever removed something from the detection table - it might be interesting to keep for documentation purposes.

**Comment by BLooperZ** [comment]
IMO, keeping the old entry would be unneccessarily confusing.
(i.e. how can we evaluate compatibility for a game that does not exists, so no one is able to test?)
Even if this version of the game was publicly available, I would advise to show a warning modal that recommends to download a newer patch, as we do in Grim Fandango and others

**Review by orgads — APPROVED** [review]

**Comment by sev-** [comment]
In fact, we do not accept WIP checksums. I was not aware that that was the case for the first submission.

Since it was never made public, there is no benefit in keeping the old WIP md5 in the detection table.

Now, the question, will the exact version that was shared with me and is represented here, be the one that will go public?

**Comment by ShaharAriel** [comment]
> In fact, we do not accept WIP checksums. I was not aware that that was the case for the first submission.
> 
> Since it was never made public, there is no benefit in keeping the old WIP md5 in the detection table.
> 
> Now, the question, will the exact version that was shared with me and is represented here, be the one that will go public?

Yes this is the final version.
But the old version was not a WIP version either, we were planning to release it but after the PR merge, we found some important fixes that we didn't notice before.

**Comment by sev-** [comment]
Though, the previous version was NOT released publicly, right? Or was it?

**Comment by orgads** [comment]
It wasn't released.

**Comment by sev-** [comment]
Ok, thank you for the clarification. Merging.

**Comment by sev-** [comment]
@ShaharAriel I have no access to the file. I requested it.

**Comment by ShaharAriel** [comment]
> @ShaharAriel I have no access to the file. I requested it.

Approved, in the previous sharing I used the email of ScummVm domain to share, now I have also shared the requested email (gmail).
 Thanks you all.

**Comment by ShaharAriel** [comment]
> @ShaharAriel I have no access to the file. I requested it.

We would be happy to know the expected date for the game update on the site,
We prefer to publish the patch on ScummVM site than on our group,
Thanks in advance.

**Comment by sev-** [comment]
> > @ShaharAriel I have no access to the file. I requested it.
> 
> We would be happy to know the expected date for the game update on the site, We prefer to publish the patch on ScummVM site than on our group, Thanks in advance.

It is live now

**Pull request merged**
