### PR TITLE
AGI: Add detection for a few more variants

### PR DESCRIPTION
**Pull request by einstein95**

### CODE REVIEW

**Comment by bluegr** [comment]
Thanks!

**Comment by Thpwg** [comment]
Hi eientei95,

I'm writing to ask, if to your knowledge, the 1984 version of King's Quest 1 exists in MS-DOS? Maybe, it's Version Game 1.0U - Interpreter Version 2.272. But, I'm not sure, it's possibly a PC Booter or IBM PCjr version.

I hope you can enlighten me. 
My best,
Threepwang

**Comment by einstein95** [comment]
> Hi eientei95,
> 
> I'm writing to ask, if to your knowledge, the 1984 version of King's Quest 1 exists in MS-DOS? Maybe, it's Version Game 1.0U - Interpreter Version 2.272. But, I'm not sure, it's possibly a PC Booter or IBM PCjr version.
> 
> I hope you can enlighten me. My best, Threepwang

The game is definitely an MS-DOS version, I was able to "crack" the AGI file and run it fine in DOSbox. From what I can see, it's not a PC Booter as it has a DOS file system. The game does have a `JR_GRAF.OVL` file though attempting to run the game in DOSbox as a PCjr fails, will have to double check this in 86box.

**Comment by Thpwg** [comment]
Hi eientei95,

Wow, it's incredible! Do you have the 1984 or 1986 edition? It seems to me that the 1986 edition is an improved version that precedes the final 1987 version. For purists, the first edition of 1984 is unsurpassed ;^) 

Do you have a blog or a site for communicating by PM? Because I file a lot of Sierra interpreters and it's interesting to exchange points of view. There are some very singular cases. 

Thanks a lot :^)

**Comment by einstein95** [comment]
> Hi eientei95,
> 
> Wow, it's incredible! Do you have the 1984 or 1986 edition? It seems to me that the 1986 edition is an improved version that precedes the final 1987 version. For purists, the first edition of 1984 is unsurpassed ;^)
> 
> Do you have a blog or a site for communicating by PM? Because I file a lot of Sierra interpreters and it's interesting to exchange points of view. There are some very singular cases.
> 
> Thanks a lot :^)

Probably best to chat over Discord, I'm eientei in the ScummVM server

**Comment by Thpwg** [comment]
> > Hi eientei95,
> > Wow, it's incredible! Do you have the 1984 or 1986 edition? It seems to me that the 1986 edition is an improved version that precedes the final 1987 version. For purists, the first edition of 1984 is unsurpassed ;^)
> > Do you have a blog or a site for communicating by PM? Because I file a lot of Sierra interpreters and it's interesting to exchange points of view. There are some very singular cases.
> > Thanks a lot :^)
> 
> Probably best to chat over Discord, I'm eientei in the ScummVM server

Unfortunately, I don't have access to Discord, but I've listed you in the index I've created mainly for translators [AGI-SCI-index](https://github.com/Thpwg/AGI-SCI-index).

**Pull request merged**
