### PR TITLE
AGS: Support for Korean fan translations

### PR DESCRIPTION
**Pull request by british-choi**
I write code for font handling and word warping to support Korean fan translation in the AGS engine.
The following games have been tested for Korean fan translation using this code.

[ScummVM-Kor-Trs](https://github.com/british-choi/ScummVM-Kor-Trs)
* 30 minutes
* The Blackwell Legacy
* Blackwell Unbound
* 5 Days A Stranger
* King's Quest I: Quest for the Crown Remake

More AGS games will be translated and released in Korean.

### CODE REVIEW

**Comment by tag2015** [comment]
Hi, thanks for your work!
I don't think this code is part of the upstream AGS interpreter, is there any reason why you want to add it to ScummVM and not to their project first?

**Comment by british-choi** [comment]
> Hi, thanks for your work! I don't think this code is part of the upstream AGS interpreter, is there any reason why you want to add it to ScummVM and not to their project first?

Hello
I've been working on the Korean translation of some games that use ScummVM's AGS engine.
I apologize. I don't know about "the upstream AGS interpreter".
I just want Koreans to be able to play the games with the Korean translation on ScummVM.

**Comment by tag2015** [comment]
Ah, all right! The AGS engine in ScummVM is based off the 3.6.0 branch of the upstream AGS interpreter which is available here
https://github.com/adventuregamestudio/ags

Generally we try to follow their codebase to avoid diverging too much, maybe you could try opening a PR there (I don't think it will require many changes)? That'll give even more visibility to your work

**Comment by british-choi** [comment]
> Ah, all right! The AGS engine in ScummVM is based off the 3.6.0 branch of the upstream AGS interpreter which is available here https://github.com/adventuregamestudio/ags
> 
> Generally we try to follow their codebase to avoid diverging too much, maybe you could try opening a PR there (I don't think it will require many changes)? That'll give even more visibility to your work

OK.
I understand. I will try it.

**Pull request closed without merging**
