### PR TITLE
WIP: Scaler plugins rebased

### PR DESCRIPTION
**Pull request by sandsmark**
doesn't even build yet, but it's a start

edit: as @sev- said below, this is a rebase of PR #271 on top of master.

### CODE REVIEW

**Comment by sandsmark** [comment]
now it runs at least

**Comment by sandsmark** [comment]
some of the scalers crash, otherwise "fine"

**Comment by sandsmark** [comment]
sorry, didn't mean to close it

**Comment by angstsmurf** [comment]
I've been trying this out with The Secret of Monkey Island on macOS 10.12 with Iris Pro graphics, and so far I've been unable to crash it. All of the included scalers seem to work as intended.

**Comment by tobiatesan** [comment]
Hi, this look very very interesting, but... what is it, for those who are not in the loop (yours truly is certainly guilty)?
Would you please add half a line of explanation when you have a spare second?

Thank you!

**Comment by sev-** [comment]
@tobia, pr#271 rebasef

**Comment by sandsmark** [comment]
sorry for not explaining that. forgot that the original PR is so old it's not immediately visible.

**Comment by bluegr** [comment]
LordHoto had continued work on this in another branch. Perhaps there are some changes of interest there:

https://github.com/lordhoto/scummvm/commits/gsoc2012-scalers-cont

**Comment by tobia** [comment]
@sev- um, that's not me, but good luck on your game emulator thingy :-)

**Comment by bluegr** [comment]
Two more comments:
- digitall has also worked on this in his branch, here: https://github.com/digitall/scummvm/tree/gsoc2012-scalers-cont
- Your commit messages do not follow our commit guidelines:
http://wiki.scummvm.org/index.php/Commit_Guidelines

Overall, I believe that @digitall also put @lordhoto 's work in his branch, so that branch is probably more up to date than @singron 's branch

**Comment by digitall** [comment]
@bluegr : Yes, my gsoc2012-scalers-cont was basically Lordhoto's continuation of singron's GSoC work, but since that was not completed, it too also got bitrot, so I did a merge of upstream back in 2014 and fixed up the compilation breakages due to various minor API changes.... but my branch too would probably be slightly bitrotted again current master so nice to see some work on updating this.

**Comment by lotharsm** [comment]
@sandsmark: Any updates on this?

**Comment by Mataniko** [comment]
So a lot of work has been put into this, but today we can get better scalers using shaders. They achieve a much better effect at much lower cost of performance. 

In 2012 this PR may have made sense, but now with OpenGL being available across most ports is this worth the effort to get it to work and maintain?

**Comment by Kawa-oneechan** [comment]
I'd say probably not.

**Comment by bluegr** [comment]
Closing this, as it has bitrot, and the work done here has been continued in PR #2358

**Pull request closed without merging**
