### PR TITLE
PRINCE: Add Spanish translation support

### PR DESCRIPTION
**Pull request by aviloria**
Add support for upcomming Spanish translation

### CODE REVIEW

**Comment by lotharsm** [comment]
Thank you! Just to make sure, this will be the detection entry for a new translation via our translation system? [1]

[1] https://translations.scummvm.org/projects/prince/prince/

**Comment by aviloria** [comment]
The new spanish translation has not been done using the ScummVM translation service.
It requires an special font file including different glyphs for some spanish letters.
The translation has been completed and reviewed by pairs by a trusted spanish team.
With the provided changes will be enough to run on ScummVM.

A link to the translation patch (over German or Polish game) will be published soon on ScummVM discord channel

**Comment by bluegr** [comment]
> The new spanish translation has not been done using the ScummVM translation service

Since all the other translations for prince have been done using the translation system, the Spanish translation should follow the same rules. Please, use our translations system for this as well.

**Comment by aviloria** [comment]
Sorry, but the translation cannot be done using the translation service only.
It requires an special font file including different glyphs for some spanish letters.

**Comment by lotharsm** [comment]
Well, the strings themselves could still be merged into Weblate - the goal is to have _every_ translation available there.

**Comment by aviloria** [comment]
We've been trying to move the trnaslation to the ScummVM service.
We are logged in but when we tried to do add it, we are getting an error regarding permisions.
Anyway, the changes in this commit are required to get it working. The translation file is appart. So could you please, let proposed changes to be merged?

**Comment by sev-** [comment]
@Pakolmo as this violates the spirit of open source and the purpose of ScummVM, we are rejecting this code change and will black list your translation in the ScummVM master.

**Comment by sev-** [comment]
And to clarify, if you based your translation on the English translation, you abused MY work. As an author, I was not giving you permission to build a derivative work and lock it down.

**Comment by sev-** [comment]
In case there is a misunderstanding, as pointed out by a Spanish-speaking team member and you just have technical problems with uploading the translation and not truly DENYING us from using it, please clarify and I bring my apologies.

**Comment by aviloria** [comment]
@sev- I'm pretty sure this has been totally misunderstood.
Pakolmo just was trying to contribute with his translation to the project, same as me.
He has technical problems to upload the translation strings to the ScummVM translation service. He is always getting a "forbidden" error on each try.
Anyway, the changes from this MergeRequest has nothing to do with uploading the strings to the ScummVM translation service. The code changed here is just to support the translation, no matter if it is shared or uploaded (when possible) to the translation service.

**Comment by Pakolmo** [comment]
I'm sorry. Thank you for your English translation.
I don't undestand your point of view. The ScummVM tools can only export the databank.ptc in polish and german.
The Spanish translation is free and universal from all Spanish people. And I NOT DENYING uising it.
I know @aviloria user, and we are trying to update code to run the translation.
I have permisions problems with translation web, I can't do any changes in spanish texts.

Can I upload the Spanish translation? Can you remove the translation to the black list? 

Thanks.

**Comment by Pakolmo** [comment]
**PRINCE: Blacklist Spanish translation by Pakolmo as he denied us from…** IT IS FALSE.


Could we start again? 
I did the translation and I want everybody can enjoy it.
what is the problem?

@Aviloria is helping me to do compatible the translation.

Please, @sev- Could you help me adding the code?

I hope the misunderstanding is solved.

Thank you very much.

**Comment by sev-** [comment]
Yes, apologies. I misread your statements, and your demands to get the code with four exclamation marks contributed to it too. I read it as you're denying to put your translation to our translation service.

I will take it from here in the upcoming days. Please be a bit more patient.

**Comment by sev-** [comment]
I merged the code changes. Will work on putting the translation on Weblate later.

**Comment by aviloria** [comment]
Thank you so much, @sev-

**Comment by Pakolmo** [comment]
Thank you  @sev-

My problem now is how I upload the translation on Weblate. I have technical problems with my user. My user doen't have enought permision to make changes in weblate.

**Pull request closed without merging**
