### PR TITLE
KYRA: Extract Korean strings, preliminary work

### PR DESCRIPTION
**Pull request by einstein95**
This is just the bare minimum to get it running in ScummVM. The `MK15.BIT` font isn't currently loaded so this is the best you'll get atm:
image

TODO:
- ~~CREDITS.HAN~~
- Font loading

### CODE REVIEW

**Comment by athrxx** [comment]
Thanks, your additions all look good to me. I'll see that I get it to a working state...

**Comment by einstein95** [comment]
The version of the EXE the strings were extracted from was
```
The Legend of Kyrandia, Version 1.0h
Copyright (c) 1992, 1993 Westwood Studios, Inc. All rights reserved.
Manufactured and Distributed in Korea by Dong Seo Game Channel.
```

**Comment by einstein95** [comment]
There's the fix for it building along with loading CREDITS.HAN. I'm unsure which one to use tbh, as upon further investigation, CREDITS.HAN is an incomplete translation of CREDITS.TXT, the only differences of CREDITS.TXT from the English version is that `THE END` is translated, and this is added to the end:
```
Hangle translation by Pantheon Laboratory
of Dong Seo Game Channel
```

**Comment by athrxx** [comment]
Thanks!
Sometimes the credits didn't get translated. The teams who did the localizations apparently did what they wanted. E. g. for Japanese FM-TOWNS, they added a couple line for the localization guys, but there is no use of the Japanese font at all and it is in English.

**Comment by athrxx** [comment]
I have added a commit with some font drawing support. It isn't finished yet, but the intro seems mostly okay.

**Comment by athrxx** [comment]
Okay, this is getting somewhere, now. The dialogue line still need to be tweaked. And also the save/load menus. Also, the orginal (only) allows typing Hangul characters into the save description line...

**Comment by athrxx** [comment]
This can be merged, now. Thanks for your work on this!

**Pull request merged**
