### PR TITLE
MIYOOMINI: Enable neon and freetype2 in documented compilation script

### PR DESCRIPTION
**Pull request by phcoder**

### CODE REVIEW

**Comment by bluegr** [comment]
What's the reasoning behind this change?

**Comment by Leemann07** [comment]
> What's the reasoning behind this change?

I requested it.

**Comment by bluegr** [comment]
> > What's the reasoning behind this change?
> 
> I requested it.

OK, why did you request it?

**Comment by phcoder** [comment]
> > > What's the reasoning behind this change?
> > 
> > 
> > I requested it.
> 
> OK, why did you request it?

He didn't. I just sent him a link to preexisting PR.

**Comment by phcoder** [comment]
> What's the reasoning behind this change?

Without this argument our configure script fails to discover freetype2 in miyoomini toolchain. This is to document which options I used for 2.8.0 release and keep using them going forward

**Comment by bluegr** [comment]
> > What's the reasoning behind this change?
> 
> Without this argument our configure script fails to discover freetype2 in miyoomini toolchain. This is to document which options I used for 2.8.0 release and keep using them going forward

Thanks! Merging

**Pull request merged**
