### PR TITLE
GUI: Add slider for Grid Launcher icon size

### PR DESCRIPTION
**Pull request by criezy**
This commit adds a slider to the Grid Launcher so that the user has some control over the size of the icons. For example on my small laptop screen it is appreciable to be able to use smaller icons.

Default (and current) size:
image

With smaller icons:
image

The slider has 5 positions, and currently this applies a scaling to the size specified in the Theme.
Size from the Theme:
 - 192x192 if the window is wider than 640 pixels
 - 96x96 if the window is 640 pixels wide or smaller.

The scaling from the slider is between 0.6 and 1.4.

I also considered two other options:
 - Have the slider indicate an absolute size instead of a scaling.
 - Have the slider indicate a number of icons to fit in the window.

I don't think that the first of these two alternatives is a good idea. It's good to have smaller icons for smaller windows by default.

However I do like the second alternative, and I could try that if you think that is a good idea. But a possible downside is that the icons would be resized every time we resize the window, which could have a performance hit.

### CODE REVIEW

**Comment by criezy** [comment]
I have added a second commit that implements the `Have the slider indicate a number of icons to fit in the window`. I don't know if this is a good idea, so I kept it as a separate commit so that both options can be tested. But if we decide the second one is better, it would probably be a good idea to squash the two commits.
image

**Comment by bluegr** [comment]
With the latest changes to the theme files, this has conflicts now. Could you please fix them?

**Comment by criezy** [comment]
> With the latest changes to the theme files, this has conflicts now. Could you please fix them?

Done.
I have kept two separate commits for now to give us the option to go for either of the two implemented methods.

**Comment by sev-** [comment]
Please rebase it and then merge and backport

**Comment by criezy** [comment]
Rebased, squashed, merged, and backported.

**Pull request closed without merging**
