### PR TITLE
NOTFORMERGE: Switch from zlib to gzio as much as possible 

### PR DESCRIPTION
**Pull request by phcoder**

### CODE REVIEW

**Comment by rvanlaar** [comment]
@phcoder Something is wrong.

Scummvm is at 100% CPU and displays a black screen for Director games.
Reproducable with: `./scummvm -c scummvm.conf -p ./engines/director/lingo/tests/ --start-movie=XObjects.lingo directortest`

**Comment by phcoder** [comment]
> Scummvm is at 100% CPU and displays a black screen for Director games.

Fixed

**Comment by lephilousophe** [comment]
What is the rationale behind this change?
zlib is needed anyway because of the libPNG dependency so it's not like it will remove a dependency.

**Comment by sev-** [comment]
@phcoder What is the status of this PR?

**Comment by sev-** [comment]
Closing in favour of #5212

**Pull request closed without merging**
