### PR TITLE
CINE: Show splash screen in CD version of Future Wars

### PR DESCRIPTION
**Pull request by eriktorbjorn**
This simply shows the Sony splash screen included with the CD version of Future Wars. I think it does all the necessary sanity checking and cleanups, though some might find it a bit hackish.

### CODE REVIEW

**Comment by digitall** [comment]
Code looks good to me...

**Comment by bluegr** [comment]
So the resolution of the splash screen itself is 640x480, whereas the game itself runs at 320x200? Odd.

Other than that, the changes look fine to me

**Comment by eriktorbjorn** [comment]
Yeah, I don't know much about the image format but *file* identifies it as "IFF data, ILBM interleaved image, 640 x 480".

**Comment by bluegr** [comment]
Just tested this and it works great. As usual, thank you for your work!

Merging

**Comment by Kirben** [comment]
The original game switched to 640 x 480 resolution (16 colors) for the splash screen, so the resolution is definitely correct.

Unfortunately this patch breaks scaling though, the game isn't set to the current scaler after the splash screen.

**Comment by eriktorbjorn** [comment]
Odd, it seemed to work for me. At least no worse than _Lost in Time_ and _DreamWeb_, which also switch between resolutions during their intros. Could you elaborate?

**Comment by Kirben** [comment]
When the default scaling (2x) is been used, Future Wars (CD) reverts back to smaller 320 x 200 size, after the splash screen is shown.

**Comment by eriktorbjorn** [comment]
That doesn't happen for me. There are the settings from my .scummvmrc's [scummvm] section that I assume are relevant:

gfx_mode=2x
fullscreen=false
aspect_ratio=false

There are no graphics-related settings in the [fw-cd-us] section.

For me, when the game starts the splash screen is shown unscaled. After it's gone, the game runs with the 2x scaler.

**Comment by Kirben** [comment]
Try again, with no gfx_mode setting in the config file.

**Comment by eriktorbjorn** [comment]
Ah. But that will happen with both _Lost in Time_ and _DreamWeb_ as well, so I don't really have any suggestions for how to deal with that. (I don't remember off-hand if there are any other games that ScummVM supports that changes resolution like that.)

**Pull request merged**
