### PR TITLE
WINTERMUTE: Add new Steam flavours for "Reversion: The Meeting"

### PR DESCRIPTION
**Pull request by aviloria**
Add new Steam flavours for "Reversion: The Meeting"

### CODE REVIEW

**Comment by bluegr** [comment]
Excellent! Thanks

**Comment by sev-** [comment]
The commit log message was not conformant to our commit guidelines. It's sad it was merged as-is, without review.

**Comment by aviloria** [comment]
@sev just for the following contributions... what's wrong with it?

**Comment by sev-** [comment]
In your case it should just as the Pull Request is named: "WINTERMUTE: Add new Steam flavours for "Reversion: The Meeting"", but you have it as:
"WINTERMUTE
Add new Steam flavours for Reversion: The Meeting".

As a result, the oneline git log looks like:
```
ec12c5acbd WINTERMUTE
b2233f83e2 DIRECTOR: LINGO: Add sanity checks to script execution
07ad932262 DIRECTOR: LINGO: Improved debug output
```

**Comment by aviloria** [comment]
sorry for that!
... and thanks for the advise... I'll take it into account for the next time

**Pull request merged**
