### PR TITLE
SCI32: Fix GK1 day 2 binoculars lockup

### PR DESCRIPTION
**Pull request by sluicebox**
Fixes a lockup in floppy version. bug #10797

### CODE REVIEW

**Comment by sluicebox** [comment]
I wrestled with that sentence! Thanks for the feedback, I'll give it another shot

**Comment by raziel-** [comment]
i know that feeling :-)

awesome job, btw, don't leave again ;-)

**Comment by sluicebox** [comment]
There we go, that's as good as she's gonna get. =)

Thanks! I love reading the script patch notes too, mine are all homages.

**Comment by raziel-** [comment]
Lovely :-)

Nitpicking:

"to be blown away" and "is blown away"?

I need a to add i don't know what really happens, the picture is probably not blowing away something, or is it?

**Comment by sluicebox** [comment]
It might blow you away to know the script is named sDrawingBlows

**Comment by raziel-** [comment]
lol, awesome :-D

**Comment by bluegr** [comment]
@sluicebox: This looks good, but I’m still awaiting a reply to my question above, before merging it :)

**Comment by sluicebox** [comment]
I'm confused, I don't see any comments posted by you on this PR?

**Comment by bluegr** [comment]
My comment was in a pending state. Sorry for the confusion, it should be visible now :)

**Comment by sluicebox** [comment]
How about I add a comment to the signature calling out the redundant initialization?

**Comment by bluegr** [comment]
Yes, please do that, it makes it easier to understand the patch

**Comment by bluegr** [comment]
Thanks! Merging

**Pull request merged**
