### PR TITLE
GRAPHICS: Make setPixel ignore drawings outside of the surface

### PR DESCRIPTION
**Pull request by phcoder**
Not really necessarry for this patchset but makes life much easier in face of bugs

### CODE REVIEW

**Comment by antoniou79** [comment]
I could prevent bugs, but my (minor) concern is that we introduce an extra condition check for every setPixel() call which may already be redundant for most cases (as engines might already do this before calling setPixel()).

**Comment by phcoder** [comment]
> It could prevent bugs, but my (minor) concern is that we introduce an extra condition check for every setPixel() call which may already be redundant for most cases (as engines might already do this before calling setPixel()).

Engines that are heavily optimized don't and should not use setPixel. They should use getBasePtr and discover bpp outside of the loop and AFAIK they do.

setPixel is a shortcut for when engine doesn't need to optimize and one check is no big deal in this case

**Comment by lephilousophe** [comment]
Grepping through our codebase on `setPixel` seems to indicate that it's used by several engines (freescape, grim, hypno, mtropolis, scumm, sherlock, tinsel, trecision, ultima and vcruise). and about dialog (easter egg) and opengl backend use it too.
In quite a lot of places, it's used in a double loop (x, y).
It's a code which is inlined so it may not be that inefficient and adding a test will indeed make it slower.

**Comment by lephilousophe** [comment]
In addition, a `return` statement will hide the errors.
An assert would be safer and will magically disappear in release builds: this seems better.

**Comment by sev-** [comment]
I am closing this but adding an assert manually. As other people mentioned, this silent `return` will hide the problems: the caller code must use proper clipping

**Pull request closed without merging**
