### PR TITLE
QDENGINE: Add more settings to `ConfMan`

### PR DESCRIPTION
**Pull request by kunxl-gg**
- Add a few more settings to ConfMan
- Add `ConfigManager::getFloat` and `ConfigManager::setFloat`

### CODE REVIEW

**Comment by bluegr** [comment]
The second commit touches common code, so its message should be adapted accordingly, I.e. `COMMON: Add ConfMan.getFloat and ConfMan.setFloat`

**Comment by bluegr** [comment]
Also, please split the changes to whitespace in a separate commit, to reduce noise regarding the actual changes

**Comment by bluegr** [comment]
Since most of the old config code is gone now, can you remove the remaining uses of `qdGameConfig`?

**Comment by sev-** [comment]
Thanks!

**Pull request merged**
