### PR TITLE
TINYGL: Use the existing list of rectangles when copying to the screen

### PR DESCRIPTION
**Pull request by ccawley2011**
This seems to work, but is in draft mode until it can be tested more thoroughly.

### CODE REVIEW

**Comment by aquadran** [comment]
I wanted to add something like this, but tglPresentBuffer return list of rects for g_system->copyRectToScreen. I don't want g_system access in tinygl, this is part of engine doing.

**Comment by ccawley2011** [comment]
> I wanted to add something like this, but tglPresentBuffer return list of Rect for g_system->copyRectToScreen. I don't want g_system access in tinygl, this is part of engine doing. Can you try that?

OK, I've done that.

**Comment by aquadran** [comment]
thx! I'll test it a bit and we can merge it

**Comment by aquadran** [comment]
ok, I tested it, please push as final PR.

**Comment by ccawley2011** [comment]
> ok, I tested it, please push as final PR.

Thanks, I've marked the PR as ready.

**Pull request merged**
