### PR TITLE
GOB: add kFeatures for Non/Interactive demos

### PR DESCRIPTION
**Pull request by BJNFNE**

### CODE REVIEW

**Comment by BJNFNE** [comment]
> And what is the function of this, may I ask?

i added kFeaturesNonInteractive to the Non interactive demos and kFeaturesInteractiveDemo to the InteractiveDemos,
(example) its similar as like for kFeaturesCD for this function it is only used for the CD versions to mark them as CD versions, so i did similar changes to the Non Interactive demos / Interactive demos

**Comment by bluegr** [comment]
@BJNFNE yes, but as @sev- asked, why do we need this information? If we are not using it in any way in the engine, it's superfluous.

Also, there seems to be overlap between the `kFeaturesSCNDemo` and the `kFeaturesNonInteractiveDemo` features, perhaps we can avoid adding a new feature, if it's already there?

Finally, demos can be either interactive or non-interactive, so we can rely on a combination of the existing `ADGF_DEMO` and one flag to determine if it's interactive or not. For example:

- ADGF_NONE -> full game
- ADGF_DEMO + kFeaturesSCNDemo -> non-interactive demo
- ADGF_DEMO only -> interactive demo

**Comment by BJNFNE** [comment]
Ah okay, i agree with that, what we are now should do with the PR?

**Comment by sev-** [comment]
I am closing this as irrelevant. If you want to document and distinguish those versions, then the possible options are comments or perhaps the extra field. But the engine itself does not require these features since there are no functional changes.

**Pull request closed without merging**
