### PR TITLE
BBVS: Fix memory leak in audio code

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by bluegr** [comment]
Memory leak? Why?
This code is used in other engines in ScummVM as well, so if there's a leak, it'll be in multiple places

**Comment by ccawley2011** [comment]
> Memory leak? Why? This code is used in other engines in ScummVM as well, so if there's a leak, it'll be in multiple places

The code only holds on to a reference to the base audio stream, so the looping stream needs to be deleted by the mixer if one is created.

**Comment by somaen** [comment]
Makes sense to me, as long as the ownership of _stream should not be DisposeAfterUse::YES, then a solution like this is the way to go, especially since there is no current way of flagging that the inner stream of the loop should NOT be DisposeAfterUse::YES with makeLoopingAudioStream.

**Comment by bluegr** [comment]
Thanks! This does plug a memory leak indeed
Merging

**Pull request merged**
