### PR TITLE
MADS: Remove git conflict markers in menu_views.h

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Comment by salty-horse** [comment]
Do you mind renaming the commit message to "Remove git conflict markers [...]"? (This isn't an actual conflict)

**Comment by RobLoach** [comment]
Thanks, I'll amend it, please hold.

**Comment by salty-horse** [comment]
Oh, sorry: Also prefix it with the engine name, as required by our commit conventions.
"MADS: ..."

**Comment by salty-horse** [comment]
Thanks! Committed as aa95183b93dcfaa74e0e732259c87e9b9d39d518

**Pull request closed without merging**
