### PR TITLE
Make "Enable copy protection" a GUI option

### PR DESCRIPTION
**Pull request by eriktorbjorn**
We've had the --copy-protection command line parameter for a long time, but it's not easily discoverable unless you're used to a command line. This aims to add "Enable copy protection" as an engine checkbox to the relevant games. I think it gets most of the way.

Several of these games I either don't own or never tried in ScummVM. I hope I got things right.

**SCUMM**

- Maniac Mansion v1 (DOS) and v2 (everything), but not the NES version.
- Zak McKracken v1 and v2. Not FM-Towns.
- Loom EGA. I believe the copy protection is either not present (e.g. TurboGrafx-16, FM Towns) or always enabled (e.g. Macintosh) for the other versions.
- Monkey Island 1 VGA, Macintosh.
- Monkey Island 2, except FM Towns and Ultimate Talkie
- Indiana Jones and the Fate of Atlantis, floppy versions including Amiga.

This will add the checkbox to the Mac CD Game Pack release of Fate of Atlantis, where the copy protection has been stripped out completely. (The same thing is true about that version of Monkey Island 2, but there we re-insert the missing script to enable difficulty selection.)

Demos do not get the checkbox, or at least that's the intention.

**Lure**

The copy protection screen looks wrong for the EGA version, but that's an old bug apparently.

**Voyeur**

Here the checkbox is called "Enable lockout system", since that's what the manual calls it. It's not copy protection, it's parental control, but it uses the same "copy_protection" setting.

**MADS**

Rex Nebular, but not the demo. I noticed that there is one detection entry for Rex Nebular that doesn't have the TTS option. Is that intentional?

**SAGA**

I've made the assumption that it should apply to all releases of Inherit the Earth.

**AGOS**

The floppy versions of Simon 1 and 2. I don't own the floppy version of Simon 2, so I've never actually seen any copy protection there.

**DreamWeb**

This apparently only affects whether or not terminals should display a list of available commands. Perhaps it should be called something else than "Enable copy protection"?

**MM**

I've made the assumption that it applies to all of the Xeen games, but I know nothing about them.

**Gob**

I haven't touched this one. Apparently it should apply to Gobliiins 1 and 2, but only the floppy versions? The floppy version of Gobliiins 3 shows a copy protection screen, but at least the GOG version seems to accept anything and it's not affected by the copy protection setting? Also Adibou 1, which I know nothing about.

Detection in this engine is just a bit too hairy for me right now.

### CODE REVIEW

**Comment by BJNFNE** [comment]
Regarding Gob, Adibou 1 has aswell the copy protection but only the floppy version the two German CD versions don't use an copy protection, Geisha has aswell an Copy Protection in ScummVM. and several other Gob games like Bargon Attack. i guess also some littlered and Lost in Time? but i am not quite sure.

**Comment by bluegr** [comment]
Nice work!

Some feedback on your statements:

- MADS: The entry without the TTS option is a mistake - nice catch!
- SAGA: The copy protection was only present in the floppy versions. Check here: https://bugs.scummvm.org/ticket/2256
- Dreamweb: The copy protection was the manual, which explained all the available commands for the terminal. The help system for the terminal commands is an enhancement that was not available in the original version, and is tied to the copy protection flag to keep the screens faithful to the original. Check here for more info: https://github.com/scummvm/scummvm/commit/42b8f3db4d3fbddb2e59db761b8b1f488e279071

**Comment by eriktorbjorn** [comment]
@BJNFNE 

The only cases I could find where we check the "copy_protection" setting in GOB are:

- Inter_v1::o1_callSub() to skip copy protection screens in Gobliiins, Gobliins 2, and Adibou 1.
- Inter_v2::o2_totSub() to skip copy protection screen in Adibou 1.

So if there is more copy protection it's either not bypassed, always bypassed, or not implemented at all. The checkbox would have no effect on those.

I don't have Adibou 1, and I can't find the copy protection screen in Gobliiins 1. The GOG floppy version of Gobliins 2 does have it, though. As does the GOG floppy version of Goblins 3, but there it always seems to bypass the protection. I don't know if it's ScummVM that does that, or if GOG is selling a cracked version.

**Comment by eriktorbjorn** [comment]
@bluegr 

Thanks, I had forgotten that there were versions of ITE that don't have copy protection. It's been ages since I played the game (I don't like the mazes), and even longer since I played it outside of ScummVM. I've removed the copy protection option from all CD versions, except the one that supposedly "behaves like a DOS floppy version". I don't have any of these versions myself, though.

**Comment by eriktorbjorn** [comment]
@sdelamarre 

Thanks, I missed the o1_if() one in my summary. Still, it's only Goblins 1 and 2, and Adibou 1 where the copy protection setting makes any difference currently, so it's only they that should get an engine checkbox at this point. I just haven't looked enough at the detection entries to make that change yet. It's a bit hairier than others.

**Comment by eriktorbjorn** [comment]
I've tried updating my branch so it won't conflict with the recent changes to the SCUMM detection tables, and I've added the copy protection checkbox to all floppy versions of Gobliiins 1, Gobliins 2, and Adibou 1. That's just a guess though. The only floppy versions I own are the ones from GOG, and I don't own any Adibou games at all.

So that's as far as I can take this on my own.

**Comment by eriktorbjorn** [comment]
I could be wrong, but I get the impression that only _some_ floppy versions of Gobliiins 1 actually have a copy protection screen. The bypass happens when o1_callSub() is called with a certain offset while running intro.tot (the "start TOT"). I have two versions that I assume were made for floppy distribution:

- The one that GOG sells, identified as "Gobliiins (VGA/DOS). Intro.tot seems to be used for the intro, but if so it never calls o1_callSub() at all.
- The one that's included with Sierra's School House: Math, identified as "Gobliiins (VGA/DOS/English (GB))". This one seems to not have an intro (!), and the stub that is intro.tot doesn't call o1_callSub() at all.

In this pull request I've marked all floppy version as having copy protection, but that was just my initial assumption.

**Comment by sdelamarre** [comment]
>  I've added the copy protection checkbox to all floppy versions of Gobliiins 1, Gobliins 2, and Adibou 1. That's just a guess though. The only floppy versions I own are the ones from GOG, and I don't own any Adibou games at all.

Just gave it a try on my Adibou 1 version, it works well. It's nice to be able to bring back those copy protection screens so easily - even for them I feel some kind of a nostalgia. :grin:

Not specific to the copy protection setting, but I was confused at first because the checkbox was not showing ; then I noted that it was there after re-adding the game, as the allowed Gui options per game seem to be cached in scummvm.ini. Is there a clean way to refesh the gui options without re-adding the game ?

**Comment by eriktorbjorn** [comment]
> Is there a clean way to refesh the gui options without re-adding the game ?

I believe they are refreshed every time you start the game?

**Comment by sdelamarre** [comment]
> I believe they are refreshed every time you start the game?
Indeed, fair enough!

**Comment by BJNFNE** [comment]
What is the status of this PR? It would be great to see this gets soon be merged into master.

**Comment by bluegr** [comment]
This is in a good state to be merged, so unless someone objects, I'll merge it today

**Comment by eriktorbjorn** [comment]
Thanks! The one thing I'm concerned about (though not very much) is that I may have marked some GOB games as having copy protection that don't actually have it. I don't think I have any version.of Gobliiins 1 with the copy protection.

And I think some new detection entries were added. If so, I don't know about those either.

**Comment by BJNFNE** [comment]
> Thanks! The one thing I'm concerned about (though not very much) is that I may have marked some GOB games as having copy protection that don't actually have it. I don't think I have any version.of Gobliiins 1 with the copy protection.
> 
> 
> 
> And I think some new detection entries were added. If so, I don't know about those either.

I can later help out when bluegr merged this PR. I would then check which Games or variants needs the new Game flag and add it to them and push an PR which needs them

**Comment by sev-** [comment]
Thank you!

**Pull request merged**
