### PR TITLE
BUILD: Improve rules for compiling Windows resource scripts

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by digitall** [comment]
The code changes looks reasonable and should only affect Win32 and WinCE ports.
@ccawley2011 : Have you tried compiling this with MinGW toolchain for Win32 to check it locally?

**Comment by digitall** [comment]
@ccawley2011 : OK to merge?

**Comment by digitall** [comment]
Since this PR has been open for some time without any argument, I am going to merge that now since it looks pretty self-contained and the Win32 / WinCE porter will need to do some testing / feedback anyway to catch any issues.

**Comment by peterkohaut** [comment]
my msys2 stopped working with this update, windres is now using cppflags and freetype is adding there  -mms-bitfields option which is not working with windres

**Comment by ccawley2011** [comment]
Does commit 552275e fix this for you?

**Comment by peterkohaut** [comment]
yes it works, thanks for quick fix

**Pull request merged**
