### PR TITLE
PSP: Don't hard-code the version and list of data files in the build script

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by digitall** [comment]
Looks good, though you might want to use DISTVERSION rather than VERSION?
See: https://github.com/scummvm/scummvm/blob/master/Makefile.common#L213

**Comment by rsn8887** [comment]
Can you make the change to DISTVERSION, and then I will merge this.

**Comment by ccawley2011** [comment]
OK, done.

**Comment by digitall** [comment]
@ccawley2011 : Thanks for making those changes. Looks good to me.
@rsn8887 : Can you check @ccawley2011 's changes and then push the resolve / approve button on your review if happy? :) I can override and merge without needing that done, but a bit "rude" ;-)

**Comment by rsn8887** [comment]
Great work! Thanks!

**Comment by digitall** [comment]
@rsn8887 : Thanks. Merging...

**Pull request merged**
