### PR TITLE
GLK: Allow enabling/disabling individual subengines

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by digitall** [comment]
This looks like a good improvement since GLK has a large number of sub-engines. One point, not sure if we should prefix the engine names with glk_ as per scumm,scumm_7_8 etc. to avoid future name collisions ... I am mainly thinking that several subengines have quite generic names i.e. scott, quest and adrift and this also will make glkhugo into glk_hugo which is more readable.

**Comment by dreammaster** [comment]
I agree with digitall. This looks good in theory, but it's really going to need "GLK_" prefixes to differentiate them if we want to go this way. There are already a dozen engines, with more to follow, so some way is really needed to disambiguate them.

**Comment by digitall** [comment]
@dreammaster : Just to be clear... I assume you mean lowercase for the engine names in configure.engine etc. i.e. ./configure --enable-engine=glk,glk_hugo rather than ./configure --enable-engine=glk,GLK_hugo  ... but obviously the ENABLE defines will be ENABLE_GLK_HUGO etc.

**Comment by dreammaster** [comment]
Right. One other thing is that the configure.engine should flag the engine as having sub-engines, so that the GLK entry properly lists "[all games]' like SCI or Kyra do

**Comment by ccawley2011** [comment]
OK, done.

**Comment by digitall** [comment]
Looks good to me. @dreammaster : OK to squash this and rebase?

**Comment by dreammaster** [comment]
Go for it (squash and rebase). Though I do have a remaining minor quibble for the Codacy warning about "gd being assigned but never used". Maybe an explicit extra #ifdef ENABLE_GLK could be wrapped around the content of the method to suppress it.. I'm not sure. I mean, are engines with multiple subengines even able to be enabled if all the subengines are explicitly disabled? Not as far as I'm aware. But it'd still be good to nip the warning in the bud, so to speak.

**Comment by digitall** [comment]
@dreammaster : Yes, I wondered about that warning too. I think it is not critical, but @ccawley2011 would you like to apply a fix for that unused gd warning before I merge in?

**Comment by dreammaster** [comment]
I did a squash and a workaround for the issue. Thanks for the work.

**Pull request closed without merging**
