### PR TITLE
MADS: Return of the Phantom WIP

### PR DESCRIPTION
**Pull request by bluegr**
Hello

This is a pull request to sync the work done on the MADS engine for Return of the Phantom (mainly) and Dragonsphere.

The hardcoded logic for Return of the Phantom has been created, and a lot of the functionality needed for V2 games (i.e. Return of the Phantom and Dragonsphere) has been implemented in the core engine.

The game isn't playable yet, as there is functionality missing for V2 games:
- New dialog graphics
- Conversation subsystem
- Some logic for scene scrolling (camera panning)
- Menus
- Synthesized music and sound effects (game specific sound drivers)
- Switching screen dimensions to letterbox for some scenes
- Load all scene information
- Some functionality for dynamic hotspots
- Fixes to scene/sprite depth

The reason why a merge is requested is because in order to include some of the functionality needed for V2 games, there are some small but important changes made for Rex Nebular too (e.g. there is better support for multiple animations). Thus, it would be great if these changes could be merged, so that testers can perform a playthrough of Rex and check if anything has been affected. Then, any further work on V2 games can continue in-tree.

Edit: There are some unrelated commits for sherlock... not quite sure what's wrong here.

### CODE REVIEW

**Comment by sev-** [comment]
This last commit is incorrect. It has bunch of non-related stuff from merge.

**Comment by wjp** [comment]
There are serious merge issues in this history of this branch that have to be fixed. I can take a look at that later, if you want.

**Comment by bluegr** [comment]
wjp: That would be great! :) Thanks!

**Comment by wjp** [comment]
I fixed at least the merge problems and commits from other engines in my tree here:

https://github.com/wjp/scummvm/tree/phantom

There's still a bunch of commits in the beginning of the branch that seem to already have been cherry-picked into master in the past, but I just left those in there.

**Comment by wjp** [comment]
Force pushed it to the PR now.

**Comment by dreammaster** [comment]
Now, thanks to wjp's good work, the commit history is fixed, is there any reason to delay merging it into master? This isn't a completely new game engine, so I'm not sure if we really need to allow several weeks for feedback.

**Comment by wjp** [comment]
I haven't looked at it, but if it's fine by you, it's fine by me.

**Comment by bluegr** [comment]
Since the history is fixed, and wjp, dreammaster and Strangerke are OK with this, I would like to have this merged in-tree.

Unless someone objects, this will be merged in three days (on Sunday, the 22nd of November, 2015).

**Comment by sev-** [comment]
I have no objections

**Pull request merged**
