### PR TITLE
GOB: Use ADGF_CD flag for gob games + general cleanup

### PR DESCRIPTION
**Pull request by tag2015**
General cleanup of the GOB detection tables, for uniformity with the other engines.
- Remove gob1cd, gob2cd, gob3cd identifiers and use the AD flag instead (gob1-cd, ...)
- Move "CD" string to description instead of using the game name (e.g. Gobliiins 2 CD (DOS/English) -> Gobliins 2 (CD/DOS/English)
- A couple minor fixes

### CODE REVIEW

**Comment by sev-** [comment]
This will break existing configs. Please use obsolete target autoupgrade feature. For example, see `obsoleteGameIDsTable` in the AGOS engine.

**Comment by BJNFNE** [comment]
GOB has aswell an obsolete.h

**Comment by tag2015** [comment]
> This will break existing configs. Please use the obsolete target autoupgrade feature. For example, see `obsoleteGameIDsTable` in the AGOS engine.

Of course, done. Please check. I also shortened the fascination descriptions to match the style of the other entries

**Review by bluegr — APPROVED** [review]
Looks good! Nice work

**Comment by sev-** [comment]
Thank you! Getting closer to perfection :)

**Pull request merged**
