### PR TITLE
DOCS: Add Thimbleweed Park documentation

### PR DESCRIPTION
**Pull request by scemino**
This commit add documentation about Thimbleweed Park GUI options.

### CODE REVIEW

**Comment by bluegr** [comment]
@scemino please, split this into two commits: one that fixes the whitespace issues, and one that actually adds the Thimbleweed Park documentation

**Comment by scemino** [comment]
> @scemino please, split this into two commits: one that fixes the whitespace issues, and one that actually adds the Thimbleweed Park documentation

Sorry about that I didn't see that "format on save" config (it's not even enabled).

**Comment by bluegr** [comment]
Wait, the whitespace fixes were legitimate. Please, don't roll them back, just submit them as a separate commit  :)

**Comment by scemino** [comment]
> Wait, the whitespace fixes were legitimate. Please, don't roll them back, just submit them as a separate commit :)

Better?

**Comment by bluegr** [comment]
Great work, thanks!

**Pull request merged**
