### PR TITLE
CLOUD: Fix format for uint64 variables

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by bluegr** [comment]
Thanks, merging

**Comment by digitall** [comment]
@bluegr , @orgads : I assume this change was made to build with no warnings for MinGW on Win64, but on Linux x86_64 with GCC, it gives this now:

````
backends/cloud/cloudmanager.cpp: In member function ‘void Cloud::CloudManager::save()’:
backends/cloud/cloudmanager.cpp:127:80: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64’ {aka ‘long unsigned int’} [-Wformat=]
   ConfMan.set(kStoragePrefix + name + "_usedBytes", Common::String::format("%llu", _storages[i].usedBytes), ConfMan.kCloudDomain);
                                                                             ~~~^
                                                                                |
                                                                                long long unsigned int
                                                                             %lu
backends/cloud/googledrive/googledrivestorage.cpp: In member function ‘void Cloud::GoogleDrive::GoogleDriveStorage::printInfo(Cloud::Storage::StorageInfoResponse)’:
backends/cloud/googledrive/googledrivestorage.cpp:181:29: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘uint64’ {aka ‘long unsigned int’} [-Wformat=]
  debug(9, "\tdisk usage: %llu/%llu", response.value.used(), response.value.available());
                          ~~~^        ~~~~~~~~~~~~~~~~~~~~~
                             |                           |
                             long long unsigned int      uint64 {aka long unsigned int}
                          %lu
backends/cloud/googledrive/googledrivestorage.cpp:181:34: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘uint64’ {aka ‘long unsigned int’} [-Wformat=]
  debug(9, "\tdisk usage: %llu/%llu", response.value.used(), response.value.available());
                               ~~~^                          ~~~~~~~~~~~~~~~~~~~~~~~~~~
                                  |                                                  |
                                  long long unsigned int                             uint64 {aka long unsigned int}
                               %lu
backends/cloud/googledrive/googledriveuploadrequest.cpp: In member function ‘void Cloud::GoogleDrive::GoogleDriveUploadRequest::uploadNextPart()’:
backends/cloud/googledrive/googledriveuploadrequest.cpp:202:85: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64’ {aka ‘long unsigned int’} [-Wformat=]
    warning("GoogleDriveUploadRequest: cannot upload because stream couldn't seek(%llu)", _serverReceivedBytes);
                                                                                  ~~~^    ~~~~~~~~~~~~~~~~~~~~
                                                                                     |    |
                                                                                     |    uint64 {aka long unsigned int}
                                                                                     long long unsigned int
                                                                                  %lu
                                                                                  
````

**Comment by digitall** [comment]
This may require a solution adding platform specific string literal symbols to common/debug.h or OSystem, along these lines i.e.
````
#ifdef __WIN32
#define PRINTF_FORMAT_UINT64 "%lu"
#else
#define PRINTF_FORMAT_UINT64 "%llu"
#endif
...
debug(9, "\tdisk usage: " PRINTF_FORMAT_UINT64 "/" PRINTF_FORMAT_UINT64, response.value.used(), response.value.available());
````

**Comment by orgads** [comment]
This won't work on Linux 32.

Better use `PRIu64` from `inttypes.h`.

**Comment by orgads** [comment]
Or cast to `unsigned long long`.

**Comment by orgads** [comment]
I see that PRI* macros are not used anywhere in the codebase. Is it not supported on some old toolchains you use? Or you just never needed it? Do you prefer to cast instead?

**Comment by lephilousophe** [comment]
PRIu64 is C99 while we still target C++98.
Besides, I am not sure about its status in MSVC.

**Comment by orgads** [comment]
MSVC has PRIu64, but never mind. I filed a PR with casts. #2892.

**Pull request merged**
